// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

import { createDOMRenderer } from '@griffel/react';

// Singleton Griffel DOM renderer scoped to this web part.
//
// The classNameHashSalt (= web part manifest component ID) ensures that atomic
// CSS class names generated by this web part's Griffel instance do not collide
// with SharePoint Online's own Fluent UI v9 / Griffel instance on the same page.
// Without the salt both renderers target the same style buckets in document.head
// and can overwrite each other's CSS rules, causing missing backgrounds, borders,
// and shadows (especially in portal contexts such as Popover and OverlayDrawer).
//
// Defined here as a module-level singleton so GuestSponsorInfo, SponsorCard, and
// WelcomeDialog all share exactly one renderer instance — avoiding duplicate style
// injection and ensuring consistent class-name generation across the bundle.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const griffelRenderer: any = createDOMRenderer(document, {
  classNameHashSalt: '16be4020-0cfb-4b1b-9d50-d3d4af2e90e6',
});
