// CommonJS equivalent of loc/en-us.js.
// The original locale file uses the AMD define() pattern which jest cannot evaluate
// in a CommonJS test environment. This shim exposes the same strings via module.exports.
module.exports = {
  PropertyPaneDescription: 'Configure the Guest Sponsor Info web part.',
  BasicGroupName: 'Settings',
  TitleFieldLabel: 'Title',
  LoadingMessage: 'Loading your sponsors\u2026',
  NoSponsorsTitle: 'No sponsors found',
  NoSponsorsMessage: 'No sponsors found for your account.',
  SponsorUnavailableTitle: 'Sponsor not available',
  SponsorUnavailableMessage:
    'Your sponsor is no longer available. Please contact your project stakeholder to have a new sponsor assigned to your account.',
  ErrorMessageTitle: 'Something went wrong',
  ErrorMessage: 'Could not load sponsor information. Please try again later.',
  EditModePlaceholder: 'Guest Sponsor Info \u2014 switch to view mode to see sponsors.',
  GuestOnlyPlaceholder: 'This web part is only visible to guest users in view mode.',

  PresenceAvailable: 'Available',
  PresenceAvailableIdle: 'Available, Idle',
  PresenceAway: 'Away',
  PresenceBeRightBack: 'Be Right Back',
  PresenceBusy: 'Busy',
  PresenceBusyIdle: 'Busy, Idle',
  PresenceDoNotDisturb: 'Do Not Disturb',
  PresenceInAMeeting: 'In a meeting',
  PresenceInACall: 'In a call',
  PresencePresenting: 'Presenting',
  PresenceFocusing: 'Focusing',
  PresenceOutOfOffice: 'Out of office',
  PresenceOutOfOfficeSuffix: ', out of office',
  PresenceOffline: 'Offline',

  ContactDetailsAriaLabel: 'Contact details for {0}',
  ContactActionsAriaLabel: 'Contact actions',
  ChatTitle: 'Chat in Microsoft Teams',
  EmailTitle: 'Send email',
  CallTitle: 'Call',
  ChatLabel: 'Chat',
  EmailLabel: 'Email',
  CallLabel: 'Call',

  ContactInfoSection: 'Contact information',
  EmailFieldLabel: 'Email',
  WorkPhoneFieldLabel: 'Work phone',
  MobileFieldLabel: 'Mobile',
  WorkLocationFieldLabel: 'Work location',
  StreetAddressFieldLabel: 'Street',
  PostalCodeFieldLabel: 'ZIP',
  StateFieldLabel: 'State',
  CityFieldLabel: 'City',
  CountryFieldLabel: 'Country',
  ShowStructuredAddressFieldLabel: 'Show structured address',
  ShowStreetAddressFieldLabel: 'Show street',
  ShowPostalCodeFieldLabel: 'Show ZIP code',
  ShowStateFieldLabel: 'Show state',
  LocationDisplayHintAddressEnabled: 'Structured address fields are enabled and can be shown in additional rows.',
  LocationDisplayHintSeparateRows: 'City/country and work location are shown as separate rows when enabled.',
  LocationDisplayHintHidden: 'All location fields are hidden.',
  AdvancedDisplayGroupName: 'Advanced display options',
  ManagerOptionsDisabledHint: 'Enable "Show manager" to configure manager-specific fields.',

  OrganizationSection: 'Organization',
  ManagerLabel: 'Manager',

  CopiedFeedback: 'Copied!',
  CopyEmailAriaLabel: 'Copy email address',
  CopyWorkPhoneAriaLabel: 'Copy work phone',
  CopyMobileAriaLabel: 'Copy mobile number',
  CopyLocationAriaLabel: 'Copy work location',
  CopyStreetAddressAriaLabel: 'Copy street',
  CopyPostalCodeAriaLabel: 'Copy ZIP code',
  CopyStateAriaLabel: 'Copy state',
  AddressMapSectionLabel: 'Map preview',
  AddressMapLoadingLabel: 'Loading map preview…',
  OpenAddressInMapLabel: 'Open in map',
  CopyCityAriaLabel: 'Copy city',
  CopyCountryAriaLabel: 'Copy country',

  ShowAddressMapFieldLabel: 'Show address map preview',
  AzureMapsSubscriptionKeyFieldLabel: 'Azure Maps subscription key',
  ExternalMapProviderFieldLabel: 'External map provider fallback',
  MapProviderBingOption: 'Bing Maps',
  MapProviderGoogleOption: 'Google Maps',
  MapProviderAppleOption: 'Apple Maps',
  MapProviderOpenStreetMapOption: 'OpenStreetMap',
  MapProviderHereOption: 'HERE WeGo',
  MapProviderNoneOption: 'Disabled (no map link)',
  AddressMapProviderHint: 'Enable at least city and country — that is sufficient for any map provider to show a meaningful location.',
  AddressMapFallbackHint: 'If no Azure Maps key is configured or map lookup fails, an external map link is shown.',
  UseInformalAddressFieldLabel: 'Use informal salutation (du/tu)',

  VersionMismatchTitle: 'Update available',
  VersionMismatchMessage: 'A web part update is available. Ask your administrator to ensure the web part and the Azure Function are running the same version.',
  InsufficientPermissionsTitle: 'Permission required',
  InsufficientPermissionsMessage: 'Could not load sponsor information — a required service permission has not been granted. Please contact your IT administrator.',
};
