// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

// CommonJS equivalent of loc/en-us.js.
// The original locale file uses the AMD define() pattern which jest cannot evaluate
// in a CommonJS test environment. This shim exposes the same strings via module.exports.
module.exports = {
  BasicGroupName: 'Settings',
  ShowTitleFieldLabel: 'Show title',
  TitleFieldLabel: 'Title',
  LoadingMessage: 'Loading your sponsors\u2026',
  NoSponsorsTitle: 'No sponsors found',
  NoSponsorsMessage: 'No sponsors found for your account.',
  SponsorUnavailableTitle: 'Sponsor not available',
  SponsorUnavailableMessage:
    'Your sponsor is no longer available. Please contact your project stakeholder to have a new sponsor assigned to your account.',
  ErrorMessageTitle: 'Something went wrong',
  ErrorMessage: 'Could not load sponsor information. Please try again later.',
  EditModePlaceholder: 'Guest Sponsor Info \u2014 switch to view mode to see sponsors.',
  GuestOnlyPlaceholder: 'This web part is only visible to guest users in view mode.',
  MockModeFieldLabel: 'Enable public demo mode for internal users',
  MockModeFieldDescription: 'Applies only to the live page for visitors. In edit mode, the preview does not change.',

  PresenceAvailable: 'Available',
  PresenceAvailableIdle: 'Available, Idle',
  PresenceAway: 'Away',
  PresenceBeRightBack: 'Be Right Back',
  PresenceBusy: 'Busy',
  PresenceBusyIdle: 'Busy, Idle',
  PresenceDoNotDisturb: 'Do Not Disturb',
  PresenceInAMeeting: 'In a meeting',
  PresenceInACall: 'In a call',
  PresencePresenting: 'Presenting',
  PresenceFocusing: 'Focusing',
  PresenceOutOfOffice: 'Out of office',
  PresenceOutOfOfficeSuffix: ', out of office',
  PresenceOffline: 'Offline',

  ContactDetailsAriaLabel: 'Contact details for {0}',
  ContactActionsAriaLabel: 'Contact actions',
  ChatTitle: 'Chat in Microsoft Teams',
  EmailTitle: 'Send email',
  CallTitle: 'Call',
  ChatLabel: 'Chat',
  EmailLabel: 'Email',
  CallLabel: 'Call',

  ContactInfoSection: 'Contact information',
  EmailFieldLabel: 'Email',
  WorkPhoneFieldLabel: 'Work phone',
  MobileFieldLabel: 'Mobile',
  WorkLocationFieldLabel: 'Work location',
  StreetAddressFieldLabel: 'Street',
  PostalCodeFieldLabel: 'ZIP',
  StateFieldLabel: 'State',
  CityFieldLabel: 'City',
  CountryFieldLabel: 'Country',
  ShowStructuredAddressFieldLabel: 'Show structured address',
  ShowStreetAddressFieldLabel: 'Show street',
  ShowPostalCodeFieldLabel: 'Show ZIP code',
  ShowStateFieldLabel: 'Show state',
  LocationDisplayHintAddressEnabled: 'Structured address fields are enabled and can be shown in additional rows.',
  LocationDisplayHintSeparateRows: 'City/country and work location are shown as separate rows when enabled.',
  AdvancedDisplayGroupName: 'Advanced display options',

  OrganizationSection: 'Organization',
  ManagerLabel: 'Manager',

  CopiedFeedback: 'Copied!',
  CopyEmailAriaLabel: 'Copy email address',
  CopyWorkPhoneAriaLabel: 'Copy work phone',
  CopyMobileAriaLabel: 'Copy mobile number',
  CopyLocationAriaLabel: 'Copy work location',
  CopyStreetAddressAriaLabel: 'Copy street',
  CopyPostalCodeAriaLabel: 'Copy ZIP code',
  CopyStateAriaLabel: 'Copy state',
  AddressMapSectionLabel: 'Map preview',
  AddressMapLoadingLabel: 'Loading map preview…',
  OpenAddressInMapLabel: 'Open in map',
  CopyCityAriaLabel: 'Copy city',
  CopyCountryAriaLabel: 'Copy country',

  ShowAddressMapFieldLabel: 'Show address map preview',
  AzureMapsSubscriptionKeyFieldLabel: 'Azure Maps subscription key',
  MapProviderModeAutoLabel: 'Auto mode (recommended)',
  MapProviderModeManualLabel: 'Manual (same for all devices)',
  MapProviderModeHint: 'Choose a map provider for each operating system, including iOS and Android. Links open in the browser or the provider\'s app if installed.',
  MapProviderIosLabel: 'iOS:',
  MapProviderAndroidLabel: 'Android:',
  MapProviderWindowsLabel: 'Windows:',
  MapProviderMacOSLabel: 'macOS:',
  MapProviderLinuxLabel: 'Linux:',
  ExternalMapProviderFieldLabel: 'External map provider fallback',
  MapProviderBingOption: 'Bing Maps',
  MapProviderGoogleOption: 'Google Maps',
  MapProviderAppleOption: 'Apple Maps',
  MapProviderOpenStreetMapOption: 'OpenStreetMap',
  MapProviderNoneOption: 'Disabled (no map link)',
  AddressMapProviderHint: 'Enable at least city and country — that is sufficient for any map provider to show a meaningful location.',
  AzureMapsPreviewHint:
    'Optional: Add your Azure Maps subscription key to show a small inline map preview in the contact section. If you deployed the Guest Sponsor API, an Azure Maps account was included — copy the key from its Authentication settings. Without a key, only the map link above is shown.',
  AddressMapFallbackHint: 'If no Azure Maps key is configured or map lookup fails, an external map link is shown.',
  UseInformalAddressFieldLabel: 'Use informal salutation (du/tu)',

  SponsorEligibilityGroupName: 'Sponsor Eligibility',
  SponsorEligibilityGroupHint: 'Sponsor assignments in Microsoft Entra are maintained by your organization and may not always be accurate. These filters help improve the quality of sponsors shown to guests and prevent unintended information disclosure caused by incorrect assignments.',

  VersionMismatchTitle: 'Update available',
  VersionMismatchMessage: 'A web part update is available. Ask your administrator to ensure the web part and the Azure Function are running the same version.',
  InsufficientPermissionsTitle: 'Permission required',
  InsufficientPermissionsMessage: 'Could not load sponsor information — a required service permission has not been granted. Please contact your IT administrator.',
  ServiceAuthorizationIssueTitle: 'Temporary service issue',
  ServiceAuthorizationIssueMessage: 'Could not load sponsor information because the sponsor service could not complete an internal authorization step. Please try again in a moment. If the problem continues, contact your IT administrator.',
};
