// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Nastavení",
    ShowTitleFieldLabel: "Zobrazit nadpis",
    TitleFieldLabel: "Nadpis",
    LoadingMessage: "Načítají se sponzoři…",
    NoSponsorsTitle: "Žádní sponzoři nenalezeni",
    NoSponsorsMessage: "Pro váš účet nebyli nalezeni žádní sponzoři.",
    SponsorUnavailableTitle: "Sponzor není k dispozici",
    SponsorUnavailableMessage:
      "Váš sponzor již není k dispozici. Obraťte se na odpovědnou osobu ve vašem projektu, aby byl vašemu účtu přiřazen nový sponzor.",
    ErrorMessageTitle: "Něco se pokazilo",
    ErrorMessage: "Nepodařilo se načíst informace o sponzorovi. Zkuste to prosím znovu.",
    EditModePlaceholder: "Informace o sponzorovi hosta — přepněte do režimu zobrazení, chcete-li vidět sponzory.",
    GuestOnlyPlaceholder: "Tato webová část je viditelná pouze pro hostující uživatele v režimu zobrazení.",
    MockModeFieldLabel: "Povolit veřejný demo režim pro interní uživatele",
    MockModeFieldDescription:
      "Platí pouze pro živou stránku pro návštěvníky. V režimu úprav se náhled nemění. Povolte toto nastavení pro testování webové části se simulovanými sponzory pro interní uživatele ve vašem tenantovi; pokud je zakázáno, obsah sponzorů vidí pouze hosté.",
    MockModeFieldTooltip:
      "Při povolení se demo režim zobrazuje pouze na živé stránce pro testovací účely. Režim úprav a náhled zůstávají nezměněny.",
    MockModePlaceholder:
      "Informace o sponzorovi hosta — Demo režim je aktivní. Přepněte do režimu zobrazení, chcete-li vidět simulované sponzory.",
    MockSimulatedHintFieldLabel: "Simulovat oznámení hosta",
    MockSimulatedHintNoneOption: "Žádné (bez oznámení)",
    MockSimulatedHintTeamsAccessPendingOption: "Teams ještě není nastaveno",
    MockSimulatedHintVersionMismatchOption: "Je k dispozici aktualizace",
    MockSimulatedHintSponsorUnavailableOption: "Sponzor není k dispozici",
    MockSimulatedHintNoSponsorsOption: "Žádní sponzoři nenalezeni",
    MaxSponsorCountFieldLabel: "Viditelní sponzoři",
    MaxSponsorCountFieldTooltip:
      "Omezuje počet zobrazených aktivních karet sponzorů. Do tohoto limitu se započítávají pouze aktivní (dostupní) sponzoři. Pokud účet přiřazeného sponzora přestane být dostupný (je zakázán, odstraněn nebo dosud nezřízen), automaticky přejde na jeho místo další sponzor v pořadí priorit. Hosté tak vždy vidí nakonfigurovaný počet dostupných kontaktů.",
    PresenceAvailable: "K dispozici",
    PresenceAvailableIdle: "K dispozici, nečinný",
    PresenceAway: "Pryč",
    PresenceBeRightBack: "Hned jsem zpět",
    PresenceBusy: "Zaneprázdněný",
    PresenceBusyIdle: "Zaneprázdněný, nečinný",
    PresenceDoNotDisturb: "Nerušit",
    PresenceInAMeeting: "Na schůzce",
    PresenceInACall: "Na hovoru",
    PresencePresenting: "Prezentuje",
    PresenceFocusing: "Soustředění",
    PresenceOutOfOffice: "Mimo kancelář",
    PresenceOutOfOfficeSuffix: ", mimo kancelář",
    PresenceOffline: "Offline",
    ContactDetailsAriaLabel: "Kontaktní údaje pro {0}",
    ContactActionsAriaLabel: "Akce kontaktu",
    CloseLabel: "Zavřít",
    ChatTitle: "Zahájit chat s {name}",
    EmailTitle: "Odeslat e-mail uživateli {name}",
    CallTitle: "Zahájit audiohovor s {name}",
    ChatLabel: "Chat",
    EmailLabel: "E-mail",
    CallLabel: "Hovor",
    ContactInfoSection: "Kontakt",
    EmailFieldLabel: "E-mail",
    WorkPhoneFieldLabel: "Pracovní telefon",
    MobileFieldLabel: "Mobilní telefon",
    WorkLocationFieldLabel: "Místo výkonu práce",
    AddressFieldLabel: "Adresa",
    StreetAddressFieldLabel: "Ulice",
    PostalCodeFieldLabel: "PSČ",
    StateFieldLabel: "Kraj/region",
    OrganizationSection: "Organizace",
    ReportsToSection: "Nadřízený",
    ManagerLabel: "Manažer",
    CopiedFeedback: "Zkopírováno!",
    CopyEmailAriaLabel: "Kopírovat e-mailovou adresu",
    CopyWorkPhoneAriaLabel: "Kopírovat pracovní telefon",
    CopyMobileAriaLabel: "Kopírovat číslo mobilního telefonu",
    CopyLocationAriaLabel: "Kopírovat místo výkonu práce",
    CopyAddressAriaLabel: "Kopírovat adresu",
    CopyStreetAddressAriaLabel: "Kopírovat ulici",
    CopyPostalCodeAriaLabel: "Kopírovat PSČ",
    CopyStateAriaLabel: "Kopírovat kraj/region",
    AddressMapSectionLabel: "Náhled mapy",
    AddressMapLoadingLabel: "Načítání náhledu mapy…",
    OpenAddressInMapLabel: "Otevřít v mapě",
    TeamsAccessPendingTitle: "Microsoft Teams ještě není nastaven",
    TeamsAccessPendingMessage:
      "Váš přístup hosta k Microsoft Teams v této organizaci ještě nebyl nastaven. To nemá vliv na váš vlastní účet Teams. Požádejte svého sponzora, aby vás přidal do týmu — poté budou funkce Teams, jako je chat, hovory a schůzky, dostupné zde.",
    TeamsNotReadyChatTooltip: "Chat není v této organizaci dostupný — váš přístup hosta k Teams ještě nebyl nastaven",
    TeamsNotReadyCallTooltip: "Hovor není v této organizaci dostupný — váš přístup hosta k Teams ještě nebyl nastaven",
    VersionMismatchTitle: "Je k dispozici aktualizace",
    VersionMismatchMessage:
      "Je k dispozici aktualizace webové části. Požádejte správce, aby zajistil, že webová část a Guest Sponsor API používají stejnou verzi.",
    InsufficientPermissionsTitle: "Vyžadováno oprávnění",
    InsufficientPermissionsMessage:
      "Nepodařilo se načíst informace o sponzorovi — požadované oprávnění služby nebylo uděleno. Obraťte se prosím na správce IT.",
    GuestNotificationsGroupName: "Oznámení pro hosty",
    GuestNotificationsGroupHint: "Nastavte, která informační oznámení se zobrazují hostujícím uživatelům.",
    ShowTeamsAccessPendingHintLabel: 'Zobrazit oznámení "Teams ještě není nastaveno"',
    ShowVersionMismatchHintLabel: 'Zobrazit oznámení "Je k dispozici aktualizace"',
    ShowSponsorUnavailableHintLabel: 'Zobrazit oznámení "Sponzor není k dispozici"',
    ShowNoSponsorsHintLabel: 'Zobrazit oznámení "Žádní sponzoři nenalezeni"',
    DisplayGroupName: "Zobrazení",
    CardLayoutFieldLabel: "Rozložení karty",
    CardLayoutAutoOption: "Automatické",
    CardLayoutAutoThresholdFieldLabel: "Přepnout na kompaktní od tohoto počtu sponzorů",
    CardLayoutFullOption: "Plné",
    CardLayoutCompactOption: "Kompaktní",
    ShowBusinessPhonesFieldLabel: "Zobrazit pracovní telefony",
    ShowMobilePhoneFieldLabel: "Zobrazit mobilní telefon",
    ShowWorkLocationFieldLabel: "Zobrazit místo výkonu práce",
    ShowStreetAddressFieldLabel: "Zobrazit ulici",
    ShowPostalCodeFieldLabel: "Zobrazit PSČ",
    ShowStateFieldLabel: "Zobrazit kraj/region",
    AzureMapsSubscriptionKeyFieldLabel: "Klíč předplatného Azure Maps",
    MapProviderModeAutoLabel: "Automatický režim (doporučeno)",
    MapProviderModeManualLabel: "Ruční (stejné pro všechna zařízení)",
    MapProviderModeHint:
      "Zvolte poskytovatele map pro každý operační systém, včetně iOS a Androidu. Odkaz se otevírá v prohlížeči nebo v aplikaci poskytovatele, je-li nainstalována.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Poskytovatel map",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Vypnuto (bez odkazu na mapu)",
    AddressMapProviderHint:
      "Povolte alespoň město a zemi — to stačí, aby jakýkoli poskytovatel map zobrazil smysluplnou polohu.",
    AzureMapsPreviewHint:
      "Přidejte klíč předplatného Azure Maps pro zobrazení malého vloženého náhledu mapy v sekci kontaktu. Pokud jste nasadili Guest Sponsor API, bylo součástí i konto Azure Maps — zkopírujte klíč z jeho ověřovacích nastavení. Bez klíče se zobrazuje pouze výše uvedený odkaz na mapu.",
    ShowManagerFieldLabel: "Zobrazit manažera",
    UseInformalAddressFieldLabel: "Používat neformální oslovení (ty)",
    SponsorEligibilityGroupName: "Způsobilost sponzora",
    SponsorEligibilityGroupHint:
      "Přiřazení sponzorů v Microsoft Entra spravuje vaše organizace a nemusí být vždy přesné. Tyto filtry pomáhají zlepšit kvalitu sponzorů zobrazovaných hostům a zamezit neúmyslnému úniku informací způsobenému nesprávnými přiřazeními.",
    SponsorFilterFieldLabel: "Sponzor musí mít",
    SponsorFilterTeamsOption: "Licenci Teams (doporučeno)",
    SponsorFilterExchangeOption: "Licenci Exchange Online",
    SponsorFilterAnyOption: "Licenci (jakoukoli aktivní licenci)",
    RequireUserMailboxFieldLabel: "Vyžadovat typ poštovní schránky uživatele",
    LocationDisplayHintSeparateRows: "Povolená pole adresy jsou sloučena do jednoho klikatelného řádku.",
    AdvancedDisplayGroupName: "Pokročilé možnosti zobrazení",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "Základní URL",
    WebPartClientIdFieldLabel: "ID aplikace (klienta)",
    SessionCacheTtlMinutesFieldLabel: "Doba trvání mezipaměti relace (minuty)",
    PpClientIdHintLabel: "Kde najdu ID klienta?",
    PpClientIdHintBody: "Zkopírujte ID klienta (ID aplikace) z registrace aplikace vytvořené při nastavení.",
    FunctionEntraLinkLabel: "Najít v Microsoft Entra →",
    ProxyStatusChecking: "Kontrola připojení k Guest Sponsor API…",
    ProxyStatusOk: "Připojení úspěšné",
    ProxyStatusError: "Připojení selhalo",
    PpSetupIntro: "Požadované nastavení:",
    PpSetupRerunHint:
      "Problém s připojením? Instalační skript je idempotentí — opětné spuštění se stejnými parametry vyřeší většinu problémů.",
    CopyToClipboardLabel: "Kopírovat",
    CopiedToClipboardLabel: "Zkopírováno!",
    AuthorSectionGroupName: "O aplikaci",
    AuthorSectionCreatedBy: "Vytvořeno a provozováno",
    AuthorSectionIntro: "Správa Microsoft 365, identita a přístup hostů — naše doména.",
    AuthorSectionWebsiteLinkLabel: "Spolupracujte s námi",
    AuthorSectionConsultingText:
      "Tuto webovou část jsme vytvořili, protože se těmito výzvami zabýváme každý den. Od architektury po zavedení pomáháme organizacím navrhovat bezpečnou a škálovatelnou spolupráci na platformě Microsoft 365.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Verze webové části",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Kliknutím na tlačítko spusťte nasazení:",
    AuthorSectionDeploymentGuideLabel: "Průvodce nasazením",
    NewReleaseAvailableLabel: "Je k dispozici nová verze — kliknutím otevřete GitHub Releases",
    DiagnosticsGroupName: "Přístupnost pro hosty",
    DiagnosticsGroupHint:
      "Ověřuje, zda je balíček JavaScript webové části a web vstupní stránky přístupný pro hostující uživatele B2B.",
    DiagnosticsChecking: "Probíhá kontrola přístupnosti pro hosty…",
    DiagnosticsRetryButtonLabel: "Spustit kontroly znovu",
    DiagPublicCdnOk:
      "Balíček je doručován prostřednictvím veřejné sítě CDN Office 365 — anonymní doručování, pro hosty nejsou vyžadována žádná zvláštní oprávnění.",
    DiagPrivateCdnInfo:
      "Balíček je doručován prostřednictvím privátní sítě CDN Office 365 — hosté s přístupem ke čtení webu jej mohou načíst. Ujistěte se, že hostující uživatelé mají přístup k webu vstupní stránky.",
    DiagSiteColCatalogOk:
      "Balíček je doručován z katalogu aplikací kolekce webů tohoto webu — přístup hostů se řídí vlastními oprávněními webu.",
    DiagTenantCatalogEveryoneOk:
      "Balíček je doručován z katalogu aplikací tenanta. Deklarace identity 'Všichni' má přístup ke čtení katalogu — hostující uživatelé mohou balíček načíst.",
    DiagTenantCatalogEveryoneDenied:
      "Balíček je doručován z katalogu aplikací tenanta, ale 'Všichni' nemají přístup ke čtení. Hostující uživatelé nemohou webovou část načíst. Doporučení: povolte veřejnou síť CDN Office 365 nebo udělte skupině 'Všichni' přístup pro návštěvníky na web katalogu aplikací.",
    DiagTenantCatalogEveryoneUnknown:
      "Balíček je doručován z katalogu aplikací tenanta. Nelze ověřit, zda má skupina 'Všichni' přístup ke čtení (nedostatečná oprávnění). Ověřte ručně, zda hosté mohou přistupovat ke katalogu aplikací, nebo povolte veřejnou síť CDN Office 365.",
    DiagAssetSourceUnknown:
      "Zdroj balíčku nelze určit. Ověřte ručně, zda mohou hostující uživatelé přistupovat k balíčku JavaScript webové části.",
    DiagSiteEveryoneOk:
      "'Všichni' jsou ve skupině Návštěvníci webu — nově přijatí hosté mají okamžitý přístup ke čtení vstupní stránky.",
    DiagSiteEveryoneMissing:
      "'Všichni' nejsou ve skupině Návštěvníci webu. Přístup hostů může záviset na statické skupině zabezpečení Entra (přijatelné) nebo dynamické skupině (zpoždění až 24 h pro nové hosty). Pokud není nakonfigurována žádná skupina zahrnující hosty, zobrazí se jim stránka s odepřeným přístupem.",
    DiagSiteEveryoneUnknown:
      "Nelze ověřit oprávnění návštěvníků webu. Zkontrolujte prosím, zda mají hostující uživatelé na tomto webu alespoň přístup ke čtení.",
    ShowSponsorJobTitleFieldLabel: "Zobrazit pracovní pozici sponzora",
    ShowManagerJobTitleFieldLabel: "Zobrazit pracovní pozici manažera",
    ShowSponsorDepartmentFieldLabel: "Zobrazit oddělení sponzora",
    ShowManagerDepartmentFieldLabel: "Zobrazit oddělení manažera",
    DepartmentLabel: "Oddělení",
    ShowCityFieldLabel: "Zobrazit město",
    ShowCountryFieldLabel: "Zobrazit zemi",
    CityFieldLabel: "Město",
    CountryFieldLabel: "Země",
    CopyCityAriaLabel: "Kopírovat město",
    CopyCountryAriaLabel: "Kopírovat zemi",
    ShowPresenceFieldLabel: "Zobrazit stav přítomnosti",
    ShowSponsorPhotoFieldLabel: "Zobrazit fotografii sponzora",
    ShowManagerPhotoFieldLabel: "Zobrazit fotografii manažera",
    TitlePlaceholder: "Moji sponzoři",
    TitleSizeFieldLabel: "Velikost nadpisu",
    TitleSizeH2Option: "Nadpis 2",
    TitleSizeH3Option: "Nadpis 3",
    TitleSizeH4Option: "Nadpis 4",
    TitleSizeNormalOption: "Normální",
    WelcomeDialogTitle: "Nastavit Informace o sponzorovi hosta",
    WelcomeDialogBody:
      "Tato webová část zobrazuje každému hostujícímu uživateli jeho sponzory ve službě Microsoft Entra na vstupní stránce SharePointu. Aby byla webová část smysluplná, mělo by být přiřazování sponzorů aktivně řízeno a měl by být již zaveden proces správy životního cyklu hostů — webová část tuto odpovědnost zviditelňuje, ale nenahrazuje samotnou správu.",
    WelcomeDialogBroughtToYouBy:
      "Vytvořeno společností Workoho — specialisty na správu přístupu hostů a správu životního cyklu.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Jdeme na to",
    WelcomeDialogNextButton: "Další",
    WelcomeDialogBackButton: "Zpět",
    WelcomeDialogSkipButton: "Teď ne",
    WelcomeDialogSaveButton: "Uložit",
    WelcomeDialogSkipApiButton: "Přeskočit",
    InvalidUrlFormat: "Zadejte platnou adresu URL (např. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Zadejte platný identifikátor GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Vyberte způsob nastavení",
    WelcomeDialogSetupIntro:
      "Vyberte cestu nasazení. Mezi oběma možnostmi lze kdykoli přepínat prostřednictvím nastavení webové části.",
    WelcomeDialogOptionApiTitle: "Použít Guest Sponsor API",
    WelcomeDialogOptionApiBody:
      "Plnohodnotné prostředí využívající Azure Function. Vyžaduje jednorázové nastavení Azure — doporučeno pro produkci.",
    WelcomeDialogOptionApiDocsLabel: "Zobrazit průvodce nastavením",
    WelcomeDialogSetupGuideNote:
      "Tento příkaz je zkrácený postup. Před spuštěním si přečtěte průvodce nastavením — abyste rozuměli, co příkaz dělá.",
    WelcomeDialogDeployToAzureLabel: "Nasadit API do Azure",
    WelcomeDialogDeployNote:
      "Tato možnost vyžaduje nasazení Guest Sponsor API ve vašem předplatném Azure. Můžete to provést přímo zde — zabere to jen pár minut.",
    WelcomeDialogSetupStepsOrderHint: "Postupujte podle kroků v uvedeném pořadí:",
    WelcomeDialogSetupStep1Label: "Vytvořit registraci aplikace",
    WelcomeDialogSetupStep2Hint: "Používá registraci aplikace vytvořenou v kroku 1",
    WelcomeDialogSetupStep3Label: "Udělit oprávnění Graph",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupStep3Hint: "Používá registraci aplikace (krok 1) a URL Function App (krok 2)",
    ViewScriptSourceLabel: "Zkontrolovat skript",
    WelcomeDialogConnectApiTitle: "Zadejte podrobnosti připojení k API",
    WelcomeDialogConnectApiIntro:
      "Zadejte podrobnosti připojení pro vaše Guest Sponsor API. Tento krok můžete prozatím přeskočit a přidat je později v nastavení webowé části.",
    WelcomeDialogUrlHintLabel: "Kde najdu URL?",
    WelcomeDialogUrlHintBody:
      "Zkopírujte URL funkční aplikace z portálu Azure po nasazení. Přejděte do vaší funkční aplikace → Přehled → Výchozí doména.",
    WelcomeDialogOptionDemoTitle: "Prozkoumat v demo režimu",
    WelcomeDialogOptionDemoBody:
      "Povolte demo režim pro zobrazení simulovaných sponzorů na živé stránce, včetně interních uživatelů ve vašem tenantovi. Toto nastavení použijte pro testování bez nastavení Azure a kdykoli přepněte na skutečné API.",
    WelcomeDialogFunctionUrlRequired: "Zadejte základní URL adresu Guest Sponsor API.",
    WelcomeDialogDoneApiTitle: "API nakonfigurováno!",
    WelcomeDialogDoneApiBody:
      "Připojení k Guest Sponsor API bylo uloženo. Nezapomeňte stránku uložit, aby se nastavení uplatnilo pro všechny.",
    WelcomeDialogDoneApiSkippedTitle: "Téměř hotovo!",
    WelcomeDialogDoneApiSkippedBody:
      "Nebyly zadány žádné přihlašovací údaje. Dokončení nastavení: otevřete nastavení webowé části, zadejte Base URL a ID klienta v části Guest Sponsor API a uložte stránku.",
    WelcomeDialogDoneDemoTitle: "Demo režim aktivován!",
    WelcomeDialogDoneDemoBody:
      "Demo režim je nyní aktivní pro živou stránku. Uložte stránku, aby se použil pro návštěvníky, a přepněte do režimu zobrazení pro ověření simulovaných karet sponzorů.",
    PpSectionLivePage: "▶ Živá stránka",
    PpSectionDemoMode: "🧪 Veřejný demo režim",
    PpSectionCardLayout: "🗂️ Rozložení karet",
    PpSectionProfileFields: "👤 Pole profilu",
    PpSectionPhone: "📞 Telefonní čísla",
    PpSectionWorkLocation: "📍 Místo výkonu práce",
    PpSectionAddress: "🏠 Poštovní adresa",
    PpSectionMapLink: "🧭 Odkaz na mapu",
    PpSectionMapPreview: "🗺️ Vložený náhled mapy"
  };
});
