define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurer webdelen Gæstesponsoroplysninger.",
    "BasicGroupName": "Indstillinger",
    "TitleFieldLabel": "Titel",
    "LoadingMessage": "Indlæser dine sponsorer…",
    "NoSponsorsTitle": "Ingen sponsorer fundet",
    "NoSponsorsMessage": "Der blev ikke fundet nogen sponsorer for din konto.",
    "SponsorUnavailableTitle": "Sponsor ikke tilgængelig",
    "SponsorUnavailableMessage": "Din sponsor er ikke længre tilgængelig. Kontakt din projektansvarlige om at få tildelt en ny sponsor til din konto.",
    "ErrorMessageTitle": "Noget gik galt",
    "ErrorMessage": "Det var ikke muligt at indlæse sponsoroplysninger. Prøv igen senere.",
    "EditModePlaceholder": "Gæstesponsoroplysninger — skift til visningstilstand for at se sponsorer.",
    "GuestOnlyPlaceholder": "Denne webdel er kun synlig for gæstebrugere i visningstilstand.",
    "MockModeFieldLabel": "Vis altid demo-sponsorer (offentlig demotilstand)",
    "MockModePlaceholder": "Gæstesponsoroplysninger — Demotilstand aktiv. Skift til visningstilstand for at se testdata.",
    "MockSimulatedHintFieldLabel": "Simuler gæstenotifikation",
    "MockSimulatedHintNoneOption": "Ingen notifikation",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams ikke konfigureret endnu",
    "MockSimulatedHintVersionMismatchOption": "Opdatering tilgængelig",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsor ikke tilgængelig",
    "MockSimulatedHintNoSponsorsOption": "Ingen sponsorer fundet",
    "MaxSponsorCountFieldLabel": "Synlige sponsorer (live-side)",
    "MockSponsorCountFieldLabel": "Antal demosponsorers",

    "PresenceAvailable": "Tilgængelig",
    "PresenceAvailableIdle": "Tilgængelig, inaktiv",
    "PresenceAway": "Væk",
    "PresenceBeRightBack": "Er lige straks tilbage",
    "PresenceBusy": "Optaget",
    "PresenceBusyIdle": "Optaget, inaktiv",
    "PresenceDoNotDisturb": "Forstyr ikke",
    "PresenceInAMeeting": "I et møde",
    "PresenceInACall": "I et opkald",
    "PresencePresenting": "Præsenterer",
    "PresenceFocusing": "Fokuseret",
    "PresenceOutOfOffice": "Uden for kontoret",
    "PresenceOutOfOfficeSuffix": ", uden for kontoret",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Kontaktoplysninger for {0}",
    "ContactActionsAriaLabel": "Kontakthandlinger",
    "ChatTitle": "Start en chat med {name}",
    "EmailTitle": "Send e-mail til {name}",
    "CallTitle": "Start et lydopkald med {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Ring op",

    "ContactInfoSection": "Kontakt",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Arbejdstelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbejdssted",
    "AddressFieldLabel": "Adresse",
    "StreetAddressFieldLabel": "Gade",
    "PostalCodeFieldLabel": "Postnummer",
    "StateFieldLabel": "Stat/region",

    "OrganizationSection": "Organisation",
    "ReportsToSection": "Rapporterer til",
    "ManagerLabel": "Chef",

    "CopiedFeedback": "Kopieret!",
    "CopyEmailAriaLabel": "Kopiér e-mailadresse",
    "CopyWorkPhoneAriaLabel": "Kopiér arbejdstelefon",
    "CopyMobileAriaLabel": "Kopiér mobilnummer",
    "CopyLocationAriaLabel": "Kopiér arbejdssted",
    "CopyAddressAriaLabel": "Kopiér adresse",
    "CopyStreetAddressAriaLabel": "Kopier gade",
    "CopyPostalCodeAriaLabel": "Kopier postnummer",
    "CopyStateAriaLabel": "Kopier stat/region",
    "AddressMapSectionLabel": "Kortforhåndsvisning",
    "AddressMapLoadingLabel": "Indlæser kortforhåndsvisning...",
    "OpenAddressInMapLabel": "Åbn i kort",

    "TeamsAccessPendingTitle": "Microsoft Teams er endnu ikke konfigureret",
    "TeamsAccessPendingMessage": "Din gæsteadgang til Microsoft Teams i denne organisation er endnu ikke konfigureret. Din egen Teams-konto er ikke berørt. Bed din sponsor om at tilføje dig til et team — derefter kan du bruge Teams-funktioner som chat, opkald og møder her.",
    "TeamsNotReadyChatTooltip": "Chat ikke tilgængelig her — din Teams-gæsteadgang er endnu ikke konfigureret",
    "TeamsNotReadyCallTooltip": "Opkald ikke tilgængeligt her — din Teams-gæsteadgang er endnu ikke konfigureret",

    "VersionMismatchTitle": "Opdatering tilgængelig",
    "VersionMismatchMessage": "Der er en opdatering tilgængelig til denne webdel. Bed din administrator om at sikre, at webdelen og Guest Sponsor API kører den samme version.",
    "InsufficientPermissionsTitle": "Manglende tilladelse",
    "InsufficientPermissionsMessage": "Det var ikke muligt at indlæse sponsoroplysninger — en påkrævet servicetilladelse er ikke tildelt. Kontakt din IT-administrator.",

    "GuestNotificationsGroupName": "Notifikationer til gæster",
    "GuestNotificationsGroupHint": "Styr hvilke informationsmeddelelser der vises til gæstebrugere.",
    "ShowTeamsAccessPendingHintLabel": "Vis notifikation \"Microsoft Teams ikke konfigureret endnu\"",
    "ShowVersionMismatchHintLabel": "Vis notifikation \"Opdatering tilgængelig\"",
    "ShowSponsorUnavailableHintLabel": "Vis notifikation \"Sponsor ikke tilgængelig\"",
    "ShowNoSponsorsHintLabel": "Vis notifikation \"Ingen sponsorer fundet\"",
    "DisplayGroupName": "Visning",
    "CardLayoutFieldLabel": "Kortlayout",
    "CardLayoutAutoOption": "Automatisk",
    "CardLayoutAutoThresholdFieldLabel": "Skift til kompakt layout fra dette antal sponsorer",
    "CardLayoutFullOption": "Fuld",
    "CardLayoutCompactOption": "Kompakt",
    "ShowBusinessPhonesFieldLabel": "Vis arbejdstelefonnumre",
    "ShowMobilePhoneFieldLabel": "Vis mobilnummer",
    "ShowWorkLocationFieldLabel": "Vis arbejdssted",
    "ShowManagerFieldLabel": "Vis chef",
    "UseInformalAddressFieldLabel": "Uformel tiltaleform",
    "ShowWorkLocationFallbackFieldLabel": "Vis arbejdssted som fallback",
    "LocationDisplayHintGeoWithFallback": "By og land kombineres til én geografisk linje. Arbejdsstedet vises kun, hvis der ikke findes by-/landdata.",
    "LocationDisplayHintGeoOnly": "By og land kombineres til én geografisk linje. Arbejdsstedet er skjult.",
    "LocationDisplayHintOfficeOnly": "Kun arbejdsstedet vises. Aktivér by og/eller land for i stedet at vise en geografisk linje.",
    "LocationDisplayHintHidden": "Alle placerings- og adressefelter er skjult.",
    "LocationDisplayHintSeparateRows": "Aktiverede adressefelter kombineres til en enkelt klikbar række.",
    "AdvancedDisplayGroupName": "Avancerede visningsindstillinger",
    "ManagerOptionsDisabledHint": "Aktivér visning af chef for at konfigurere chefrelaterede felter.",

  "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "Guest Sponsor API basis-URL",
    "FunctionClientIdFieldLabel": "Guest Sponsor API klient-ID (appregistrering)",
    "ProxyStatusChecking": "Tjekker Guest Sponsor API…",
    "ProxyStatusOk": "Guest Sponsor API er tilgængelig",
    "ProxyStatusError": "Guest Sponsor API er ikke tilgængelig",
    "AuthorSectionGroupName": "Om Workoho",
    "AuthorSectionIntro": "Microsoft 365-governance, identiteter og gæsteadgang \u2014 vores felt.",
    "AuthorSectionWebsiteLinkLabel": "Kom i kontakt",
    "AuthorSectionConsultingText": "Vi har bygget dette webpart, fordi det er præcis det, vi arbejder med til daglig. Fra arkitektur til udrulning hjælper vi organisationer med at opbygge sikre og skalerbare samarbejdsmiljøer på Microsoft 365.",
    "AuthorSectionPartnerPrefix": "Workoho er",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum-salgs- og implementeringspartner.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automatiserer livscyklusstyring for Teams, SharePoint-websteder, Viva Engage og andre Microsoft 365-arbejdsområder — herunder gæsteoptagelse og sponsorhåndtering.",
    "AuthorSectionSourceCodeLabel": "Kildekode på GitHub",
    "AuthorSectionVersionLabel": "Webpart-version",
    "ShowSponsorJobTitleFieldLabel": "Vis sponsors jobtitel",
    "ShowManagerJobTitleFieldLabel": "Vis lederens jobtitel",
    "ShowSponsorDepartmentFieldLabel": "Vis sponsors afdeling",
    "ShowManagerDepartmentFieldLabel": "Vis lederens afdeling",
    "DepartmentLabel": "Afdeling",
    "ShowCityFieldLabel": "Vis by",
    "ShowCountryFieldLabel": "Vis land",
    "ShowStreetAddressFieldLabel": "Vis gade",
    "ShowPostalCodeFieldLabel": "Vis postnummer",
    "ShowStateFieldLabel": "Vis stat/region",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-abonnementsnøgle",
    "ExternalMapProviderFieldLabel": "Kortudbyder",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "MapProviderNoneOption": "Deaktiveret (intet kortlink)",
    "AddressMapProviderHint": "Aktiver mindst by og land — det er nok til, at enhver korttjeneste kan vise en meningsfuld placering.",
    "CityFieldLabel": "By",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopiér by",
    "CopyCountryAriaLabel": "Kopiér land",
    "ShowPresenceFieldLabel": "Vis tilstedeværelsesstatus",
    "ShowSponsorPhotoFieldLabel": "Vis sponsor-foto",
    "ShowManagerPhotoFieldLabel": "Vis overordnets foto",
  }
});
