define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurer webdelen G\u00e6stesponsoroplysninger.",
    "BasicGroupName": "Indstillinger",
    "TitleFieldLabel": "Titel",
    "LoadingMessage": "Indl\u00e6ser dine sponsorer\u2026",
    "NoSponsorsMessage": "Der blev ikke fundet nogen sponsorer for din konto.",
    "SponsorUnavailableMessage": "Din sponsor/ejer er ikke l\u00e6ngre tilg\u00e6ngelig. Kontakt din projektansvarlige om at f\u00e5 tildelt en ny sponsor/ejer til din konto.",
    "ErrorMessage": "Det var ikke muligt at indl\u00e6se sponsoroplysninger. Pr\u00f8v igen senere.",
    "EditModePlaceholder": "G\u00e6stesponsoroplysninger \u2014 skift til visningstilstand for at se sponsorer.",
    "GuestOnlyPlaceholder": "Denne webdel er kun synlig for g\u00e6stebrugere i visningstilstand.",
    "MockModeFieldLabel": "Demotilstand (testdata)",
    "MockModePlaceholder": "G\u00e6stesponsoroplysninger \u2014 Demotilstand aktiv. Skift til visningstilstand for at se testdata.",

    "PresenceAvailable": "Tilg\u00e6ngelig",
    "PresenceAvailableIdle": "Tilg\u00e6ngelig, inaktiv",
    "PresenceAway": "V\u00e6k",
    "PresenceBeRightBack": "Er lige straks tilbage",
    "PresenceBusy": "Optaget",
    "PresenceBusyIdle": "Optaget, inaktiv",
    "PresenceDoNotDisturb": "Forstyr ikke",
    "PresenceInAMeeting": "I et m\u00f8de",
    "PresenceInACall": "I et opkald",
    "PresencePresenting": "Pr\u00e6senterer",
    "PresenceFocusing": "Fokuseret",
    "PresenceOutOfOffice": "Uden for kontoret",
    "PresenceOutOfOfficeSuffix": ", uden for kontoret",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Kontaktoplysninger for {0}",
    "ContactActionsAriaLabel": "Kontakthandlinger",
    "ChatTitle": "Chat i Microsoft Teams",
    "EmailTitle": "Send e-mail",
    "CallTitle": "Lydopkald i Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Ring op",

    "ContactInfoSection": "Kontaktoplysninger",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Arbejdstelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbejdssted",
    "StreetAddressFieldLabel": "Gade",
    "PostalCodeFieldLabel": "Postnummer",
    "StateFieldLabel": "Stat/region",

    "OrganizationSection": "Organisation",
    "ManagerLabel": "Chef",

    "CopiedFeedback": "Kopieret!",
    "CopyEmailAriaLabel": "Kopi\u00e9r e-mailadresse",
    "CopyWorkPhoneAriaLabel": "Kopi\u00e9r arbejdstelefon",
    "CopyMobileAriaLabel": "Kopi\u00e9r mobilnummer",
    "CopyLocationAriaLabel": "Kopi\u00e9r arbejdssted",
    "CopyStreetAddressAriaLabel": "Kopier gade",
    "CopyPostalCodeAriaLabel": "Kopier postnummer",
    "CopyStateAriaLabel": "Kopier stat/region",
    "AddressMapSectionLabel": "Kortforhandsvisning",
    "AddressMapLoadingLabel": "Indlaeser kortforhandsvisning...",
    "OpenAddressInMapLabel": "Aabn i kort",

    "TeamsAccessPendingTitle": "Microsoft Teams er endnu ikke konfigureret",
    "TeamsAccessPendingMessage": "Din g\u00e6steadgang til Microsoft Teams i denne organisation er endnu ikke konfigureret. Din egen Teams-konto er ikke ber\u00f8rt. Bed din sponsor om at tilf\u00f8je dig til et team \u2014 derefter kan du bruge Teams-funktioner som chat, opkald og m\u00f8der her.",
    "TeamsNotReadyChatTooltip": "Chat ikke tilg\u00e6ngelig her \u2014 din Teams-g\u00e6steadgang er endnu ikke konfigureret",
    "TeamsNotReadyCallTooltip": "Opkald ikke tilg\u00e6ngeligt her \u2014 din Teams-g\u00e6steadgang er endnu ikke konfigureret",

    "DisplayGroupName": "Visning",
    "ShowBusinessPhonesFieldLabel": "Vis arbejdstelefonnumre",
    "ShowMobilePhoneFieldLabel": "Vis mobilnummer",
    "ShowWorkLocationFieldLabel": "Vis arbejdssted",
    "ShowManagerFieldLabel": "Vis chef",
    "UseInformalAddressFieldLabel": "Uformel tiltaleform",
    "ShowWorkLocationFallbackFieldLabel": "Vis arbejdssted som fallback",
    "LocationDisplayHintGeoWithFallback": "By og land kombineres til én geografisk linje. Arbejdsstedet vises kun, hvis der ikke findes by-/landdata.",
    "LocationDisplayHintGeoOnly": "By og land kombineres til én geografisk linje. Arbejdsstedet er skjult.",
    "LocationDisplayHintOfficeOnly": "Kun arbejdsstedet vises. Aktivér by og/eller land for i stedet at vise en geografisk linje.",
    "LocationDisplayHintHidden": "Alle lokaliseringsoplysninger er skjult.",
    "AddressMapFallbackHint": "Hvis der ikke er konfigureret en Azure Maps-nogle, eller opslaget fejler, vises et eksternt kortlink.",
    "LocationDisplayHintAddressEnabled": "Strukturerede adressefelter er aktiveret og kan vises i ekstra raekker.",
    "LocationDisplayHintSeparateRows": "By/land og arbejdssted vises som separate raekker, naar de er aktiveret.",
    "AdvancedDisplayGroupName": "Avancerede visningsindstillinger",
    "ManagerOptionsDisabledHint": "Aktivér visning af chef for at konfigurere chefrelaterede felter.",

  "FunctionGroupName": "Azure-funktion",
    "FunctionUrlFieldLabel": "Sponsor-API-URL (Azure-funktion)",
    "FunctionClientIdFieldLabel": "Sponsor-API-klient-ID (Azure Function-appregistrering)",
    "ProxyStatusChecking": "Tjekker Azure-funktion\u2026",
    "ProxyStatusOk": "Azure-funktion er tilg\u00e6ngelig",
    "ProxyStatusError": "Azure-funktion er ikke tilg\u00e6ngelig",
    "ShowSponsorJobTitleFieldLabel": "Vis sponsors jobtitel",
    "ShowManagerJobTitleFieldLabel": "Vis lederens jobtitel",
    "ShowSponsorDepartmentFieldLabel": "Vis sponsors afdeling",
    "ShowManagerDepartmentFieldLabel": "Vis lederens afdeling",
    "DepartmentLabel": "Afdeling",
    "ShowCityFieldLabel": "Vis by",
    "ShowCountryFieldLabel": "Vis land",
    "ShowStructuredAddressFieldLabel": "Vis struktureret adresse",
    "ShowStreetAddressFieldLabel": "Vis gade",
    "ShowPostalCodeFieldLabel": "Vis postnummer",
    "ShowStateFieldLabel": "Vis stat/region",
    "ShowAddressMapFieldLabel": "Vis kortforhandsvisning af adresse",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-abonnementsnogle",
    "ExternalMapProviderFieldLabel": "Ekstern kortudbyder (fallback)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "By",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopi\u00e9r by",
    "CopyCountryAriaLabel": "Kopi\u00e9r land",
    "ShowPresenceFieldLabel": "Vis tilstedev\u00e6relsesstatus"
  }
});
