// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function() {
  return {
    "BasicGroupName": "Indstillinger",
    "ShowTitleFieldLabel": "Vis titel",
    "TitleFieldLabel": "Titel",
    "LoadingMessage": "Indlæser dine sponsorer…",
    "NoSponsorsTitle": "Ingen sponsorer fundet",
    "NoSponsorsMessage": "Der blev ikke fundet nogen sponsorer for din konto.",
    "SponsorUnavailableTitle": "Sponsor ikke tilgængelig",
    "SponsorUnavailableMessage": "Din sponsor er ikke længre tilgængelig. Kontakt din projektansvarlige om at få tildelt en ny sponsor til din konto.",
    "ErrorMessageTitle": "Noget gik galt",
    "ErrorMessage": "Det var ikke muligt at indlæse sponsoroplysninger. Prøv igen senere.",
    "EditModePlaceholder": "Gæstesponsoroplysninger — skift til visningstilstand for at se sponsorer.",
    "GuestOnlyPlaceholder": "Denne webdel er kun synlig for gæstebrugere i visningstilstand.",
    "MockModeFieldLabel": "Vis altid demo-sponsorer (offentlig demotilstand)",
    "MockModeFieldDescription": "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    "MockModeFieldTooltip": "Når aktiveret, vises demotilstand kun på live-siden til testformål. Redigeringstilstand og eksempel ændres ikke.",
    "MockModePlaceholder": "Gæstesponsoroplysninger — Demotilstand aktiv. Skift til visningstilstand for at se testdata.",
    "MockSimulatedHintFieldLabel": "Simuler gæstenotifikation",
    "MockSimulatedHintNoneOption": "Ingen notifikation",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams ikke konfigureret endnu",
    "MockSimulatedHintVersionMismatchOption": "Opdatering tilgængelig",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsor ikke tilgængelig",
    "MockSimulatedHintNoSponsorsOption": "Ingen sponsorer fundet",
    "MaxSponsorCountFieldLabel": "Synlige sponsorer",
    "MaxSponsorCountFieldTooltip": "Begrænser antallet af viste sponsor-kort. Kun aktive (tilgængelige) sponsorer tælles mod denne grænse. Hvis en tildelt sponsor ikke længere er tilgængelig (deaktiveret, slettet eller endnu ikke klargjort), rykker næste sponsor i prioriteringsorden automatisk op for at fylde pladsen. Dette sikrer, at gæsten altid ser det konfigurerede antal af tilgængelige kontakter.",

    "PresenceAvailable": "Tilgængelig",
    "PresenceAvailableIdle": "Tilgængelig, inaktiv",
    "PresenceAway": "Væk",
    "PresenceBeRightBack": "Er lige straks tilbage",
    "PresenceBusy": "Optaget",
    "PresenceBusyIdle": "Optaget, inaktiv",
    "PresenceDoNotDisturb": "Forstyr ikke",
    "PresenceInAMeeting": "I et møde",
    "PresenceInACall": "I et opkald",
    "PresencePresenting": "Præsenterer",
    "PresenceFocusing": "Fokuseret",
    "PresenceOutOfOffice": "Uden for kontoret",
    "PresenceOutOfOfficeSuffix": ", uden for kontoret",
    "PresenceOffline": "Offline",

    "CloseLabel": "Luk",
    "ContactDetailsAriaLabel": "Kontaktoplysninger for {0}",
    "ContactActionsAriaLabel": "Kontakthandlinger",
    "ChatTitle": "Start en chat med {name}",
    "EmailTitle": "Send e-mail til {name}",
    "CallTitle": "Start et lydopkald med {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Ring op",

    "ContactInfoSection": "Kontakt",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Arbejdstelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbejdssted",
    "AddressFieldLabel": "Adresse",
    "StreetAddressFieldLabel": "Gade",
    "PostalCodeFieldLabel": "Postnummer",
    "StateFieldLabel": "Stat/region",

    "OrganizationSection": "Organisation",
    "ReportsToSection": "Rapporterer til",
    "ManagerLabel": "Chef",

    "CopiedFeedback": "Kopieret!",
    "CopyEmailAriaLabel": "Kopiér e-mailadresse",
    "CopyWorkPhoneAriaLabel": "Kopiér arbejdstelefon",
    "CopyMobileAriaLabel": "Kopiér mobilnummer",
    "CopyLocationAriaLabel": "Kopiér arbejdssted",
    "CopyAddressAriaLabel": "Kopiér adresse",
    "CopyStreetAddressAriaLabel": "Kopier gade",
    "CopyPostalCodeAriaLabel": "Kopier postnummer",
    "CopyStateAriaLabel": "Kopier stat/region",
    "AddressMapSectionLabel": "Kortforhåndsvisning",
    "AddressMapLoadingLabel": "Indlæser kortforhåndsvisning...",
    "OpenAddressInMapLabel": "Åbn i kort",

    "TeamsAccessPendingTitle": "Microsoft Teams er endnu ikke konfigureret",
    "TeamsAccessPendingMessage": "Din gæsteadgang til Microsoft Teams i denne organisation er endnu ikke konfigureret. Din egen Teams-konto er ikke berørt. Bed din sponsor om at tilføje dig til et team — derefter kan du bruge Teams-funktioner som chat, opkald og møder her.",
    "TeamsNotReadyChatTooltip": "Chat ikke tilgængelig her — din Teams-gæsteadgang er endnu ikke konfigureret",
    "TeamsNotReadyCallTooltip": "Opkald ikke tilgængeligt her — din Teams-gæsteadgang er endnu ikke konfigureret",

    "VersionMismatchTitle": "Opdatering tilgængelig",
    "VersionMismatchMessage": "Der er en opdatering tilgængelig til denne webdel. Bed din administrator om at sikre, at webdelen og Guest Sponsor API kører den samme version.",
    "InsufficientPermissionsTitle": "Manglende tilladelse",
    "InsufficientPermissionsMessage": "Det var ikke muligt at indlæse sponsoroplysninger — en påkrævet servicetilladelse er ikke tildelt. Kontakt din IT-administrator.",

    "GuestNotificationsGroupName": "Notifikationer til gæster",
    "GuestNotificationsGroupHint": "Styr hvilke informationsmeddelelser der vises til gæstebrugere.",
    "ShowTeamsAccessPendingHintLabel": "Vis notifikation \"Microsoft Teams ikke konfigureret endnu\"",
    "ShowVersionMismatchHintLabel": "Vis notifikation \"Opdatering tilgængelig\"",
    "ShowSponsorUnavailableHintLabel": "Vis notifikation \"Sponsor ikke tilgængelig\"",
    "ShowNoSponsorsHintLabel": "Vis notifikation \"Ingen sponsorer fundet\"",
    "DisplayGroupName": "Visning",
    "CardLayoutFieldLabel": "Kortlayout",
    "CardLayoutAutoOption": "Automatisk",
    "CardLayoutAutoThresholdFieldLabel": "Skift til kompakt layout fra dette antal sponsorer",
    "CardLayoutFullOption": "Fuld",
    "CardLayoutCompactOption": "Kompakt",
    "ShowBusinessPhonesFieldLabel": "Vis arbejdstelefonnumre",
    "ShowMobilePhoneFieldLabel": "Vis mobilnummer",
    "ShowWorkLocationFieldLabel": "Vis arbejdssted",
    "ShowManagerFieldLabel": "Vis chef",
    "SponsorEligibilityGroupName": "Sponsorberettigelse",
    "SponsorEligibilityGroupHint": "Sponsortildelinger i Microsoft Entra vedligeholdes af din organisation og er ikke altid korrekte. Disse filtre forbedrer kvaliteten af de viste sponsorer og forebygger utilsigtet videregivelse af oplysninger som følge af forkerte tildelinger.",
    "SponsorFilterFieldLabel": "Sponsor skal være",
    "SponsorFilterTeamsOption": "Teams-licenseret (anbefalet)",
    "SponsorFilterExchangeOption": "Exchange Online-licenseret",
    "SponsorFilterAnyOption": "Licenseret (enhver aktiv licens)",
    "RequireUserMailboxFieldLabel": "Kræv brugerpostbokstype",
    "UseInformalAddressFieldLabel": "Uformel tiltaleform",
    "LocationDisplayHintSeparateRows": "Aktiverede adressefelter kombineres til en enkelt klikbar række.",
    "AdvancedDisplayGroupName": "Avancerede visningsindstillinger",

  "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "Basis-URL",
    "FunctionClientIdFieldLabel": "Program-id (klient)",
    "PpClientIdHintLabel": "Hvor finder jeg klient-ID?",
    "PpClientIdHintBody": "Kopi\u00e9r klient-ID (program-ID) fra den appregistrering, der blev oprettet under ops\u00e6tningen.",
    "FunctionEntraLinkLabel": "Find i Microsoft Entra →",
    "ProxyStatusChecking": "Tjekker forbindelse…",
    "ProxyStatusOk": "Forbindelse oprettet",
    "ProxyStatusError": "Forbindelse mislykkedes",
    "PpSetupIntro": "Påkrævet opsætning:",
    "PpSetupRerunHint": "Forbindelsesproblem? Opsætningsscripterne er idempotente \u2014 kør dem igen med samme parametre for at løse de fleste problemer.",
    "CopyToClipboardLabel": "Kopiér",
    "CopiedToClipboardLabel": "Kopieret!",
    "AuthorSectionGroupName": "Om",
    "AuthorSectionCreatedBy": "Oprettet og vedligeholdt af",
    "AuthorSectionIntro": "Microsoft 365-governance, identiteter og gæsteadgang \u2014 vores felt.",
    "AuthorSectionWebsiteLinkLabel": "Kom i kontakt",
    "AuthorSectionConsultingText": "Vi har bygget dette webpart, fordi det er præcis det, vi arbejder med til daglig. Fra arkitektur til udrulning hjælper vi organisationer med at opbygge sikre og skalerbare samarbejdsmiljøer på Microsoft 365.",
    "AuthorSectionAppWebsiteLabel": "Website",
    "AuthorSectionVersionLabel": "Webpart-version",
    "AuthorSectionDeployToAzureLabel": "Deploy to Azure",
    "DeployToAzureClickHint": "Klik p\u00e5 knappen for at starte udrulningen:",
    "AuthorSectionDeploymentGuideLabel": "Installationsvejledning",
    "NewReleaseAvailableLabel": "Ny version tilg\u00e6ngelig \u2014 \u00e5bn GitHub Releases",

    // Diagnostik: g\u00e6stens tilg\u00e6ngelighed
    "DiagnosticsGroupName": "G\u00e6stetilg\u00e6ngelighed",
    "DiagnosticsGroupHint": "Kontrollerer, om web parts JavaScript-bundle og landingssiten er tilg\u00e6ngelige for B2B-g\u00e6stbrugere.",
    "DiagnosticsChecking": "Kontrollerer g\u00e6stetilg\u00e6ngelighed\u2026",
    "DiagPublicCdnOk": "Bundle leveres via det offentlige Office 365 CDN \u2014 anonym levering, ingen s\u00e6rlige tilladelser kr\u00e6ves for g\u00e6ster.",
    "DiagPrivateCdnInfo": "Bundle leveres via det private Office 365 CDN \u2014 g\u00e6ster med l\u00e6seadgang til sitet kan indl\u00e6se det. S\u00f8rg for, at landingssiten er tilg\u00e6ngelig for g\u00e6ster.",
    "DiagSiteColCatalogOk": "Bundle leveres fra site-samlingens app-katalog \u2014 g\u00e6steadgang f\u00f8lger sitets egne tilladelser.",
    "DiagTenantCatalogEveryoneOk": "Bundle leveres fra lejerens app-katalog. Gruppen \u2018Alle\u2019 har l\u00e6seadgang til kataloget \u2014 g\u00e6stbrugere kan indl\u00e6se bundlet.",
    "DiagTenantCatalogEveryoneDenied": "Bundle leveres fra lejerens app-katalog, men \u2018Alle\u2019 har ikke l\u00e6seadgang. G\u00e6stbrugere kan ikke indl\u00e6se web partet. Anbefaling: aktiv\u00e9r det offentlige Office 365 CDN, eller giv \u2018Alle\u2019 G\u00e6steadgang til app-katalogssitet.",
    "DiagTenantCatalogEveryoneUnknown": "Bundle leveres fra lejerens app-katalog. Det var ikke muligt at kontrollere, om \u2018Alle\u2019 har l\u00e6seadgang (utilstr\u00e6kkelige rettigheder). Kontroller manuelt, at g\u00e6ster kan n\u00e5 kataloget, eller aktiv\u00e9r det offentlige Office 365 CDN.",
    "DiagAssetSourceUnknown": "Kilden til bundlet kunne ikke fastsl\u00e5s. Kontroller manuelt, at g\u00e6stbrugere kan tilg\u00e5 web partets JavaScript-bundle.",
    "DiagSiteEveryoneOk": "\u2018Alle\u2019 er i sitets Bes\u00f8gende-gruppe \u2014 nyligt accepterede g\u00e6ster f\u00e5r straks l\u00e6seadgang til landingssiden.",
    "DiagSiteEveryoneMissing": "\u2018Alle\u2019 er ikke i sitets Bes\u00f8gende-gruppe. G\u00e6steadgang afh\u00e6nger m\u00e5ske af en statisk Entra-sikkerhedsgruppe (acceptabelt) eller dynamisk gruppe (op til 24\u00a0timers forsinkelse for nye g\u00e6ster). Hvis ingen g\u00e6stevenlig gruppe er konfigureret, ser g\u00e6ster en adgang-n\u00e6gtet-side.",
    "DiagSiteEveryoneUnknown": "Sitets bes\u00f8gendertilladelser kunne ikke verificeres. S\u00f8rg for, at g\u00e6stbrugere har mindst l\u00e6seadgang til dette site.",
    "ShowSponsorJobTitleFieldLabel": "Vis sponsors jobtitel",
    "ShowManagerJobTitleFieldLabel": "Vis lederens jobtitel",
    "ShowSponsorDepartmentFieldLabel": "Vis sponsors afdeling",
    "ShowManagerDepartmentFieldLabel": "Vis lederens afdeling",
    "DepartmentLabel": "Afdeling",
    "ShowCityFieldLabel": "Vis by",
    "ShowCountryFieldLabel": "Vis land",
    "ShowStreetAddressFieldLabel": "Vis gade",
    "ShowPostalCodeFieldLabel": "Vis postnummer",
    "ShowStateFieldLabel": "Vis stat/region",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-abonnementsnøgle",
    "MapProviderModeAutoLabel": "Automatik-tilstand (anbefalet)",
    "MapProviderModeManualLabel": "Manuelt (ensartet for alle enheder)",
    "MapProviderModeHint": "Vælg en kortudbyder pr. operativsystem, herunder iOS og Android. Linket åbnes i browseren eller i udbyderens app, hvis den er installeret.",
    "MapProviderIosLabel": "iOS:",
    "MapProviderAndroidLabel": "Android:",
    "MapProviderWindowsLabel": "Windows:",
    "MapProviderMacOSLabel": "macOS:",
    "MapProviderLinuxLabel": "Linux:",
    "ExternalMapProviderFieldLabel": "Kortudbyder",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderNoneOption": "Deaktiveret (intet kortlink)",
    "AddressMapProviderHint": "Aktiver mindst by og land — det er nok til, at enhver korttjeneste kan vise en meningsfuld placering.",
    "AzureMapsPreviewHint": "Tilføj din Azure Maps-abonnementsnøgle for at vise en lille kortforhåndsvisning i kontaktsektionen. Hvis du har udrullet Guest Sponsor API'et, er der inkluderet en Azure Maps-konto - kopiér nøglen fra dens godkendelsesindstillinger. Uden nøgle vises kun kortlinket ovenfor.",
    "CityFieldLabel": "By",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopiér by",
    "CopyCountryAriaLabel": "Kopiér land",
    "ShowPresenceFieldLabel": "Vis tilstedeværelsesstatus",
    "ShowSponsorPhotoFieldLabel": "Vis sponsor-foto",
    "ShowManagerPhotoFieldLabel": "Vis overordnets foto",
    "TitlePlaceholder": "Mine sponsorer",
    "TitleSizeFieldLabel": "Titelstørrelse",
    "TitleSizeH2Option": "Overskrift 2",
    "TitleSizeH3Option": "Overskrift 3",
    "TitleSizeH4Option": "Overskrift 4",
    "TitleSizeNormalOption": "Normal",

    "WelcomeDialogTitle": "Konfigurer Gæstesponsoroplysninger",
    "WelcomeDialogBody": "Denne webdel viser hver gæstebruger deres Microsoft Entra-sponsorer på din SharePoint-landingsside. For at webdelen skal give mening, bør sponsortildelinger aktivt vedligeholdes og en livscyklusproces for gæster allerede være på plads — den synliggør dette ansvar, men erstatter ikke den underliggende styring.",
    "WelcomeDialogBroughtToYouBy": "Udviklet af Workoho — specialister i gæstestyring og livscyklushåndtering.",
    "WelcomeDialogWorkohoLinkLabel": "workoho.com",
    "WelcomeDialogNextButton": "Næste",
    "WelcomeDialogBackButton": "Tilbage",
    "WelcomeDialogSkipButton": "Ikke nu",
    "WelcomeDialogSaveButton": "Gem",
    "WelcomeDialogSkipApiButton": "Spring over",
    "InvalidUrlFormat": "Angiv en gyldig URL (f.eks. my-app.azurewebsites.net)",
    "InvalidGuidFormat": "Angiv en gyldig GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    "WelcomeDialogSetupTitle": "Vælg din opsætningsmetode",
    "WelcomeDialogSetupIntro": "Vælg din installationsmetode. Du kan skifte mellem de to muligheder til enhver tid via webdelens indstillinger.",
    "WelcomeDialogOptionApiTitle": "Brug Guest Sponsor API",
    "WelcomeDialogOptionApiBody": "Fuld funktionsrig oplevelse via en Azure Function. Kræver engangsopsætning i Azure — anbefales til produktion.",
    "WelcomeDialogOptionApiDocsLabel": "Se installationsvejledningen",
    "WelcomeDialogSetupGuideNote": "Disse trin er en genvej. Læs installationsvejledningen, inden du kører scripts — så du forstår, hvad hvert kommando gør.",
    "WelcomeDialogDeployToAzureLabel": "Installer API'en i Azure",
    "WelcomeDialogDeployNote": "Denne mulighed kræver, at Guest Sponsor API er installeret i dit Azure-abonnement. Du kan gøre det her \u2014 det tager kun få minutter.",
    "WelcomeDialogSetupStepsOrderHint": "Gennemfør disse trin i rækkefølge:",
    "WelcomeDialogSetupStep1Label": "Opret appregistrering",
    "WelcomeDialogSetupStep2Hint": "Bruger appregistreringen oprettet i trin 1",
    "WelcomeDialogSetupStep3Label": "Tildel Graph-tilladelser",
    "WelcomeDialogSetupPwshHint": "PowerShell 7+:",
    "WelcomeDialogSetupStep3Hint": "Bruger appregistreringen (trin 1) og Function App-URL'en (trin 2)",
    "ViewScriptSourceLabel": "Undersøg script",
    "WelcomeDialogConnectApiTitle": "Angiv API-forbindelsesoplysninger",
    "WelcomeDialogConnectApiIntro": "Angiv forbindelsesoplysningerne til din Guest Sponsor API. Du kan springe dette trin over for nu og tilføje dem senere i indstillingerne for webdelen.",
    "WelcomeDialogUrlHintLabel": "Hvor finder jeg URL'en?",
    "WelcomeDialogUrlHintBody": "Kopiér Function App-URL'en fra Azure-portalen efter implementering. Gå til din Function App → Oversigt → Standarddomæne.",
    "WelcomeDialogOptionDemoTitle": "Udforsk i demotilstand",
    "WelcomeDialogOptionDemoBody": "Prøv webdelen med simulerede sponsordata — ingen Azure-opsætning kræves. Skift til den rigtige API fra indstillingerne til enhver tid.",
    "WelcomeDialogFunctionUrlRequired": "Angiv basis-URL'en for Guest Sponsor API.",
    "WelcomeDialogDoneApiTitle": "API konfigureret!",
    "WelcomeDialogDoneApiSkippedTitle": "Næsten færdig!",
    "WelcomeDialogDoneApiSkippedBody": "Der er ikke indtastet legitimationsoplysninger. For at fuldgøre opsætningen: åbn web part-indstillingerne, angiv basis-URL og klient-ID under Guest Sponsor API, og gem siden.",
    "WelcomeDialogDoneApiBody": "Forbindelsen til Guest Sponsor API er gemt. Husk at gemme siden, så dine indstillinger gælder for alle.",
    "WelcomeDialogDoneDemoTitle": "Demotilstand aktiveret!",
    "WelcomeDialogDoneDemoBody": "Skift til visningstilstand for at se webdelen med simulerede sponsorkort. Tilslut Guest Sponsor API fra indstillingerne, når du er klar.",
    "WelcomeDialogDismissButton": "Kom i gang",
    "PpSectionLivePage": "▶ Live-side",
    "PpSectionDemoMode": "🧪 Demo-tilstand",
    "PpSectionCardLayout": "🗂️ Kortlayout",
    "PpSectionProfileFields": "👤 Profilfelter",
    "PpSectionPhone": "📞 Telefonnumre",
    "PpSectionWorkLocation": "📍 Arbejdssted",
    "PpSectionAddress": "🏠 Postadresse",
    "PpSectionMapLink": "🧭 Kortlink",
    "PpSectionMapPreview": "🗺️ Integreret kortforhåndsvisning"
  }
});
