define([], function() {
  return {
    "PropertyPaneDescription": "Configure the Guest Sponsor Info web part.",
    "BasicGroupName": "Settings",
    "TitleFieldLabel": "Title",
    "LoadingMessage": "Loading your sponsors…",
    "NoSponsorsTitle": "No sponsors found",
    "NoSponsorsMessage": "No sponsors found for your account.",
    "SponsorUnavailableTitle": "Sponsor not available",
    "SponsorUnavailableMessage": "Your sponsor is no longer available. Please contact your project stakeholder to have a new sponsor assigned to your account.",
    "ErrorMessageTitle": "Something went wrong",
    "ErrorMessage": "Could not load sponsor information. Please try again later.",
    "EditModePlaceholder": "Guest Sponsor Info — switch to view mode to see sponsors.",
    "GuestOnlyPlaceholder": "This web part is only visible to guest users in view mode.",
    "MockModeFieldLabel": "Always show mock sponsors (enable public demo mode)",
    "MockModePlaceholder": "Guest Sponsor Info — Demo mode active. Switch to view mode to see mock sponsors.",
    "MockSimulatedHintFieldLabel": "Simulate guest notification",
    "MockSimulatedHintNoneOption": "None (no notification)",
    "MockSimulatedHintTeamsAccessPendingOption": "Teams not set up yet",
    "MockSimulatedHintVersionMismatchOption": "Update available",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsor not available",
    "MockSimulatedHintNoSponsorsOption": "No sponsors found",
    "MaxSponsorCountFieldLabel": "Visible sponsors (live page)",
    "MockSponsorCountFieldLabel": "Number of demo sponsors",

    "PresenceAvailable": "Available",
    "PresenceAvailableIdle": "Available, Idle",
    "PresenceAway": "Away",
    "PresenceBeRightBack": "Be Right Back",
    "PresenceBusy": "Busy",
    "PresenceBusyIdle": "Busy, Idle",
    "PresenceDoNotDisturb": "Do Not Disturb",
    "PresenceInAMeeting": "In a meeting",
    "PresenceInACall": "In a call",
    "PresencePresenting": "Presenting",
    "PresenceFocusing": "Focusing",
    "PresenceOutOfOffice": "Out of office",
    "PresenceOutOfOfficeSuffix": ", out of office",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Contact details for {0}",
    "ContactActionsAriaLabel": "Contact actions",
    "ChatTitle": "Start a chat with {name}",
    "EmailTitle": "Send email to {name}",
    "CallTitle": "Start an audio call with {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "Email",
    "CallLabel": "Call",

    "ContactInfoSection": "Contact",
    "EmailFieldLabel": "Email",
    "WorkPhoneFieldLabel": "Work phone",
    "MobileFieldLabel": "Mobile",
    "WorkLocationFieldLabel": "Work location",
    "AddressFieldLabel": "Address",
    "StreetAddressFieldLabel": "Street",
    "PostalCodeFieldLabel": "ZIP",
    "StateFieldLabel": "State",

    "OrganizationSection": "Organization",
    "ReportsToSection": "Reports to",
    "ManagerLabel": "Manager",

    "CopiedFeedback": "Copied!",
    "CopyEmailAriaLabel": "Copy email address",
    "CopyWorkPhoneAriaLabel": "Copy work phone",
    "CopyMobileAriaLabel": "Copy mobile number",
    "CopyLocationAriaLabel": "Copy work location",
    "CopyAddressAriaLabel": "Copy address",
    "CopyStreetAddressAriaLabel": "Copy street",
    "CopyPostalCodeAriaLabel": "Copy ZIP code",
    "CopyStateAriaLabel": "Copy state",
    "AddressMapSectionLabel": "Map preview",
    "AddressMapLoadingLabel": "Loading map preview…",
    "OpenAddressInMapLabel": "Open in map",

    "TeamsAccessPendingTitle": "Microsoft Teams not set up yet",
    "TeamsAccessPendingMessage": "Your guest access to Microsoft Teams in this organization hasn’t been set up yet. This doesn’t affect your own Teams account. Ask your sponsor to add you to a Team — once they do, Teams features like chat, calls, and meetings will become available here.",
    "TeamsNotReadyChatTooltip": "Chat not available in this organization — your Teams guest access hasn’t been set up yet",
    "TeamsNotReadyCallTooltip": "Call not available in this organization — your Teams guest access hasn’t been set up yet",
    "VersionMismatchTitle": "Update available",
    "VersionMismatchMessage": "A web part update is available. Ask your administrator to ensure the web part and the Guest Sponsor API are running the same version.",
    "InsufficientPermissionsTitle": "Permission required",
    "InsufficientPermissionsMessage": "Could not load sponsor information — a required service permission has not been granted. Please contact your IT administrator.",
    "GuestNotificationsGroupName": "Guest Notifications",
    "GuestNotificationsGroupHint": "Control which informational notices are shown to guest users.",
    "ShowTeamsAccessPendingHintLabel": "Show \"Teams not set up yet\" notice",
    "ShowVersionMismatchHintLabel": "Show \"Update available\" notice",
    "ShowSponsorUnavailableHintLabel": "Show \"Sponsor not available\" notice",
    "ShowNoSponsorsHintLabel": "Show \"No sponsors found\" notice",
    "DisplayGroupName": "Display",
    "CardLayoutFieldLabel": "Card layout",
    "CardLayoutAutoOption": "Automatic",
    "CardLayoutAutoThresholdFieldLabel": "Switch to compact when at least this many sponsors",
    "CardLayoutFullOption": "Full",
    "CardLayoutCompactOption": "Compact",
    "ShowBusinessPhonesFieldLabel": "Show business phone numbers",
    "ShowMobilePhoneFieldLabel": "Show mobile phone number",
    "ShowWorkLocationFieldLabel": "Show work location",
    "ShowStreetAddressFieldLabel": "Show street",
    "ShowPostalCodeFieldLabel": "Show ZIP code",
    "ShowStateFieldLabel": "Show state",
    "ExternalMapProviderFieldLabel": "Map provider",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps subscription key",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "MapProviderNoneOption": "Disabled (no map link)",
    "AddressMapProviderHint": "Enable at least city and country — that is sufficient for any map provider to show a meaningful location.",
    "ShowManagerFieldLabel": "Show manager",
    "UseInformalAddressFieldLabel": "Use informal salutation (du/tu)",
    "LocationDisplayHintSeparateRows": "Enabled address fields are combined into a single clickable row.",
    "LocationDisplayHintHidden": "All location and address fields are hidden.",
    "AdvancedDisplayGroupName": "Advanced display options",
    "ManagerOptionsDisabledHint": "Enable \"Show manager\" to configure manager-specific fields.",

    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "Guest Sponsor API Base URL",
    "FunctionClientIdFieldLabel": "Guest Sponsor API Client ID (App Registration)",
    "ProxyStatusChecking": "Checking Guest Sponsor API connection…",
    "ProxyStatusOk": "Guest Sponsor API reachable",
    "ProxyStatusError": "Guest Sponsor API not reachable",
    "AuthorSectionGroupName": "About Workoho",
    "AuthorSectionIntro": "Microsoft 365 governance, identity, and guest access \u2014 our domain.",
    "AuthorSectionWebsiteLinkLabel": "Work with us",
    "AuthorSectionConsultingText": "We built this web part because we work with exactly these challenges every day. From architecture to rollout, we help organisations design secure, scalable collaboration on Microsoft 365.",
    "AuthorSectionPartnerPrefix": "Workoho is an",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum sales and implementation partner.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automates lifecycle management for Teams, SharePoint sites, Viva Engage, and other Microsoft 365 workspaces — including guest onboarding and sponsor assignments.",
    "AuthorSectionSourceCodeLabel": "Source code on GitHub",
    "AuthorSectionVersionLabel": "Web part version",
    "ShowSponsorJobTitleFieldLabel": "Show sponsor's job title",
    "ShowManagerJobTitleFieldLabel": "Show manager's job title",
    "ShowSponsorDepartmentFieldLabel": "Show sponsor's department",
    "ShowManagerDepartmentFieldLabel": "Show manager's department",
    "DepartmentLabel": "Department",
    "ShowCityFieldLabel": "Show city",
    "ShowCountryFieldLabel": "Show country",
    "CityFieldLabel": "City",
    "CountryFieldLabel": "Country",
    "CopyCityAriaLabel": "Copy city",
    "CopyCountryAriaLabel": "Copy country",
    "ShowPresenceFieldLabel": "Show presence status",
    "ShowSponsorPhotoFieldLabel": "Show sponsor photo",
    "ShowManagerPhotoFieldLabel": "Show manager photo",
  }
});
