// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function() {
  return {
    "BasicGroupName": "Settings",
    "ShowTitleFieldLabel": "Show title",
    "TitleFieldLabel": "Title",
    "LoadingMessage": "Loading your sponsors…",
    "NoSponsorsTitle": "No sponsors found",
    "NoSponsorsMessage": "No sponsors found for your account.",
    "SponsorUnavailableTitle": "Sponsor not available",
    "SponsorUnavailableMessage": "Your sponsor is no longer available. Please contact your project stakeholder to have a new sponsor assigned to your account.",
    "ErrorMessageTitle": "Something went wrong",
    "ErrorMessage": "Could not load sponsor information. Please try again later.",
    "EditModePlaceholder": "Guest Sponsor Info — switch to view mode to see sponsors.",
    "GuestOnlyPlaceholder": "This web part is only visible to guest users in view mode.",
    "MockModeFieldLabel": "Enable public demo mode for internal users",
    "MockModeFieldDescription": "Applies only to the live page for visitors. In edit mode, the preview does not change. Enable this to test the web part with simulated sponsors for internal users in your tenant; when disabled, only guest users see sponsor content.",
    "MockModeFieldTooltip": "When enabled, demo mode appears on the live page only for testing. Edit mode and preview remain unchanged.",
    "MockModePlaceholder": "Guest Sponsor Info — Demo mode active. Switch to view mode to see mock sponsors.",
    "MockSimulatedHintFieldLabel": "Simulate guest notification",
    "MockSimulatedHintNoneOption": "None (no notification)",
    "MockSimulatedHintTeamsAccessPendingOption": "Teams not set up yet",
    "MockSimulatedHintVersionMismatchOption": "Update available",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsor not available",
    "MockSimulatedHintNoSponsorsOption": "No sponsors found",
    "MaxSponsorCountFieldLabel": "Visible sponsors",
    "MaxSponsorCountFieldTooltip": "Limits the number of active sponsor cards shown. Only active (available) sponsors count toward this limit. If an assigned sponsor's account becomes unavailable (disabled, deleted, or not yet provisioned), the next sponsor in the priority order automatically advances to fill the empty slot. This ensures guests always see the configured number of available contacts.",

    "PresenceAvailable": "Available",
    "PresenceAvailableIdle": "Available, Idle",
    "PresenceAway": "Away",
    "PresenceBeRightBack": "Be Right Back",
    "PresenceBusy": "Busy",
    "PresenceBusyIdle": "Busy, Idle",
    "PresenceDoNotDisturb": "Do Not Disturb",
    "PresenceInAMeeting": "In a meeting",
    "PresenceInACall": "In a call",
    "PresencePresenting": "Presenting",
    "PresenceFocusing": "Focusing",
    "PresenceOutOfOffice": "Out of office",
    "PresenceOutOfOfficeSuffix": ", out of office",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Contact details for {0}",
    "ContactActionsAriaLabel": "Contact actions",
    "CloseLabel": "Close",
    "ChatTitle": "Start a chat with {name}",
    "EmailTitle": "Send email to {name}",
    "CallTitle": "Start an audio call with {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "Email",
    "CallLabel": "Call",

    "ContactInfoSection": "Contact",
    "EmailFieldLabel": "Email",
    "WorkPhoneFieldLabel": "Work phone",
    "MobileFieldLabel": "Mobile",
    "WorkLocationFieldLabel": "Work location",
    "AddressFieldLabel": "Address",
    "StreetAddressFieldLabel": "Street",
    "PostalCodeFieldLabel": "ZIP",
    "StateFieldLabel": "State",

    "OrganizationSection": "Organization",
    "ReportsToSection": "Reports to",
    "ManagerLabel": "Manager",

    "CopiedFeedback": "Copied!",
    "CopyEmailAriaLabel": "Copy email address",
    "CopyWorkPhoneAriaLabel": "Copy work phone",
    "CopyMobileAriaLabel": "Copy mobile number",
    "CopyLocationAriaLabel": "Copy work location",
    "CopyAddressAriaLabel": "Copy address",
    "CopyStreetAddressAriaLabel": "Copy street",
    "CopyPostalCodeAriaLabel": "Copy ZIP code",
    "CopyStateAriaLabel": "Copy state",
    "AddressMapSectionLabel": "Map preview",
    "AddressMapLoadingLabel": "Loading map preview…",
    "OpenAddressInMapLabel": "Open in map",

    "TeamsAccessPendingTitle": "Microsoft Teams not set up yet",
    "TeamsAccessPendingMessage": "Your guest access to Microsoft Teams in this organization hasn’t been set up yet. This doesn’t affect your own Teams account. Ask your sponsor to add you to a Team — once they do, Teams features like chat, calls, and meetings will become available here.",
    "TeamsNotReadyChatTooltip": "Chat not available in this organization — your Teams guest access hasn’t been set up yet",
    "TeamsNotReadyCallTooltip": "Call not available in this organization — your Teams guest access hasn’t been set up yet",
    "VersionMismatchTitle": "Update available",
    "VersionMismatchMessage": "A web part update is available. Ask your administrator to ensure the web part and the Guest Sponsor API are running the same version.",
    "InsufficientPermissionsTitle": "Permission required",
    "InsufficientPermissionsMessage": "Could not load sponsor information — a required service permission has not been granted. Please contact your IT administrator.",
    "GuestNotificationsGroupName": "Guest Notifications",
    "GuestNotificationsGroupHint": "Control which informational notices are shown to guest users.",
    "ShowTeamsAccessPendingHintLabel": "Show \"Teams not set up yet\" notice",
    "ShowVersionMismatchHintLabel": "Show \"Update available\" notice",
    "ShowSponsorUnavailableHintLabel": "Show \"Sponsor not available\" notice",
    "ShowNoSponsorsHintLabel": "Show \"No sponsors found\" notice",
    "DisplayGroupName": "Display",
    "CardLayoutFieldLabel": "Card layout",
    "CardLayoutAutoOption": "Automatic",
    "CardLayoutAutoThresholdFieldLabel": "Switch to compact when at least this many sponsors",
    "CardLayoutFullOption": "Full",
    "CardLayoutCompactOption": "Compact",
    "ShowBusinessPhonesFieldLabel": "Show business phone numbers",
    "ShowMobilePhoneFieldLabel": "Show mobile phone number",
    "ShowWorkLocationFieldLabel": "Show work location",
    "ShowStreetAddressFieldLabel": "Show street",
    "ShowPostalCodeFieldLabel": "Show ZIP code",
    "ShowStateFieldLabel": "Show state",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps subscription key",
    "MapProviderModeAutoLabel": "Auto mode (recommended)",
    "MapProviderModeManualLabel": "Manual (same for all devices)",
    "MapProviderModeHint": "Choose a map provider for each operating system, including iOS and Android. Links open in the browser or the provider's app if installed.",
    "MapProviderIosLabel": "iOS:",
    "MapProviderAndroidLabel": "Android:",
    "MapProviderWindowsLabel": "Windows:",
    "MapProviderMacOSLabel": "macOS:",
    "MapProviderLinuxLabel": "Linux:",
    "ExternalMapProviderFieldLabel": "Map provider",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderNoneOption": "Disabled (no map link)",
    "AddressMapProviderHint": "Enable at least city and country — that is sufficient for any map provider to show a meaningful location.",
    "AzureMapsPreviewHint": "Add your Azure Maps subscription key to show a small inline map preview in the contact section. If you deployed the Guest Sponsor API, an Azure Maps account was included — copy the key from its Authentication settings. Without a key, only the map link above is shown.",
    "ShowManagerFieldLabel": "Show manager",
    "UseInformalAddressFieldLabel": "Use informal salutation (du/tu)",
    "SponsorEligibilityGroupName": "Sponsor Eligibility",
    "SponsorEligibilityGroupHint": "Sponsor assignments in Microsoft Entra are maintained by your organization and may not always be accurate. These filters help improve the quality of sponsors shown to guests and prevent unintended information disclosure caused by incorrect assignments.",
    "SponsorFilterFieldLabel": "Sponsor must be",
    "SponsorFilterTeamsOption": "Teams licensed (recommended)",
    "SponsorFilterExchangeOption": "Exchange Online licensed",
    "SponsorFilterAnyOption": "Licensed (any active license)",
    "RequireUserMailboxFieldLabel": "Require user mailbox type",
    "LocationDisplayHintSeparateRows": "Enabled address fields are combined into a single clickable row.",
    "AdvancedDisplayGroupName": "Advanced display options",

    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "Base URL",
    "FunctionClientIdFieldLabel": "Application (client) ID",
    "PpClientIdHintLabel": "Where do I find the Client ID?",
    "PpClientIdHintBody": "Copy the Client ID (Application ID) from the App Registration created during setup.",
    "FunctionEntraLinkLabel": "Find in Microsoft Entra →",
    "ProxyStatusChecking": "Checking Guest Sponsor API connection…",
    "ProxyStatusOk": "Connection successful",
    "ProxyStatusError": "Connection failed",
    "PpSetupIntro": "Required setup:",
    "PpSetupRerunHint": "Connection problem? The setup scripts are idempotent \u2014 re-running them with the same parameters fixes most issues.",
    "CopyToClipboardLabel": "Copy",
    "CopiedToClipboardLabel": "Copied!",
    "AuthorSectionGroupName": "About Workoho",
    "AuthorSectionIntro": "Microsoft 365 governance, identity, and guest access \u2014 our domain.",
    "AuthorSectionWebsiteLinkLabel": "Work with us",
    "AuthorSectionConsultingText": "We built this web part because we work with exactly these challenges every day. From architecture to rollout, we help organisations design secure, scalable collaboration on Microsoft 365.",
    "AuthorSectionPartnerPrefix": "Workoho is an",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum Partner.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automates lifecycle management for Teams, SharePoint sites, Viva Engage, and other Microsoft 365 workspaces — including guest onboarding and sponsor assignments.",
    "AuthorSectionSourceCodeLabel": "Source code",
    "AuthorSectionVersionLabel": "Web part version",
    "AuthorSectionDeployToAzureLabel": "Deploy to Azure",
    "DeployToAzureClickHint": "Click the button to start the deployment:",
    "AuthorSectionDeploymentGuideLabel": "Deployment guide",
    "NewReleaseAvailableLabel": "New release available — click to open GitHub Releases",
    "ShowSponsorJobTitleFieldLabel": "Show sponsor's job title",
    "ShowManagerJobTitleFieldLabel": "Show manager's job title",
    "ShowSponsorDepartmentFieldLabel": "Show sponsor's department",
    "ShowManagerDepartmentFieldLabel": "Show manager's department",
    "DepartmentLabel": "Department",
    "ShowCityFieldLabel": "Show city",
    "ShowCountryFieldLabel": "Show country",
    "CityFieldLabel": "City",
    "CountryFieldLabel": "Country",
    "CopyCityAriaLabel": "Copy city",
    "CopyCountryAriaLabel": "Copy country",
    "ShowPresenceFieldLabel": "Show presence status",
    "ShowSponsorPhotoFieldLabel": "Show sponsor photo",
    "ShowManagerPhotoFieldLabel": "Show manager photo",
    "TitlePlaceholder": "My Sponsors",
    "TitleSizeFieldLabel": "Title size",
    "TitleSizeH2Option": "Heading 2",
    "TitleSizeH3Option": "Heading 3",
    "TitleSizeH4Option": "Heading 4",
    "TitleSizeNormalOption": "Normal",

    "WelcomeDialogTitle": "Set Up Guest Sponsor Info",
    "WelcomeDialogBody": "This web part shows each guest user their Microsoft Entra sponsors on your SharePoint landing page. For the web part to be meaningful, sponsor assignments should be actively governed and a guest lifecycle management process should already be in place — it makes that accountability visible, but does not replace the underlying governance.",
    "WelcomeDialogBroughtToYouBy": "Built by Workoho — specialists in guest governance and lifecycle management.",
    "WelcomeDialogWorkohoLinkLabel": "workoho.com",
    "WelcomeDialogDismissButton": "Let's go",
    "WelcomeDialogNextButton": "Next",
    "WelcomeDialogBackButton": "Back",
    "WelcomeDialogSkipButton": "Not now",
    "WelcomeDialogSaveButton": "Save",
    "WelcomeDialogSkipApiButton": "Skip",
    "InvalidUrlFormat": "Please enter a valid URL (e.g. my-app.azurewebsites.net)",
    "InvalidGuidFormat": "Please enter a valid GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    "WelcomeDialogSetupTitle": "Get started in minutes",
    "WelcomeDialogSetupIntro": "Choose your deployment path. You can switch between both options any time via the web part settings.",
    "WelcomeDialogOptionApiTitle": "Use Guest Sponsor API",
    "WelcomeDialogOptionApiBody": "Full-featured experience powered by an Azure Function. Requires one-time Azure setup — recommended for production.",
    "WelcomeDialogOptionApiDocsLabel": "View setup guide",
    "WelcomeDialogDeployToAzureLabel": "Deploy the API to Azure",
    "WelcomeDialogDeployNote": "This option requires the Guest Sponsor API to be deployed to your Azure subscription. You can do this right here \u2014 it only takes a few minutes.",
    "WelcomeDialogSetupStep1Label": "Create App Registration",
    "WelcomeDialogSetupStep3Label": "Grant Graph permissions",
    "WelcomeDialogSetupPwshHint": "PowerShell 7+:",
    "WelcomeDialogSetupStep3Hint": "Uses values from steps 1 and 2",
    "WelcomeDialogConnectApiTitle": "Connect Guest Sponsor API",
    "WelcomeDialogConnectApiIntro": "Optionally enter the connection details for your Guest Sponsor API. You can also add them later in the web part settings.",
    "WelcomeDialogOptionDemoTitle": "Explore in Demo Mode",
    "WelcomeDialogOptionDemoBody": "Enable demo mode to show simulated sponsors on the live page, including for internal users in your tenant. Use this for testing without Azure setup, and switch to the real API any time.",
    "WelcomeDialogFunctionUrlRequired": "Please enter the Guest Sponsor API base URL.",
    "WelcomeDialogDoneApiTitle": "API configured!",
    "WelcomeDialogDoneApiBody": "The Guest Sponsor API connection has been saved. Remember to save the page so your settings are applied for everyone.",
    "WelcomeDialogDoneApiSkippedTitle": "Almost there!",
    "WelcomeDialogDoneApiSkippedBody": "No credentials entered yet. Open the web part settings to connect the Guest Sponsor API whenever you're ready.",
    "WelcomeDialogDoneDemoTitle": "Demo Mode activated!",
    "WelcomeDialogDoneDemoBody": "Demo mode is now active for the live page. Save the page to apply it for visitors, then switch to view mode to verify the simulated sponsor cards.",
    "PpSectionLivePage": "▶ Live page",
    "PpSectionDemoMode": "🧪 Public demo mode",
    "PpSectionCardLayout": "🗂️ Card layout",
    "PpSectionProfileFields": "👤 Profile fields",
    "PpSectionPhone": "📞 Phone numbers",
    "PpSectionWorkLocation": "📍 Work location",
    "PpSectionAddress": "🏠 Postal address",
    "PpSectionMapLink": "🧭 Map link",
    "PpSectionMapPreview": "🗺️ Inline map preview",
  }
});
