define([], function() {
  return {
    "PropertyPaneDescription": "Configure el elemento web \u00abInformaci\u00f3n del patrocinador invitado\u00bb.",
    "BasicGroupName": "Configuraci\u00f3n",
    "TitleFieldLabel": "T\u00edtulo",
    "LoadingMessage": "Cargando sus patrocinadores\u2026",
    "NoSponsorsMessage": "No se encontraron patrocinadores para su cuenta.",
    "SponsorUnavailableMessage": "Su patrocinador/propietario ya no est\u00e1 disponible. P\u00f3ngase en contacto con su responsable del proyecto para que se le asigne un nuevo patrocinador/propietario.",
    "ErrorMessage": "No se pudo cargar la informaci\u00f3n del patrocinador. Int\u00e9ntelo de nuevo m\u00e1s tarde.",
    "EditModePlaceholder": "Informaci\u00f3n del patrocinador invitado \u2014 cambie al modo de visualizaci\u00f3n para ver los patrocinadores.",
    "GuestOnlyPlaceholder": "Este elemento web solo es visible para los usuarios invitados en modo de visualizaci\u00f3n.",
    "MockModeFieldLabel": "Modo demo (datos de prueba)",
    "MockModePlaceholder": "Informaci\u00f3n del patrocinador invitado \u2014 Modo demo activo. Cambie al modo de visualizaci\u00f3n para ver los datos de prueba.",

    "PresenceAvailable": "Disponible",
    "PresenceAvailableIdle": "Disponible, inactivo",
    "PresenceAway": "Ausente",
    "PresenceBeRightBack": "Vuelvo enseguida",
    "PresenceBusy": "Ocupado",
    "PresenceBusyIdle": "Ocupado, inactivo",
    "PresenceDoNotDisturb": "No molestar",
    "PresenceInAMeeting": "En una reuni\u00f3n",
    "PresenceInACall": "En una llamada",
    "PresencePresenting": "Presentando",
    "PresenceFocusing": "Concentrado",
    "PresenceOutOfOffice": "Fuera de la oficina",
    "PresenceOutOfOfficeSuffix": ", fuera de la oficina",
    "PresenceOffline": "Sin conexi\u00f3n",

    "ContactDetailsAriaLabel": "Detalles de contacto de {0}",
    "ContactActionsAriaLabel": "Acciones de contacto",
    "ChatTitle": "Chatear en Microsoft Teams",
    "EmailTitle": "Enviar correo electr\u00f3nico",
    "CallTitle": "Llamada de audio en Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "Correo electr\u00f3nico",
    "CallLabel": "Llamada",

    "ContactInfoSection": "Informaci\u00f3n de contacto",
    "EmailFieldLabel": "Correo electr\u00f3nico",
    "WorkPhoneFieldLabel": "Tel\u00e9fono del trabajo",
    "MobileFieldLabel": "M\u00f3vil",
    "WorkLocationFieldLabel": "Ubicaci\u00f3n de trabajo",
    "StreetAddressFieldLabel": "Calle",
    "PostalCodeFieldLabel": "Código postal",
    "StateFieldLabel": "Estado/región",

    "OrganizationSection": "Organizaci\u00f3n",
    "ManagerLabel": "Responsable",

    "CopiedFeedback": "\u00a1Copiado!",
    "CopyEmailAriaLabel": "Copiar direcci\u00f3n de correo electr\u00f3nico",
    "CopyWorkPhoneAriaLabel": "Copiar tel\u00e9fono del trabajo",
    "CopyMobileAriaLabel": "Copiar n\u00famero de m\u00f3vil",
    "CopyLocationAriaLabel": "Copiar ubicaci\u00f3n de trabajo",
    "CopyStreetAddressAriaLabel": "Copiar calle",
    "CopyPostalCodeAriaLabel": "Copiar código postal",
    "CopyStateAriaLabel": "Copiar estado/región",
    "AddressMapSectionLabel": "Vista previa del mapa",
    "AddressMapLoadingLabel": "Cargando vista previa del mapa…",
    "OpenAddressInMapLabel": "Abrir en el mapa",

    "TeamsAccessPendingTitle": "Microsoft Teams a\u00fan no configurado",
    "TeamsAccessPendingMessage": "Su acceso como invitado a Microsoft Teams en esta organizaci\u00f3n a\u00fan no se ha configurado. Su propia cuenta de Teams no se ve afectada. Pida a su patrocinador que le agregue a un equipo \u2014 una vez hecho, las funciones de Teams como chat, llamadas y reuniones estar\u00e1n disponibles aqu\u00ed.",
    "TeamsNotReadyChatTooltip": "Chat no disponible aqu\u00ed \u2014 su acceso de invitado de Teams a\u00fan no se ha configurado",
    "TeamsNotReadyCallTooltip": "Llamada no disponible aqu\u00ed \u2014 su acceso de invitado de Teams a\u00fan no se ha configurado",

    "LoadingMessageInformal": "Cargando tus patrocinadores\u2026",
    "NoSponsorsMessageInformal": "No se encontraron patrocinadores para tu cuenta.",
    "SponsorUnavailableMessageInformal": "Tu patrocinador/propietario ya no est\u00e1 disponible. Ponte en contacto con tu responsable del proyecto para que se te asigne un nuevo patrocinador/propietario.",
    "ErrorMessageInformal": "No se pudo cargar la informaci\u00f3n del patrocinador. Int\u00e9ntalo de nuevo m\u00e1s tarde.",
    "TeamsAccessPendingMessageInformal": "Tu acceso como invitado a Microsoft Teams en esta organizaci\u00f3n a\u00fan no se ha configurado. Tu propia cuenta de Teams no se ve afectada. Pide a tu patrocinador que te agregue a un equipo \u2014 una vez hecho, las funciones de Teams como chat, llamadas y reuniones estar\u00e1n disponibles aqu\u00ed.",
    "TeamsNotReadyChatTooltipInformal": "Chat no disponible aqu\u00ed \u2014 tu acceso de invitado de Teams a\u00fan no se ha configurado",
    "TeamsNotReadyCallTooltipInformal": "Llamada no disponible aqu\u00ed \u2014 tu acceso de invitado de Teams a\u00fan no se ha configurado",

    "DisplayGroupName": "Visualizaci\u00f3n",
    "ShowBusinessPhonesFieldLabel": "Mostrar tel\u00e9fono del trabajo",
    "ShowMobilePhoneFieldLabel": "Mostrar n\u00famero de m\u00f3vil",
    "ShowWorkLocationFieldLabel": "Mostrar ubicaci\u00f3n de trabajo",
    "ShowManagerFieldLabel": "Mostrar responsable",
    "UseInformalAddressFieldLabel": "Tratamiento informal (t\u00fa)",

    "ShowWorkLocationFallbackFieldLabel": "Mostrar ubicación de trabajo como alternativa",
    "LocationDisplayHintGeoWithFallback": "La ciudad y el país se combinan en una sola línea geográfica. La ubicación de trabajo solo se muestra si no hay datos de ciudad/país.",
    "LocationDisplayHintGeoOnly": "La ciudad y el país se combinan en una sola línea geográfica. La ubicación de trabajo está oculta.",
    "LocationDisplayHintOfficeOnly": "Solo se muestra la ubicación de trabajo. Active la ciudad y/o el país para mostrar en su lugar una línea geográfica.",
    "LocationDisplayHintHidden": "Toda la información de ubicación está oculta.",
    "AddressMapFallbackHint": "Si no se configura una clave de Azure Maps o falla la búsqueda, se muestra un enlace a un mapa externo.",
    "LocationDisplayHintAddressEnabled": "Los campos de dirección estructurada están habilitados y se pueden mostrar en filas adicionales.",
    "LocationDisplayHintSeparateRows": "Ciudad/país y ubicación de trabajo se muestran en filas separadas cuando están habilitados.",
    "AdvancedDisplayGroupName": "Opciones de visualización avanzadas",
    "ManagerOptionsDisabledHint": "Active la visualización del responsable para configurar campos específicos del responsable.",
    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "URL de la API de patrocinadores (Azure Function)",
    "FunctionClientIdFieldLabel": "ID de cliente de la API de patrocinadores (registro de aplicaci\u00f3n de Azure Function)",
    "ProxyStatusChecking": "Comprobando Azure Function\u2026",
    "ProxyStatusOk": "Azure Function accesible",
    "ProxyStatusError": "Azure Function no accesible",
    "ShowSponsorJobTitleFieldLabel": "Mostrar cargo del patrocinador",
    "ShowManagerJobTitleFieldLabel": "Mostrar cargo del responsable",
    "ShowSponsorDepartmentFieldLabel": "Mostrar departamento del patrocinador",
    "ShowManagerDepartmentFieldLabel": "Mostrar departamento del responsable",
    "DepartmentLabel": "Departamento",
    "ShowCityFieldLabel": "Mostrar ciudad",
    "ShowCountryFieldLabel": "Mostrar pa\u00eds",
    "ShowStructuredAddressFieldLabel": "Mostrar dirección estructurada",
    "ShowStreetAddressFieldLabel": "Mostrar calle",
    "ShowPostalCodeFieldLabel": "Mostrar código postal",
    "ShowStateFieldLabel": "Mostrar estado/región",
    "ShowAddressMapFieldLabel": "Mostrar vista previa del mapa de dirección",
    "AzureMapsSubscriptionKeyFieldLabel": "Clave de suscripción de Azure Maps",
    "ExternalMapProviderFieldLabel": "Proveedor de mapa externo (respaldo)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Ciudad",
    "CountryFieldLabel": "Pa\u00eds",
    "CopyCityAriaLabel": "Copiar ciudad",
    "CopyCountryAriaLabel": "Copiar pa\u00eds",
    "ShowPresenceFieldLabel": "Mostrar estado de presencia"
  }
});
