define([], function() {
  return {
    "PropertyPaneDescription": "Configure el elemento web «Información del patrocinador invitado».",
    "BasicGroupName": "Configuración",
    "TitleFieldLabel": "Título",
    "LoadingMessage": "Cargando sus patrocinadores…",
    "NoSponsorsTitle": "Sin patrocinadores",
    "NoSponsorsMessage": "No se encontraron patrocinadores para su cuenta.",
    "SponsorUnavailableTitle": "Patrocinador no disponible",
    "SponsorUnavailableMessage": "Su patrocinador ya no está disponible. Póngase en contacto con su responsable del proyecto para que se le asigne un nuevo patrocinador.",
    "ErrorMessageTitle": "Error al cargar",
    "ErrorMessage": "No se pudo cargar la información del patrocinador. Inténtelo de nuevo más tarde.",
    "EditModePlaceholder": "Información del patrocinador invitado — cambie al modo de visualización para ver los patrocinadores.",
    "GuestOnlyPlaceholder": "Este elemento web solo es visible para los usuarios invitados en modo de visualización.",
    "MockModeFieldLabel": "Modo demo (datos de prueba)",
    "MockModePlaceholder": "Información del patrocinador invitado — Modo demo activo. Cambie al modo de visualización para ver los datos de prueba.",
    "MockSimulatedHintFieldLabel": "Simular notificación de invitado",
    "MockSimulatedHintNoneOption": "Ninguna notificación",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams aún no configurado",
    "MockSimulatedHintVersionMismatchOption": "Actualización disponible",
    "MockSimulatedHintSponsorUnavailableOption": "Patrocinador no disponible",
    "MockSimulatedHintNoSponsorsOption": "No se encontraron patrocinadores",

    "PresenceAvailable": "Disponible",
    "PresenceAvailableIdle": "Disponible, inactivo",
    "PresenceAway": "Ausente",
    "PresenceBeRightBack": "Vuelvo enseguida",
    "PresenceBusy": "Ocupado",
    "PresenceBusyIdle": "Ocupado, inactivo",
    "PresenceDoNotDisturb": "No molestar",
    "PresenceInAMeeting": "En una reunión",
    "PresenceInACall": "En una llamada",
    "PresencePresenting": "Presentando",
    "PresenceFocusing": "Concentrado",
    "PresenceOutOfOffice": "Fuera de la oficina",
    "PresenceOutOfOfficeSuffix": ", fuera de la oficina",
    "PresenceOffline": "Sin conexión",

    "ContactDetailsAriaLabel": "Detalles de contacto de {0}",
    "ContactActionsAriaLabel": "Acciones de contacto",
    "ChatTitle": "Iniciar un chat con {name}",
    "EmailTitle": "Enviar un correo a {name}",
    "CallTitle": "Iniciar una llamada de voz con {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "Correo electrónico",
    "CallLabel": "Llamada",

    "ContactInfoSection": "Contacto",
    "EmailFieldLabel": "Correo electrónico",
    "WorkPhoneFieldLabel": "Teléfono del trabajo",
    "MobileFieldLabel": "Móvil",
    "WorkLocationFieldLabel": "Ubicación de trabajo",
    "AddressFieldLabel": "Dirección",
    "StreetAddressFieldLabel": "Calle",
    "PostalCodeFieldLabel": "Código postal",
    "StateFieldLabel": "Estado/región",

    "OrganizationSection": "Organización",
    "ReportsToSection": "Reporta a",
    "ManagerLabel": "Responsable",

    "CopiedFeedback": "¡Copiado!",
    "CopyEmailAriaLabel": "Copiar dirección de correo electrónico",
    "CopyWorkPhoneAriaLabel": "Copiar teléfono del trabajo",
    "CopyMobileAriaLabel": "Copiar número de móvil",
    "CopyLocationAriaLabel": "Copiar ubicación de trabajo",
    "CopyAddressAriaLabel": "Copiar dirección",
    "CopyStreetAddressAriaLabel": "Copiar calle",
    "CopyPostalCodeAriaLabel": "Copiar código postal",
    "CopyStateAriaLabel": "Copiar estado/región",
    "AddressMapSectionLabel": "Vista previa del mapa",
    "AddressMapLoadingLabel": "Cargando vista previa del mapa…",
    "OpenAddressInMapLabel": "Abrir en el mapa",

    "TeamsAccessPendingTitle": "Microsoft Teams aún no configurado",
    "TeamsAccessPendingMessage": "Su acceso como invitado a Microsoft Teams en esta organización aún no se ha configurado. Su propia cuenta de Teams no se ve afectada. Pida a su patrocinador que le agregue a un equipo — una vez hecho, las funciones de Teams como chat, llamadas y reuniones estarán disponibles aquí.",
    "TeamsNotReadyChatTooltip": "Chat no disponible aquí — su acceso de invitado de Teams aún no se ha configurado",
    "TeamsNotReadyCallTooltip": "Llamada no disponible aquí — su acceso de invitado de Teams aún no se ha configurado",

    "VersionMismatchTitle": "Actualización disponible",
    "VersionMismatchMessage": "Hay una actualización disponible para este elemento web. Solicite a su administrador que compruebe que el elemento web y la Función de Azure usan la misma versión.",    "InsufficientPermissionsTitle": "Permiso insuficiente",
    "InsufficientPermissionsMessage": "No se pudo cargar la información del patrocinador — no se ha concedido un permiso de servicio requerido. Póngase en contacto con su administrador de TI.",
    "LoadingMessageInformal": "Cargando tus patrocinadores…",
    "NoSponsorsMessageInformal": "No se encontraron patrocinadores para tu cuenta.",
    "SponsorUnavailableMessageInformal": "Tu patrocinador ya no está disponible. Ponte en contacto con tu responsable del proyecto para que se te asigne un nuevo patrocinador.",
    "ErrorMessageInformal": "No se pudo cargar la información del patrocinador. Inténtalo de nuevo más tarde.",
    "TeamsAccessPendingMessageInformal": "Tu acceso como invitado a Microsoft Teams en esta organización aún no se ha configurado. Tu propia cuenta de Teams no se ve afectada. Pide a tu patrocinador que te agregue a un equipo — una vez hecho, las funciones de Teams como chat, llamadas y reuniones estarán disponibles aquí.",
    "TeamsNotReadyChatTooltipInformal": "Chat no disponible aquí — tu acceso de invitado de Teams aún no se ha configurado",
    "TeamsNotReadyCallTooltipInformal": "Llamada no disponible aquí — tu acceso de invitado de Teams aún no se ha configurado",

    "GuestNotificationsGroupName": "Notificaciones para invitados",
    "GuestNotificationsGroupHint": "Controle qué notificaciones informativas se muestran a los usuarios invitados.",
    "ShowTeamsAccessPendingHintLabel": "Mostrar el aviso «Microsoft Teams aún no configurado»",
    "ShowVersionMismatchHintLabel": "Mostrar el aviso «Actualización disponible»",
    "ShowSponsorUnavailableHintLabel": "Mostrar el aviso «Patrocinador no disponible»",
    "ShowNoSponsorsHintLabel": "Mostrar el aviso «No se encontraron patrocinadores»",
    "DisplayGroupName": "Visualización",
    "CardLayoutFieldLabel": "Diseño de tarjeta",
    "CardLayoutAutoOption": "Automático",
    "CardLayoutFullOption": "Completo",
    "CardLayoutCompactOption": "Compacto",
    "ShowBusinessPhonesFieldLabel": "Mostrar teléfono del trabajo",
    "ShowMobilePhoneFieldLabel": "Mostrar número de móvil",
    "ShowWorkLocationFieldLabel": "Mostrar ubicación de trabajo",
    "ShowManagerFieldLabel": "Mostrar responsable",
    "UseInformalAddressFieldLabel": "Tratamiento informal (tú)",

    "ShowWorkLocationFallbackFieldLabel": "Mostrar ubicación de trabajo como alternativa",
    "LocationDisplayHintGeoWithFallback": "La ciudad y el país se combinan en una sola línea geográfica. La ubicación de trabajo solo se muestra si no hay datos de ciudad/país.",
    "LocationDisplayHintGeoOnly": "La ciudad y el país se combinan en una sola línea geográfica. La ubicación de trabajo está oculta.",
    "LocationDisplayHintOfficeOnly": "Solo se muestra la ubicación de trabajo. Active la ciudad y/o el país para mostrar en su lugar una línea geográfica.",
    "LocationDisplayHintHidden": "Todos los campos de ubicación y dirección están ocultos.",
    "LocationDisplayHintSeparateRows": "Los campos de dirección activados se combinan en una sola fila clicable.",
    "AdvancedDisplayGroupName": "Opciones de visualización avanzadas",
    "ManagerOptionsDisabledHint": "Active la visualización del responsable para configurar campos específicos del responsable.",
    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "URL base de Azure Function",
    "FunctionClientIdFieldLabel": "ID de cliente de la API de patrocinadores (registro de aplicación de Azure Function)",
    "ProxyStatusChecking": "Comprobando Azure Function…",
    "ProxyStatusOk": "Azure Function accesible",
    "ProxyStatusError": "Azure Function no accesible",
    "AuthorSectionGroupName": "Sobre Workoho",
    "AuthorSectionIntro": "Gobernanza de Microsoft 365, identidades y acceso de invitados \u2014 nuestro campo.",
    "AuthorSectionWebsiteLinkLabel": "Hablemos",
    "AuthorSectionConsultingText": "Desarrollamos este componente porque es lo que hacemos cada día. De la arquitectura al despliegue, ayudamos a las organizaciones a construir una colaboración segura y escalable en Microsoft 365.",
    "AuthorSectionPartnerPrefix": "Workoho es",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "partner Platinum de ventas e implementación.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automatiza la gestión del ciclo de vida en Teams, SharePoint, Viva Engage y otros entornos de Microsoft 365 — incluidos el registro de invitados y la gestión de patrocinadores.",
    "AuthorSectionSourceCodeLabel": "Código fuente en GitHub",
    "AuthorSectionVersionLabel": "Versión del web part",
    "ShowSponsorJobTitleFieldLabel": "Mostrar cargo del patrocinador",
    "ShowManagerJobTitleFieldLabel": "Mostrar cargo del responsable",
    "ShowSponsorDepartmentFieldLabel": "Mostrar departamento del patrocinador",
    "ShowManagerDepartmentFieldLabel": "Mostrar departamento del responsable",
    "DepartmentLabel": "Departamento",
    "ShowCityFieldLabel": "Mostrar ciudad",
    "ShowCountryFieldLabel": "Mostrar país",
    "ShowStreetAddressFieldLabel": "Mostrar calle",
    "ShowPostalCodeFieldLabel": "Mostrar código postal",
    "ShowStateFieldLabel": "Mostrar estado/región",
    "AzureMapsSubscriptionKeyFieldLabel": "Clave de suscripción de Azure Maps",
    "ExternalMapProviderFieldLabel": "Proveedor de mapas",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "MapProviderNoneOption": "Desactivado (sin enlace de mapa)",
    "AddressMapProviderHint": "Active al menos la ciudad y el país — es suficiente para que cualquier proveedor de mapas muestre una ubicación significativa.",
    "CityFieldLabel": "Ciudad",
    "CountryFieldLabel": "País",
    "CopyCityAriaLabel": "Copiar ciudad",
    "CopyCountryAriaLabel": "Copiar país",
    "ShowPresenceFieldLabel": "Mostrar estado de presencia",
    "ShowSponsorPhotoFieldLabel": "Mostrar foto del patrocinador",
    "ShowManagerPhotoFieldLabel": "Mostrar foto del responsable",
  }
});
