// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Configuración",
    ShowTitleFieldLabel: "Mostrar título",
    TitleFieldLabel: "Título",
    LoadingMessage: "Cargando sus patrocinadores…",
    NoSponsorsTitle: "Sin patrocinadores",
    NoSponsorsMessage: "No se encontraron patrocinadores para su cuenta.",
    SponsorUnavailableTitle: "Patrocinador no disponible",
    SponsorUnavailableMessage:
      "Su patrocinador ya no está disponible. Póngase en contacto con su responsable del proyecto para que se le asigne un nuevo patrocinador.",
    ErrorMessageTitle: "Error al cargar",
    ErrorMessage: "No se pudo cargar la información del patrocinador. Inténtelo de nuevo más tarde.",
    EditModePlaceholder:
      "Información del patrocinador invitado — cambie al modo de visualización para ver los patrocinadores.",
    GuestOnlyPlaceholder: "Este elemento web solo es visible para los usuarios invitados en modo de visualización.",
    MockModeFieldLabel: "Mostrar siempre patrocinadores de demo (modo demo público)",
    MockModeFieldDescription: "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    MockModeFieldTooltip:
      "Cuando está habilitado, el modo de demostración aparece solo en la página activa para fines de prueba. El modo de edición y vista previa no cambian.",
    MockModePlaceholder:
      "Información del patrocinador invitado — Modo demo activo. Cambie al modo de visualización para ver los datos de prueba.",
    MockSimulatedHintFieldLabel: "Simular notificación de invitado",
    MockSimulatedHintNoneOption: "Ninguna notificación",
    MockSimulatedHintTeamsAccessPendingOption: "Microsoft Teams aún no configurado",
    MockSimulatedHintVersionMismatchOption: "Actualización disponible",
    MockSimulatedHintSponsorUnavailableOption: "Patrocinador no disponible",
    MockSimulatedHintNoSponsorsOption: "No se encontraron patrocinadores",
    MaxSponsorCountFieldLabel: "Patrocinadores visibles",
    MaxSponsorCountFieldTooltip:
      "Limita el número de tarjetas de patrocinador mostradas. Solo los patrocinadores activos (disponibles) cuentan hacia este límite. Si una cuenta de patrocinador asignada deja de estar disponible (deshabilitada, eliminada o aún no aprovisionada), el siguiente patrocinador en el orden de prioridad avanza automáticamente para llenar el espacio vacío. Esto garantiza que los invitados siempre vean el número configurado de contactos disponibles.",
    PresenceAvailable: "Disponible",
    PresenceAvailableIdle: "Disponible, inactivo",
    PresenceAway: "Ausente",
    PresenceBeRightBack: "Vuelvo enseguida",
    PresenceBusy: "Ocupado",
    PresenceBusyIdle: "Ocupado, inactivo",
    PresenceDoNotDisturb: "No molestar",
    PresenceInAMeeting: "En una reunión",
    PresenceInACall: "En una llamada",
    PresencePresenting: "Presentando",
    PresenceFocusing: "Concentrado",
    PresenceOutOfOffice: "Fuera de la oficina",
    PresenceOutOfOfficeSuffix: ", fuera de la oficina",
    PresenceOffline: "Sin conexión",
    ContactDetailsAriaLabel: "Detalles de contacto de {0}",
    ContactActionsAriaLabel: "Acciones de contacto",
    CloseLabel: "Cerrar",
    ChatTitle: "Iniciar un chat con {name}",
    EmailTitle: "Enviar un correo a {name}",
    CallTitle: "Iniciar una llamada de voz con {name}",
    ChatLabel: "Chat",
    EmailLabel: "Correo electrónico",
    CallLabel: "Llamada",
    ContactInfoSection: "Contacto",
    EmailFieldLabel: "Correo electrónico",
    WorkPhoneFieldLabel: "Teléfono del trabajo",
    MobileFieldLabel: "Móvil",
    WorkLocationFieldLabel: "Ubicación de trabajo",
    AddressFieldLabel: "Dirección",
    StreetAddressFieldLabel: "Calle",
    PostalCodeFieldLabel: "Código postal",
    StateFieldLabel: "Estado/región",
    OrganizationSection: "Organización",
    ReportsToSection: "Reporta a",
    ManagerLabel: "Responsable",
    CopiedFeedback: "¡Copiado!",
    CopyEmailAriaLabel: "Copiar dirección de correo electrónico",
    CopyWorkPhoneAriaLabel: "Copiar teléfono del trabajo",
    CopyMobileAriaLabel: "Copiar número de móvil",
    CopyLocationAriaLabel: "Copiar ubicación de trabajo",
    CopyAddressAriaLabel: "Copiar dirección",
    CopyStreetAddressAriaLabel: "Copiar calle",
    CopyPostalCodeAriaLabel: "Copiar código postal",
    CopyStateAriaLabel: "Copiar estado/región",
    AddressMapSectionLabel: "Vista previa del mapa",
    AddressMapLoadingLabel: "Cargando vista previa del mapa…",
    OpenAddressInMapLabel: "Abrir en el mapa",
    TeamsAccessPendingTitle: "Microsoft Teams aún no configurado",
    TeamsAccessPendingMessage:
      "Su acceso como invitado a Microsoft Teams en esta organización aún no se ha configurado. Su propia cuenta de Teams no se ve afectada. Pida a su patrocinador que le agregue a un equipo — una vez hecho, las funciones de Teams como chat, llamadas y reuniones estarán disponibles aquí.",
    TeamsNotReadyChatTooltip: "Chat no disponible aquí — su acceso de invitado de Teams aún no se ha configurado",
    TeamsNotReadyCallTooltip: "Llamada no disponible aquí — su acceso de invitado de Teams aún no se ha configurado",
    VersionMismatchTitle: "Actualización disponible",
    VersionMismatchMessage:
      "Hay una actualización disponible para este elemento web. Solicite a su administrador que compruebe que el elemento web y la Guest Sponsor API usan la misma versión.",
    InsufficientPermissionsTitle: "Permiso insuficiente",
    InsufficientPermissionsMessage:
      "No se pudo cargar la información del patrocinador — no se ha concedido un permiso de servicio requerido. Póngase en contacto con su administrador de TI.",
    GuestNotificationsGroupName: "Notificaciones para invitados",
    GuestNotificationsGroupHint: "Controle qué notificaciones informativas se muestran a los usuarios invitados.",
    ShowTeamsAccessPendingHintLabel: "Mostrar el aviso «Microsoft Teams aún no configurado»",
    ShowVersionMismatchHintLabel: "Mostrar el aviso «Actualización disponible»",
    ShowSponsorUnavailableHintLabel: "Mostrar el aviso «Patrocinador no disponible»",
    ShowNoSponsorsHintLabel: "Mostrar el aviso «No se encontraron patrocinadores»",
    DisplayGroupName: "Visualización",
    CardLayoutFieldLabel: "Diseño de tarjeta",
    CardLayoutAutoOption: "Automático",
    CardLayoutAutoThresholdFieldLabel: "Cambiar a diseño compacto a partir de este número de patrocinadores",
    CardLayoutFullOption: "Completo",
    CardLayoutCompactOption: "Compacto",
    ShowBusinessPhonesFieldLabel: "Mostrar teléfono del trabajo",
    ShowMobilePhoneFieldLabel: "Mostrar número de móvil",
    ShowWorkLocationFieldLabel: "Mostrar ubicación de trabajo",
    ShowStreetAddressFieldLabel: "Mostrar calle",
    ShowPostalCodeFieldLabel: "Mostrar código postal",
    ShowStateFieldLabel: "Mostrar estado/región",
    AzureMapsSubscriptionKeyFieldLabel: "Clave de suscripción de Azure Maps",
    MapProviderModeAutoLabel: "Modo automático (recomendado)",
    MapProviderModeManualLabel: "Manual (igual para todos los dispositivos)",
    MapProviderModeHint:
      "Elija un proveedor de mapas por sistema operativo, incluidos iOS y Android. El enlace se abre en el navegador o en la aplicación del proveedor si está instalada.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Proveedor de mapas",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Desactivado (sin enlace de mapa)",
    AddressMapProviderHint:
      "Active al menos la ciudad y el país — es suficiente para que cualquier proveedor de mapas muestre una ubicación significativa.",
    AzureMapsPreviewHint:
      "Añade tu clave de suscripción de Azure Maps para mostrar una pequeña vista previa del mapa en la sección de contacto. Si has implementado la API de Guest Sponsor, se ha incluido una cuenta de Azure Maps — copia la clave desde su configuración de autenticación. Sin clave, solo se mostrará el enlace al mapa de arriba.",
    ShowManagerFieldLabel: "Mostrar responsable",
    UseInformalAddressFieldLabel: "Tratamiento informal (tú)",
    SponsorEligibilityGroupName: "Elegibilidad del patrocinador",
    SponsorEligibilityGroupHint:
      "Las asignaciones de patrocinador en Microsoft Entra las gestiona tu organización y pueden no ser siempre exactas. Estos filtros mejoran la calidad de los patrocinadores que se muestran a los invitados y evitan la divulgación no intencionada de información por asignaciones incorrectas.",
    SponsorFilterFieldLabel: "El patrocinador debe estar",
    SponsorFilterTeamsOption: "Con licencia de Teams (recomendado)",
    SponsorFilterExchangeOption: "Con licencia de Exchange Online",
    SponsorFilterAnyOption: "Con licencia (cualquier licencia activa)",
    RequireUserMailboxFieldLabel: "Requerir tipo de buzón de usuario",
    LocationDisplayHintSeparateRows: "Los campos de dirección activados se combinan en una sola fila clicable.",
    AdvancedDisplayGroupName: "Opciones de visualización avanzadas",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "URL base",
    WebPartClientIdFieldLabel: "Id. de aplicación (cliente)",
    SessionCacheTtlMinutesFieldLabel: "Duración de la caché de la sesión (minutos)",
    PpClientIdHintLabel: "¿Dónde encuentro el ID de cliente?",
    PpClientIdHintBody:
      "Copie el ID de cliente (ID de aplicación) del registro de aplicación creado durante la configuración.",
    FunctionEntraLinkLabel: "Buscar en Microsoft Entra →",
    ProxyStatusChecking: "Comprobando Guest Sponsor API…",
    ProxyStatusOk: "Conexión exitosa",
    ProxyStatusError: "Conexión fallida",
    PpSetupIntro: "Configuración necesaria:",
    PpSetupRerunHint:
      "¿Problema de conexión? Los scripts de configuración son idempotentes \u2014 volver a ejecutarlos con los mismos parámetros corrige la mayoría de problemas.",
    CopyToClipboardLabel: "Copiar",
    CopiedToClipboardLabel: "¡Copiado!",
    AuthorSectionGroupName: "Sobre",
    AuthorSectionCreatedBy: "Creado y mantenido por",
    AuthorSectionIntro: "Gobernanza de Microsoft 365, identidades y acceso de invitados \u2014 nuestro campo.",
    AuthorSectionWebsiteLinkLabel: "Hablemos",
    AuthorSectionConsultingText:
      "Desarrollamos este componente porque es lo que hacemos cada día. De la arquitectura al despliegue, ayudamos a las organizaciones a construir una colaboración segura y escalable en Microsoft 365.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Versión del web part",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Haga clic en el bot\u00f3n para iniciar la implementaci\u00f3n:",
    AuthorSectionDeploymentGuideLabel: "Guía de implementación",
    NewReleaseAvailableLabel: "Nueva versi\u00f3n disponible \u2014 abrir en GitHub Releases",
    DiagnosticsGroupName: "Accesibilidad para invitados",
    DiagnosticsGroupHint:
      "Comprueba si el paquete JavaScript del componente y el sitio de p\u00e1gina de aterrizaje son accesibles para usuarios invitados B2B.",
    DiagnosticsChecking: "Comprobando accesibilidad para invitados\u2026",
    DiagnosticsRetryButtonLabel: "Ejecutar comprobaciones de nuevo",
    DiagPublicCdnOk:
      "Paquete distribuido a trav\u00e9s de la CDN p\u00fablica de Office 365 \u2014 entrega an\u00f3nima, sin permisos especiales para los invitados.",
    DiagPrivateCdnInfo:
      "Paquete distribuido a trav\u00e9s de la CDN privada de Office 365 \u2014 los invitados con acceso de lectura al sitio pueden cargarlo. Aseg\u00farese de que el sitio de p\u00e1gina de aterrizaje sea accesible para los invitados.",
    DiagSiteColCatalogOk:
      "Paquete distribuido desde el cat\u00e1logo de aplicaciones de la colecci\u00f3n de sitios \u2014 el acceso de invitados sigue los permisos del propio sitio.",
    DiagTenantCatalogEveryoneOk:
      "Paquete distribuido desde el cat\u00e1logo de aplicaciones del inquilino. El grupo \u2018Todos\u2019 tiene acceso de lectura al cat\u00e1logo \u2014 los invitados pueden cargar el paquete.",
    DiagTenantCatalogEveryoneDenied:
      "Paquete distribuido desde el cat\u00e1logo de aplicaciones del inquilino, pero \u2018Todos\u2019 no tiene acceso de lectura. Los invitados no pueden cargar el componente. Recomendaci\u00f3n: active la CDN p\u00fablica de Office 365 o conceda acceso de Visitante a \u2018Todos\u2019 en el sitio del cat\u00e1logo.",
    DiagTenantCatalogEveryoneUnknown:
      "Paquete distribuido desde el cat\u00e1logo de aplicaciones del inquilino. No se pudo verificar si \u2018Todos\u2019 tiene acceso de lectura (permisos insuficientes). Verifique manualmente que los invitados puedan acceder al cat\u00e1logo o active la CDN p\u00fablica de Office 365.",
    DiagAssetSourceUnknown:
      "No se pudo determinar el origen del paquete. Verifique manualmente que los usuarios invitados puedan acceder al paquete JavaScript del componente.",
    DiagSiteEveryoneOk:
      "\u2018Todos\u2019 est\u00e1 en el grupo Visitantes del sitio \u2014 los invitados reci\u00e9n aceptados obtienen acceso de lectura inmediato a la p\u00e1gina de aterrizaje.",
    DiagSiteEveryoneMissing:
      "\u2018Todos\u2019 no est\u00e1 en el grupo Visitantes del sitio. El acceso de invitados puede depender de un grupo de seguridad de Entra est\u00e1tico (aceptable) o din\u00e1mico (hasta 24\u00a0h de retraso para nuevos invitados). Si no hay ning\u00fan grupo que incluya invitados, estos ver\u00e1n una p\u00e1gina de acceso denegado.",
    DiagSiteEveryoneUnknown:
      "No se pudieron verificar los permisos de visitante del sitio. Aseg\u00farese de que los usuarios invitados tengan al menos acceso de lectura a este sitio.",
    ShowSponsorJobTitleFieldLabel: "Mostrar cargo del patrocinador",
    ShowManagerJobTitleFieldLabel: "Mostrar cargo del responsable",
    ShowSponsorDepartmentFieldLabel: "Mostrar departamento del patrocinador",
    ShowManagerDepartmentFieldLabel: "Mostrar departamento del responsable",
    DepartmentLabel: "Departamento",
    ShowCityFieldLabel: "Mostrar ciudad",
    ShowCountryFieldLabel: "Mostrar país",
    CityFieldLabel: "Ciudad",
    CountryFieldLabel: "País",
    CopyCityAriaLabel: "Copiar ciudad",
    CopyCountryAriaLabel: "Copiar país",
    ShowPresenceFieldLabel: "Mostrar estado de presencia",
    ShowSponsorPhotoFieldLabel: "Mostrar foto del patrocinador",
    ShowManagerPhotoFieldLabel: "Mostrar foto del responsable",
    TitlePlaceholder: "Mis patrocinadores",
    TitleSizeFieldLabel: "Tamaño del título",
    TitleSizeH2Option: "Encabezado 2",
    TitleSizeH3Option: "Encabezado 3",
    TitleSizeH4Option: "Encabezado 4",
    TitleSizeNormalOption: "Normal",
    WelcomeDialogTitle: "Configurar Información del patrocinador invitado",
    WelcomeDialogBody:
      "Este elemento web muestra a cada usuario invitado sus sponsors de Microsoft Entra en su página de inicio de SharePoint. Para que el elemento web sea útil, las asignaciones de sponsors deben gestionarse activamente y ya debe existir un proceso de ciclo de vida para los invitados — hace visible esa responsabilidad, pero no reemplaza la gobernanza subyacente.",
    WelcomeDialogBroughtToYouBy:
      "Desarrollado por Workoho — especialistas en gobernanza de invitados y gestión del ciclo de vida.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "\u00a1Empecemos!",
    WelcomeDialogNextButton: "Siguiente",
    WelcomeDialogBackButton: "Atrás",
    WelcomeDialogSkipButton: "Ahora no",
    WelcomeDialogSaveButton: "Guardar",
    WelcomeDialogSkipApiButton: "Omitir",
    InvalidUrlFormat: "Por favor, introduzca una URL válida (p. ej. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Por favor, introduzca un GUID válido (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Elige tu método de configuración",
    WelcomeDialogSetupIntro:
      "Elija su ruta de implementación. Puede cambiar entre ambas opciones en cualquier momento desde la configuración del elemento web.",
    WelcomeDialogOptionApiTitle: "Usar la API Guest Sponsor",
    WelcomeDialogOptionApiBody:
      "Experiencia completa impulsada por una Azure Function. Requiere configuración única en Azure — recomendado para producción.",
    WelcomeDialogOptionApiDocsLabel: "Ver la guía de configuración",
    WelcomeDialogSetupGuideNote:
      "Estos pasos son un atajo. Antes de ejecutar cualquier script, lee la guía de configuración para entender qué hace cada comando.",
    WelcomeDialogDeployToAzureLabel: "Implementar la API en Azure",
    WelcomeDialogDeployNote:
      "Esta opción requiere que la API Guest Sponsor esté implementada en tu suscripción de Azure. Puedes hacerlo aquí mismo \u2014 solo toma unos minutos.",
    WelcomeDialogSetupStepsOrderHint: "Completa estos pasos en orden:",
    WelcomeDialogSetupStep1Label: "Crear el registro de aplicación",
    WelcomeDialogSetupStep2Hint: "Usa el Registro de aplicación creado en el paso 1",
    WelcomeDialogSetupStep3Label: "Conceder permisos de Graph",
    WelcomeDialogSetupPwshHint: "PowerShell:",
    WelcomeDialogSetupStep3Hint: "Usa el Registro de aplicación (paso 1) y la URL de Function App (paso 2)",
    ViewScriptSourceLabel: "Inspeccionar script",
    WelcomeDialogConnectApiTitle: "Introduce los datos de conexión de la API",
    WelcomeDialogConnectApiIntro:
      "Introduce los detalles de conexión de tu API Guest Sponsor. Puedes omitir este paso por ahora y añadirlos más tarde en la configuración del web part.",
    WelcomeDialogUrlHintLabel: "¿Dónde encontrar la URL?",
    WelcomeDialogUrlHintBody:
      "Copia la URL de la Function App desde el portal de Azure tras el despliegue. Ve a tu Function App → Información general → Dominio predeterminado.",
    WelcomeDialogOptionDemoTitle: "Explorar en modo demo",
    WelcomeDialogOptionDemoBody:
      "Pruebe el elemento web con datos de patrocinadores simulados — sin configuración de Azure. Cambie a la API real desde la configuración en cualquier momento.",
    WelcomeDialogFunctionUrlRequired: "Introduzca la URL base de la API Guest Sponsor.",
    WelcomeDialogDoneApiTitle: "¡API configurada!",
    WelcomeDialogDoneApiBody:
      "La conexión a la API Guest Sponsor se ha guardado. Recuerde guardar la página para que la configuración se aplique a todos.",
    WelcomeDialogDoneApiSkippedTitle: "¡Casi listo!",
    WelcomeDialogDoneApiSkippedBody:
      "No se han introducido credenciales. Para terminar la configuración: abre la configuración del web part, introduce la URL base y el ID de cliente en Guest Sponsor API y guarda la página.",
    WelcomeDialogDoneDemoTitle: "¡Modo demo activado!",
    WelcomeDialogDoneDemoBody:
      "Cambie al modo de visualización para ver el elemento web con tarjetas de patrocinadores simuladas. Conecte la API Guest Sponsor desde la configuración cuando esté listo.",
    PpSectionLivePage: "▶ Página en vivo",
    PpSectionDemoMode: "🧪 Modo demo",
    PpSectionCardLayout: "🗂️ Diseño de tarjeta",
    PpSectionProfileFields: "👤 Campos de perfil",
    PpSectionPhone: "📞 Números de teléfono",
    PpSectionWorkLocation: "📍 Lugar de trabajo",
    PpSectionAddress: "🏠 Dirección postal",
    PpSectionMapLink: "🧭 Enlace del mapa",
    PpSectionMapPreview: "🗺️ Vista previa del mapa en línea"
  };
});
