define([], function() {
  return {
    "PropertyPaneDescription": "M\u00e4\u00e4rit\u00e4 Vieraan sponsoritiedot -verkko-osa.",
    "BasicGroupName": "Asetukset",
    "TitleFieldLabel": "Otsikko",
    "LoadingMessage": "Ladataan sponsoreitasi\u2026",
    "NoSponsorsMessage": "Tilillesi ei l\u00f6ydy sponsoreita.",
    "SponsorUnavailableMessage": "Sponsorisi/omistajasi ei ole en\u00e4\u00e4 k\u00e4ytett\u00e4viss\u00e4. Ota yhteytt\u00e4 projektip\u00e4\u00e4llikk\u00f6\u00f6n, jotta tilillesi voidaan nimet\u00e4 uusi sponsori/omistaja.",
    "ErrorMessage": "Sponsoritietojen lataaminen ep\u00e4onnistui. Yrit\u00e4 my\u00f6hemmin uudelleen.",
    "EditModePlaceholder": "Vieraan sponsoritiedot \u2014 siirry n\u00e4ytt\u00f6tilaan n\u00e4hd\u00e4ksesi sponsorit.",
    "GuestOnlyPlaceholder": "T\u00e4m\u00e4 verkko-osa n\u00e4kyy vain vierask\u00e4ytt\u00e4jille n\u00e4ytt\u00f6tilassa.",
    "MockModeFieldLabel": "Demotila (testitiedot)",
    "MockModePlaceholder": "Vieraan sponsoritiedot \u2014 Demotila on aktiivinen. Siirry n\u00e4ytt\u00f6tilaan n\u00e4hd\u00e4ksesi testitiedot.",

    "PresenceAvailable": "Saatavilla",
    "PresenceAvailableIdle": "Saatavilla, poissaoleva",
    "PresenceAway": "Poissa",
    "PresenceBeRightBack": "Palaan pian",
    "PresenceBusy": "Varattu",
    "PresenceBusyIdle": "Varattu, poissaoleva",
    "PresenceDoNotDisturb": "\u00c4l\u00e4 h\u00e4iritse",
    "PresenceInAMeeting": "Kokouksessa",
    "PresenceInACall": "Puhelussa",
    "PresencePresenting": "Esitt\u00e4\u00e4",
    "PresenceFocusing": "Keskittymistilassa",
    "PresenceOutOfOffice": "Poissa toimistosta",
    "PresenceOutOfOfficeSuffix": ", poissa toimistosta",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "{0} yhteystiedot",
    "ContactActionsAriaLabel": "Yhteydenottomahdollisuudet",
    "ChatTitle": "Chatti Microsoft Teamsissa",
    "EmailTitle": "L\u00e4het\u00e4 s\u00e4hk\u00f6postia",
    "CallTitle": "\u00c4\u00e4nipuhelu Microsoft Teamsissa",
    "ChatLabel": "Chatti",
    "EmailLabel": "S\u00e4hk\u00f6posti",
    "CallLabel": "Soita",

    "ContactInfoSection": "Yhteystiedot",
    "EmailFieldLabel": "S\u00e4hk\u00f6posti",
    "WorkPhoneFieldLabel": "Ty\u00f6puhelin",
    "MobileFieldLabel": "Matkapuhelin",
    "WorkLocationFieldLabel": "Ty\u00f6paikka",
    "StreetAddressFieldLabel": "Katu",
    "PostalCodeFieldLabel": "Postinumero",
    "StateFieldLabel": "Osavaltio/alue",

    "OrganizationSection": "Organisaatio",
    "ManagerLabel": "Esimies",

    "CopiedFeedback": "Kopioitu!",
    "CopyEmailAriaLabel": "Kopioi s\u00e4hk\u00f6postiosoite",
    "CopyWorkPhoneAriaLabel": "Kopioi ty\u00f6puhelin",
    "CopyMobileAriaLabel": "Kopioi matkapuhelinnumero",
    "CopyLocationAriaLabel": "Kopioi ty\u00f6paikka",
    "CopyStreetAddressAriaLabel": "Kopioi katu",
    "CopyPostalCodeAriaLabel": "Kopioi postinumero",
    "CopyStateAriaLabel": "Kopioi osavaltio/alue",
    "AddressMapSectionLabel": "Kartan esikatselu",
    "AddressMapLoadingLabel": "Ladataan kartan esikatselua...",
    "OpenAddressInMapLabel": "Avaa kartassa",

    "TeamsAccessPendingTitle": "Microsoft Teamsia ei ole viel\u00e4 m\u00e4\u00e4ritetty",
    "TeamsAccessPendingMessage": "Vierasoikeuksiasi Microsoft Teamsiin t\u00e4ss\u00e4 organisaatiossa ei ole viel\u00e4 m\u00e4\u00e4ritetty. T\u00e4m\u00e4 ei vaikuta omaan Teams-tiliisi. Pyyd\u00e4 sponsoriasi lis\u00e4\u00e4m\u00e4\u00e4n sinut tiimiin \u2014 sen j\u00e4lkeen Teams-toiminnot kuten chat, puhelut ja kokoukset ovat k\u00e4ytett\u00e4viss\u00e4 t\u00e4\u00e4ll\u00e4.",
    "TeamsNotReadyChatTooltip": "Chat ei k\u00e4ytett\u00e4viss\u00e4 t\u00e4\u00e4ll\u00e4 \u2014 Teams-vierasoikeuksiasi ei ole viel\u00e4 m\u00e4\u00e4ritetty",
    "TeamsNotReadyCallTooltip": "Puhelu ei k\u00e4ytett\u00e4viss\u00e4 t\u00e4\u00e4ll\u00e4 \u2014 Teams-vierasoikeuksiasi ei ole viel\u00e4 m\u00e4\u00e4ritetty",

    "DisplayGroupName": "N\u00e4ytt\u00f6",
    "ShowBusinessPhonesFieldLabel": "N\u00e4yt\u00e4 ty\u00f6puhelin",
    "ShowMobilePhoneFieldLabel": "N\u00e4yt\u00e4 matkapuhelin",
    "ShowWorkLocationFieldLabel": "N\u00e4yt\u00e4 ty\u00f6paikka",
    "ShowManagerFieldLabel": "N\u00e4yt\u00e4 esimies",
    "UseInformalAddressFieldLabel": "K\u00e4yt\u00e4 sinuttelumuotoa",

    "ShowWorkLocationFallbackFieldLabel": "Näytä työpaikka varana",
    "LocationDisplayHintGeoWithFallback": "Kaupunki ja maa yhdistetään yhdeksi maantieteelliseksi riviksi. Työpaikka näytetään vain, jos kaupunki-/maatietoja ei ole saatavilla.",
    "LocationDisplayHintGeoOnly": "Kaupunki ja maa yhdistetään yhdeksi maantieteelliseksi riviksi. Työpaikka on piilotettu.",
    "LocationDisplayHintOfficeOnly": "Vain työpaikka näytetään. Ota kaupunki ja/tai maa käyttöön, jotta näytetään maantieteellinen rivi.",
    "LocationDisplayHintHidden": "Kaikki sijaintitiedot on piilotettu.",
    "AddressMapFallbackHint": "Jos Azure Maps -avainta ei ole maaritetty tai haku epaonnistuu, naytetaan ulkoinen karttalinkki.",
    "LocationDisplayHintAddressEnabled": "Jasennellyt osoitekentat ovat kaytossa ja ne voidaan nayttaa lisariveilla.",
    "LocationDisplayHintSeparateRows": "Kaupunki/maa ja tyopaikka naytetaan erillisilla riveilla, kun ne ovat kaytossa.",
    "AdvancedDisplayGroupName": "Lisänäyttöasetukset",
    "ManagerOptionsDisabledHint": "Ota esimiehen näyttö käyttöön, jotta voit määrittää esimieskohtaiset kentät.",
    "FunctionGroupName": "Azure-funktio",
    "FunctionUrlFieldLabel": "Sponsori-API-URL (Azure-funktio)",
    "FunctionClientIdFieldLabel": "Sponsori-API-asiakas-ID (Azure-funktiosovelluksen rekister\u00f6inti)",
    "ProxyStatusChecking": "Tarkistetaan Azure-funktiota\u2026",
    "ProxyStatusOk": "Azure-funktio tavoitettavissa",
    "ProxyStatusError": "Azure-funktiota ei l\u00f6ydy",
    "ShowSponsorJobTitleFieldLabel": "N\u00e4yt\u00e4 sponsorin teht\u00e4v\u00e4nimike",
    "ShowManagerJobTitleFieldLabel": "N\u00e4yt\u00e4 esihenkil\u00f6n teht\u00e4v\u00e4nimike",
    "ShowSponsorDepartmentFieldLabel": "N\u00e4yt\u00e4 sponsorin osasto",
    "ShowManagerDepartmentFieldLabel": "N\u00e4yt\u00e4 esihenkil\u00f6n osasto",
    "DepartmentLabel": "Osasto",
    "ShowCityFieldLabel": "N\u00e4yt\u00e4 kaupunki",
    "ShowCountryFieldLabel": "N\u00e4yt\u00e4 maa",
    "ShowStructuredAddressFieldLabel": "Nayta jasennelty osoite",
    "ShowStreetAddressFieldLabel": "Nayta katu",
    "ShowPostalCodeFieldLabel": "Nayta postinumero",
    "ShowStateFieldLabel": "Nayta osavaltio/alue",
    "ShowAddressMapFieldLabel": "Nayta osoitteen karttaesikatselu",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps -tilaavain",
    "ExternalMapProviderFieldLabel": "Ulkoinen karttapalvelu (varavaihtoehto)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Kaupunki",
    "CountryFieldLabel": "Maa",
    "CopyCityAriaLabel": "Kopioi kaupunki",
    "CopyCountryAriaLabel": "Kopioi maa",
    "ShowPresenceFieldLabel": "N\u00e4yt\u00e4 l\u00e4sn\u00e4olotila"
  }
});
