// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function() {
  return {
    "BasicGroupName": "Asetukset",
    "ShowTitleFieldLabel": "Näytä otsikko",
    "TitleFieldLabel": "Otsikko",
    "LoadingMessage": "Ladataan sponsoreitasi…",
    "NoSponsorsTitle": "Ei sponsoreita",
    "NoSponsorsMessage": "Tilillesi ei löydy sponsoreita.",
    "SponsorUnavailableTitle": "Sponsori ei käytettävissä",
    "SponsorUnavailableMessage": "Sponsorisi ei ole enää käytettävissä. Ota yhteyttä projektipäällikköön, jotta tilillesi voidaan nimeätä uusi sponsori.",
    "ErrorMessageTitle": "Jokin meni pieleen",
    "ErrorMessage": "Sponsoritietojen lataaminen epäonnistui. Yritä myöhemmin uudelleen.",
    "EditModePlaceholder": "Vieraan sponsoritiedot — siirry näyttötilaan nähdäksesi sponsorit.",
    "GuestOnlyPlaceholder": "Tämä verkko-osa näkyy vain vieraskäyttäjille näyttötilassa.",
    "MockModeFieldLabel": "Näytä aina demosponsorit (julkinen demotila)",
    "MockModeFieldDescription": "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    "MockModeFieldTooltip": "Kun se on käytössä, demotila näkyy vain live-sivulla testausta varten. Muokkaustila ja esikatselu pysyvät muuttumattomina.",
    "MockModePlaceholder": "Vieraan sponsoritiedot — Demotila on aktiivinen. Siirry näyttötilaan nähdäksesi testitiedot.",
    "MockSimulatedHintFieldLabel": "Simuloi vierailijailmoitus",
    "MockSimulatedHintNoneOption": "Ei ilmoitusta",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams ei ole vielä määritetty",
    "MockSimulatedHintVersionMismatchOption": "Päivitys saatavilla",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsori ei ole käytettävissä",
    "MockSimulatedHintNoSponsorsOption": "Sponsoreita ei löydy",
    "MaxSponsorCountFieldLabel": "Näkyvien sponsoreiden määrä",
    "MaxSponsorCountFieldTooltip": "Rajoittaa näytettävien sponsori-korttien määrää. Vain aktiiviset (käytettävissä olevat) sponsorit lasketaan tätä rajaa vastaan. Jos määritetyn sponsorin tili ei ole enää saatavilla (poistettu käytöstä, poistettu tai ei vielä valmistettu), seuraava sponsori prioriteettijärjestyksessä siirtyy automaattisesti täyttämään tyhjän paikan. Tämä varmistaa, että vieraat näkevät aina määritetyn määrän käytettävissä olevia yhteystietoja.",

    "PresenceAvailable": "Saatavilla",
    "PresenceAvailableIdle": "Saatavilla, poissaoleva",
    "PresenceAway": "Poissa",
    "PresenceBeRightBack": "Palaan pian",
    "PresenceBusy": "Varattu",
    "PresenceBusyIdle": "Varattu, poissaoleva",
    "PresenceDoNotDisturb": "Älä häiritse",
    "PresenceInAMeeting": "Kokouksessa",
    "PresenceInACall": "Puhelussa",
    "PresencePresenting": "Esittää",
    "PresenceFocusing": "Keskittymistilassa",
    "PresenceOutOfOffice": "Poissa toimistosta",
    "PresenceOutOfOfficeSuffix": ", poissa toimistosta",
    "PresenceOffline": "Offline",

    "CloseLabel": "Sulje",
    "ContactDetailsAriaLabel": "{0} yhteystiedot",
    "ContactActionsAriaLabel": "Yhteydenottomahdollisuudet",
    "ChatTitle": "Aloita chat – {name}",
    "EmailTitle": "Sähköposti – {name}",
    "CallTitle": "Aloita äänipuhelu – {name}",
    "ChatLabel": "Chatti",
    "EmailLabel": "Sähköposti",
    "CallLabel": "Soita",

    "ContactInfoSection": "Yhteystieto",
    "EmailFieldLabel": "Sähköposti",
    "WorkPhoneFieldLabel": "Työpuhelin",
    "MobileFieldLabel": "Matkapuhelin",
    "WorkLocationFieldLabel": "Työpaikka",
    "AddressFieldLabel": "Osoite",
    "StreetAddressFieldLabel": "Katu",
    "PostalCodeFieldLabel": "Postinumero",
    "StateFieldLabel": "Osavaltio/alue",

    "OrganizationSection": "Organisaatio",
    "ReportsToSection": "Raportoi henkilölle",
    "ManagerLabel": "Esimies",

    "CopiedFeedback": "Kopioitu!",
    "CopyEmailAriaLabel": "Kopioi sähköpostiosoite",
    "CopyWorkPhoneAriaLabel": "Kopioi työpuhelin",
    "CopyMobileAriaLabel": "Kopioi matkapuhelinnumero",
    "CopyLocationAriaLabel": "Kopioi työpaikka",
    "CopyAddressAriaLabel": "Kopioi osoite",
    "CopyStreetAddressAriaLabel": "Kopioi katu",
    "CopyPostalCodeAriaLabel": "Kopioi postinumero",
    "CopyStateAriaLabel": "Kopioi osavaltio/alue",
    "AddressMapSectionLabel": "Kartan esikatselu",
    "AddressMapLoadingLabel": "Ladataan kartan esikatselua...",
    "OpenAddressInMapLabel": "Avaa kartassa",

    "TeamsAccessPendingTitle": "Microsoft Teamsia ei ole vielä määritetty",
    "TeamsAccessPendingMessage": "Vierasoikeuksiasi Microsoft Teamsiin tässä organisaatiossa ei ole vielä määritetty. Tämä ei vaikuta omaan Teams-tiliisi. Pyydä sponsoriasi lisäämään sinut tiimiin — sen jälkeen Teams-toiminnot kuten chat, puhelut ja kokoukset ovat käytettävissä täällä.",
    "TeamsNotReadyChatTooltip": "Chat ei käytettävissä täällä — Teams-vierasoikeuksiasi ei ole vielä määritetty",
    "TeamsNotReadyCallTooltip": "Puhelu ei käytettävissä täällä — Teams-vierasoikeuksiasi ei ole vielä määritetty",

    "VersionMismatchTitle": "Päivitys saatavilla",
    "VersionMismatchMessage": "Verkko-osalle on saatavana päivitys. Pyydä järjestelmänvalvojaasi varmistamaan, että verkko-osa ja Guest Sponsor API käyttävät samaa versiota.",
    "InsufficientPermissionsTitle": "Lupa puuttuu",
    "InsufficientPermissionsMessage": "Sponsoritietoja ei voitu ladata — vaadittua palvelulupaa ei ole myönnetty. Ota yhteyttä IT-järjestelmänvalvojaasi.",

    "GuestNotificationsGroupName": "Vierailijailmoitukset",
    "GuestNotificationsGroupHint": "Hallinnoi, mitkä tiedottavat ilmoitukset näytetään vierailukäyttäjille.",
    "ShowTeamsAccessPendingHintLabel": "Näytä ilmoitus \"Microsoft Teams ei ole vielä määritetty\"",
    "ShowVersionMismatchHintLabel": "Näytä ilmoitus \"Päivitys saatavilla\"",
    "ShowSponsorUnavailableHintLabel": "Näytä ilmoitus \"Sponsori ei ole käytettävissä\"",
    "ShowNoSponsorsHintLabel": "Näytä ilmoitus \"Sponsoreita ei löydy\"",
    "DisplayGroupName": "Näyttö",
    "CardLayoutFieldLabel": "Kortin asettelu",
    "CardLayoutAutoOption": "Automaattinen",
    "CardLayoutAutoThresholdFieldLabel": "Vaihda tiiviiseen asetteluun tästä sponsorimäärästä alkaen",
    "CardLayoutFullOption": "Täysi",
    "CardLayoutCompactOption": "Tiivis",
    "ShowBusinessPhonesFieldLabel": "Näytä työpuhelin",
    "ShowMobilePhoneFieldLabel": "Näytä matkapuhelin",
    "ShowWorkLocationFieldLabel": "Näytä työpaikka",
    "ShowManagerFieldLabel": "Näytä esimies",
    "SponsorEligibilityGroupName": "Sponsorin kelpoisuus",
    "SponsorEligibilityGroupHint": "Microsoft Entran sponsoriliitoksia yllläpitää organisaatiosi, eivätkä ne ole aina tarkkoja. Nämä suodattimet parantavat vieraille näytettävien sponsoreiden laatua ja ehkäisevät tahatonta tietovuotoa virheellisten liitosten vuoksi.",
    "SponsorFilterFieldLabel": "Sponsorilla täytyy olla",
    "SponsorFilterTeamsOption": "Teams-lisenssi (suositeltu)",
    "SponsorFilterExchangeOption": "Exchange Online -lisenssi",
    "SponsorFilterAnyOption": "Lisenssi (mikä tahansa aktiivinen lisenssi)",
    "RequireUserMailboxFieldLabel": "Vaadi käyttäjäpostilaatikkotyyppi",
    "UseInformalAddressFieldLabel": "Käytä sinuttelumuotoa",

    "LocationDisplayHintSeparateRows": "Käytössä olevat osoitekentät yhdistetään yhdeksi klikattavaksi riviksi.",
    "AdvancedDisplayGroupName": "Lisänäyttöasetukset",
    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "Guest Sponsor API perus-URL",
    "FunctionClientIdFieldLabel": "Guest Sponsor API asiakas-ID (sovelluksen rekisteröinti)",
    "ProxyStatusChecking": "Tarkistetaan Guest Sponsor API…",
    "ProxyStatusOk": "Guest Sponsor API tavoitettavissa",
    "ProxyStatusError": "Guest Sponsor API ei tavoitettavissa",
    "AuthorSectionGroupName": "Tietoja Workoho:sta",
    "AuthorSectionIntro": "Microsoft 365:n hallinto, identiteetit ja vieraskäyttö \u2014 osaamisemme ydintä.",
    "AuthorSectionWebsiteLinkLabel": "Ota yhteyttä",
    "AuthorSectionConsultingText": "Rakensimme tämän verkkosovelman, koska se on juuri sitä, mitä teemme päivittäin. Arkkitehtuurista käyttöönottoon autamme organisaatioita rakentamaan turvallisen ja skaalautuvan yhteistyöympäristön Microsoft 365:ssä.",
    "AuthorSectionPartnerPrefix": "Workoho on",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum-kumppani.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automatisoi elinkaarihallinnan Teams-, SharePoint-sivusto- ja Viva Engage -ympäristöissä sekä muissa Microsoft 365 -työtiloissa – mukaan lukien vieraiden käyttöönotto ja sponsorinhallinta.",
    "AuthorSectionSourceCodeLabel": "Lähdekoodi",
    "AuthorSectionVersionLabel": "Web-osan versio",
    "AuthorSectionDeployToAzureLabel": "Deploy to Azure",
    "AuthorSectionDeploymentGuideLabel": "Käyttöönotto-opas",
    "NewReleaseAvailableLabel": "Uusi versio saatavilla — avaa GitHub Releases",
    "ShowSponsorJobTitleFieldLabel": "Näytä sponsorin tehtävänimike",
    "ShowManagerJobTitleFieldLabel": "Näytä esihenkilön tehtävänimike",
    "ShowSponsorDepartmentFieldLabel": "Näytä sponsorin osasto",
    "ShowManagerDepartmentFieldLabel": "Näytä esihenkilön osasto",
    "DepartmentLabel": "Osasto",
    "ShowCityFieldLabel": "Näytä kaupunki",
    "ShowCountryFieldLabel": "Näytä maa",
    "ShowStreetAddressFieldLabel": "Näytä katu",
    "ShowPostalCodeFieldLabel": "Näytä postinumero",
    "ShowStateFieldLabel": "Näytä osavaltio/alue",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps -tilaavain",
    "MapProviderModeAutoLabel": "Automaattitila (suositeltu)",
    "MapProviderModeManualLabel": "Manuaalinen (sama kaikille laitteille)",
    "MapProviderModeHint": "Valitse karttapalvelu kullekin käyttöjärjestelmälle, iOS ja Android mukaan lukien. Linkki avautuu selaimessa tai palveluntarjoajan sovelluksessa, jos se on asennettu.",
    "MapProviderIosLabel": "iOS:",
    "MapProviderAndroidLabel": "Android:",
    "MapProviderWindowsLabel": "Windows:",
    "MapProviderMacOSLabel": "macOS:",
    "MapProviderLinuxLabel": "Linux:",
    "ExternalMapProviderFieldLabel": "Karttapalvelu",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderNoneOption": "Poistettu käytöstä (ei karttaostaman)",
    "AddressMapProviderHint": "Ota käyttöön vähintään kaupunki ja maa — se riittää mille tahansa karttatarjoajalle merkityksellisen sijainnin näyttämiseen.",
    "AzureMapsPreviewHint": "Lisää Azure Maps -tilausavaimesi, jotta yhteystieto-osioon näytetään pieni kartan esikatselu. Jos olet ottanut käyttöön Guest Sponsor API:n, käyttöönottoon sisältyi Azure Maps -tili — kopioi avain sen todennusasetuksista. Ilman avainta näytetään vain yllä oleva karttalinkki.",
    "CityFieldLabel": "Kaupunki",
    "CountryFieldLabel": "Maa",
    "CopyCityAriaLabel": "Kopioi kaupunki",
    "CopyCountryAriaLabel": "Kopioi maa",
    "ShowPresenceFieldLabel": "Näytä läsnäolotila",
    "ShowSponsorPhotoFieldLabel": "Näytä sponsorin kuva",
    "ShowManagerPhotoFieldLabel": "Näytä esihenkilön kuva",
    "TitlePlaceholder": "Omat sponsorini",
    "TitleSizeFieldLabel": "Otsikon koko",
    "TitleSizeH2Option": "Otsikko 2",
    "TitleSizeH3Option": "Otsikko 3",
    "TitleSizeH4Option": "Otsikko 4",
    "TitleSizeNormalOption": "Normaali",

    "WelcomeDialogTitle": "Määritä Vieraan sponsoritiedot",
    "WelcomeDialogBody": "Tämä verkko-osa näyttää Microsoft 365 -sponsorisi — organisaation sisäiset kollegat, jotka vastaavat vieraskäyttäjätilisi hallinnasta, perehdytyksestäsi ja päivittäisestä tuestäsi.",
    "WelcomeDialogBroughtToYouBy": "Workoho on kehittänyt tämän verkko-osan — asiantuntijat Microsoft 365:n hallinnassa, identiteetissä ja vieraskäyttäjien pääsynhallinnassa.",
    "WelcomeDialogWorkohoLinkLabel": "Vieraile workoho.com-sivustolla",
    "WelcomeDialogNextButton": "Seuraava",
    "WelcomeDialogBackButton": "Takaisin",
    "WelcomeDialogSkipButton": "Ei nyt",
    "WelcomeDialogSaveButton": "Tallenna",
    "WelcomeDialogSkipApiButton": "Ohita",
    "InvalidUrlFormat": "Anna kelvollinen URL (esim. my-app.azurewebsites.net)",
    "InvalidGuidFormat": "Anna kelvollinen GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    "WelcomeDialogSetupTitle": "Valmis muutamassa minuutissa",
    "WelcomeDialogSetupIntro": "Valitse, miten haluat käyttää verkko-osaa. Voit muuttaa tätä milloin tahansa asetuksissa.",
    "WelcomeDialogOptionApiTitle": "Käytä Guest Sponsor -ohjelmointirajapintaa",
    "WelcomeDialogOptionApiBody": "Täysimittainen kokemus Azure-funktion avulla. Vaatii kertaluonteisen Azure-määrityksen — suositellaan tuotantokäyttöön.",
    "WelcomeDialogOptionApiDocsLabel": "Katso asennusopas",
    "WelcomeDialogDeployToAzureLabel": "Deploy to Azure",
    "WelcomeDialogDeployNote": "Tämä vaihtoehto edellyttää, että Guest Sponsor -ohjelmointirajapinta on otettu käyttöön Azure-tilaussasi. Voit tehdä sen tässä — se vie vain muutaman minuutin.",
    "WelcomeDialogConnectApiTitle": "Yhdistä Guest Sponsor -ohjelmointirajapinta",
    "WelcomeDialogConnectApiIntro": "Voit syöttää Guest Sponsor -ohjelmointirajapinnan yhteystiedot tässä vaiheessa. Voit myös lisätä ne myöhemmin verkko-osan asetuksissa.",
    "WelcomeDialogOptionDemoTitle": "Tutustu esittelytilassa",
    "WelcomeDialogOptionDemoBody": "Kokeile verkko-osaa simuloiduilla sponsoritiedoilla — ei Azure-määritystä tarvita. Vaihda oikeaan ohjelmointirajapintaan asetuksista milloin tahansa.",
    "WelcomeDialogFunctionUrlRequired": "Anna Guest Sponsor -ohjelmointirajapinnan perus-URL.",
    "WelcomeDialogDoneApiTitle": "Ohjelmointirajapinta määritetty!",
    "WelcomeDialogDoneApiSkippedTitle": "Melkein valmista!",
    "WelcomeDialogDoneApiSkippedBody": "Tunnistetietoja ei syötetty. Avaa verkko-osan asetukset yhdistääksesi Guest Sponsor -ohjelmointirajapintaan milloin tahansa.",
    "WelcomeDialogDoneApiBody": "Yhteys Guest Sponsor -ohjelmointirajapintaan on tallennettu. Muista tallentaa sivu, jotta asetukset otetaan käyttöön kaikille.",
    "WelcomeDialogDoneDemoTitle": "Esittelytila aktivoitu!",
    "WelcomeDialogDoneDemoBody": "Vaihda näyttötilaan nähdäksesi verkko-osan simuloitujen sponsorikorttien kanssa. Yhdistä Guest Sponsor -ohjelmointirajapinta asetuksista, kun olet valmis.",
    "WelcomeDialogDismissButton": "Aloitetaan",
    "PpSectionLivePage": "▶ Live-sivu",
    "PpSectionDemoMode": "🧪 Demotila",
    "PpSectionCardLayout": "🗂️ Kortin asettelu",
    "PpSectionProfileFields": "👤 Profilikentät",
    "PpSectionPhone": "📞 Puhelinnumerot",
    "PpSectionWorkLocation": "📍 Toimipaikka",
    "PpSectionAddress": "🏠 Postiosoite",
    "PpSectionMapLink": "🧭 Karttalinkki",
    "PpSectionMapPreview": "🗺️ Upotettu kartan esikatselu"
  }
});
