define([], function() {
  return {
    "PropertyPaneDescription": "Määritä Vieraan sponsoritiedot -verkko-osa.",
    "BasicGroupName": "Asetukset",
    "TitleFieldLabel": "Otsikko",
    "LoadingMessage": "Ladataan sponsoreitasi…",
    "NoSponsorsMessage": "Tilillesi ei löydy sponsoreita.",
    "SponsorUnavailableMessage": "Sponsorisi/omistajasi ei ole enää käytettävissä. Ota yhteyttä projektipäällikköön, jotta tilillesi voidaan nimetä uusi sponsori/omistaja.",
    "ErrorMessage": "Sponsoritietojen lataaminen epäonnistui. Yritä myöhemmin uudelleen.",
    "EditModePlaceholder": "Vieraan sponsoritiedot — siirry näyttötilaan nähdäksesi sponsorit.",
    "GuestOnlyPlaceholder": "Tämä verkko-osa näkyy vain vieraskäyttäjille näyttötilassa.",
    "MockModeFieldLabel": "Demotila (testitiedot)",
    "MockModePlaceholder": "Vieraan sponsoritiedot — Demotila on aktiivinen. Siirry näyttötilaan nähdäksesi testitiedot.",

    "PresenceAvailable": "Saatavilla",
    "PresenceAvailableIdle": "Saatavilla, poissaoleva",
    "PresenceAway": "Poissa",
    "PresenceBeRightBack": "Palaan pian",
    "PresenceBusy": "Varattu",
    "PresenceBusyIdle": "Varattu, poissaoleva",
    "PresenceDoNotDisturb": "Älä häiritse",
    "PresenceInAMeeting": "Kokouksessa",
    "PresenceInACall": "Puhelussa",
    "PresencePresenting": "Esittää",
    "PresenceFocusing": "Keskittymistilassa",
    "PresenceOutOfOffice": "Poissa toimistosta",
    "PresenceOutOfOfficeSuffix": ", poissa toimistosta",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "{0} yhteystiedot",
    "ContactActionsAriaLabel": "Yhteydenottomahdollisuudet",
    "ChatTitle": "Chatti Microsoft Teamsissa",
    "EmailTitle": "Lähetä sähköpostia",
    "CallTitle": "Äänipuhelu Microsoft Teamsissa",
    "ChatLabel": "Chatti",
    "EmailLabel": "Sähköposti",
    "CallLabel": "Soita",

    "ContactInfoSection": "Yhteystiedot",
    "EmailFieldLabel": "Sähköposti",
    "WorkPhoneFieldLabel": "Työpuhelin",
    "MobileFieldLabel": "Matkapuhelin",
    "WorkLocationFieldLabel": "Työpaikka",
    "StreetAddressFieldLabel": "Katu",
    "PostalCodeFieldLabel": "Postinumero",
    "StateFieldLabel": "Osavaltio/alue",

    "OrganizationSection": "Organisaatio",
    "ManagerLabel": "Esimies",

    "CopiedFeedback": "Kopioitu!",
    "CopyEmailAriaLabel": "Kopioi sähköpostiosoite",
    "CopyWorkPhoneAriaLabel": "Kopioi työpuhelin",
    "CopyMobileAriaLabel": "Kopioi matkapuhelinnumero",
    "CopyLocationAriaLabel": "Kopioi työpaikka",
    "CopyStreetAddressAriaLabel": "Kopioi katu",
    "CopyPostalCodeAriaLabel": "Kopioi postinumero",
    "CopyStateAriaLabel": "Kopioi osavaltio/alue",
    "AddressMapSectionLabel": "Kartan esikatselu",
    "AddressMapLoadingLabel": "Ladataan kartan esikatselua...",
    "OpenAddressInMapLabel": "Avaa kartassa",

    "TeamsAccessPendingTitle": "Microsoft Teamsia ei ole vielä määritetty",
    "TeamsAccessPendingMessage": "Vierasoikeuksiasi Microsoft Teamsiin tässä organisaatiossa ei ole vielä määritetty. Tämä ei vaikuta omaan Teams-tiliisi. Pyydä sponsoriasi lisäämään sinut tiimiin — sen jälkeen Teams-toiminnot kuten chat, puhelut ja kokoukset ovat käytettävissä täällä.",
    "TeamsNotReadyChatTooltip": "Chat ei käytettävissä täällä — Teams-vierasoikeuksiasi ei ole vielä määritetty",
    "TeamsNotReadyCallTooltip": "Puhelu ei käytettävissä täällä — Teams-vierasoikeuksiasi ei ole vielä määritetty",

    "VersionMismatchMessage": "Verkko-osalle on saatavana päivitys. Pyydä järjestelmänvalvojaasi varmistamaan, että verkko-osa ja Azure Function käyttävät samaa versiota.",
    "InsufficientPermissionsMessage": "Sponsoritietoja ei voitu ladata — vaadittua palvelulupaa ei ole myönnetty. Ota yhteyttä IT-järjestelmänvalvojaasi.",

    "DisplayGroupName": "Näyttö",
    "ShowBusinessPhonesFieldLabel": "Näytä työpuhelin",
    "ShowMobilePhoneFieldLabel": "Näytä matkapuhelin",
    "ShowWorkLocationFieldLabel": "Näytä työpaikka",
    "ShowManagerFieldLabel": "Näytä esimies",
    "UseInformalAddressFieldLabel": "Käytä sinuttelumuotoa",

    "ShowWorkLocationFallbackFieldLabel": "Näytä työpaikka varana",
    "LocationDisplayHintGeoWithFallback": "Kaupunki ja maa yhdistetään yhdeksi maantieteelliseksi riviksi. Työpaikka näytetään vain, jos kaupunki-/maatietoja ei ole saatavilla.",
    "LocationDisplayHintGeoOnly": "Kaupunki ja maa yhdistetään yhdeksi maantieteelliseksi riviksi. Työpaikka on piilotettu.",
    "LocationDisplayHintOfficeOnly": "Vain työpaikka näytetään. Ota kaupunki ja/tai maa käyttöön, jotta näytetään maantieteellinen rivi.",
    "LocationDisplayHintHidden": "Kaikki sijaintitiedot on piilotettu.",
    "AddressMapFallbackHint": "Jos Azure Maps -avainta ei ole määritetty tai haku epäonnistuu, näytetään ulkoinen karttalinkki.",
    "LocationDisplayHintAddressEnabled": "Jäsennellyt osoitekentät ovat käytössä ja ne voidaan näyttää lisäriveillä.",
    "LocationDisplayHintSeparateRows": "Kaupunki/maa ja työpaikka näytetään erillisillä riveillä, kun ne ovat käytössä.",
    "AdvancedDisplayGroupName": "Lisänäyttöasetukset",
    "ManagerOptionsDisabledHint": "Ota esimiehen näyttö käyttöön, jotta voit määrittää esimieskohtaiset kentät.",
    "FunctionGroupName": "Azure-funktio",
    "FunctionUrlFieldLabel": "Sponsori-API-URL (Azure-funktio)",
    "FunctionClientIdFieldLabel": "Sponsori-API-asiakas-ID (Azure-funktiosovelluksen rekisteröinti)",
    "ProxyStatusChecking": "Tarkistetaan Azure-funktiota…",
    "ProxyStatusOk": "Azure-funktio tavoitettavissa",
    "ProxyStatusError": "Azure-funktiota ei löydy",
    "ShowSponsorJobTitleFieldLabel": "Näytä sponsorin tehtävänimike",
    "ShowManagerJobTitleFieldLabel": "Näytä esihenkilön tehtävänimike",
    "ShowSponsorDepartmentFieldLabel": "Näytä sponsorin osasto",
    "ShowManagerDepartmentFieldLabel": "Näytä esihenkilön osasto",
    "DepartmentLabel": "Osasto",
    "ShowCityFieldLabel": "Näytä kaupunki",
    "ShowCountryFieldLabel": "Näytä maa",
    "ShowStructuredAddressFieldLabel": "Näytä jäsennelty osoite",
    "ShowStreetAddressFieldLabel": "Näytä katu",
    "ShowPostalCodeFieldLabel": "Näytä postinumero",
    "ShowStateFieldLabel": "Näytä osavaltio/alue",
    "ShowAddressMapFieldLabel": "Näytä osoitteen karttaesikatselu",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps -tilaavain",
    "ExternalMapProviderFieldLabel": "Ulkoinen karttapalvelu (varavaihtoehto)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Kaupunki",
    "CountryFieldLabel": "Maa",
    "CopyCityAriaLabel": "Kopioi kaupunki",
    "CopyCountryAriaLabel": "Kopioi maa",
    "ShowPresenceFieldLabel": "Näytä läsnäolotila"
  }
});
