define([], function() {
  return {
    "PropertyPaneDescription": "Configurer le composant WebPart «Infos sur le sponsor invité».",
    "BasicGroupName": "Paramètres",
    "TitleFieldLabel": "Titre",
    "LoadingMessage": "Chargement de vos sponsors…",
    "NoSponsorsMessage": "Aucun sponsor trouvé pour votre compte.",
    "SponsorUnavailableMessage": "Votre sponsor/propriétaire n’est plus disponible. Veuillez contacter votre responsable de projet pour qu’un nouveau sponsor/propriétaire vous soit attribué.",
    "ErrorMessage": "Impossible de charger les informations sur les sponsors. Veuillez réessayer ultérieurement.",
    "EditModePlaceholder": "Infos sur le sponsor invité — passez en mode d’affichage pour voir les sponsors.",
    "GuestOnlyPlaceholder": "Ce composant WebPart n’est visible qu’aux utilisateurs invités en mode d’affichage.",
    "MockModeFieldLabel": "Mode démo (données fictives)",
    "MockModePlaceholder": "Infos sur le sponsor invité — Mode démo actif. Passez en mode d’affichage pour voir les données fictives.",

    "PresenceAvailable": "Disponible",
    "PresenceAvailableIdle": "Disponible, inactif",
    "PresenceAway": "Absent",
    "PresenceBeRightBack": "De retour dans un instant",
    "PresenceBusy": "Occupé",
    "PresenceBusyIdle": "Occupé, inactif",
    "PresenceDoNotDisturb": "Ne pas déranger",
    "PresenceInAMeeting": "En réunion",
    "PresenceInACall": "En appel",
    "PresencePresenting": "En présentation",
    "PresenceFocusing": "En concentration",
    "PresenceOutOfOffice": "Absent du bureau",
    "PresenceOutOfOfficeSuffix": ", absent du bureau",
    "PresenceOffline": "Hors connexion",

    "ContactDetailsAriaLabel": "Coordonnées de {0}",
    "ContactActionsAriaLabel": "Actions de contact",
    "ChatTitle": "Discuter dans Microsoft Teams",
    "EmailTitle": "Envoyer un e-mail",
    "CallTitle": "Appel audio dans Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Appel",

    "ContactInfoSection": "Coordonnées",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Téléphone professionnel",
    "MobileFieldLabel": "Mobile",
    "WorkLocationFieldLabel": "Lieu de travail",
    "StreetAddressFieldLabel": "Rue",
    "PostalCodeFieldLabel": "Code postal",
    "StateFieldLabel": "État/région",

    "OrganizationSection": "Organisation",
    "ManagerLabel": "Responsable",

    "CopiedFeedback": "Copié !",
    "CopyEmailAriaLabel": "Copier l’adresse e-mail",
    "CopyWorkPhoneAriaLabel": "Copier le téléphone professionnel",
    "CopyMobileAriaLabel": "Copier le numéro de mobile",
    "CopyLocationAriaLabel": "Copier le lieu de travail",
    "CopyStreetAddressAriaLabel": "Copier la rue",
    "CopyPostalCodeAriaLabel": "Copier le code postal",
    "CopyStateAriaLabel": "Copier l’état/la région",
    "AddressMapSectionLabel": "Aperçu de la carte",
    "AddressMapLoadingLabel": "Chargement de l’aperçu de la carte…",
    "OpenAddressInMapLabel": "Ouvrir dans la carte",

    "TeamsAccessPendingTitle": "Microsoft Teams pas encore configuré",
    "TeamsAccessPendingMessage": "Votre accès invité à Microsoft Teams dans cette organisation n’a pas encore été configuré. Votre propre compte Teams n’est pas concerné. Demandez à votre sponsor de vous ajouter à une équipe — ensuite, les fonctionnalités Teams telles que le chat, les appels et les réunions seront disponibles ici.",
    "TeamsNotReadyChatTooltip": "Chat non disponible ici — votre accès invité Teams n’a pas encore été configuré",
    "TeamsNotReadyCallTooltip": "Appel non disponible ici — votre accès invité Teams n’a pas encore été configuré",
    "VersionMismatchMessage": "Une mise à jour du composant WebPart est disponible. Demandez à votre administrateur de s'assurer que le composant WebPart et la fonction Azure utilisent la même version.",
    "InsufficientPermissionsMessage": "Impossible de charger les informations sur les sponsors — une autorisation de service requise n'a pas été accordée. Veuillez contacter votre administrateur informatique.",
    "LoadingMessageInformal": "Chargement de tes sponsors…",
    "NoSponsorsMessageInformal": "Aucun sponsor trouvé pour ton compte.",
    "SponsorUnavailableMessageInformal": "Ton sponsor/propriétaire n’est plus disponible. Contacte ton responsable de projet pour qu’un nouveau sponsor/propriétaire te soit attribué.",
    "ErrorMessageInformal": "Impossible de charger les informations sur les sponsors. Réessaie plus tard.",
    "TeamsAccessPendingMessageInformal": "Ton accès invité à Microsoft Teams dans cette organisation n’a pas encore été configuré. Ton propre compte Teams n’est pas concerné. Demande à ton sponsor de t’ajouter à une équipe — ensuite, tu pourras utiliser les fonctionnalités Teams comme le chat, les appels et les réunions ici.",
    "TeamsNotReadyChatTooltipInformal": "Chat non disponible ici — ton accès invité Teams n’a pas encore été configuré",
    "TeamsNotReadyCallTooltipInformal": "Appel non disponible ici — ton accès invité Teams n’a pas encore été configuré",

    "DisplayGroupName": "Affichage",
    "ShowBusinessPhonesFieldLabel": "Afficher le téléphone professionnel",
    "ShowMobilePhoneFieldLabel": "Afficher le numéro de mobile",
    "ShowWorkLocationFieldLabel": "Afficher le lieu de travail",
    "ShowManagerFieldLabel": "Afficher le responsable",
    "UseInformalAddressFieldLabel": "Utiliser le tutoiement (tu)",

    "ShowWorkLocationFallbackFieldLabel": "Afficher le lieu de travail comme repli",
    "LocationDisplayHintGeoWithFallback": "La ville et le pays sont combinés sur une seule ligne géographique. Le lieu de travail n'est affiché que si aucune donnée de ville/pays n'est disponible.",
    "LocationDisplayHintGeoOnly": "La ville et le pays sont combinés sur une seule ligne géographique. Le lieu de travail est masqué.",
    "LocationDisplayHintOfficeOnly": "Seul le lieu de travail est affiché. Activez la ville et/ou le pays pour afficher plutôt une ligne géographique.",
    "LocationDisplayHintHidden": "Toutes les informations de localisation sont masquées.",
    "AddressMapFallbackHint": "Si aucune clé Azure Maps n’est configurée ou si la recherche échoue, un lien de carte externe est affiché.",
    "LocationDisplayHintAddressEnabled": "Les champs d’adresse structurée sont activés et peuvent être affichés dans des lignes supplémentaires.",
    "LocationDisplayHintSeparateRows": "Ville/pays et lieu de travail sont affichés sur des lignes séparées lorsqu’ils sont activés.",
    "AdvancedDisplayGroupName": "Options d'affichage avancées",
    "ManagerOptionsDisabledHint": "Activez l'affichage du responsable pour configurer les champs spécifiques au responsable.",
    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "URL de l'API des sponsors (Azure Function)",
    "FunctionClientIdFieldLabel": "ID de client de l'API des sponsors (inscription d'application Azure Function)",
    "ProxyStatusChecking": "Vérification de la Azure Function…",
    "ProxyStatusOk": "Azure Function accessible",
    "ProxyStatusError": "Azure Function inaccessible",
    "ShowSponsorJobTitleFieldLabel": "Afficher le poste du sponsor",
    "ShowManagerJobTitleFieldLabel": "Afficher le poste du responsable",
    "ShowSponsorDepartmentFieldLabel": "Afficher le service du sponsor",
    "ShowManagerDepartmentFieldLabel": "Afficher le service du responsable",
    "DepartmentLabel": "Service",
    "ShowCityFieldLabel": "Afficher la ville",
    "ShowCountryFieldLabel": "Afficher le pays",
    "ShowStructuredAddressFieldLabel": "Afficher l’adresse structurée",
    "ShowStreetAddressFieldLabel": "Afficher la rue",
    "ShowPostalCodeFieldLabel": "Afficher le code postal",
    "ShowStateFieldLabel": "Afficher l’état/la région",
    "ShowAddressMapFieldLabel": "Afficher l’aperçu cartographique de l’adresse",
    "AzureMapsSubscriptionKeyFieldLabel": "Clé d’abonnement Azure Maps",
    "ExternalMapProviderFieldLabel": "Fournisseur cartographique externe (repli)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Ville",
    "CountryFieldLabel": "Pays",
    "CopyCityAriaLabel": "Copier la ville",
    "CopyCountryAriaLabel": "Copier le pays",
    "ShowPresenceFieldLabel": "Afficher le statut de présence"
  }
});
