// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function() {
  return {
    "BasicGroupName": "Paramètres",
    "ShowTitleFieldLabel": "Afficher le titre",
    "TitleFieldLabel": "Titre",
    "LoadingMessage": "Chargement de vos sponsors…",
    "NoSponsorsTitle": "Aucun sponsor trouvé",
    "NoSponsorsMessage": "Aucun sponsor trouvé pour votre compte.",
    "SponsorUnavailableTitle": "Sponsor indisponible",
    "SponsorUnavailableMessage": "Votre sponsor n'est plus disponible. Veuillez contacter votre responsable de projet pour qu'un nouveau sponsor vous soit attribué.",
    "ErrorMessageTitle": "Une erreur est survenue",
    "ErrorMessage": "Impossible de charger les informations sur les sponsors. Veuillez réessayer ultérieurement.",
    "EditModePlaceholder": "Infos sur le sponsor invité — passez en mode d’affichage pour voir les sponsors.",
    "GuestOnlyPlaceholder": "Ce composant WebPart n’est visible qu’aux utilisateurs invités en mode d’affichage.",
    "MockModeFieldLabel": "Toujours afficher les sponsors de démo (mode démo public)",
    "MockModeFieldDescription": "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    "MockModeFieldTooltip": "Lorsqu'il est activé, le mode démo s'affiche uniquement sur la page active à des fins de test. Le mode d'édition et l'aperçu restent inchangés.",
    "MockModePlaceholder": "Infos sur le sponsor invité — Mode démo actif. Passez en mode d’affichage pour voir les données fictives.",
    "MockSimulatedHintFieldLabel": "Simuler une notification invité",
    "MockSimulatedHintNoneOption": "Aucune notification",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams pas encore configuré",
    "MockSimulatedHintVersionMismatchOption": "Mise à jour disponible",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsor indisponible",
    "MockSimulatedHintNoSponsorsOption": "Aucun sponsor trouvé",
    "MaxSponsorCountFieldLabel": "Sponsors affichés",
    "MaxSponsorCountFieldTooltip": "Limite le nombre de cartes de parrain affichées. Seuls les parrains actifs (disponibles) sont comptés pour cette limite. Si le compte d'un parrain assigné devient indisponible (désactivé, supprimé ou pas encore approvisionné), le parrain suivant dans l'ordre de priorité avance automatiquement pour remplir la place vide. Cela garantit que les invités voient toujours le nombre configuré de contacts disponibles.",

    "PresenceAvailable": "Disponible",
    "PresenceAvailableIdle": "Disponible, inactif",
    "PresenceAway": "Absent",
    "PresenceBeRightBack": "De retour dans un instant",
    "PresenceBusy": "Occupé",
    "PresenceBusyIdle": "Occupé, inactif",
    "PresenceDoNotDisturb": "Ne pas déranger",
    "PresenceInAMeeting": "En réunion",
    "PresenceInACall": "En appel",
    "PresencePresenting": "En présentation",
    "PresenceFocusing": "En concentration",
    "PresenceOutOfOffice": "Absent du bureau",
    "PresenceOutOfOfficeSuffix": ", absent du bureau",
    "PresenceOffline": "Hors connexion",

    "CloseLabel": "Fermer",
    "ContactDetailsAriaLabel": "Coordonnées de {0}",
    "ContactActionsAriaLabel": "Actions de contact",
    "ChatTitle": "Démarrer un chat avec {name}",
    "EmailTitle": "Envoyer un e-mail à {name}",
    "CallTitle": "Démarrer un appel audio avec {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Appel",

    "ContactInfoSection": "Contact",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Téléphone professionnel",
    "MobileFieldLabel": "Mobile",
    "WorkLocationFieldLabel": "Lieu de travail",
    "AddressFieldLabel": "Adresse",
    "StreetAddressFieldLabel": "Rue",
    "PostalCodeFieldLabel": "Code postal",
    "StateFieldLabel": "État/région",

    "OrganizationSection": "Organisation",
    "ReportsToSection": "Rend compte à",
    "ManagerLabel": "Responsable",

    "CopiedFeedback": "Copié !",
    "CopyEmailAriaLabel": "Copier l’adresse e-mail",
    "CopyWorkPhoneAriaLabel": "Copier le téléphone professionnel",
    "CopyMobileAriaLabel": "Copier le numéro de mobile",
    "CopyLocationAriaLabel": "Copier le lieu de travail",
    "CopyAddressAriaLabel": "Copier l'adresse",
    "CopyStreetAddressAriaLabel": "Copier la rue",
    "CopyPostalCodeAriaLabel": "Copier le code postal",
    "CopyStateAriaLabel": "Copier l’état/la région",
    "AddressMapSectionLabel": "Aperçu de la carte",
    "AddressMapLoadingLabel": "Chargement de l’aperçu de la carte…",
    "OpenAddressInMapLabel": "Ouvrir dans la carte",

    "TeamsAccessPendingTitle": "Microsoft Teams pas encore configuré",
    "TeamsAccessPendingMessage": "Votre accès invité à Microsoft Teams dans cette organisation n’a pas encore été configuré. Votre propre compte Teams n’est pas concerné. Demandez à votre sponsor de vous ajouter à une équipe — ensuite, les fonctionnalités Teams telles que le chat, les appels et les réunions seront disponibles ici.",
    "TeamsNotReadyChatTooltip": "Chat non disponible ici — votre accès invité Teams n’a pas encore été configuré",
    "TeamsNotReadyCallTooltip": "Appel non disponible ici — votre accès invité Teams n’a pas encore été configuré",
    "VersionMismatchTitle": "Mise à jour disponible",
    "VersionMismatchMessage": "Une mise à jour du composant WebPart est disponible. Demandez à votre administrateur de s'assurer que le composant WebPart et la Guest Sponsor API utilisent la même version.",
    "InsufficientPermissionsTitle": "Autorisation requise",
    "InsufficientPermissionsMessage": "Impossible de charger les informations sur les sponsors — une autorisation de service requise n'a pas été accordée. Veuillez contacter votre administrateur informatique.",

    "GuestNotificationsGroupName": "Notifications pour les invités",
    "GuestNotificationsGroupHint": "Contrôlez les notifications informatives affichées aux utilisateurs invités.",
    "ShowTeamsAccessPendingHintLabel": "Afficher la notification « Microsoft Teams pas encore configuré »",
    "ShowVersionMismatchHintLabel": "Afficher la notification « Mise à jour disponible »",
    "ShowSponsorUnavailableHintLabel": "Afficher la notification « Sponsor indisponible »",
    "ShowNoSponsorsHintLabel": "Afficher la notification « Aucun sponsor trouvé »",
    "DisplayGroupName": "Affichage",
    "CardLayoutFieldLabel": "Disposition des cartes",
    "CardLayoutAutoOption": "Automatique",    "CardLayoutAutoThresholdFieldLabel": "Passer en affichage compact à partir de ce nombre de sponsors",    "CardLayoutFullOption": "Complète",
    "CardLayoutCompactOption": "Compacte",
    "ShowBusinessPhonesFieldLabel": "Afficher le téléphone professionnel",
    "ShowMobilePhoneFieldLabel": "Afficher le numéro de mobile",
    "ShowWorkLocationFieldLabel": "Afficher le lieu de travail",
    "ShowManagerFieldLabel": "Afficher le responsable",
    "SponsorEligibilityGroupName": "Éligibilité des sponsors",
    "SponsorEligibilityGroupHint": "Les assignations de sponsor dans Microsoft Entra sont gérées par votre organisation et peuvent ne pas être toujours exactes. Ces filtres améliorent la qualité des sponsors affichés aux invités et préviennent la divulgation involontaire d'informations due à des assignations incorrectes.",
    "SponsorFilterFieldLabel": "Le sponsor doit être",
    "SponsorFilterTeamsOption": "Licencié Teams (recommandé)",
    "SponsorFilterExchangeOption": "Licencié Exchange Online",
    "SponsorFilterAnyOption": "Licencié (toute licence active)",
    "RequireUserMailboxFieldLabel": "Exiger un type de boîte aux lettres utilisateur",
    "UseInformalAddressFieldLabel": "Utiliser le tutoiement (tu)",

    "LocationDisplayHintSeparateRows": "Les champs d'adresse activés sont combinés en une seule ligne cliquable.",
    "AdvancedDisplayGroupName": "Options d'affichage avancées",
    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "URL de base",
    "FunctionClientIdFieldLabel": "ID d'application (client)",
    "PpClientIdHintLabel": "O\u00f9 trouver l'ID de client ?",
    "PpClientIdHintBody": "Copiez l'ID de client (ID d'application) depuis l'inscription d'application cr\u00e9\u00e9e lors de la configuration.",
    "FunctionEntraLinkLabel": "Rechercher dans Microsoft Entra →",
    "ProxyStatusChecking": "Vérification de la Guest Sponsor API…",
    "ProxyStatusOk": "Connexion r\u00e9ussie",
    "ProxyStatusError": "Connexion \u00e9chou\u00e9e",
    "PpSetupIntro": "Configuration requise :",
    "PpSetupRerunHint": "Problème de connexion ? Les scripts de configuration sont idempotents \u2014 les relancer avec les mêmes paramètres corrige la plupart des problèmes.",
    "CopyToClipboardLabel": "Copier",
    "CopiedToClipboardLabel": "Copié !",
    "AuthorSectionGroupName": "À propos de Workoho",
    "AuthorSectionIntro": "Gouvernance Microsoft 365, identités et accès invité \u2014 notre domaine.",
    "AuthorSectionWebsiteLinkLabel": "Travaillons ensemble",
    "AuthorSectionConsultingText": "Nous avons conçu ce composant parce que c'est notre quotidien. De l'architecture au déploiement, nous aidons les organisations à bâtir une collaboration sécurisée et évolutive sur Microsoft 365.",
    "AuthorSectionPartnerPrefix": "Workoho est",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Partenaire Platinum.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automatise la gestion du cycle de vie pour Teams, les sites SharePoint, Viva Engage et d'autres espaces de travail Microsoft 365 — y compris l'intégration des invités et la gestion des sponsors.",
    "AuthorSectionSourceCodeLabel": "Code source",
    "AuthorSectionVersionLabel": "Version du composant Web",
    "AuthorSectionDeployToAzureLabel": "Deploy to Azure",
    "DeployToAzureClickHint": "Cliquez sur le bouton pour lancer le d\u00e9ploiement :",
    "AuthorSectionDeploymentGuideLabel": "Guide de déploiement",
    "NewReleaseAvailableLabel": "Nouvelle version disponible — ouvrir GitHub Releases",
    "ShowSponsorJobTitleFieldLabel": "Afficher le poste du sponsor",
    "ShowManagerJobTitleFieldLabel": "Afficher le poste du responsable",
    "ShowSponsorDepartmentFieldLabel": "Afficher le service du sponsor",
    "ShowManagerDepartmentFieldLabel": "Afficher le service du responsable",
    "DepartmentLabel": "Service",
    "ShowCityFieldLabel": "Afficher la ville",
    "ShowCountryFieldLabel": "Afficher le pays",
    "ShowStreetAddressFieldLabel": "Afficher la rue",
    "ShowPostalCodeFieldLabel": "Afficher le code postal",
    "ShowStateFieldLabel": "Afficher l’état/la région",
    "AzureMapsSubscriptionKeyFieldLabel": "Clé d’abonnement Azure Maps",    "MapProviderModeAutoLabel": "Mode automatique (recommandé)",
    "MapProviderModeManualLabel": "Manuel (identique pour tous les appareils)",
    "MapProviderModeHint": "Choisissez un fournisseur de cartes par système d'exploitation, y compris iOS et Android. Le lien s'ouvre dans le navigateur ou dans l'application du fournisseur si elle est installée.",
    "MapProviderIosLabel": "iOS:",
    "MapProviderAndroidLabel": "Android:",
    "MapProviderWindowsLabel": "Windows :",
    "MapProviderMacOSLabel": "macOS :",
    "MapProviderLinuxLabel": "Linux :",    "ExternalMapProviderFieldLabel": "Fournisseur cartographique",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderNoneOption": "Désactivé (aucun lien carte)",
    "AddressMapProviderHint": "Activez au moins la ville et le pays — cela suffit à tout fournisseur de carte pour afficher une vue pertinente de l'emplacement.",
    "AzureMapsPreviewHint": "Ajoutez votre clé d'abonnement Azure Maps pour afficher un petit aperçu de carte dans la section de contact. Si vous avez déployé l'API Guest Sponsor, un compte Azure Maps a été inclus — copiez la clé depuis ses paramètres d'authentification. Sans clé, seul le lien de carte ci-dessus est affiché.",
    "CityFieldLabel": "Ville",
    "CountryFieldLabel": "Pays",
    "CopyCityAriaLabel": "Copier la ville",
    "CopyCountryAriaLabel": "Copier le pays",
    "ShowPresenceFieldLabel": "Afficher le statut de présence",
    "ShowSponsorPhotoFieldLabel": "Afficher la photo du sponsor",
    "ShowManagerPhotoFieldLabel": "Afficher la photo du responsable",
    "TitlePlaceholder": "Mes sponsors",
    "TitleSizeFieldLabel": "Taille du titre",
    "TitleSizeH2Option": "Titre 2",
    "TitleSizeH3Option": "Titre 3",
    "TitleSizeH4Option": "Titre 4",
    "TitleSizeNormalOption": "Normal",

    "WelcomeDialogTitle": "Configurer Infos sur le sponsor invité",
    "WelcomeDialogBody": "Ce composant affiche les sponsors Microsoft Entra de chaque utilisateur invité sur votre page d'accueil SharePoint. Pour que le composant soit utile, les attributions de sponsors doivent être gérées activement et un processus de cycle de vie des invités doit déjà être en place — il rend cette responsabilité visible, mais ne remplace pas la gouvernance sous-jacente.",
    "WelcomeDialogBroughtToYouBy": "Développé par Workoho — spécialistes de la gouvernance des invités et de la gestion du cycle de vie.",
    "WelcomeDialogWorkohoLinkLabel": "workoho.com",
    "WelcomeDialogNextButton": "Suivant",
    "WelcomeDialogBackButton": "Retour",
    "WelcomeDialogSkipButton": "Pas maintenant",
    "WelcomeDialogSaveButton": "Enregistrer",
    "WelcomeDialogSkipApiButton": "Ignorer",
    "InvalidUrlFormat": "Veuillez entrer une URL valide (p. ex. my-app.azurewebsites.net)",
    "InvalidGuidFormat": "Veuillez entrer un GUID valide (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    "WelcomeDialogSetupTitle": "Prêt en quelques minutes",
    "WelcomeDialogSetupIntro": "Choisissez votre méthode de déploiement. Vous pouvez basculer entre les deux options à tout moment via les paramètres du composant.",
    "WelcomeDialogOptionApiTitle": "Utiliser l'API Guest Sponsor",
    "WelcomeDialogOptionApiBody": "Expérience complète alimentée par une Azure Function. Nécessite une configuration Azure unique — recommandé pour la production.",
    "WelcomeDialogOptionApiDocsLabel": "Voir le guide de configuration",
    "WelcomeDialogDeployToAzureLabel": "Déployer l'API dans Azure",
    "WelcomeDialogDeployNote": "Cette option nécessite que l'API Guest Sponsor soit déployée dans votre abonnement Azure. Vous pouvez le faire ici même \u2014 cela ne prend que quelques minutes.",
    "WelcomeDialogSetupStep1Label": "Créer l'inscription d'application",
    "WelcomeDialogSetupStep3Label": "Accorder les autorisations Graph",
    "WelcomeDialogSetupPwshHint": "PowerShell 7+ :",
    "WelcomeDialogSetupStep3Hint": "Utilise les valeurs des étapes 1 et 2",
    "WelcomeDialogConnectApiTitle": "Connecter l'API Guest Sponsor",
    "WelcomeDialogConnectApiIntro": "Entrez facultativement les informations de connexion à votre API Guest Sponsor. Vous pouvez aussi les ajouter plus tard dans les paramètres du composant.",
    "WelcomeDialogOptionDemoTitle": "Explorer en mode démo",
    "WelcomeDialogOptionDemoBody": "Essayez le composant avec des données de sponsors simulées — aucune configuration Azure requise. Passez à l'API réelle depuis les paramètres à tout moment.",
    "WelcomeDialogFunctionUrlRequired": "Veuillez entrer l'URL de base de l'API Guest Sponsor.",
    "WelcomeDialogDoneApiTitle": "API configurée !",
    "WelcomeDialogDoneApiSkippedTitle": "Presque terminé !",
    "WelcomeDialogDoneApiSkippedBody": "Aucune information d'identification n'a été saisie. Ouvrez les paramètres du composant Web pour connecter l'API Sponsor Invité dès que vous serez prêt.",
    "WelcomeDialogDoneApiBody": "La connexion à l'API Guest Sponsor a été enregistrée. N'oubliez pas d'enregistrer la page pour que vos paramètres soient appliqués pour tout le monde.",
    "WelcomeDialogDoneDemoTitle": "Mode démo activé !",
    "WelcomeDialogDoneDemoBody": "Passez en mode affichage pour voir le composant avec des cartes de sponsors simulées. Connectez l'API Guest Sponsor depuis les paramètres quand vous êtes prêt.",
    "WelcomeDialogDismissButton": "C'est parti",
    "PpSectionLivePage": "▶ Page active",
    "PpSectionDemoMode": "🧪 Mode démo",
    "PpSectionCardLayout": "🗂️ Mise en page",
    "PpSectionProfileFields": "👤 Champs de profil",
    "PpSectionPhone": "📞 Numéros de téléphone",
    "PpSectionWorkLocation": "📍 Lieu de travail",
    "PpSectionAddress": "🏠 Adresse postale",
    "PpSectionMapLink": "🧭 Lien de carte",
    "PpSectionMapPreview": "🗺️ Aperçu de carte intégré"
  }
});
