// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Beállítások",
    ShowTitleFieldLabel: "Cím megjelenítése",
    TitleFieldLabel: "Cím",
    LoadingMessage: "Szponzorok betöltése…",
    NoSponsorsTitle: "Nem találhatók szponzorok",
    NoSponsorsMessage: "A fiókjához nem találhatók szponzorok.",
    SponsorUnavailableTitle: "A szponzor nem érhető el",
    SponsorUnavailableMessage:
      "A szponzora már nem érhető el. Kérjük, lépjen kapcsolatba a projekt felelős személyével, hogy új szponzort rendeljenek a fiókjához.",
    ErrorMessageTitle: "Valami hiba történt",
    ErrorMessage: "Nem sikerült betölteni a szponzor adatait. Kérjük, próbálja újra később.",
    EditModePlaceholder: "Vendég szponzor információ — váltson nézeti módba a szponzorok megtekintéséhez.",
    GuestOnlyPlaceholder: "Ez a webes kijelző csak a vendégfelhasználók számára látható nézeti módban.",
    MockModeFieldLabel: "Nyilvános demó mód engedélyezése belső felhasználóknak",
    MockModeFieldDescription:
      "Csak a látogatók élő oldalára vonatkozik. Szerkesztési módban az előnézet nem változik. Engedélyezze ezt a webes kijelző teszteléséhez szimulált szponzorokkal a belső felhasználók számára a bérlőjében; letiltva csak a vendégfelhasználók látják a szponzortartalmat.",
    MockModeFieldTooltip:
      "Ha engedélyezve van, a demó mód az élő oldalon csak tesztelési célból jelenik meg. A szerkesztési mód és az előnézet változatlan marad.",
    MockModePlaceholder:
      "Vendég szponzor információ — Demó mód aktív. Váltson nézeti módba a szimulált szponzorok megtekintéséhez.",
    MockSimulatedHintFieldLabel: "Vendégértesítés szimulálása",
    MockSimulatedHintNoneOption: "Nincs (értesítés nélkül)",
    MockSimulatedHintTeamsAccessPendingOption: "A Teams még nincs beállítva",
    MockSimulatedHintVersionMismatchOption: "Frissítés elérhető",
    MockSimulatedHintSponsorUnavailableOption: "A szponzor nem érhető el",
    MockSimulatedHintNoSponsorsOption: "Nem találhatók szponzorok",
    MaxSponsorCountFieldLabel: "Látható szponzorok",
    MaxSponsorCountFieldTooltip:
      "Korlátozza a megjelenített aktív szponzorkartyák számát. Ebbe a korlátba csak az aktív (elérhető) szponzorok számítanak bele. Ha egy hozzárendelt szponzor fiókja elérhetetlenné válik (letiltva, törölve vagy még nem kiépítve), a prioritási sorrendben következő szponzor automatikusan előre lép az üres hely betöltéséhez. Így a vendégek mindig a beállított számú elérhető kapcsolatot látják.",
    PresenceAvailable: "Elérhető",
    PresenceAvailableIdle: "Elérhető, tétlen",
    PresenceAway: "Távol",
    PresenceBeRightBack: "Mindjárt itt vagyok",
    PresenceBusy: "Foglalt",
    PresenceBusyIdle: "Foglalt, tétlen",
    PresenceDoNotDisturb: "Ne zavarjanak",
    PresenceInAMeeting: "Megbeszélésen",
    PresenceInACall: "Hívásban",
    PresencePresenting: "Prezentál",
    PresenceFocusing: "Fókuszálás",
    PresenceOutOfOffice: "Irodán kívül",
    PresenceOutOfOfficeSuffix: ", irodán kívül",
    PresenceOffline: "Offline",
    ContactDetailsAriaLabel: "Kapcsolattartási adatok: {0}",
    ContactActionsAriaLabel: "Kapcsolatfelvételi műveletek",
    CloseLabel: "Bezárás",
    ChatTitle: "Chat indítása ezzel: {name}",
    EmailTitle: "E-mail küldése: {name}",
    CallTitle: "Hanghívás indítása ezzel: {name}",
    ChatLabel: "Chat",
    EmailLabel: "E-mail",
    CallLabel: "Hívás",
    ContactInfoSection: "Kapcsolat",
    EmailFieldLabel: "E-mail",
    WorkPhoneFieldLabel: "Munkahelyi telefon",
    MobileFieldLabel: "Mobil",
    WorkLocationFieldLabel: "Munkahely",
    AddressFieldLabel: "Cím",
    StreetAddressFieldLabel: "Utca",
    PostalCodeFieldLabel: "Irányítószám",
    StateFieldLabel: "Megye/Régió",
    OrganizationSection: "Szervezet",
    ReportsToSection: "Felettese",
    ManagerLabel: "Vezető",
    CopiedFeedback: "Másolva!",
    CopyEmailAriaLabel: "E-mail cím másolása",
    CopyWorkPhoneAriaLabel: "Munkahelyi telefon másolása",
    CopyMobileAriaLabel: "Mobilszám másolása",
    CopyLocationAriaLabel: "Munkahely másolása",
    CopyAddressAriaLabel: "Cím másolása",
    CopyStreetAddressAriaLabel: "Utca másolása",
    CopyPostalCodeAriaLabel: "Irányítószám másolása",
    CopyStateAriaLabel: "Megye/Régió másolása",
    AddressMapSectionLabel: "Térkép előnézet",
    AddressMapLoadingLabel: "Térkép előnézet betöltése…",
    OpenAddressInMapLabel: "Megnyitás térképen",
    TeamsAccessPendingTitle: "A Microsoft Teams még nincs beállítva",
    TeamsAccessPendingMessage:
      "A szervezetnél még nincs beállítva a Microsoft Teams vendéghozzáférés az Ön számára. Ez nem érinti a saját Teams-fiókját. Kérje meg szponzorát, hogy adja hozzá Önt egy csapathoz — ezt követően az olyan Teams-funkciók, mint a chat, a hívások és az értekezletek, elérhetővé válnak majd itt.",
    TeamsNotReadyChatTooltip:
      "A chat nem érhető el ebben a szervezetben — a Teams vendéghozzáférés még nincs beállítva",
    TeamsNotReadyCallTooltip:
      "A hívás nem érhető el ebben a szervezetben — a Teams vendéghozzáférés még nincs beállítva",
    VersionMismatchTitle: "Frissítés elérhető",
    VersionMismatchMessage:
      "Elérhető egy webes kijelző frissítés. Kérje meg a rendszergazdát, hogy gondoskodjon arról, hogy a webes kijelző és a Guest Sponsor API azonos verziót futtasson.",
    InsufficientPermissionsTitle: "Jogosultság szükséges",
    InsufficientPermissionsMessage:
      "Nem sikerült betölteni a szponzor adatait — egy szükséges szolgáltatásengedély nem lett megadva. Kérjük, lépjen kapcsolatba az informatikai rendszergazdájával.",
    GuestNotificationsGroupName: "Vendégértesítések",
    GuestNotificationsGroupHint:
      "Szabályozza, hogy mely tájékoztató értesítések jelenjenek meg a vendégfelhasználóknak.",
    ShowTeamsAccessPendingHintLabel: '"A Teams még nincs beállítva" értesítés megjelenítése',
    ShowVersionMismatchHintLabel: '"Frissítés elérhető" értesítés megjelenítése',
    ShowSponsorUnavailableHintLabel: '"A szponzor nem érhető el" értesítés megjelenítése',
    ShowNoSponsorsHintLabel: '"Nem találhatók szponzorok" értesítés megjelenítése',
    DisplayGroupName: "Megjelenítés",
    CardLayoutFieldLabel: "Kártya elrendezés",
    CardLayoutAutoOption: "Automatikus",
    CardLayoutAutoThresholdFieldLabel: "Váltás kompakt nézetre ennyi szponzortól",
    CardLayoutFullOption: "Teljes",
    CardLayoutCompactOption: "Kompakt",
    ShowBusinessPhonesFieldLabel: "Munkahelyi telefonszámok megjelenítése",
    ShowMobilePhoneFieldLabel: "Mobilszám megjelenítése",
    ShowWorkLocationFieldLabel: "Munkahely megjelenítése",
    ShowStreetAddressFieldLabel: "Utca megjelenítése",
    ShowPostalCodeFieldLabel: "Irányítószám megjelenítése",
    ShowStateFieldLabel: "Megye/Régió megjelenítése",
    AzureMapsSubscriptionKeyFieldLabel: "Azure Maps előfizetési kulcs",
    MapProviderModeAutoLabel: "Automatikus mód (ajánlott)",
    MapProviderModeManualLabel: "Kézi (ugyanaz minden eszközre)",
    MapProviderModeHint:
      "Válasszon térképszolgáltatót minden operációs rendszerhez, beleértve az iOS-t és az Androidot. A hivatkozások a böngészőben vagy a szolgáltató alkalmazásában nyílnak meg, ha telepítve van.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Térképszolgáltató",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Letiltva (nincs térképhivatkozás)",
    AddressMapProviderHint:
      "Engedélyezze legalább a várost és az országot — ez elegendő bármely térképszolgáltató számára egy értelmes helyszín megjelenítéséhez.",
    AzureMapsPreviewHint:
      "Adja meg az Azure Maps előfizetési kulcsát egy kis beágyazott térkép előnézet megjelenítéséhez a kapcsolattartási részben. Ha telepítette a Guest Sponsor API-t, egy Azure Maps-fiók is mellékelve volt — másolja ki a kulcsot a hitelesítési beállításokból. Kulcs nélkül csak a fenti térképhivatkozás jelenik meg.",
    ShowManagerFieldLabel: "Vezető megjelenítése",
    UseInformalAddressFieldLabel: "Informális megszólítás használata (te)",
    SponsorEligibilityGroupName: "Szponzorjogosultság",
    SponsorEligibilityGroupHint:
      "A Microsoft Entra-ban lévő szponzor-hozzárendeléseket a szervezet kezeli, és nem mindig pontosak. Ezek a szűrők segítenek javítani a vendégek számára megjelenített szponzorok minőségét, és megakadályozzák a helytelen hozzárendelések által okozott véletlen adatszivárgást.",
    SponsorFilterFieldLabel: "A szponzornak rendelkeznie kell",
    SponsorFilterTeamsOption: "Teams licenccel (ajánlott)",
    SponsorFilterExchangeOption: "Exchange Online licenccel",
    SponsorFilterAnyOption: "Licenccel (bármely aktív licenc)",
    RequireUserMailboxFieldLabel: "Felhasználói postaláda típusának megkövetelése",
    LocationDisplayHintSeparateRows: "Az engedélyezett címmezők egyetlen kattintható sorba kerülnek összevonásra.",
    AdvancedDisplayGroupName: "Speciális megjelenítési beállítások",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "Alap URL",
    FunctionClientIdFieldLabel: "Alkalmazás (ügyfél) azonosítója",
    PpClientIdHintLabel: "Hol találom az ügyfélazonosítót?",
    PpClientIdHintBody:
      "Másolja ki az ügyfélazonosítót (alkalmazásazonosítót) a telepítés során létrehozott alkalmazásregisztrációból.",
    FunctionEntraLinkLabel: "Keresés a Microsoft Entra-ban →",
    ProxyStatusChecking: "Guest Sponsor API kapcsolat ellenőrzése…",
    ProxyStatusOk: "Kapcsolat sikeres",
    ProxyStatusError: "Kapcsolat sikertelen",
    PpSetupIntro: "Szükséges beállítás:",
    PpSetupRerunHint:
      "Kapcsolódási probléma? A beállítási szkriptek idempotensek — azonos paraméterekkel újrafuttatva a legtöbb problémát megoldják.",
    CopyToClipboardLabel: "Másolás",
    CopiedToClipboardLabel: "Másolva!",
    AuthorSectionGroupName: "Névjegy",
    AuthorSectionCreatedBy: "Létrehozta és karbantartja",
    AuthorSectionIntro: "Microsoft 365 irányítás, identitás és vendéghozzáférés — a mi szakterületünk.",
    AuthorSectionWebsiteLinkLabel: "Dolgozzon velünk",
    AuthorSectionConsultingText:
      "Ezt a webes kijelzőt azért hoztuk létre, mert naponta pontosan ezekkel a kihívásokkal foglalkozunk. Az architektúrától a bevezetésig segítünk a szervezeteknek biztonságos és skálázható együttműködést kialakítani a Microsoft 365-ön.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Webes kijelző verziója",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Kattintson a gombra a telepítés indításához:",
    AuthorSectionDeploymentGuideLabel: "Telepítési útmutató",
    NewReleaseAvailableLabel: "Új kiadás érhető el — kattintson a GitHub Releases megnyitásához",
    DiagnosticsGroupName: "Vendégakadálymentesség",
    DiagnosticsGroupHint:
      "Ellenőrzi, hogy a webes kijelző JavaScript-csomagja és a céloldal webhelye elérhető-e a B2B vendégfelhasználók számára.",
    DiagnosticsChecking: "Vendégakadálymentességi ellenőrzések futtatása…",
    DiagnosticsRetryButtonLabel: "Ellenőrzések újbóli futtatása",
    DiagPublicCdnOk:
      "A csomag az Office 365 nyilvános CDN-jén keresztül érkezik — névtelen kézbesítés, a vendégfelhasználók számára nincs szükség speciális engedélyekre.",
    DiagPrivateCdnInfo:
      "A csomag az Office 365 privát CDN-jén keresztül érkezik — az olvasási hozzáféréssel rendelkező vendégek betölthetik. Győződjön meg arról, hogy a céloldal webhelye elérhető a vendégek számára.",
    DiagSiteColCatalogOk:
      "A csomag erről a webhelyről a webhelygyűjtemény alkalmazáskatalógusából érkezik — a vendéghozzáférés a webhely saját engedélyeit követi.",
    DiagTenantCatalogEveryoneOk:
      "A csomag a bérlő alkalmazáskatalógusából érkezik. A 'Mindenki' jogcím olvasási hozzáféréssel rendelkezik a katalógushoz — a vendégfelhasználók betölthetik a csomagot.",
    DiagTenantCatalogEveryoneDenied:
      "A csomag a bérlő alkalmazáskatalógusából érkezik, de a 'Mindenki' nem rendelkezik olvasási hozzáféréssel. A vendégfelhasználók nem tölthetik be a webes kijelzőt. Javaslat: engedélyezze az Office 365 nyilvános CDN-jét, vagy adjon 'Mindenki' számára látogató hozzáférést a bérlő alkalmazáskatalógus webhelyéhez.",
    DiagTenantCatalogEveryoneUnknown:
      "A csomag a bérlő alkalmazáskatalógusából érkezik. Nem sikerült ellenőrizni, rendelkezik-e a 'Mindenki' olvasási hozzáféréssel (elégtelen jogosultságok). Kérjük, ellenőrizze manuálisan, hogy a vendégek elérhetik-e az alkalmazáskatalógust, vagy engedélyezze az Office 365 nyilvános CDN-jét.",
    DiagAssetSourceUnknown:
      "A csomag forrása nem állapítható meg. Kérjük, ellenőrizze manuálisan, hogy a vendégfelhasználók hozzáférhetnek-e a webes kijelző JavaScript-csomagjához.",
    DiagSiteEveryoneOk:
      "A 'Mindenki' a webhely Látogató csoportjában van — az újonnan elfogadott vendégek azonnal olvasási hozzáférést kapnak a céloldalhoz.",
    DiagSiteEveryoneMissing:
      "A 'Mindenki' nincs a webhely Látogató csoportjában. A vendéghozzáférés egy statikus Entra biztonsági csoporton (elfogadható) vagy dinamikus csoporton (akár 24 óra késedelem az új vendégeknél) alapulhat. Ha nincs konfigurálva vendégeket tartalmazó csoport, a vendégfelhasználók hozzáférés-megtagadási oldalt látnak majd.",
    DiagSiteEveryoneUnknown:
      "Nem sikerült ellenőrizni a webhely látogatói jogosultságait. Kérjük, győződjön meg arról, hogy a vendégfelhasználók legalább olvasási hozzáféréssel rendelkeznek ehhez a webhelyhez.",
    ShowSponsorJobTitleFieldLabel: "Szponzor beosztásának megjelenítése",
    ShowManagerJobTitleFieldLabel: "Vezető beosztásának megjelenítése",
    ShowSponsorDepartmentFieldLabel: "Szponzor osztályának megjelenítése",
    ShowManagerDepartmentFieldLabel: "Vezető osztályának megjelenítése",
    DepartmentLabel: "Osztály",
    ShowCityFieldLabel: "Város megjelenítése",
    ShowCountryFieldLabel: "Ország megjelenítése",
    CityFieldLabel: "Város",
    CountryFieldLabel: "Ország",
    CopyCityAriaLabel: "Város másolása",
    CopyCountryAriaLabel: "Ország másolása",
    ShowPresenceFieldLabel: "Jelenlét állapot megjelenítése",
    ShowSponsorPhotoFieldLabel: "Szponzor fényképének megjelenítése",
    ShowManagerPhotoFieldLabel: "Vezető fényképének megjelenítése",
    TitlePlaceholder: "Szponzorjaim",
    TitleSizeFieldLabel: "Cím mérete",
    TitleSizeH2Option: "2. fejléc",
    TitleSizeH3Option: "3. fejléc",
    TitleSizeH4Option: "4. fejléc",
    TitleSizeNormalOption: "Normál",
    WelcomeDialogTitle: "Vendég szponzor információ beállítása",
    WelcomeDialogBody:
      "Ez a webes kijelző minden vendégfelhasználónak megjeleníti a Microsoft Entra szponzorjait a SharePoint céloldalon. Ahhoz, hogy a webes kijelző értelmes legyen, a szponzor-hozzárendeléseket aktívan kell kezelni, és a vendégek életciklus-kezelési folyamatának már be kell lennie vezetve — láthatóvá teszi ezt a felelősséget, de nem helyettesíti az alapul szolgáló irányítást.",
    WelcomeDialogBroughtToYouBy:
      "A Workoho hozta létre — szakértők a vendéghozzáférés-irányítás és életciklus-kezelés területén.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Kezdjük el",
    WelcomeDialogNextButton: "Tovább",
    WelcomeDialogBackButton: "Vissza",
    WelcomeDialogSkipButton: "Most nem",
    WelcomeDialogSaveButton: "Mentés",
    WelcomeDialogSkipApiButton: "Kihagyás",
    InvalidUrlFormat: "Adjon meg érvényes URL-t (pl. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Adjon meg érvényes GUID-t (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Válassza a telepítési módot",
    WelcomeDialogSetupIntro:
      "Válassza ki a telepítési útvonalat. Bármikor válthat a két lehetőség között a webes kijelző beállításain keresztül.",
    WelcomeDialogOptionApiTitle: "Guest Sponsor API használata",
    WelcomeDialogOptionApiBody:
      "Teljes funkcionalitású élmény Azure Function által biztosítva. Egyszeri Azure-beállítást igényel — éles környezethez ajánlott.",
    WelcomeDialogOptionApiDocsLabel: "Beállítási útmutató megtekintése",
    WelcomeDialogSetupGuideNote:
      "Ezek a lépések egy parancsikon. Szkriptek futtatása előtt olvassa el a beállítási útmutatót, hogy megértse, mit csinál minden parancs.",
    WelcomeDialogDeployToAzureLabel: "API telepítése Azure-ba",
    WelcomeDialogDeployNote:
      "Ehhez a lehetőséghez szükséges, hogy a Guest Sponsor API-t telepítse az Azure-előfizetésébe. Ezt közvetlenül innen is megteheti — csak néhány percet vesz igénybe.",
    WelcomeDialogSetupStepsOrderHint: "Hajtsa végre ezeket a lépéseket sorrendben:",
    WelcomeDialogSetupStep1Label: "Alkalmazásregisztráció létrehozása",
    WelcomeDialogSetupStep2Hint: "Az 1. lépésben létrehozott alkalmazásregisztrációt használja",
    WelcomeDialogSetupStep3Label: "Graph-engedélyek megadása",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupStep3Hint: "Az alkalmazásregisztrációt (1. lépés) és a Function App URL-jét (2. lépés) használja",
    ViewScriptSourceLabel: "Szkript ellenőrzése",
    WelcomeDialogConnectApiTitle: "Adja meg az API kapcsolati adatait",
    WelcomeDialogConnectApiIntro:
      "Adja meg a Guest Sponsor API kapcsolati adatait. Ezt a lépést most kihagyhatja, és az adatokat később is hozzáadhatja a webes kijelő beállításaiban.",
    WelcomeDialogUrlHintLabel: "Hol találom az URL-t?",
    WelcomeDialogUrlHintBody:
      "Másolja be a Function App URL-jét az Azure Portalból a telepítés után. Nyissa meg a Function Appot → Áttekintés → Alapértelmezett tartomány.",
    WelcomeDialogOptionDemoTitle: "Felfedezés demó módban",
    WelcomeDialogOptionDemoBody:
      "Engedélyezze a demó módot szimulált szponzorok megjelenítéséhez az élő oldalon, beleértve a bérlőjében lévő belső felhasználókat is. Ezt Azure-beállítás nélküli tesztelésre használja, és bármikor válthat a valódi API-ra.",
    WelcomeDialogFunctionUrlRequired: "Adja meg a Guest Sponsor API alap URL-jét.",
    WelcomeDialogDoneApiTitle: "API konfigurálva!",
    WelcomeDialogDoneApiBody:
      "A Guest Sponsor API kapcsolat el lett mentve. Ne felejtse el menteni az oldalt, hogy a beállítások mindenki számára érvényesüljenek.",
    WelcomeDialogDoneApiSkippedTitle: "Majdnem kész!",
    WelcomeDialogDoneApiSkippedBody:
      "Még nem adott meg hitelesítő adatokat. A beállítás befejezéséhez: nyissa meg a webes kijelző beállításait, adja meg az alap URL-t és az ügyfél-azonosítót a Guest Sponsor API alatt, majd mentse az oldalt.",
    WelcomeDialogDoneDemoTitle: "Demó mód aktiválva!",
    WelcomeDialogDoneDemoBody:
      "A demó mód most aktív az élő oldalon. Mentse el az oldalt a látogatókra való alkalmazáshoz, majd váltson nézeti módba a szimulált szponzorkartyák ellenőrzéséhez.",
    PpSectionLivePage: "▶ Élő oldal",
    PpSectionDemoMode: "🧪 Nyilvános demó mód",
    PpSectionCardLayout: "🗂️ Kártyaelrendezés",
    PpSectionProfileFields: "👤 Profilmezők",
    PpSectionPhone: "📞 Telefonszámok",
    PpSectionWorkLocation: "📍 Munkahely",
    PpSectionAddress: "🏠 Postai cím",
    PpSectionMapLink: "🧭 Térképhivatkozás",
    PpSectionMapPreview: "🗺️ Beágyazott térkép előnézet"
  };
});
