define([], function() {
  return {
    "PropertyPaneDescription": "Configura la web part \u00abInfo sponsor ospite\u00bb.",
    "BasicGroupName": "Impostazioni",
    "TitleFieldLabel": "Titolo",
    "LoadingMessage": "Caricamento degli sponsor in corso\u2026",
    "NoSponsorsMessage": "Nessuno sponsor trovato per il Suo account.",
    "SponsorUnavailableMessage": "Il Suo sponsor/proprietario non \u00e8 pi\u00f9 disponibile. Contatti il Suo referente di progetto per richiedere l\u2019assegnazione di un nuovo sponsor/proprietario.",
    "ErrorMessage": "Impossibile caricare le informazioni sugli sponsor. Riprovi pi\u00f9 tardi.",
    "EditModePlaceholder": "Info sponsor ospite \u2014 passa alla modalit\u00e0 di visualizzazione per vedere gli sponsor.",
    "GuestOnlyPlaceholder": "Questa web part \u00e8 visibile solo agli utenti ospiti in modalit\u00e0 di visualizzazione.",
    "MockModeFieldLabel": "Modalit\u00e0 demo (dati simulati)",
    "MockModePlaceholder": "Info sponsor ospite \u2014 Modalit\u00e0 demo attiva. Passa alla modalit\u00e0 di visualizzazione per vedere i dati simulati.",

    "PresenceAvailable": "Disponibile",
    "PresenceAvailableIdle": "Disponibile, inattivo",
    "PresenceAway": "Assente",
    "PresenceBeRightBack": "Torno subito",
    "PresenceBusy": "Occupato",
    "PresenceBusyIdle": "Occupato, inattivo",
    "PresenceDoNotDisturb": "Non disturbare",
    "PresenceInAMeeting": "In riunione",
    "PresenceInACall": "In una chiamata",
    "PresencePresenting": "In presentazione",
    "PresenceFocusing": "In modalità focus",
    "PresenceOutOfOffice": "Fuori ufficio",
    "PresenceOutOfOfficeSuffix": ", fuori ufficio",
    "PresenceOffline": "Non in linea",

    "ContactDetailsAriaLabel": "Dettagli di contatto di {0}",
    "ContactActionsAriaLabel": "Azioni di contatto",
    "ChatTitle": "Chatta in Microsoft Teams",
    "EmailTitle": "Invia e-mail",
    "CallTitle": "Chiamata audio in Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Chiama",

    "ContactInfoSection": "Informazioni di contatto",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Telefono ufficio",
    "MobileFieldLabel": "Cellulare",
    "WorkLocationFieldLabel": "Luogo di lavoro",
    "StreetAddressFieldLabel": "Via",
    "PostalCodeFieldLabel": "CAP",
    "StateFieldLabel": "Stato/regione",

    "OrganizationSection": "Organizzazione",
    "ManagerLabel": "Responsabile",

    "CopiedFeedback": "Copiato!",
    "CopyEmailAriaLabel": "Copia indirizzo e-mail",
    "CopyWorkPhoneAriaLabel": "Copia telefono ufficio",
    "CopyMobileAriaLabel": "Copia numero di cellulare",
    "CopyLocationAriaLabel": "Copia luogo di lavoro",
    "CopyStreetAddressAriaLabel": "Copia via",
    "CopyPostalCodeAriaLabel": "Copia CAP",
    "CopyStateAriaLabel": "Copia stato/regione",
    "AddressMapSectionLabel": "Anteprima mappa",
    "AddressMapLoadingLabel": "Caricamento anteprima mappa…",
    "OpenAddressInMapLabel": "Apri nella mappa",

    "TeamsAccessPendingTitle": "Microsoft Teams non ancora configurato",
    "TeamsAccessPendingMessage": "Il Suo accesso ospite a Microsoft Teams in questa organizzazione non \u00e8 ancora stato configurato. Il Suo account Teams personale non \u00e8 interessato. Chieda al Suo sponsor di aggiungerLa a un Team \u2014 una volta fatto, le funzionalit\u00e0 di Teams come chat, chiamate e riunioni saranno disponibili qui.",
    "TeamsNotReadyChatTooltip": "Chat non disponibile qui \u2014 il Suo accesso ospite Teams non \u00e8 ancora stato configurato",
    "TeamsNotReadyCallTooltip": "Chiamata non disponibile qui \u2014 il Suo accesso ospite Teams non \u00e8 ancora stato configurato",

    "NoSponsorsMessageInformal": "Nessuno sponsor trovato per il tuo account.",
    "SponsorUnavailableMessageInformal": "Il tuo sponsor/proprietario non \u00e8 pi\u00f9 disponibile. Contatta il tuo referente di progetto per richiedere l\u2019assegnazione di un nuovo sponsor/proprietario.",
    "ErrorMessageInformal": "Impossibile caricare le informazioni sugli sponsor. Riprova pi\u00f9 tardi.",
    "TeamsAccessPendingMessageInformal": "Il tuo accesso ospite a Microsoft Teams in questa organizzazione non \u00e8 ancora stato configurato. Il tuo account Teams personale non \u00e8 interessato. Chiedi al tuo sponsor di aggiungerti a un Team \u2014 una volta fatto, le funzionalit\u00e0 di Teams come chat, chiamate e riunioni saranno disponibili qui.",
    "TeamsNotReadyChatTooltipInformal": "Chat non disponibile qui \u2014 il tuo accesso ospite Teams non \u00e8 ancora stato configurato",
    "TeamsNotReadyCallTooltipInformal": "Chiamata non disponibile qui \u2014 il tuo accesso ospite Teams non \u00e8 ancora stato configurato",

    "DisplayGroupName": "Visualizzazione",
    "ShowBusinessPhonesFieldLabel": "Mostra telefono ufficio",
    "ShowMobilePhoneFieldLabel": "Mostra numero di cellulare",
    "ShowWorkLocationFieldLabel": "Mostra luogo di lavoro",
    "ShowManagerFieldLabel": "Mostra responsabile",
    "UseInformalAddressFieldLabel": "Trattamento informale (tu)",

    "ShowWorkLocationFallbackFieldLabel": "Mostra luogo di lavoro come fallback",
    "LocationDisplayHintGeoWithFallback": "La città e il paese sono combinati in un'unica riga geografica. Il luogo di lavoro viene mostrato solo se non sono disponibili dati su città/paese.",
    "LocationDisplayHintGeoOnly": "La città e il paese sono combinati in un'unica riga geografica. Il luogo di lavoro è nascosto.",
    "LocationDisplayHintOfficeOnly": "Viene mostrato solo il luogo di lavoro. Attiva città e/o paese per mostrare invece una riga geografica.",
    "LocationDisplayHintHidden": "Tutte le informazioni sulla posizione sono nascoste.",
    "AddressMapFallbackHint": "Se non è configurata una chiave Azure Maps o la ricerca fallisce, viene mostrato un collegamento a una mappa esterna.",
    "LocationDisplayHintAddressEnabled": "I campi di indirizzo strutturato sono attivati e possono essere mostrati in righe aggiuntive.",
    "LocationDisplayHintSeparateRows": "Città/paese e luogo di lavoro vengono mostrati su righe separate quando abilitati.",
    "AdvancedDisplayGroupName": "Opzioni di visualizzazione avanzate",
    "ManagerOptionsDisabledHint": "Attiva la visualizzazione del responsabile per configurare i campi specifici del responsabile.",
    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "URL API sponsor (Azure Function)",
    "FunctionClientIdFieldLabel": "ID client API sponsor (registrazione applicazione Azure Function)",
    "ProxyStatusChecking": "Verifica Azure Function in corso\u2026",
    "ProxyStatusOk": "Azure Function raggiungibile",
    "ProxyStatusError": "Azure Function non raggiungibile",
    "ShowSponsorJobTitleFieldLabel": "Mostra il ruolo dello sponsor",
    "ShowManagerJobTitleFieldLabel": "Mostra il ruolo del responsabile",
    "ShowSponsorDepartmentFieldLabel": "Mostra il reparto dello sponsor",
    "ShowManagerDepartmentFieldLabel": "Mostra il reparto del responsabile",
    "DepartmentLabel": "Reparto",
    "ShowCityFieldLabel": "Mostra citt\u00e0",
    "ShowCountryFieldLabel": "Mostra paese",
    "ShowStructuredAddressFieldLabel": "Mostra indirizzo strutturato",
    "ShowStreetAddressFieldLabel": "Mostra via",
    "ShowPostalCodeFieldLabel": "Mostra CAP",
    "ShowStateFieldLabel": "Mostra stato/regione",
    "ShowAddressMapFieldLabel": "Mostra anteprima mappa indirizzo",
    "AzureMapsSubscriptionKeyFieldLabel": "Chiave sottoscrizione Azure Maps",
    "ExternalMapProviderFieldLabel": "Provider mappa esterno (fallback)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Citt\u00e0",
    "CountryFieldLabel": "Paese",
    "CopyCityAriaLabel": "Copia citt\u00e0",
    "CopyCountryAriaLabel": "Copia paese",
    "ShowPresenceFieldLabel": "Mostra stato di presenza"
  }
});
