// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Impostazioni",
    ShowTitleFieldLabel: "Mostra titolo",
    TitleFieldLabel: "Titolo",
    LoadingMessage: "Caricamento degli sponsor in corso…",
    NoSponsorsTitle: "Nessuno sponsor trovato",
    NoSponsorsMessage: "Nessuno sponsor trovato per il Suo account.",
    SponsorUnavailableTitle: "Sponsor non disponibile",
    SponsorUnavailableMessage:
      "Il Suo sponsor/proprietario non è più disponibile. Contatti il Suo referente di progetto per richiedere l’assegnazione di un nuovo sponsor/proprietario.",
    ErrorMessageTitle: "Si è verificato un errore",
    ErrorMessage: "Impossibile caricare le informazioni sugli sponsor. Riprovi più tardi.",
    EditModePlaceholder: "Info sponsor ospite — passa alla modalità di visualizzazione per vedere gli sponsor.",
    GuestOnlyPlaceholder: "Questa web part è visibile solo agli utenti ospiti in modalità di visualizzazione.",
    MockModeFieldLabel: "Mostra sempre sponsor demo (modalità demo pubblica)",
    MockModeFieldDescription: "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    MockModeFieldTooltip:
      "Quando abilitata, la modalità demo appare solo nella pagina dal vivo per scopi di test. La modalità di modifica e l'anteprima rimangono invariate.",
    MockModePlaceholder:
      "Info sponsor ospite — Modalità demo attiva. Passa alla modalità di visualizzazione per vedere i dati simulati.",
    MockSimulatedHintFieldLabel: "Simula notifica ospite",
    MockSimulatedHintNoneOption: "Nessuna notifica",
    MockSimulatedHintTeamsAccessPendingOption: "Microsoft Teams non ancora configurato",
    MockSimulatedHintVersionMismatchOption: "Aggiornamento disponibile",
    MockSimulatedHintSponsorUnavailableOption: "Sponsor non disponibile",
    MockSimulatedHintNoSponsorsOption: "Nessuno sponsor trovato",
    MaxSponsorCountFieldLabel: "Sponsor visibili",
    MaxSponsorCountFieldTooltip:
      "Limita il numero di carte sponsor visualizzate. Solo gli sponsor attivi (disponibili) contano verso questo limite. Se un account sponsor assegnato non è più disponibile (disabilitato, eliminato o non ancora fornito), lo sponsor successivo nell'ordine di priorità avanza automaticamente per riempire lo spazio vuoto. Ciò garantisce che i guest vedano sempre il numero configurato di contatti disponibili.",
    PresenceAvailable: "Disponibile",
    PresenceAvailableIdle: "Disponibile, inattivo",
    PresenceAway: "Assente",
    PresenceBeRightBack: "Torno subito",
    PresenceBusy: "Occupato",
    PresenceBusyIdle: "Occupato, inattivo",
    PresenceDoNotDisturb: "Non disturbare",
    PresenceInAMeeting: "In riunione",
    PresenceInACall: "In una chiamata",
    PresencePresenting: "In presentazione",
    PresenceFocusing: "In modalità focus",
    PresenceOutOfOffice: "Fuori ufficio",
    PresenceOutOfOfficeSuffix: ", fuori ufficio",
    PresenceOffline: "Non in linea",
    ContactDetailsAriaLabel: "Dettagli di contatto di {0}",
    ContactActionsAriaLabel: "Azioni di contatto",
    CloseLabel: "Chiudi",
    ChatTitle: "Avvia una chat con {name}",
    EmailTitle: "Invia un'e-mail a {name}",
    CallTitle: "Avvia una chiamata audio con {name}",
    ChatLabel: "Chat",
    EmailLabel: "E-mail",
    CallLabel: "Chiama",
    ContactInfoSection: "Contatto",
    EmailFieldLabel: "E-mail",
    WorkPhoneFieldLabel: "Telefono ufficio",
    MobileFieldLabel: "Cellulare",
    WorkLocationFieldLabel: "Luogo di lavoro",
    AddressFieldLabel: "Indirizzo",
    StreetAddressFieldLabel: "Via",
    PostalCodeFieldLabel: "CAP",
    StateFieldLabel: "Stato/regione",
    OrganizationSection: "Organizzazione",
    ReportsToSection: "Riporta a",
    ManagerLabel: "Responsabile",
    CopiedFeedback: "Copiato!",
    CopyEmailAriaLabel: "Copia indirizzo e-mail",
    CopyWorkPhoneAriaLabel: "Copia telefono ufficio",
    CopyMobileAriaLabel: "Copia numero di cellulare",
    CopyLocationAriaLabel: "Copia luogo di lavoro",
    CopyAddressAriaLabel: "Copia indirizzo",
    CopyStreetAddressAriaLabel: "Copia via",
    CopyPostalCodeAriaLabel: "Copia CAP",
    CopyStateAriaLabel: "Copia stato/regione",
    AddressMapSectionLabel: "Anteprima mappa",
    AddressMapLoadingLabel: "Caricamento anteprima mappa…",
    OpenAddressInMapLabel: "Apri nella mappa",
    TeamsAccessPendingTitle: "Microsoft Teams non ancora configurato",
    TeamsAccessPendingMessage:
      "Il Suo accesso ospite a Microsoft Teams in questa organizzazione non è ancora stato configurato. Il Suo account Teams personale non è interessato. Chieda al Suo sponsor di aggiungerLa a un Team — una volta fatto, le funzionalità di Teams come chat, chiamate e riunioni saranno disponibili qui.",
    TeamsNotReadyChatTooltip: "Chat non disponibile qui — il Suo accesso ospite Teams non è ancora stato configurato",
    TeamsNotReadyCallTooltip:
      "Chiamata non disponibile qui — il Suo accesso ospite Teams non è ancora stato configurato",
    VersionMismatchTitle: "Aggiornamento disponibile",
    VersionMismatchMessage:
      "È disponibile un aggiornamento della web part. Chiedere all'amministratore di verificare che la web part e la Guest Sponsor API utilizzino la stessa versione.",
    InsufficientPermissionsTitle: "Autorizzazione necessaria",
    InsufficientPermissionsMessage:
      "Impossibile caricare le informazioni sugli sponsor — un'autorizzazione di servizio richiesta non è stata concessa. Contattare l'amministratore IT.",
    GuestNotificationsGroupName: "Notifiche per gli ospiti",
    GuestNotificationsGroupHint: "Controlla quali notifiche informative vengono mostrate agli utenti ospiti.",
    ShowTeamsAccessPendingHintLabel: "Mostra l'avviso «Microsoft Teams non ancora configurato»",
    ShowVersionMismatchHintLabel: "Mostra l'avviso «Aggiornamento disponibile»",
    ShowSponsorUnavailableHintLabel: "Mostra l'avviso «Sponsor non disponibile»",
    ShowNoSponsorsHintLabel: "Mostra l'avviso «Nessuno sponsor trovato»",
    DisplayGroupName: "Visualizzazione",
    CardLayoutFieldLabel: "Layout scheda",
    CardLayoutAutoOption: "Automatico",
    CardLayoutAutoThresholdFieldLabel: "Passa al layout compatto da questo numero di sponsor",
    CardLayoutFullOption: "Completo",
    CardLayoutCompactOption: "Compatto",
    ShowBusinessPhonesFieldLabel: "Mostra telefono ufficio",
    ShowMobilePhoneFieldLabel: "Mostra numero di cellulare",
    ShowWorkLocationFieldLabel: "Mostra luogo di lavoro",
    ShowStreetAddressFieldLabel: "Mostra via",
    ShowPostalCodeFieldLabel: "Mostra CAP",
    ShowStateFieldLabel: "Mostra stato/regione",
    AzureMapsSubscriptionKeyFieldLabel: "Chiave sottoscrizione Azure Maps",
    MapProviderModeAutoLabel: "Modalità automatica (consigliata)",
    MapProviderModeManualLabel: "Manuale (uguale per tutti i dispositivi)",
    MapProviderModeHint:
      "Scegli un provider di mappe per ogni sistema operativo, inclusi iOS e Android. Il link si apre nel browser o nell'app del provider se è installata.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Provider mappa",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Disattivato (nessun link mappa)",
    AddressMapProviderHint:
      "Attiva almeno la città e il paese — è sufficiente perché qualsiasi provider di mappe mostri una posizione significativa.",
    AzureMapsPreviewHint:
      "Aggiungi la chiave di sottoscrizione di Azure Maps per mostrare una piccola anteprima della mappa nella sezione contatti. Se hai distribuito l'API Guest Sponsor, è stato incluso un account Azure Maps — copia la chiave dalle relative impostazioni di autenticazione. Senza chiave viene mostrato solo il link alla mappa qui sopra.",
    ShowManagerFieldLabel: "Mostra responsabile",
    UseInformalAddressFieldLabel: "Trattamento informale (tu)",
    SponsorEligibilityGroupName: "Idoneità dello sponsor",
    SponsorEligibilityGroupHint:
      "Le assegnazioni di sponsor in Microsoft Entra sono gestite dalla tua organizzazione e potrebbero non essere sempre accurate. Questi filtri migliorano la qualità degli sponsor mostrati agli utenti guest e prevengono la divulgazione involontaria di informazioni causata da assegnazioni errate.",
    SponsorFilterFieldLabel: "Lo sponsor deve essere",
    SponsorFilterTeamsOption: "Con licenza Teams (consigliato)",
    SponsorFilterExchangeOption: "Con licenza Exchange Online",
    SponsorFilterAnyOption: "Con licenza (qualsiasi licenza attiva)",
    RequireUserMailboxFieldLabel: "Richiedere tipo di cassetta postale utente",
    LocationDisplayHintSeparateRows: "I campi indirizzo attivati vengono combinati in una singola riga cliccabile.",
    AdvancedDisplayGroupName: "Opzioni di visualizzazione avanzate",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "URL di base",
    WebPartClientIdFieldLabel: "ID applicazione (client)",
    SessionCacheTtlMinutesFieldLabel: "Durata della cache di sessione (minuti)",
    PpClientIdHintLabel: "Dove trovo l'ID client?",
    PpClientIdHintBody:
      "Copiare l'ID client (ID applicazione) dalla registrazione applicazione creata durante la configurazione.",
    FunctionEntraLinkLabel: "Cerca in Microsoft Entra →",
    ProxyStatusChecking: "Verifica Guest Sponsor API in corso…",
    ProxyStatusOk: "Connessione riuscita",
    ProxyStatusError: "Connessione non riuscita",
    PpSetupIntro: "Configurazione necessaria:",
    PpSetupRerunHint:
      "Problema di connessione? Lo script di configurazione è idempotente — rieseguirlo con gli stessi parametri risolve la maggior parte dei problemi.",
    CopyToClipboardLabel: "Copia",
    CopiedToClipboardLabel: "Copiato!",
    AuthorSectionGroupName: "Informazioni",
    AuthorSectionCreatedBy: "Creato e mantenuto da",
    AuthorSectionIntro: "Governance Microsoft 365, identità e accesso ospite \u2014 il nostro campo.",
    AuthorSectionWebsiteLinkLabel: "Contattaci",
    AuthorSectionConsultingText:
      "Abbiamo creato questo componente perché è esattamente quello che facciamo ogni giorno. Dall'architettura al rollout, aiutiamo le organizzazioni a costruire una collaborazione sicura e scalabile su Microsoft 365.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Versione della web part",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Fare clic sul pulsante per avviare la distribuzione:",
    AuthorSectionDeploymentGuideLabel: "Guida alla distribuzione",
    NewReleaseAvailableLabel: "Nuova versione disponibile \u2014 apri GitHub Releases",
    DiagnosticsGroupName: "Accessibilit\u00e0 ospiti",
    DiagnosticsGroupHint:
      "Verifica se il bundle JavaScript del Web Part e il sito della pagina di destinazione sono accessibili agli utenti ospiti B2B.",
    DiagnosticsChecking: "Verifica accessibilit\u00e0 ospiti in corso\u2026",
    DiagnosticsRetryButtonLabel: "Esegui di nuovo i controlli",
    DiagPublicCdnOk:
      "Bundle distribuito tramite la rete CDN pubblica di Office 365 \u2014 consegna anonima, nessuna autorizzazione speciale richiesta per gli ospiti.",
    DiagPrivateCdnInfo:
      "Bundle distribuito tramite la CDN privata di Office 365 \u2014 gli ospiti con accesso in lettura al sito possono caricarlo. Verificare che il sito della pagina di destinazione sia accessibile agli ospiti.",
    DiagSiteColCatalogOk:
      "Bundle distribuito dal catalogo applicazioni della raccolta siti \u2014 l'accesso degli ospiti segue le autorizzazioni del sito stesso.",
    DiagTenantCatalogEveryoneOk:
      "Bundle distribuito dal catalogo applicazioni del tenant. Il gruppo \u2018Tutti\u2019 ha accesso in lettura al catalogo \u2014 gli ospiti possono caricare il bundle.",
    DiagTenantCatalogEveryoneDenied:
      "Bundle distribuito dal catalogo applicazioni del tenant, ma \u2018Tutti\u2019 non ha accesso in lettura. Gli ospiti non possono caricare il Web Part. Raccomandazione: abilitare la CDN pubblica di Office 365 oppure concedere l'accesso Visitatore a \u2018Tutti\u2019 sul sito del catalogo.",
    DiagTenantCatalogEveryoneUnknown:
      "Bundle distribuito dal catalogo applicazioni del tenant. Impossibile verificare se \u2018Tutti\u2019 ha accesso in lettura (autorizzazioni insufficienti). Verificare manualmente che gli ospiti possano raggiungere il catalogo o abilitare la CDN pubblica di Office 365.",
    DiagAssetSourceUnknown:
      "Impossibile determinare la sorgente del bundle. Verificare manualmente che gli utenti ospiti possano accedere al bundle JavaScript del Web Part.",
    DiagSiteEveryoneOk:
      "\u2018Tutti\u2019 \u00e8 nel gruppo Visitatori del sito \u2014 gli ospiti appena accettati ottengono immediatamente accesso in lettura alla pagina di destinazione.",
    DiagSiteEveryoneMissing:
      "\u2018Tutti\u2019 non \u00e8 nel gruppo Visitatori del sito. L'accesso degli ospiti potrebbe dipendere da un gruppo di sicurezza Entra statico (accettabile) o dinamico (fino a 24\u00a0ore di ritardo per i nuovi ospiti). Se non \u00e8 configurato un gruppo che includa ospiti, questi vedranno una pagina di accesso negato.",
    DiagSiteEveryoneUnknown:
      "Impossibile verificare le autorizzazioni dei visitatori del sito. Assicurarsi che gli utenti ospiti abbiano almeno accesso in lettura a questo sito.",
    ShowSponsorJobTitleFieldLabel: "Mostra il ruolo dello sponsor",
    ShowManagerJobTitleFieldLabel: "Mostra il ruolo del responsabile",
    ShowSponsorDepartmentFieldLabel: "Mostra il reparto dello sponsor",
    ShowManagerDepartmentFieldLabel: "Mostra il reparto del responsabile",
    DepartmentLabel: "Reparto",
    ShowCityFieldLabel: "Mostra città",
    ShowCountryFieldLabel: "Mostra paese",
    CityFieldLabel: "Città",
    CountryFieldLabel: "Paese",
    CopyCityAriaLabel: "Copia città",
    CopyCountryAriaLabel: "Copia paese",
    ShowPresenceFieldLabel: "Mostra stato di presenza",
    ShowSponsorPhotoFieldLabel: "Mostra foto dello sponsor",
    ShowManagerPhotoFieldLabel: "Mostra foto del responsabile",
    TitlePlaceholder: "I miei sponsor",
    TitleSizeFieldLabel: "Dimensione del titolo",
    TitleSizeH2Option: "Titolo 2",
    TitleSizeH3Option: "Titolo 3",
    TitleSizeH4Option: "Titolo 4",
    TitleSizeNormalOption: "Normale",
    WelcomeDialogTitle: "Configura Info sponsor ospite",
    WelcomeDialogBody:
      "Questa web part mostra a ciascun utente ospite i propri sponsor Microsoft Entra nella pagina SharePoint di destinazione. Perché la web part sia utile, le assegnazioni degli sponsor devono essere gestite attivamente e deve essere già in atto un processo di ciclo di vita per gli ospiti — rende visibile quella responsabilità, ma non sostituisce la governance sottostante.",
    WelcomeDialogBroughtToYouBy:
      "Sviluppato da Workoho — specialisti nella governance degli ospiti e nella gestione del ciclo di vita.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Iniziamo",
    WelcomeDialogNextButton: "Avanti",
    WelcomeDialogBackButton: "Indietro",
    WelcomeDialogSkipButton: "Non ora",
    WelcomeDialogSaveButton: "Salva",
    WelcomeDialogSkipApiButton: "Salta",
    InvalidUrlFormat: "Inserire un URL valido (es. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Inserire un GUID valido (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Scegli il percorso di configurazione",
    WelcomeDialogSetupIntro:
      "Scegli il tuo percorso di distribuzione. Puoi passare da un'opzione all'altra in qualsiasi momento dalle impostazioni della web part.",
    WelcomeDialogOptionApiTitle: "Usa la Guest Sponsor API",
    WelcomeDialogOptionApiBody:
      "Esperienza completa alimentata da una Azure Function. Richiede una configurazione Azure una tantum — consigliato per la produzione.",
    WelcomeDialogOptionApiDocsLabel: "Visualizza la guida di configurazione",
    WelcomeDialogSetupGuideNote:
      "Questo comando è un collegamento rapido. Prima di eseguirlo, leggi la guida di configurazione per capire cosa fa.",
    WelcomeDialogDeployToAzureLabel: "Distribuire l'API in Azure",
    WelcomeDialogDeployNote:
      "Questa opzione richiede che la Guest Sponsor API sia distribuita nella tua sottoscrizione Azure. Puoi farlo direttamente qui \u2014 bastano pochi minuti.",
    WelcomeDialogPreflightTitle: "Before deployment, the installer checks:",
    WelcomeDialogPreflightTools: "PowerShell, Azure CLI, Azure Developer CLI, and Bicep support.",
    WelcomeDialogPreflightSignIn: "Azure sign-in and the target subscription.",
    WelcomeDialogPreflightRoles: "Azure RBAC and Entra roles, with a copy/paste request if anything is missing.",
    WelcomeDialogSetupStepsOrderHint: "Completa questi passaggi nell'ordine indicato:",
    WelcomeDialogSetupStep1Label: "Creare la registrazione dell'app",
    WelcomeDialogSetupStep2Hint: "Usa la registrazione dell'app creata nel passaggio 1",
    WelcomeDialogSetupStep3Label: "Concedere le autorizzazioni Graph",
    WelcomeDialogSetupPwshHint: "PowerShell:",
    WelcomeDialogSetupShellHint: "macOS/Linux shell:",
    WelcomeDialogUseShellCommandLabel: "macOS/Linux without PowerShell?",
    WelcomeDialogUsePowerShellCommandLabel: "Use PowerShell command",
    WelcomeDialogSetupStep3Hint:
      "Usa la registrazione dell'app (passaggio 1) e l'URL dell'app per le funzioni (passaggio 2)",
    ViewScriptSourceLabel: "Ispeziona script",
    WelcomeDialogConnectApiTitle: "Inserisci i dettagli di connessione API",
    WelcomeDialogConnectApiIntro:
      "Inserisci i dettagli di connessione per la tua Guest Sponsor API. Puoi saltare questo passaggio per ora e aggiungerli in seguito nelle impostazioni della web part.",
    WelcomeDialogUrlHintLabel: "Dove trovare l'URL?",
    WelcomeDialogUrlHintBody:
      "Copia l'URL della Function App dal portale Azure dopo la distribuzione. Vai alla tua Function App → Panoramica → Dominio predefinito.",
    WelcomeDialogOptionDemoTitle: "Esplora in modalità demo",
    WelcomeDialogOptionDemoBody:
      "Prova la web part con dati di sponsor simulati — senza configurazione Azure. Passa all'API reale dalle impostazioni in qualsiasi momento.",
    WelcomeDialogFunctionUrlRequired: "Inserisci l'URL base della Guest Sponsor API.",
    WelcomeDialogDoneApiTitle: "API configurata!",
    WelcomeDialogDoneApiBody:
      "La connessione alla Guest Sponsor API è stata salvata. Ricorda di salvare la pagina affinché le impostazioni vengano applicate a tutti.",
    WelcomeDialogDoneApiSkippedTitle: "Quasi pronto!",
    WelcomeDialogDoneApiSkippedBody:
      "Nessuna credenziale inserita. Per completare la configurazione: apri le impostazioni della web part, inserisci l'URL di base e l'ID client in Guest Sponsor API, e salva la pagina.",
    WelcomeDialogDoneDemoTitle: "Modalità demo attivata!",
    WelcomeDialogDoneDemoBody:
      "Passa alla modalità di visualizzazione per vedere la web part con schede sponsor simulate. Connetti la Guest Sponsor API dalle impostazioni quando sei pronto.",
    PpSectionLivePage: "▶ Pagina live",
    PpSectionDemoMode: "🧪 Modalità demo",
    PpSectionCardLayout: "🗂️ Layout scheda",
    PpSectionProfileFields: "👤 Campi profilo",
    PpSectionPhone: "📞 Numeri di telefono",
    PpSectionWorkLocation: "📍 Luogo di lavoro",
    PpSectionAddress: "🏠 Indirizzo postale",
    PpSectionMapLink: "🧭 Link mappa",
    PpSectionMapPreview: "🗺️ Anteprima mappa in linea"
  };
});
