// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function() {
  return {
    "BasicGroupName": "設定",
    "ShowTitleFieldLabel": "タイトルを表示",
    "TitleFieldLabel": "タイトル",
    "LoadingMessage": "スポンサーを読み込んでいます…",
    "NoSponsorsTitle": "スポンサーが見つかりません",
    "NoSponsorsMessage": "アカウントのスポンサーが見つかりませんでした。",
    "SponsorUnavailableTitle": "スポンサーが利用できません",
    "SponsorUnavailableMessage": "スポンサー/オーナーは利用できなくなりました。プロジェクトの担当者に連絡して、新しいスポンサー/オーナーをアカウントに割り当ててもらってください。",
    "ErrorMessageTitle": "エラーが発生しました",
    "ErrorMessage": "スポンサー情報を読み込めませんでした。後でもう一度お試しください。",
    "EditModePlaceholder": "ゲストスポンサー情報 — スポンサーを表示するには表示モードに切り替えてください。",
    "GuestOnlyPlaceholder": "この Web パーツは、表示モードではゲスト ユーザーにのみ表示されます。",
    "MockModeFieldLabel": "デモ スポンサーを常に表示（公開デモ モード）",
    "MockModeFieldDescription": "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    "MockModeFieldTooltip": "有効にすると、デモモードはテスト目的でのみライブページに表示されます。編集モードとプレビューは変わりません。",
    "MockModePlaceholder": "ゲストスポンサー情報 — デモ モードが有効です。テスト データを表示するには表示モードに切り替えてください。",
    "MockSimulatedHintFieldLabel": "ゲスト通知をシミュレートする",
    "MockSimulatedHintNoneOption": "通知なし",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams はまだ設定されていません",
    "MockSimulatedHintVersionMismatchOption": "更新が利用可能です",
    "MockSimulatedHintSponsorUnavailableOption": "スポンサーが利用できません",
    "MockSimulatedHintNoSponsorsOption": "スポンサーが見つかりません",
    "MaxSponsorCountFieldLabel": "表示するスポンサー数",
    "MaxSponsorCountFieldTooltip": "表示されるスポンサーカードの数を制限します。このリミットに対してカウントされるのはアクティブ（利用可能）なスポンサーのみです。割り当てられたスポンサーのアカウントが利用不可（無効化、削除、またはまだプロビジョニングされていない）になった場合、優先度順の次のスポンサーが自動的に進み、空いているスロットを埋めます。これにより、ゲストはいつでも設定された数の利用可能なコンタクトを確認できます。",

    "PresenceAvailable": "連絡可能",
    "PresenceAvailableIdle": "連絡可能、アイドル",
    "PresenceAway": "退席中",
    "PresenceBeRightBack": "すぐ戻ります",
    "PresenceBusy": "取り込み中",
    "PresenceBusyIdle": "取り込み中、アイドル",
    "PresenceDoNotDisturb": "応答不可",
    "PresenceInAMeeting": "会議中",
    "PresenceInACall": "通話中",
    "PresencePresenting": "発表中",
    "PresenceFocusing": "集中中",
    "PresenceOutOfOffice": "外出中",
    "PresenceOutOfOfficeSuffix": "、外出中",
    "PresenceOffline": "オフライン",

    "CloseLabel": "閉じる",
    "ContactDetailsAriaLabel": "{0} の連絡先の詳細",
    "ContactActionsAriaLabel": "連絡先のアクション",
    "ChatTitle": "{name} とチャットを開始",
    "EmailTitle": "{name} にメールを送信",
    "CallTitle": "{name} と音声通話を開始",
    "ChatLabel": "チャット",
    "EmailLabel": "メール",
    "CallLabel": "通話",

    "ContactInfoSection": "連絡先",
    "EmailFieldLabel": "メール",
    "WorkPhoneFieldLabel": "会社電話",
    "MobileFieldLabel": "携帯電話",
    "WorkLocationFieldLabel": "勤務地",
    "AddressFieldLabel": "住所",
    "StreetAddressFieldLabel": "番地",
    "PostalCodeFieldLabel": "郵便番号",
    "StateFieldLabel": "都道府県/州",

    "OrganizationSection": "組織",
    "ReportsToSection": "上司",
    "ManagerLabel": "上司",

    "CopiedFeedback": "コピーしました!",
    "CopyEmailAriaLabel": "メール アドレスをコピー",
    "CopyWorkPhoneAriaLabel": "会社電話をコピー",
    "CopyMobileAriaLabel": "携帯電話番号をコピー",
    "CopyLocationAriaLabel": "勤務地をコピー",
    "CopyAddressAriaLabel": "住所をコピー",
    "CopyStreetAddressAriaLabel": "番地をコピー",
    "CopyPostalCodeAriaLabel": "郵便番号をコピー",
    "CopyStateAriaLabel": "都道府県/州をコピー",
    "AddressMapSectionLabel": "地図プレビュー",
    "AddressMapLoadingLabel": "地図プレビューを読み込み中...",
    "OpenAddressInMapLabel": "地図で開く",

    "TeamsAccessPendingTitle": "Microsoft Teams がまだ設定されていません",
    "TeamsAccessPendingMessage": "この組織でのゲストとしての Microsoft Teams アクセスがまだ設定されていません。ご自身の Teams アカウントには影響ありません。スポンサーにチームへの追加を依頼してください — 追加されると、この組織でチャット、通話、会議などの Teams 機能が利用可能になります。",
    "TeamsNotReadyChatTooltip": "この組織ではチャットを利用できません — Teams ゲストアクセスがまだ設定されていません",
    "TeamsNotReadyCallTooltip": "この組織では通話を利用できません — Teams ゲストアクセスがまだ設定されていません",

    "VersionMismatchTitle": "アップデートが利用可能です",
    "VersionMismatchMessage": "Web パーツの更新プログラムが利用可能です。管理者に Web パーツと Guest Sponsor API が同じバージョンを実行していることを確認するよう依頼してください。",
    "InsufficientPermissionsTitle": "権限が不足しています",
    "InsufficientPermissionsMessage": "スポンサー情報を読み込めませんでした — 必要なサービスのアクセス許可が付与されていません。IT 管理者にお問い合わせください。",

    "GuestNotificationsGroupName": "ゲストへの通知",
    "GuestNotificationsGroupHint": "ゲストユーザーに表示する情報通知を管理します。",
    "ShowTeamsAccessPendingHintLabel": "「Microsoft Teams はまだ設定されていません」通知を表示",
    "ShowVersionMismatchHintLabel": "「更新が利用可能です」通知を表示",
    "ShowSponsorUnavailableHintLabel": "「スポンサーが利用できません」通知を表示",
    "ShowNoSponsorsHintLabel": "「スポンサーが見つかりません」通知を表示",
    "DisplayGroupName": "表示",
    "CardLayoutFieldLabel": "カードレイアウト",
    "CardLayoutAutoOption": "自動",
    "CardLayoutAutoThresholdFieldLabel": "この人数以上のスポンサーからコンパクト表示に切り替える",
    "CardLayoutFullOption": "フル",
    "CardLayoutCompactOption": "コンパクト",
    "ShowBusinessPhonesFieldLabel": "会社電話を表示",
    "ShowMobilePhoneFieldLabel": "携帯電話を表示",
    "ShowWorkLocationFieldLabel": "勤務地を表示",
    "ShowManagerFieldLabel": "上司を表示",
    "SponsorEligibilityGroupName": "スポンサーの資格要件",
    "SponsorEligibilityGroupHint": "Microsoft Entra のスポンサー割り当ては組織において管理されており、常に正確であるとは限りません。これらのフィルターは、ゲストに表示されるスポンサーの品質を向上させ、誤った割り当てによる情報の漏洩を防ぎます。",
    "SponsorFilterFieldLabel": "スポンサーの要件",
    "SponsorFilterTeamsOption": "Teams ライセンスあり (推奨)",
    "SponsorFilterExchangeOption": "Exchange Online ライセンスあり",
    "SponsorFilterAnyOption": "ライセンスあり (有効なライセンスなら問わず)",
    "RequireUserMailboxFieldLabel": "ユーザーメールボックスタイプを要求する",
    "UseInformalAddressFieldLabel": "くだけた表現を使用",

    "LocationDisplayHintSeparateRows": "有効な住所フィールドは1つのクリック可能な行にまとめられます。",
    "AdvancedDisplayGroupName": "詳細な表示オプション",
    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "ベース URL",
    "FunctionClientIdFieldLabel": "アプリケーション (クライアント) ID",
    "PpClientIdHintLabel": "クライアント ID の確認方法",
    "PpClientIdHintBody": "セットアップ時に作成したアプリ登録からクライアント ID（アプリケーション ID）をコピーしてください。",
    "FunctionEntraLinkLabel": "Microsoft Entra で確認 →",
    "ProxyStatusChecking": "接続を確認中…",
    "ProxyStatusOk": "接続に成功しました",
    "ProxyStatusError": "接続に失敗しました",
    "PpSetupIntro": "必要なセットアップ:",
    "PpSetupRerunHint": "接続の問題ですか？セットアップスクリプトはべき等です \u2014 同じパラメーターで再実行するとほとんどの問題が解決します。",
    "CopyToClipboardLabel": "コピー",
    "CopiedToClipboardLabel": "コピーしました！",
    "AuthorSectionGroupName": "Workohoについて",
    "AuthorSectionIntro": "Microsoft 365 のガバナンス、ID 管理、ゲストアクセス \u2014 私たちの専門分野。",
    "AuthorSectionWebsiteLinkLabel": "お問い合わせ",
    "AuthorSectionConsultingText": "このWebパーツを開発したのは、まさにこの課題に毎日向き合っているからです。アーキテクチャから展開まで、組織が Microsoft 365 上で安全でスケーラブルなコラボレーション環境を構築する支援をしています。",
    "AuthorSectionPartnerPrefix": "Workoho は",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum パートナー。"
    "AuthorSectionPartnerTagline": "EasyLife 365 は、Teams、SharePoint サイト、Viva Engage などの Microsoft 365 ワークスペースのライフサイクル管理を自動化します。ゲストのオンボーディングやスポンサー管理も含まれます。",
    "AuthorSectionSourceCodeLabel": "ソースコード",
    "AuthorSectionVersionLabel": "Web パーツのバージョン",
    "AuthorSectionDeployToAzureLabel": "Deploy to Azure",
    "DeployToAzureClickHint": "\u30dc\u30bf\u30f3\u3092\u30af\u30ea\u30c3\u30af\u3057\u3066\u30c7\u30d7\u30ed\u30a4\u3092\u958b\u59cb\u3057\u3066\u304f\u3060\u3055\u3044\uff1a",
    "AuthorSectionDeploymentGuideLabel": "デプロイガイド",
    "NewReleaseAvailableLabel": "新しいリリースがあります — GitHub Releases を開く",
    "ShowSponsorJobTitleFieldLabel": "スポンサーの役職を表示",
    "ShowManagerJobTitleFieldLabel": "マネージャーの役職を表示",
    "ShowSponsorDepartmentFieldLabel": "スポンサーの部署を表示",
    "ShowManagerDepartmentFieldLabel": "マネージャーの部署を表示",
    "DepartmentLabel": "部署",
    "ShowCityFieldLabel": "市区町村を表示",
    "ShowCountryFieldLabel": "国を表示",
    "ShowStreetAddressFieldLabel": "番地を表示",
    "ShowPostalCodeFieldLabel": "郵便番号を表示",
    "ShowStateFieldLabel": "都道府県/州を表示",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps サブスクリプション キー",
    "MapProviderModeAutoLabel": "自動モード（推奨）",
    "MapProviderModeManualLabel": "手動（すべてのデバイスで同じ）",
    "MapProviderModeHint": "iOS と Android を含む各オペレーティング システムのマップ プロバイダーを選択します。リンクはブラウザーで開くか、プロバイダーのアプリがインストールされている場合はアプリで開きます。",
    "MapProviderIosLabel": "iOS:",
    "MapProviderAndroidLabel": "Android:",
    "MapProviderWindowsLabel": "Windows:",
    "MapProviderMacOSLabel": "macOS:",
    "MapProviderLinuxLabel": "Linux:",
    "ExternalMapProviderFieldLabel": "マッププロバイダー",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderNoneOption": "無効（地図リンクなし）",
    "AddressMapProviderHint": "少なくとも市区町村と国を有効にしてください — どの地図プロバイダーでも意味のある位置を表示するのに十分です。",
    "AzureMapsPreviewHint": "Azure Maps サブスクリプション キーを追加すると、連絡先セクションに小さな地図プレビューが表示されます。Guest Sponsor API をデプロイした場合、Azure Maps アカウントも含まれています — 認証設定からキーをコピーしてください。キーがない場合は、上の地図リンクのみ表示されます。",
    "CityFieldLabel": "市区町村",
    "CountryFieldLabel": "国",
    "CopyCityAriaLabel": "市区町村をコピー",
    "CopyCountryAriaLabel": "国をコピー",
    "ShowPresenceFieldLabel": "プレゼンスステータスを表示",
    "ShowSponsorPhotoFieldLabel": "スポンサーの写真を表示",
    "ShowManagerPhotoFieldLabel": "上司の写真を表示",
    "TitlePlaceholder": "マイスポンサー",
    "TitleSizeFieldLabel": "タイトルのサイズ",
    "TitleSizeH2Option": "見出し 2",
    "TitleSizeH3Option": "見出し 3",
    "TitleSizeH4Option": "見出し 4",
    "TitleSizeNormalOption": "標準",

    "WelcomeDialogTitle": "ゲストスポンサー情報をセットアップ",
    "WelcomeDialogBody": "この Web パーツは、各ゲスト ユーザーの Microsoft Entra スポンサーを SharePoint ランディング ページに表示します。この Web パーツを有効に活用するには、スポンサーの割り当てが適切に管理され、ゲストのライフサイクル管理プロセスがすでに確立されている必要があります — 責任の所在を可視化しますが、背後にあるガバナンスの代替にはなりません。",
    "WelcomeDialogBroughtToYouBy": "Workoho による開発 — ゲスト ガバナンスとライフサイクル管理の専門家。",
    "WelcomeDialogWorkohoLinkLabel": "workoho.com",
    "WelcomeDialogNextButton": "次へ",
    "WelcomeDialogBackButton": "戻る",
    "WelcomeDialogSkipButton": "後で",
    "WelcomeDialogSaveButton": "保存",
    "WelcomeDialogSkipApiButton": "スキップ",
    "InvalidUrlFormat": "有効なURLを入力してください（例：my-app.azurewebsites.net）",
    "InvalidGuidFormat": "有効なGUIDを入力してください（xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx）",
    "WelcomeDialogSetupTitle": "数分で利用開始",
    "WelcomeDialogSetupIntro": "デプロイ パスを選択してください。Web パーツの設定からいつでも両方のオプションを切り替えることができます。",
    "WelcomeDialogOptionApiTitle": "Guest Sponsor API を使用する",
    "WelcomeDialogOptionApiBody": "Azure Function を利用した本格的なエクスペリエンスです。Azure の初回セットアップが必要です — 本番環境に推奨。",
    "WelcomeDialogOptionApiDocsLabel": "セットアップ ガイドを表示",
    "WelcomeDialogDeployToAzureLabel": "API を Azure にデプロイ",
    "WelcomeDialogDeployNote": "このオプションには、Azure サブスクリプションへの Guest Sponsor API のデプロイが必要です。ここから数分で完了できます。",
    "WelcomeDialogSetupStep1Label": "アプリの登録を作成",
    "WelcomeDialogSetupStep3Label": "Graph のアクセス許可を付与",
    "WelcomeDialogSetupPwshHint": "PowerShell 7+:",
    "WelcomeDialogSetupStep3Hint": "ステップ 1 と 2 の値を使用",
    "WelcomeDialogConnectApiTitle": "Guest Sponsor API を接続する",
    "WelcomeDialogConnectApiIntro": "Guest Sponsor API の接続情報を入力してください（省略可能）。後で Web パーツの設定から追加することもできます。",
    "WelcomeDialogOptionDemoTitle": "デモ モードで試す",
    "WelcomeDialogOptionDemoBody": "模擬スポンサー データで Web パーツを試せます — Azure のセットアップは不要です。設定からいつでも実際の API に切り替えられます。",
    "WelcomeDialogFunctionUrlRequired": "Guest Sponsor API のベース URL を入力してください。",
    "WelcomeDialogDoneApiTitle": "API を設定しました！",
    "WelcomeDialogDoneApiSkippedTitle": "もう少しです！",
    "WelcomeDialogDoneApiSkippedBody": "資格情報は入力されませんでした。準備ができたら、Web パーツの設定を開いてゲスト スポンサー API を接続してください。",
    "WelcomeDialogDoneApiBody": "Guest Sponsor API への接続が保存されました。設定をすべてのユーザーに適用するには、ページを保存してください。",
    "WelcomeDialogDoneDemoTitle": "デモ モードを有効にしました！",
    "WelcomeDialogDoneDemoBody": "表示モードに切り替えると、模擬スポンサー カードで Web パーツが表示されます。準備ができたら、設定から Guest Sponsor API を接続してください。",
    "WelcomeDialogDismissButton": "はじめましょう",
    "PpSectionLivePage": "▶ ライブページ",
    "PpSectionDemoMode": "🧪 デモモード",
    "PpSectionCardLayout": "🗂️ カードレイアウト",
    "PpSectionProfileFields": "👤 プロフィール項目",
    "PpSectionPhone": "📞 電話番号",
    "PpSectionWorkLocation": "📍 勤務地",
    "PpSectionAddress": "🏠 住所",
    "PpSectionMapLink": "🧭 地図リンク",
    "PpSectionMapPreview": "🗺️ インライン地図プレビュー"
  }
});
