define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurer webdelen Gjestesponsorinformasjon.",
    "BasicGroupName": "Innstillinger",
    "TitleFieldLabel": "Tittel",
    "LoadingMessage": "Laster inn sponsorene dine…",
    "NoSponsorsMessage": "Ingen sponsorer ble funnet for kontoen din.",
    "SponsorUnavailableMessage": "Din sponsor/eier er ikke lenger tilgjengelig. Kontakt din prosjektansvarlige for å få tildelt en ny sponsor/eier til kontoen din.",
    "ErrorMessage": "Kunne ikke laste inn sponsorinformasjon. Prøv igjen senere.",
    "EditModePlaceholder": "Gjestesponsorinformasjon — bytt til visningsmodus for å se sponsorer.",
    "GuestOnlyPlaceholder": "Denne webdelen er bare synlig for gjestebrukere i visningsmodus.",
    "MockModeFieldLabel": "Demonstrasjonsmodus (testdata)",
    "MockModePlaceholder": "Gjestesponsorinformasjon — Demonstrasjonsmodus aktiv. Bytt til visningsmodus for å se testdata.",

    "PresenceAvailable": "Tilgjengelig",
    "PresenceAvailableIdle": "Tilgjengelig, inaktiv",
    "PresenceAway": "Borte",
    "PresenceBeRightBack": "Straks tilbake",
    "PresenceBusy": "Opptatt",
    "PresenceBusyIdle": "Opptatt, inaktiv",
    "PresenceDoNotDisturb": "Ikke forstyrr",
    "PresenceInAMeeting": "I et møte",
    "PresenceInACall": "I en samtale",
    "PresencePresenting": "Presenterer",
    "PresenceFocusing": "Fokuserer",
    "PresenceOutOfOffice": "Utenfor kontoret",
    "PresenceOutOfOfficeSuffix": ", utenfor kontoret",
    "PresenceOffline": "Frakoblet",

    "ContactDetailsAriaLabel": "Kontaktdetaljer for {0}",
    "ContactActionsAriaLabel": "Kontakthandlinger",
    "ChatTitle": "Chat i Microsoft Teams",
    "EmailTitle": "Send e-post",
    "CallTitle": "Lydsamtale i Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-post",
    "CallLabel": "Ring",

    "ContactInfoSection": "Kontaktinformasjon",
    "EmailFieldLabel": "E-post",
    "WorkPhoneFieldLabel": "Jobbtelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbeidssted",
    "StreetAddressFieldLabel": "Gate",
    "PostalCodeFieldLabel": "Postnummer",
    "StateFieldLabel": "Fylke/region",

    "OrganizationSection": "Organisasjon",
    "ManagerLabel": "Leder",

    "CopiedFeedback": "Kopiert!",
    "CopyEmailAriaLabel": "Kopier e-postadresse",
    "CopyWorkPhoneAriaLabel": "Kopier jobbtelefon",
    "CopyMobileAriaLabel": "Kopier mobilnummer",
    "CopyLocationAriaLabel": "Kopier arbeidssted",
    "CopyStreetAddressAriaLabel": "Kopier gate",
    "CopyPostalCodeAriaLabel": "Kopier postnummer",
    "CopyStateAriaLabel": "Kopier fylke/region",
    "AddressMapSectionLabel": "Kartforhåndsvisning",
    "AddressMapLoadingLabel": "Laster kartforhåndsvisning...",
    "OpenAddressInMapLabel": "Åpne i kart",

    "TeamsAccessPendingTitle": "Microsoft Teams er ikke konfigurert ennå",
    "TeamsAccessPendingMessage": "Gjestetilgangen din til Microsoft Teams i denne organisasjonen er ikke konfigurert ennå. Din egen Teams-konto er ikke berørt. Be sponsoren din om å legge deg til i et team — deretter kan du bruke Teams-funksjoner som chat, samtaler og møter her.",
    "TeamsNotReadyChatTooltip": "Chat ikke tilgjengelig her — Teams-gjestetilgangen din er ikke konfigurert ennå",
    "TeamsNotReadyCallTooltip": "Samtale ikke tilgjengelig her — Teams-gjestetilgangen din er ikke konfigurert ennå",

    "VersionMismatchMessage": "Det er en oppdatering tilgjengelig for denne webdelen. Be administratoren din om å sikre at webdelen og Azure Function kjører samme versjon.",
    "InsufficientPermissionsMessage": "Kunne ikke laste inn sponsorinformasjon — en påkrevd tjenestetillatelse er ikke innvilget. Kontakt IT-administratoren din.",

    "DisplayGroupName": "Visning",
    "ShowBusinessPhonesFieldLabel": "Vis jobbtelefonnumre",
    "ShowMobilePhoneFieldLabel": "Vis mobilnummer",
    "ShowWorkLocationFieldLabel": "Vis arbeidssted",
    "ShowManagerFieldLabel": "Vis leder",
    "UseInformalAddressFieldLabel": "Uformell tiltaleform",

    "ShowWorkLocationFallbackFieldLabel": "Vis arbeidssted som reserve",
    "LocationDisplayHintGeoWithFallback": "By og land kombineres til én geografisk rad. Arbeidsstedet vises bare hvis det ikke finnes by-/landsdata.",
    "LocationDisplayHintGeoOnly": "By og land kombineres til én geografisk rad. Arbeidsstedet er skjult.",
    "LocationDisplayHintOfficeOnly": "Bare arbeidsstedet vises. Aktiver by og/eller land for å vise en geografisk rad i stedet.",
    "LocationDisplayHintHidden": "All stedsinformasjon er skjult.",
    "AddressMapFallbackHint": "Hvis ingen Azure Maps-nøkkel er konfigurert eller oppslag feiler, vises en ekstern kartlenke.",
    "LocationDisplayHintAddressEnabled": "Strukturerte adressefelt er aktivert og kan vises i ekstra rader.",
    "LocationDisplayHintSeparateRows": "By/land og arbeidssted vises som separate rader når de er aktivert.",
    "AdvancedDisplayGroupName": "Avanserte visningsalternativer",
    "ManagerOptionsDisabledHint": "Aktiver visning av leder for å konfigurere lederspesifikke felt.",
    "FunctionGroupName": "Azure-funksjon",
    "FunctionUrlFieldLabel": "Sponsor-API-URL (Azure-funksjon)",
    "FunctionClientIdFieldLabel": "Sponsor-API-klient-ID (Azure Function-appregistrering)",
    "ProxyStatusChecking": "Sjekker Azure-funksjon…",
    "ProxyStatusOk": "Azure-funksjon er tilgjengelig",
    "ProxyStatusError": "Azure-funksjon er ikke tilgjengelig",
    "ShowSponsorJobTitleFieldLabel": "Vis sponsors stillingstittel",
    "ShowManagerJobTitleFieldLabel": "Vis lederens stillingstittel",
    "ShowSponsorDepartmentFieldLabel": "Vis sponsors avdeling",
    "ShowManagerDepartmentFieldLabel": "Vis lederens avdeling",
    "DepartmentLabel": "Avdeling",
    "ShowCityFieldLabel": "Vis by",
    "ShowCountryFieldLabel": "Vis land",
    "ShowStructuredAddressFieldLabel": "Vis strukturert adresse",
    "ShowStreetAddressFieldLabel": "Vis gate",
    "ShowPostalCodeFieldLabel": "Vis postnummer",
    "ShowStateFieldLabel": "Vis stat/region",
    "ShowAddressMapFieldLabel": "Vis adressekartforhåndsvisning",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-abonnementsnøkkel",
    "ExternalMapProviderFieldLabel": "Ekstern kartleverandør (reserve)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "By",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopier by",
    "CopyCountryAriaLabel": "Kopier land",
    "ShowPresenceFieldLabel": "Vis tilstedeværelsesstatus"
  }
});
