// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function() {
  return {
    "BasicGroupName": "Innstillinger",
    "ShowTitleFieldLabel": "Vis tittel",
    "TitleFieldLabel": "Tittel",
    "LoadingMessage": "Laster inn sponsorene dine…",
    "NoSponsorsTitle": "Ingen sponsorer funnet",
    "NoSponsorsMessage": "Ingen sponsorer ble funnet for kontoen din.",
    "SponsorUnavailableTitle": "Sponsor ikke tilgjengelig",
    "SponsorUnavailableMessage": "Din sponsor er ikke lenger tilgjengelig. Kontakt din prosjektansvarlige for å få tildelt en ny sponsor til kontoen din.",
    "ErrorMessageTitle": "Noe gikk galt",
    "ErrorMessage": "Kunne ikke laste inn sponsorinformasjon. Prøv igjen senere.",
    "EditModePlaceholder": "Gjestesponsorinformasjon — bytt til visningsmodus for å se sponsorer.",
    "GuestOnlyPlaceholder": "Denne webdelen er bare synlig for gjestebrukere i visningsmodus.",
    "MockModeFieldLabel": "Vis alltid demosponsor (offentlig demonstrasjonsmodus)",
    "MockModeFieldDescription": "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    "MockModeFieldTooltip": "Når den er aktivert, vises demomodus kun på live-siden til testformål. Redigeringsmodus og forhåndsvisning forblir uendret.",
    "MockModePlaceholder": "Gjestesponsorinformasjon — Demonstrasjonsmodus aktiv. Bytt til visningsmodus for å se testdata.",
    "MockSimulatedHintFieldLabel": "Simuler gjestevarsel",
    "MockSimulatedHintNoneOption": "Ingen varsel",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams ikke konfigurert ennå",
    "MockSimulatedHintVersionMismatchOption": "Oppdatering tilgjengelig",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsor ikke tilgjengelig",
    "MockSimulatedHintNoSponsorsOption": "Ingen sponsorer funnet",
    "MaxSponsorCountFieldLabel": "Synlige sponsorer",
    "MaxSponsorCountFieldTooltip": "Begrenser antallet sponsor-kort som vises. Bare aktive (tilgjengelige) sponsorer teller med på denne grensen. Hvis en tildelt sponsors konto ikke lenger er tilgjengelig (deaktivert, slettet eller ikke ennå gjort klar), rykker neste sponsor i prioriteringsrekkefølgen automatisk fremover for å fylle den tomme plassen. Dette sikrer at gjestene alltid ser det konfigurerte antallet av tilgjengelige kontakter.",

    "PresenceAvailable": "Tilgjengelig",
    "PresenceAvailableIdle": "Tilgjengelig, inaktiv",
    "PresenceAway": "Borte",
    "PresenceBeRightBack": "Straks tilbake",
    "PresenceBusy": "Opptatt",
    "PresenceBusyIdle": "Opptatt, inaktiv",
    "PresenceDoNotDisturb": "Ikke forstyrr",
    "PresenceInAMeeting": "I et møte",
    "PresenceInACall": "I en samtale",
    "PresencePresenting": "Presenterer",
    "PresenceFocusing": "Fokuserer",
    "PresenceOutOfOffice": "Utenfor kontoret",
    "PresenceOutOfOfficeSuffix": ", utenfor kontoret",
    "PresenceOffline": "Frakoblet",

    "CloseLabel": "Lukk",
    "ContactDetailsAriaLabel": "Kontaktdetaljer for {0}",
    "ContactActionsAriaLabel": "Kontakthandlinger",
    "ChatTitle": "Start en chat med {name}",
    "EmailTitle": "Send e-post til {name}",
    "CallTitle": "Start en lydsamtale med {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-post",
    "CallLabel": "Ring",

    "ContactInfoSection": "Kontakt",
    "EmailFieldLabel": "E-post",
    "WorkPhoneFieldLabel": "Jobbtelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbeidssted",
    "AddressFieldLabel": "Adresse",
    "StreetAddressFieldLabel": "Gate",
    "PostalCodeFieldLabel": "Postnummer",
    "StateFieldLabel": "Fylke/region",

    "OrganizationSection": "Organisasjon",
    "ReportsToSection": "Rapporterer til",
    "ManagerLabel": "Leder",

    "CopiedFeedback": "Kopiert!",
    "CopyEmailAriaLabel": "Kopier e-postadresse",
    "CopyWorkPhoneAriaLabel": "Kopier jobbtelefon",
    "CopyMobileAriaLabel": "Kopier mobilnummer",
    "CopyLocationAriaLabel": "Kopier arbeidssted",
    "CopyAddressAriaLabel": "Kopier adresse",
    "CopyStreetAddressAriaLabel": "Kopier gate",
    "CopyPostalCodeAriaLabel": "Kopier postnummer",
    "CopyStateAriaLabel": "Kopier fylke/region",
    "AddressMapSectionLabel": "Kartforhåndsvisning",
    "AddressMapLoadingLabel": "Laster kartforhåndsvisning...",
    "OpenAddressInMapLabel": "Åpne i kart",

    "TeamsAccessPendingTitle": "Microsoft Teams er ikke konfigurert ennå",
    "TeamsAccessPendingMessage": "Gjestetilgangen din til Microsoft Teams i denne organisasjonen er ikke konfigurert ennå. Din egen Teams-konto er ikke berørt. Be sponsoren din om å legge deg til i et team — deretter kan du bruke Teams-funksjoner som chat, samtaler og møter her.",
    "TeamsNotReadyChatTooltip": "Chat ikke tilgjengelig her — Teams-gjestetilgangen din er ikke konfigurert ennå",
    "TeamsNotReadyCallTooltip": "Samtale ikke tilgjengelig her — Teams-gjestetilgangen din er ikke konfigurert ennå",

    "VersionMismatchTitle": "Oppdatering tilgjengelig",
    "VersionMismatchMessage": "Det er en oppdatering tilgjengelig for denne webdelen. Be administratoren din om å sikre at webdelen og Guest Sponsor API kjører samme versjon.",
    "InsufficientPermissionsTitle": "Manglende tillatelse",
    "InsufficientPermissionsMessage": "Kunne ikke laste inn sponsorinformasjon — en påkrevd tjenestetillatelse er ikke innvilget. Kontakt IT-administratoren din.",

    "GuestNotificationsGroupName": "Varsler for gjester",
    "GuestNotificationsGroupHint": "Kontroller hvilke informasjonsvarsler som vises til gjestebrukere.",
    "ShowTeamsAccessPendingHintLabel": "Vis varselet «Microsoft Teams ikke konfigurert ennå»",
    "ShowVersionMismatchHintLabel": "Vis varselet «Oppdatering tilgjengelig»",
    "ShowSponsorUnavailableHintLabel": "Vis varselet «Sponsor ikke tilgjengelig»",
    "ShowNoSponsorsHintLabel": "Vis varselet «Ingen sponsorer funnet»",
    "DisplayGroupName": "Visning",
    "CardLayoutFieldLabel": "Kortoppsett",
    "CardLayoutAutoOption": "Automatisk",
    "CardLayoutAutoThresholdFieldLabel": "Bytt til kompakt visning fra dette antall sponsorer",
    "CardLayoutFullOption": "Full",
    "CardLayoutCompactOption": "Kompakt",
    "ShowBusinessPhonesFieldLabel": "Vis jobbtelefonnumre",
    "ShowMobilePhoneFieldLabel": "Vis mobilnummer",
    "ShowWorkLocationFieldLabel": "Vis arbeidssted",
    "ShowManagerFieldLabel": "Vis leder",
    "SponsorEligibilityGroupName": "Sponsor-berettigelse",
    "SponsorEligibilityGroupHint": "Sponsortildelinger i Microsoft Entra vedlikeholdes av organisasjonen din og er ikke alltid korrekte. Disse filtrene forbedrer kvaliteten på sponsorene som vises til gjester, og forhindrer utilsiktet informasjonsdeling forårsaket av feilaktige tildelinger.",
    "SponsorFilterFieldLabel": "Sponsor må være",
    "SponsorFilterTeamsOption": "Teams-lisensiert (anbefalt)",
    "SponsorFilterExchangeOption": "Exchange Online-lisensiert",
    "SponsorFilterAnyOption": "Lisensiert (enhver aktiv lisens)",
    "RequireUserMailboxFieldLabel": "Krev brukerpostbokstype",
    "UseInformalAddressFieldLabel": "Uformell tiltaleform",

    "LocationDisplayHintSeparateRows": "Aktiverte adressefelt kombineres til en enkelt klikkbar rad.",
    "AdvancedDisplayGroupName": "Avanserte visningsalternativer",
    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "Guest Sponsor API basis-URL",
    "FunctionClientIdFieldLabel": "Guest Sponsor API klient-ID (appregistrering)",
    "ProxyStatusChecking": "Sjekker Guest Sponsor API…",
    "ProxyStatusOk": "Guest Sponsor API er tilgjengelig",
    "ProxyStatusError": "Guest Sponsor API er ikke tilgjengelig",
    "AuthorSectionGroupName": "Om Workoho",
    "AuthorSectionIntro": "Microsoft 365-styring, identiteter og gjesteadgang \u2014 vårt felt.",
    "AuthorSectionWebsiteLinkLabel": "Ta kontakt",
    "AuthorSectionConsultingText": "Vi bygde denne webdelen fordi det er nøyaktig det vi jobber med til daglig. Fra arkitektur til utrulling hjelper vi organisasjoner med å bygge sikre og skalerbare samarbeidsmiljøer på Microsoft 365.",
    "AuthorSectionPartnerPrefix": "Workoho er",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum-partner.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automatiserer livssyklusstyring for Teams, SharePoint-nettsteder, Viva Engage og andre Microsoft 365-arbeidsrom — inkludert gjeste-onboarding og sponsorhåndtering.",
    "AuthorSectionSourceCodeLabel": "Kildekode",
    "AuthorSectionVersionLabel": "Webdel-versjon",
    "AuthorSectionDeployToAzureLabel": "Deploy to Azure",
    "AuthorSectionDeploymentGuideLabel": "Distribusjonsveiledning",
    "NewReleaseAvailableLabel": "Ny versjon tilgjengelig — åpne GitHub Releases",
    "ShowSponsorJobTitleFieldLabel": "Vis sponsors stillingstittel",
    "ShowManagerJobTitleFieldLabel": "Vis lederens stillingstittel",
    "ShowSponsorDepartmentFieldLabel": "Vis sponsors avdeling",
    "ShowManagerDepartmentFieldLabel": "Vis lederens avdeling",
    "DepartmentLabel": "Avdeling",
    "ShowCityFieldLabel": "Vis by",
    "ShowCountryFieldLabel": "Vis land",
    "ShowStreetAddressFieldLabel": "Vis gate",
    "ShowPostalCodeFieldLabel": "Vis postnummer",
    "ShowStateFieldLabel": "Vis stat/region",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-abonnementsnøkkel",
    "MapProviderModeAutoLabel": "Automatisk modus (anbefalt)",
    "MapProviderModeManualLabel": "Manuell (samme for alle enheter)",
    "MapProviderModeHint": "Velg en kartleverandør per operativsystem, inkludert iOS og Android. Lenken åpnes i nettleseren eller i leverandørens app hvis den er installert.",
    "MapProviderIosLabel": "iOS:",
    "MapProviderAndroidLabel": "Android:",
    "MapProviderWindowsLabel": "Windows:",
    "MapProviderMacOSLabel": "macOS:",
    "MapProviderLinuxLabel": "Linux:",
    "ExternalMapProviderFieldLabel": "Kartleverandør",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderNoneOption": "Deaktivert (ingen kartlenke)",
    "AddressMapProviderHint": "Aktiver minst by og land — det er nok for enhver karttjeneste til å vise en meningsfull plassering.",
    "AzureMapsPreviewHint": "Legg til Azure Maps-abonnementsnøkkelen for å vise en liten kartforhåndsvisning i kontaktseksjonen. Hvis du har distribuert Guest Sponsor API-et, ble en Azure Maps-konto inkludert — kopier nøkkelen fra autentiseringsinnstillingene. Uten nøkkel vises bare kartlenken ovenfor.",
    "CityFieldLabel": "By",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopier by",
    "CopyCountryAriaLabel": "Kopier land",
    "ShowPresenceFieldLabel": "Vis tilstedeværelsesstatus",
    "ShowSponsorPhotoFieldLabel": "Vis sponsor-bilde",
    "ShowManagerPhotoFieldLabel": "Vis overordnets bilde",
    "TitlePlaceholder": "Mine sponsorer",
    "TitleSizeFieldLabel": "Tittelstørrelse",
    "TitleSizeH2Option": "Overskrift 2 (standard)",
    "TitleSizeH3Option": "Overskrift 3",
    "TitleSizeH4Option": "Overskrift 4",
    "TitleSizeNormalOption": "Normal",

    "WelcomeDialogTitle": "Konfigurer Gjestesponsorinformasjon",
    "WelcomeDialogBody": "Denne webdelen viser dine Microsoft 365-sponsorer — de interne kollegene som er ansvarlige for gjestekontoen din, innføringen din og den daglige støtten din i denne organisasjonen.",
    "WelcomeDialogBroughtToYouBy": "Utviklet av Workoho — spesialister på Microsoft 365-styring, identitet og gjestestyring.",
    "WelcomeDialogWorkohoLinkLabel": "Besøk workoho.com",
    "WelcomeDialogNextButton": "Neste",
    "WelcomeDialogBackButton": "Tilbake",
    "WelcomeDialogSkipButton": "Ikke nå",
    "WelcomeDialogSaveButton": "Lagre",
    "WelcomeDialogSkipApiButton": "Hopp over",
    "InvalidUrlFormat": "Skriv inn en gyldig URL (f.eks. my-app.azurewebsites.net)",
    "InvalidGuidFormat": "Skriv inn en gyldig GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    "WelcomeDialogSetupTitle": "Klar på noen minutter",
    "WelcomeDialogSetupIntro": "Velg hvordan du vil kjøre webdelen. Du kan endre dette når som helst i innstillingene.",
    "WelcomeDialogOptionApiTitle": "Bruk Guest Sponsor API",
    "WelcomeDialogOptionApiBody": "Fullt utstyrt opplevelse via en Azure Function. Krever engangsoppsett i Azure — anbefales for produksjon.",
    "WelcomeDialogOptionApiDocsLabel": "Se oppsettsveiledningen",
    "WelcomeDialogDeployToAzureLabel": "Deploy to Azure",
    "WelcomeDialogDeployNote": "Dette alternativet krever at Guest Sponsor API er distribuert i Azure-abonnementet ditt. Du kan gjøre det her — det tar bare noen minutter.",
    "WelcomeDialogConnectApiTitle": "Koble til Guest Sponsor API",
    "WelcomeDialogConnectApiIntro": "Oppgi eventuelt tilkoblingsdetaljer for din Guest Sponsor API. Du kan også legge dem til senere i innstillingene for webdelen.",
    "WelcomeDialogOptionDemoTitle": "Utforsk i demomodus",
    "WelcomeDialogOptionDemoBody": "Prøv webdelen med simulerte sponsordata — ingen Azure-oppsett kreves. Bytt til den ekte API-en fra innstillingene når som helst.",
    "WelcomeDialogFunctionUrlRequired": "Skriv inn base-URL-en for Guest Sponsor API.",
    "WelcomeDialogDoneApiTitle": "API konfigurert!",
    "WelcomeDialogDoneApiSkippedTitle": "Nesten ferdig!",
    "WelcomeDialogDoneApiSkippedBody": "Ingen legitimasjon ble angitt. Åpne innstillingene for nettdelen for å koble til gjestesponsor-API-et når du er klar.",
    "WelcomeDialogDoneApiBody": "Tilkoblingen til Guest Sponsor API er lagret. Husk å lagre siden slik at innstillingene gjelder for alle.",
    "WelcomeDialogDoneDemoTitle": "Demomodus aktivert!",
    "WelcomeDialogDoneDemoBody": "Bytt til visningsmodus for å se webdelen med simulerte sponsorkort. Koble til Guest Sponsor API fra innstillingene når du er klar.",
    "WelcomeDialogDismissButton": "La oss begynne",
    "PpSectionLivePage": "▶ Live-side",
    "PpSectionDemoMode": "🧪 Demo-modus",
    "PpSectionCardLayout": "🗂️ Kortoppsett",
    "PpSectionProfileFields": "👤 Profilfelter",
    "PpSectionPhone": "📞 Telefonnumre",
    "PpSectionWorkLocation": "📍 Arbeidssted",
    "PpSectionAddress": "🏠 Postadresse",
    "PpSectionMapLink": "🧭 Kartlenke",
    "PpSectionMapPreview": "🗺️ Innebygd kartforhåndsvisning"
  }
});
