// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Instellingen",
    ShowTitleFieldLabel: "Titel weergeven",
    TitleFieldLabel: "Titel",
    LoadingMessage: "Sponsors worden geladen…",
    NoSponsorsTitle: "Geen sponsors gevonden",
    NoSponsorsMessage: "Er zijn geen sponsors gevonden voor uw account.",
    SponsorUnavailableTitle: "Sponsor niet beschikbaar",
    SponsorUnavailableMessage:
      "Uw sponsor/eigenaar is niet langer beschikbaar. Neem contact op met uw projectverantwoordelijke om een nieuwe sponsor/eigenaar aan uw account te koppelen.",
    ErrorMessageTitle: "Er is een fout opgetreden",
    ErrorMessage: "Kan sponsorinformatie niet laden. Probeer het later opnieuw.",
    EditModePlaceholder: "Gastsponsors — schakel over naar de weergavemodus om sponsors te zien.",
    GuestOnlyPlaceholder: "Dit webonderdeel is alleen zichtbaar voor gastgebruikers in de weergavemodus.",
    MockModeFieldLabel: "Altijd demosponsors tonen (openbare demomodus)",
    MockModeFieldDescription: "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    MockModeFieldTooltip:
      "Wanneer ingeschakeld, wordt de demomodus alleen op de live pagina weergegeven voor testdoeleinden. Bewerkingsmodus en voorbeeld blijven ongewijzigd.",
    MockModePlaceholder: "Gastsponsors — Demomodus actief. Schakel over naar de weergavemodus om testgegevens te zien.",
    MockSimulatedHintFieldLabel: "Gastenmelding simuleren",
    MockSimulatedHintNoneOption: "Geen melding",
    MockSimulatedHintTeamsAccessPendingOption: "Microsoft Teams nog niet ingesteld",
    MockSimulatedHintVersionMismatchOption: "Update beschikbaar",
    MockSimulatedHintSponsorUnavailableOption: "Sponsor niet beschikbaar",
    MockSimulatedHintNoSponsorsOption: "Geen sponsoren gevonden",
    MaxSponsorCountFieldLabel: "Zichtbare sponsors",
    MaxSponsorCountFieldTooltip:
      "Beperkt het aantal weergegeven sponsorkaarten. Alleen actieve (beschikbare) sponsors tellen mee voor deze limiet. Als een toegewezen sponsoraccount niet meer beschikbaar is (uitgeschakeld, verwijderd of nog niet ingericht), raakt de volgende sponsor in prioriteitsvolgorde automatisch naar voren om de lege plaats in te vullen. Dit garandeert dat gasten altijd het geconfigureerde aantal beschikbare contacten zien.",
    PresenceAvailable: "Beschikbaar",
    PresenceAvailableIdle: "Beschikbaar, inactief",
    PresenceAway: "Afwezig",
    PresenceBeRightBack: "Zo terug",
    PresenceBusy: "Bezet",
    PresenceBusyIdle: "Bezet, inactief",
    PresenceDoNotDisturb: "Niet storen",
    PresenceInAMeeting: "In een vergadering",
    PresenceInACall: "In gesprek",
    PresencePresenting: "Aan het presenteren",
    PresenceFocusing: "Focusmodus",
    PresenceOutOfOffice: "Niet op kantoor",
    PresenceOutOfOfficeSuffix: ", niet op kantoor",
    PresenceOffline: "Offline",
    ContactDetailsAriaLabel: "Contactgegevens voor {0}",
    ContactActionsAriaLabel: "Contactacties",
    CloseLabel: "Sluiten",
    ChatTitle: "Chat starten met {name}",
    EmailTitle: "E-mail sturen naar {name}",
    CallTitle: "Audiogesprek starten met {name}",
    ChatLabel: "Chat",
    EmailLabel: "E-mail",
    CallLabel: "Bellen",
    ContactInfoSection: "Contact",
    EmailFieldLabel: "E-mail",
    WorkPhoneFieldLabel: "Zakelijk telefoonnummer",
    MobileFieldLabel: "Mobiel",
    WorkLocationFieldLabel: "Werklocatie",
    AddressFieldLabel: "Adres",
    StreetAddressFieldLabel: "Straat",
    PostalCodeFieldLabel: "Postcode",
    StateFieldLabel: "Provincie/regio",
    OrganizationSection: "Organisatie",
    ReportsToSection: "Rapporteert aan",
    ManagerLabel: "Manager",
    CopiedFeedback: "Gekopieerd!",
    CopyEmailAriaLabel: "E-mailadres kopiëren",
    CopyWorkPhoneAriaLabel: "Zakelijk telefoonnummer kopiëren",
    CopyMobileAriaLabel: "Mobiel nummer kopiëren",
    CopyLocationAriaLabel: "Werklocatie kopiëren",
    CopyAddressAriaLabel: "Adres kopiëren",
    CopyStreetAddressAriaLabel: "Kopieer straat",
    CopyPostalCodeAriaLabel: "Kopieer postcode",
    CopyStateAriaLabel: "Kopieer provincie/regio",
    AddressMapSectionLabel: "Kaartvoorbeeld",
    AddressMapLoadingLabel: "Kaartvoorbeeld laden...",
    OpenAddressInMapLabel: "Openen in kaart",
    TeamsAccessPendingTitle: "Microsoft Teams is nog niet ingesteld",
    TeamsAccessPendingMessage:
      "Uw gasttoegang tot Microsoft Teams in deze organisatie is nog niet ingesteld. Uw eigen Teams-account wordt hierdoor niet beïnvloed. Vraag uw sponsor om u toe te voegen aan een team — daarna kunt u hier Teams-functies zoals chat, bellen en vergaderingen gebruiken.",
    TeamsNotReadyChatTooltip: "Chat hier niet beschikbaar — uw Teams-gasttoegang is nog niet ingesteld",
    TeamsNotReadyCallTooltip: "Bellen hier niet beschikbaar — uw Teams-gasttoegang is nog niet ingesteld",
    VersionMismatchTitle: "Update beschikbaar",
    VersionMismatchMessage:
      "Er is een update beschikbaar voor dit webonderdeel. Vraag uw beheerder om te controleren of het webonderdeel en de Guest Sponsor API dezelfde versie gebruiken.",
    InsufficientPermissionsTitle: "Onvoldoende rechten",
    InsufficientPermissionsMessage:
      "Kan sponsorinformatie niet laden — een vereiste servicemachtiging is niet verleend. Neem contact op met uw IT-beheerder.",
    GuestNotificationsGroupName: "Meldingen voor gasten",
    GuestNotificationsGroupHint: "Beheer welke informatieve meldingen worden weergegeven aan gastgebruikers.",
    ShowTeamsAccessPendingHintLabel: "Melding «Microsoft Teams nog niet ingesteld» weergeven",
    ShowVersionMismatchHintLabel: "Melding «Update beschikbaar» weergeven",
    ShowSponsorUnavailableHintLabel: "Melding «Sponsor niet beschikbaar» weergeven",
    ShowNoSponsorsHintLabel: "Melding «Geen sponsoren gevonden» weergeven",
    DisplayGroupName: "Weergave",
    CardLayoutFieldLabel: "Kaartindeling",
    CardLayoutAutoOption: "Automatisch",
    CardLayoutAutoThresholdFieldLabel: "Schakel naar compact lay-out vanaf dit aantal sponsors",
    CardLayoutFullOption: "Volledig",
    CardLayoutCompactOption: "Compact",
    ShowBusinessPhonesFieldLabel: "Zakelijk telefoonnummer weergeven",
    ShowMobilePhoneFieldLabel: "Mobiel nummer weergeven",
    ShowWorkLocationFieldLabel: "Werklocatie weergeven",
    ShowStreetAddressFieldLabel: "Straat weergeven",
    ShowPostalCodeFieldLabel: "Postcode weergeven",
    ShowStateFieldLabel: "Provincie/regio weergeven",
    AzureMapsSubscriptionKeyFieldLabel: "Azure Maps-abonnementsleutel",
    MapProviderModeAutoLabel: "Automatische modus (aanbevolen)",
    MapProviderModeManualLabel: "Handmatig (hetzelfde voor alle apparaten)",
    MapProviderModeHint:
      "Kies per besturingssysteem een kaartprovider, ook voor iOS en Android. De link wordt geopend in de browser of in de app van de provider als die is geïnstalleerd.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Kaartprovider",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Uitgeschakeld (geen kaartlink)",
    AddressMapProviderHint:
      "Activeer minimaal stad en land — dat volstaat voor elke kaartprovider om een zinvolle locatie weer te geven.",
    AzureMapsPreviewHint:
      "Voeg je Azure Maps-abonnementssleutel toe om een kleine kaartvoorbeeldweergave in de contactsectie te tonen. Als je de Guest Sponsor API hebt geïmplementeerd, is er een Azure Maps-account meegeleverd — kopieer de sleutel uit de verificatie-instellingen. Zonder sleutel wordt alleen de kaartlink hierboven getoond.",
    ShowManagerFieldLabel: "Manager weergeven",
    UseInformalAddressFieldLabel: "Informeel aanspreken (jij/je)",
    SponsorEligibilityGroupName: "Sponsorgeschiktheid",
    SponsorEligibilityGroupHint:
      "Sponsorkoppelingen in Microsoft Entra worden beheerd door uw organisatie en zijn niet altijd nauwkeurig. Deze filters verbeteren de kwaliteit van de aan gasten getoonde sponsors en voorkomen onbedoelde informatieverstrekking door onjuiste koppelingen.",
    SponsorFilterFieldLabel: "Sponsor moet zijn",
    SponsorFilterTeamsOption: "Teams-gelicenseerd (aanbevolen)",
    SponsorFilterExchangeOption: "Exchange Online-gelicenseerd",
    SponsorFilterAnyOption: "Gelicenseerd (elke actieve licentie)",
    RequireUserMailboxFieldLabel: "Gebruikerspostbustype vereisen",
    LocationDisplayHintSeparateRows: "Ingeschakelde adresvelden worden samengevoegd tot een enkele klikbare rij.",
    AdvancedDisplayGroupName: "Geavanceerde weergaveopties",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "Basis-URL",
    WebPartClientIdFieldLabel: "Toepassings-id (client)",
    SessionCacheTtlMinutesFieldLabel: "Duur van sessiecache (minuten)",
    PpClientIdHintLabel: "Waar vind ik de client-ID?",
    PpClientIdHintBody:
      "Kopieer de client-ID (toepassings-ID) van de app-registratie die tijdens de configuratie is aangemaakt.",
    FunctionEntraLinkLabel: "Zoeken in Microsoft Entra →",
    ProxyStatusChecking: "Verbinding controleren…",
    ProxyStatusOk: "Verbinding geslaagd",
    ProxyStatusError: "Verbinding mislukt",
    PpSetupIntro: "Vereiste configuratie:",
    PpSetupRerunHint:
      "Verbindingsprobleem? Het installatiescript is idempotent — opnieuw uitvoeren met dezelfde parameters lost de meeste problemen op.",
    CopyToClipboardLabel: "Kopiëren",
    CopiedToClipboardLabel: "Gekopieerd!",
    AuthorSectionGroupName: "Over",
    AuthorSectionCreatedBy: "Gemaakt en onderhouden door",
    AuthorSectionIntro: "Microsoft 365-governance, identiteiten en gasttoegang \u2014 ons vakgebied.",
    AuthorSectionWebsiteLinkLabel: "Neem contact op",
    AuthorSectionConsultingText:
      "We bouwden dit webonderdeel omdat dit precies is wat we dagelijks doen. Van architectuur tot uitrol helpen we organisaties een veilige en schaalbare samenwerking op Microsoft 365 in te richten.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Webpart-versie",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Klik op de knop om de implementatie te starten:",
    AuthorSectionDeploymentGuideLabel: "Implementatiegids",
    NewReleaseAvailableLabel: "Nieuwe versie beschikbaar \u2014 GitHub Releases openen",
    DiagnosticsGroupName: "Gasttoegankelijkheid",
    DiagnosticsGroupHint:
      "Controleert of het JavaScript-pakket van het webonderdeel en de landingspagina-site toegankelijk zijn voor B2B-gastgebruikers.",
    DiagnosticsChecking: "Gasttoegankelijkheid wordt gecontroleerd\u2026",
    DiagnosticsRetryButtonLabel: "Controles opnieuw uitvoeren",
    DiagPublicCdnOk:
      "Pakket wordt geleverd via de openbare Office 365 CDN \u2014 anonieme levering, geen speciale rechten vereist voor gasten.",
    DiagPrivateCdnInfo:
      "Pakket wordt geleverd via de priv\u00e9 Office 365 CDN \u2014 gasten met leestoegang tot de site kunnen het laden. Zorg dat de landingspagina-site toegankelijk is voor gasten.",
    DiagSiteColCatalogOk:
      "Pakket wordt geleverd vanuit de siteverzameling-appcatalogus \u2014 gasttoegang volgt de eigen machtigingen van de site.",
    DiagTenantCatalogEveryoneOk:
      "Pakket wordt geleverd vanuit de tenant-appcatalogus. De groep \u2018Iedereen\u2019 heeft leestoegang tot de catalogus \u2014 gastgebruikers kunnen het pakket laden.",
    DiagTenantCatalogEveryoneDenied:
      "Pakket wordt geleverd vanuit de tenant-appcatalogus, maar \u2018Iedereen\u2019 heeft geen leestoegang. Gastgebruikers kunnen het webonderdeel niet laden. Aanbeveling: schakel de openbare Office 365 CDN in of verleen \u2018Iedereen\u2019 bezoekers-toegang tot de appcatalogus-site.",
    DiagTenantCatalogEveryoneUnknown:
      "Pakket wordt geleverd vanuit de tenant-appcatalogus. Kon niet verifi\u00ebren of \u2018Iedereen\u2019 leestoegang heeft (onvoldoende rechten). Controleer handmatig of gasten de catalogus kunnen bereiken of schakel de openbare Office 365 CDN in.",
    DiagAssetSourceUnknown:
      "De bron van het pakket kon niet worden vastgesteld. Controleer handmatig of gastgebruikers toegang hebben tot het JavaScript-pakket van het webonderdeel.",
    DiagSiteEveryoneOk:
      "\u2018Iedereen\u2019 staat in de bezoekers-groep van de site \u2014 nieuw geaccepteerde gasten krijgen onmiddellijk leestoegang tot de landingspagina.",
    DiagSiteEveryoneMissing:
      "\u2018Iedereen\u2019 staat niet in de bezoekers-groep van de site. Gasttoegang hangt mogelijk af van een statische Entra-beveiligingsgroep (acceptabel) of dynamische groep (tot 24\u00a0uur vertraging voor nieuwe gasten). Als er geen gastinclusieve groep is geconfigureerd, zien gasten een toegang-geweigerd-pagina.",
    DiagSiteEveryoneUnknown:
      "De bezoekers-machtigingen van de site konden niet worden geverifieerd. Zorg dat gastgebruikers ten minste leestoegang hebben tot deze site.",
    ShowSponsorJobTitleFieldLabel: "Functietitel van sponsor tonen",
    ShowManagerJobTitleFieldLabel: "Functietitel van manager tonen",
    ShowSponsorDepartmentFieldLabel: "Afdeling van sponsor tonen",
    ShowManagerDepartmentFieldLabel: "Afdeling van manager tonen",
    DepartmentLabel: "Afdeling",
    ShowCityFieldLabel: "Stad weergeven",
    ShowCountryFieldLabel: "Land weergeven",
    CityFieldLabel: "Stad",
    CountryFieldLabel: "Land",
    CopyCityAriaLabel: "Stad kopiëren",
    CopyCountryAriaLabel: "Land kopiëren",
    ShowPresenceFieldLabel: "Aanwezigheidsstatus weergeven",
    ShowSponsorPhotoFieldLabel: "Foto van sponsor weergeven",
    ShowManagerPhotoFieldLabel: "Foto van leidinggevende weergeven",
    TitlePlaceholder: "Mijn sponsors",
    TitleSizeFieldLabel: "Titelgrootte",
    TitleSizeH2Option: "Kop 2",
    TitleSizeH3Option: "Kop 3",
    TitleSizeH4Option: "Kop 4",
    TitleSizeNormalOption: "Normaal",
    WelcomeDialogTitle: "Gastsponsors instellen",
    WelcomeDialogBody:
      "Dit webonderdeel toont elke gastgebruiker hun Microsoft Entra-sponsors op uw SharePoint-landingspagina. Om het webonderdeel zinvol te zijn, moeten sponsortoewijzingen actief worden beheerd en moet er al een levenscyclusproces voor gasten zijn — het maakt die verantwoordelijkheid zichtbaar, maar vervangt de onderliggende governance niet.",
    WelcomeDialogBroughtToYouBy: "Ontwikkeld door Workoho — specialisten in gastgovernance en levenscyclusbeheer.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Aan de slag",
    WelcomeDialogNextButton: "Volgende",
    WelcomeDialogBackButton: "Terug",
    WelcomeDialogSkipButton: "Niet nu",
    WelcomeDialogSaveButton: "Opslaan",
    WelcomeDialogSkipApiButton: "Overslaan",
    InvalidUrlFormat: "Voer een geldige URL in (bijv. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Voer een geldige GUID in (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Kies uw installatiepad",
    WelcomeDialogSetupIntro:
      "Kies uw implementatiepad. U kunt op elk gewenst moment schakelen via de instellingen van het webonderdeel.",
    WelcomeDialogOptionApiTitle: "Guest Sponsor API gebruiken",
    WelcomeDialogOptionApiBody:
      "Volledige ervaring aangedreven door een Azure Function. Vereist eenmalige Azure-installatie — aanbevolen voor productie.",
    WelcomeDialogOptionApiDocsLabel: "Installatiehandleiding bekijken",
    WelcomeDialogSetupGuideNote:
      "Dit commando is een snelkoppeling. Lees de installatiehandleiding voordat u het uitvoert, zodat u begrijpt wat het doet.",
    WelcomeDialogDeployToAzureLabel: "De API implementeren in Azure",
    WelcomeDialogDeployNote:
      "Voor deze optie moet de Guest Sponsor API worden geïmplementeerd in uw Azure-abonnement. U kunt dit hier doen \u2014 het duurt slechts een paar minuten.",
    WelcomeDialogSetupStepsOrderHint: "Voltooi deze stappen in volgorde:",
    WelcomeDialogSetupStep1Label: "App-registratie maken",
    WelcomeDialogSetupStep2Hint: "Gebruikt de in stap 1 gemaakte app-registratie",
    WelcomeDialogSetupStep3Label: "Graph-machtigingen verlenen",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupStep3Hint: "Gebruikt de App-registratie (stap 1) en de Function App-URL (stap 2)",
    ViewScriptSourceLabel: "Script inspecteren",
    WelcomeDialogConnectApiTitle: "API-verbindingsgegevens invoeren",
    WelcomeDialogConnectApiIntro:
      "Voer de verbindingsgegevens in voor uw Guest Sponsor API. U kunt deze stap voor nu overslaan en de gegevens later toevoegen in de instellingen van het webonderdeel.",
    WelcomeDialogUrlHintLabel: "Waar vind ik de URL?",
    WelcomeDialogUrlHintBody:
      "Kopieer de URL van de Function App na de implementatie vanuit de Azure-portal. Ga naar uw Function App → Overzicht → Standaarddomein.",
    WelcomeDialogOptionDemoTitle: "Verkennen in demomodus",
    WelcomeDialogOptionDemoBody:
      "Probeer het webonderdeel met gesimuleerde sponsorgegevens — geen Azure-installatie vereist. Schakel op elk moment over naar de echte API via de instellingen.",
    WelcomeDialogFunctionUrlRequired: "Voer de basis-URL van de Guest Sponsor API in.",
    WelcomeDialogDoneApiTitle: "API geconfigureerd!",
    WelcomeDialogDoneApiBody:
      "De verbinding met de Guest Sponsor API is opgeslagen. Vergeet niet de pagina op te slaan zodat uw instellingen voor iedereen worden toegepast.",
    WelcomeDialogDoneApiSkippedTitle: "Bijna klaar!",
    WelcomeDialogDoneApiSkippedBody:
      "Er zijn nog geen aanmeldingsgegevens ingevoerd. Om de installatie te voltooien: open de webonderdeelinstellingen, voer de basis-URL en client-ID in onder Guest Sponsor API en sla de pagina op.",
    WelcomeDialogDoneDemoTitle: "Demomodus geactiveerd!",
    WelcomeDialogDoneDemoBody:
      "Schakel over naar weergavemodus om het webonderdeel te zien met gesimuleerde sponsorkaarten. Verbind de Guest Sponsor API via de instellingen wanneer u klaar bent.",
    PpSectionLivePage: "▶ Live-pagina",
    PpSectionDemoMode: "🧪 Demomodus",
    PpSectionCardLayout: "🗂️ Kaartindeling",
    PpSectionProfileFields: "👤 Profielvelden",
    PpSectionPhone: "📞 Telefoonnummers",
    PpSectionWorkLocation: "📍 Werklocatie",
    PpSectionAddress: "🏠 Postadres",
    PpSectionMapLink: "🧭 Kaartlink",
    PpSectionMapPreview: "🗺️ Inline kaartvoorbeeld"
  };
});
