define([], function() {
  return {
    "PropertyPaneDescription": "Configureer het webonderdeel Gastsponsors.",
    "BasicGroupName": "Instellingen",
    "TitleFieldLabel": "Titel",
    "LoadingMessage": "Sponsors worden geladen…",
    "NoSponsorsTitle": "Geen sponsors gevonden",
    "NoSponsorsMessage": "Er zijn geen sponsors gevonden voor uw account.",
    "SponsorUnavailableTitle": "Sponsor niet beschikbaar",
    "SponsorUnavailableMessage": "Uw sponsor/eigenaar is niet langer beschikbaar. Neem contact op met uw projectverantwoordelijke om een nieuwe sponsor/eigenaar aan uw account te koppelen.",
    "ErrorMessageTitle": "Er is een fout opgetreden",
    "ErrorMessage": "Kan sponsorinformatie niet laden. Probeer het later opnieuw.",
    "EditModePlaceholder": "Gastsponsors — schakel over naar de weergavemodus om sponsors te zien.",
    "GuestOnlyPlaceholder": "Dit webonderdeel is alleen zichtbaar voor gastgebruikers in de weergavemodus.",
    "MockModeFieldLabel": "Demomodus (testgegevens)",
    "MockModePlaceholder": "Gastsponsors — Demomodus actief. Schakel over naar de weergavemodus om testgegevens te zien.",
    "MockSimulatedHintFieldLabel": "Gastenmelding simuleren",
    "MockSimulatedHintNoneOption": "Geen melding",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams nog niet ingesteld",
    "MockSimulatedHintVersionMismatchOption": "Update beschikbaar",
    "MockSimulatedHintSponsorUnavailableOption": "Sponsor niet beschikbaar",
    "MockSimulatedHintNoSponsorsOption": "Geen sponsoren gevonden",

    "PresenceAvailable": "Beschikbaar",
    "PresenceAvailableIdle": "Beschikbaar, inactief",
    "PresenceAway": "Afwezig",
    "PresenceBeRightBack": "Zo terug",
    "PresenceBusy": "Bezet",
    "PresenceBusyIdle": "Bezet, inactief",
    "PresenceDoNotDisturb": "Niet storen",
    "PresenceInAMeeting": "In een vergadering",
    "PresenceInACall": "In gesprek",
    "PresencePresenting": "Aan het presenteren",
    "PresenceFocusing": "Focusmodus",
    "PresenceOutOfOffice": "Niet op kantoor",
    "PresenceOutOfOfficeSuffix": ", niet op kantoor",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Contactgegevens voor {0}",
    "ContactActionsAriaLabel": "Contactacties",
    "ChatTitle": "Chat starten met {name}",
    "EmailTitle": "E-mail sturen naar {name}",
    "CallTitle": "Audiogesprek starten met {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Bellen",

    "ContactInfoSection": "Contact",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Zakelijk telefoonnummer",
    "MobileFieldLabel": "Mobiel",
    "WorkLocationFieldLabel": "Werklocatie",
    "AddressFieldLabel": "Adres",
    "StreetAddressFieldLabel": "Straat",
    "PostalCodeFieldLabel": "Postcode",
    "StateFieldLabel": "Provincie/regio",

    "OrganizationSection": "Organisatie",
    "ReportsToSection": "Rapporteert aan",
    "ManagerLabel": "Manager",

    "CopiedFeedback": "Gekopieerd!",
    "CopyEmailAriaLabel": "E-mailadres kopiëren",
    "CopyWorkPhoneAriaLabel": "Zakelijk telefoonnummer kopiëren",
    "CopyMobileAriaLabel": "Mobiel nummer kopiëren",
    "CopyLocationAriaLabel": "Werklocatie kopiëren",
    "CopyAddressAriaLabel": "Adres kopiëren",
    "CopyStreetAddressAriaLabel": "Kopieer straat",
    "CopyPostalCodeAriaLabel": "Kopieer postcode",
    "CopyStateAriaLabel": "Kopieer provincie/regio",
    "AddressMapSectionLabel": "Kaartvoorbeeld",
    "AddressMapLoadingLabel": "Kaartvoorbeeld laden...",
    "OpenAddressInMapLabel": "Openen in kaart",

    "TeamsAccessPendingTitle": "Microsoft Teams is nog niet ingesteld",
    "TeamsAccessPendingMessage": "Uw gasttoegang tot Microsoft Teams in deze organisatie is nog niet ingesteld. Uw eigen Teams-account wordt hierdoor niet beïnvloed. Vraag uw sponsor om u toe te voegen aan een team — daarna kunt u hier Teams-functies zoals chat, bellen en vergaderingen gebruiken.",
    "TeamsNotReadyChatTooltip": "Chat hier niet beschikbaar — uw Teams-gasttoegang is nog niet ingesteld",
    "TeamsNotReadyCallTooltip": "Bellen hier niet beschikbaar — uw Teams-gasttoegang is nog niet ingesteld",

    "VersionMismatchTitle": "Update beschikbaar",
    "VersionMismatchMessage": "Er is een update beschikbaar voor dit webonderdeel. Vraag uw beheerder om te controleren of het webonderdeel en de Azure Function dezelfde versie gebruiken.",
    "InsufficientPermissionsTitle": "Onvoldoende rechten",
    "InsufficientPermissionsMessage": "Kan sponsorinformatie niet laden — een vereiste servicemachtiging is niet verleend. Neem contact op met uw IT-beheerder.",

    "NoSponsorsMessageInformal": "Er zijn geen sponsors gevonden voor je account.",
    "SponsorUnavailableMessageInformal": "Je sponsor/eigenaar is niet langer beschikbaar. Neem contact op met je projectverantwoordelijke om een nieuwe sponsor/eigenaar aan je account te koppelen.",
    "TeamsAccessPendingMessageInformal": "Je gasttoegang tot Microsoft Teams in deze organisatie is nog niet ingesteld. Je eigen Teams-account wordt hierdoor niet beïnvloed. Vraag je sponsor om je toe te voegen aan een team — daarna kun je hier Teams-functies zoals chat, bellen en vergaderingen gebruiken.",
    "TeamsNotReadyChatTooltipInformal": "Chat hier niet beschikbaar — je Teams-gasttoegang is nog niet ingesteld",
    "TeamsNotReadyCallTooltipInformal": "Bellen hier niet beschikbaar — je Teams-gasttoegang is nog niet ingesteld",

    "GuestNotificationsGroupName": "Meldingen voor gasten",
    "GuestNotificationsGroupHint": "Beheer welke informatieve meldingen worden weergegeven aan gastgebruikers.",
    "ShowTeamsAccessPendingHintLabel": "Melding «Microsoft Teams nog niet ingesteld» weergeven",
    "ShowVersionMismatchHintLabel": "Melding «Update beschikbaar» weergeven",
    "ShowSponsorUnavailableHintLabel": "Melding «Sponsor niet beschikbaar» weergeven",
    "ShowNoSponsorsHintLabel": "Melding «Geen sponsoren gevonden» weergeven",
    "DisplayGroupName": "Weergave",
    "CardLayoutFieldLabel": "Kaartindeling",
    "CardLayoutAutoOption": "Automatisch",
    "CardLayoutFullOption": "Volledig",
    "CardLayoutCompactOption": "Compact",
    "ShowBusinessPhonesFieldLabel": "Zakelijk telefoonnummer weergeven",
    "ShowMobilePhoneFieldLabel": "Mobiel nummer weergeven",
    "ShowWorkLocationFieldLabel": "Werklocatie weergeven",
    "ShowManagerFieldLabel": "Manager weergeven",
    "UseInformalAddressFieldLabel": "Informeel aanspreken (jij/je)",

    "ShowWorkLocationFallbackFieldLabel": "Werklocatie als terugval weergeven",
    "LocationDisplayHintGeoWithFallback": "Stad en land worden gecombineerd in één geografische regel. De werklocatie wordt alleen weergegeven als er geen stad-/landgegevens beschikbaar zijn.",
    "LocationDisplayHintGeoOnly": "Stad en land worden gecombineerd in één geografische regel. De werklocatie is verborgen.",
    "LocationDisplayHintOfficeOnly": "Alleen de werklocatie wordt weergegeven. Schakel stad en/of land in om in plaats daarvan een geografische regel te tonen.",
    "LocationDisplayHintHidden": "Alle locatie- en adresvelden zijn verborgen.",
    "LocationDisplayHintSeparateRows": "Ingeschakelde adresvelden worden samengevoegd tot een enkele klikbare rij.",
    "AdvancedDisplayGroupName": "Geavanceerde weergaveopties",
    "ManagerOptionsDisabledHint": "Schakel managerweergave in om managerspecifieke velden te configureren.",
    "FunctionGroupName": "Azure-functie",
    "FunctionUrlFieldLabel": "Azure-functie basis-URL",
    "FunctionClientIdFieldLabel": "Sponsor API-client-ID (Azure-functie-app-registratie)",
    "ProxyStatusChecking": "Azure Function controleren…",
    "ProxyStatusOk": "Azure Function bereikbaar",
    "ProxyStatusError": "Azure Function niet bereikbaar",
    "AuthorSectionGroupName": "Over Workoho",
    "AuthorSectionIntro": "Microsoft 365-governance, identiteiten en gasttoegang \u2014 ons vakgebied.",
    "AuthorSectionWebsiteLinkLabel": "Neem contact op",
    "AuthorSectionConsultingText": "We bouwden dit webonderdeel omdat dit precies is wat we dagelijks doen. Van architectuur tot uitrol helpen we organisaties een veilige en schaalbare samenwerking op Microsoft 365 in te richten.",
    "AuthorSectionPartnerPrefix": "Workoho is",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Platinum-verkoop- en implementatiepartner.",
    "AuthorSectionPartnerTagline": "EasyLife 365 automatiseert lifecycle-management voor Teams, SharePoint-sites, Viva Engage en andere Microsoft 365-werkruimten — inclusief gast-onboarding en sponsorbeheer.",
    "AuthorSectionSourceCodeLabel": "Broncode op GitHub",
    "AuthorSectionVersionLabel": "Webpart-versie",
    "ShowSponsorJobTitleFieldLabel": "Functietitel van sponsor tonen",
    "ShowManagerJobTitleFieldLabel": "Functietitel van manager tonen",
    "ShowSponsorDepartmentFieldLabel": "Afdeling van sponsor tonen",
    "ShowManagerDepartmentFieldLabel": "Afdeling van manager tonen",
    "DepartmentLabel": "Afdeling",
    "ShowCityFieldLabel": "Stad weergeven",
    "ShowCountryFieldLabel": "Land weergeven",
    "ShowStreetAddressFieldLabel": "Straat weergeven",
    "ShowPostalCodeFieldLabel": "Postcode weergeven",
    "ShowStateFieldLabel": "Provincie/regio weergeven",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-abonnementsleutel",
    "ExternalMapProviderFieldLabel": "Kaartprovider",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "MapProviderNoneOption": "Uitgeschakeld (geen kaartlink)",
    "AddressMapProviderHint": "Activeer minimaal stad en land — dat volstaat voor elke kaartprovider om een zinvolle locatie weer te geven.",
    "CityFieldLabel": "Stad",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Stad kopiëren",
    "CopyCountryAriaLabel": "Land kopiëren",
    "ShowPresenceFieldLabel": "Aanwezigheidsstatus weergeven",
    "ShowSponsorPhotoFieldLabel": "Foto van sponsor weergeven",
    "ShowManagerPhotoFieldLabel": "Foto van leidinggevende weergeven",
  }
});
