define([], function() {
  return {
    "PropertyPaneDescription": "Skonfiguruj składnik Web Part Informacje o sponsorze gościa.",
    "BasicGroupName": "Ustawienia",
    "TitleFieldLabel": "Tytuł",
    "LoadingMessage": "Ładowanie sponsorów…",
    "NoSponsorsMessage": "Nie znaleziono sponsorów dla Twojego konta.",
    "SponsorUnavailableMessage": "Twój sponsor/właściciel nie jest już dostępny. Skontaktuj się z odpowiedzialną osobą w projekcie, aby przypisano nowego sponsora/właściciela do Twojego konta.",
    "ErrorMessage": "Nie można załadować informacji o sponsorze. Spróbuj ponownie później.",
    "EditModePlaceholder": "Informacje o sponsorze gościa — przełącz do trybu wyświetlania, aby zobaczyć sponsorów.",
    "GuestOnlyPlaceholder": "Ten składnik Web Part jest widoczny tylko dla użytkowników-gości w trybie wyświetlania.",
    "MockModeFieldLabel": "Tryb demonstracyjny (dane testowe)",
    "MockModePlaceholder": "Informacje o sponsorze gościa — aktywny tryb demonstracyjny. Przełącz do trybu wyświetlania, aby zobaczyć dane testowe.",

    "PresenceAvailable": "Dostępny",
    "PresenceAvailableIdle": "Dostępny, bezczynny",
    "PresenceAway": "Nieobecny",
    "PresenceBeRightBack": "Zaraz wróci",
    "PresenceBusy": "Zajęty",
    "PresenceBusyIdle": "Zajęty, bezczynny",
    "PresenceDoNotDisturb": "Nie przeszkadzać",
    "PresenceInAMeeting": "Na spotkaniu",
    "PresenceInACall": "W trakcie rozmowy",
    "PresencePresenting": "Prezentuje",
    "PresenceFocusing": "W trybie skupienia",
    "PresenceOutOfOffice": "Poza biurem",
    "PresenceOutOfOfficeSuffix": ", poza biurem",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Dane kontaktowe dla {0}",
    "ContactActionsAriaLabel": "Akcje kontaktowe",
    "ChatTitle": "Czat w Microsoft Teams",
    "EmailTitle": "Wyślij e-mail",
    "CallTitle": "Połączenie audio w Microsoft Teams",
    "ChatLabel": "Czat",
    "EmailLabel": "E-mail",
    "CallLabel": "Zadzwoń",

    "ContactInfoSection": "Informacje kontaktowe",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Telefon służbowy",
    "MobileFieldLabel": "Telefon komórkowy",
    "WorkLocationFieldLabel": "Lokalizacja miejsca pracy",
    "StreetAddressFieldLabel": "Ulica",
    "PostalCodeFieldLabel": "Kod pocztowy",
    "StateFieldLabel": "Województwo/region",

    "OrganizationSection": "Organizacja",
    "ManagerLabel": "Menedżer",

    "CopiedFeedback": "Skopiowano!",
    "CopyEmailAriaLabel": "Kopiuj adres e-mail",
    "CopyWorkPhoneAriaLabel": "Kopiuj telefon służbowy",
    "CopyMobileAriaLabel": "Kopiuj numer telefonu komórkowego",
    "CopyLocationAriaLabel": "Kopiuj lokalizację miejsca pracy",
    "CopyStreetAddressAriaLabel": "Kopiuj ulicę",
    "CopyPostalCodeAriaLabel": "Kopiuj kod pocztowy",
    "CopyStateAriaLabel": "Kopiuj województwo/region",
    "AddressMapSectionLabel": "Podgląd mapy",
    "AddressMapLoadingLabel": "Ładowanie podglądu mapy...",
    "OpenAddressInMapLabel": "Otwórz w mapie",

    "TeamsAccessPendingTitle": "Microsoft Teams nie został jeszcze skonfigurowany",
    "TeamsAccessPendingMessage": "Twój dostęp gościa do Microsoft Teams w tej organizacji nie został jeszcze skonfigurowany. Twoje własne konto Teams nie jest tym dotknięte. Poproś swojego sponsora o dodanie Cię do zespołu — po tym funkcje Teams, takie jak czat, połączenia i spotkania, będą dostępne tutaj.",
    "TeamsNotReadyChatTooltip": "Czat niedostępny w tej organizacji — Twój dostęp gościa Teams nie został jeszcze skonfigurowany",
    "TeamsNotReadyCallTooltip": "Połączenie niedostępne w tej organizacji — Twój dostęp gościa Teams nie został jeszcze skonfigurowany",

    "VersionMismatchMessage": "Dostępna jest aktualizacja tego składnika Web Part. Poproś administratora, aby upewnił się, że składnik Web Part i usługa Azure Function używają tej samej wersji.",
    "InsufficientPermissionsMessage": "Nie można załadować informacji o sponsorze — wymagane uprawnienie usługi nie zostało przyznane. Skontaktuj się z administratorem IT.",

    "DisplayGroupName": "Wyświetlanie",
    "ShowBusinessPhonesFieldLabel": "Pokaż telefon służbowy",
    "ShowMobilePhoneFieldLabel": "Pokaż numer telefonu komórkowego",
    "ShowWorkLocationFieldLabel": "Pokaż lokalizację miejsca pracy",
    "ShowManagerFieldLabel": "Pokaż menedżera",
    "UseInformalAddressFieldLabel": "Forma nieformalna (ty)",

    "ShowWorkLocationFallbackFieldLabel": "Pokaż lokalizację miejsca pracy jako zapasową",
    "LocationDisplayHintGeoWithFallback": "Miasto i kraj są łączone w jednym wierszu lokalizacji. Lokalizacja pracy jest wyświetlana tylko wtedy, gdy brak danych miasta/kraju.",
    "LocationDisplayHintGeoOnly": "Miasto i kraj są łączone w jednym wierszu lokalizacji. Lokalizacja pracy jest ukryta.",
    "LocationDisplayHintOfficeOnly": "Wyświetlana jest tylko lokalizacja pracy. Włącz miasto i/lub kraj, aby zamiast tego pokazać wiersz lokalizacji.",
    "LocationDisplayHintHidden": "Wszystkie informacje o lokalizacji są ukryte.",
    "AddressMapFallbackHint": "Jeśli nie skonfigurowano klucza Azure Maps lub wyszukiwanie się nie powiedzie, wyświetlany jest zewnętrzny link do mapy.",
    "LocationDisplayHintAddressEnabled": "Pola adresu strukturalnego są włączone i mogą być wyświetlane w dodatkowych wierszach.",
    "LocationDisplayHintSeparateRows": "Miasto/kraj i lokalizacja pracy są wyświetlane w osobnych wierszach po włączeniu.",
    "AdvancedDisplayGroupName": "Zaawansowane opcje wyświetlania",
    "ManagerOptionsDisabledHint": "Włącz wyświetlanie menedżera, aby skonfigurować pola specyficzne dla menedżera.",
    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "Adres URL interfejsu API sponsorów (Azure Function)",
    "FunctionClientIdFieldLabel": "Identyfikator klienta interfejsu API sponsorów (rejestracja aplikacji Azure Function)",
    "ProxyStatusChecking": "Sprawdzanie Azure Function…",
    "ProxyStatusOk": "Azure Function osiągalna",
    "ProxyStatusError": "Azure Function nieosiągalna",
    "ShowSponsorJobTitleFieldLabel": "Pokaż stanowisko sponsora",
    "ShowManagerJobTitleFieldLabel": "Pokaż stanowisko przełożonego",
    "ShowSponsorDepartmentFieldLabel": "Pokaż dział sponsora",
    "ShowManagerDepartmentFieldLabel": "Pokaż dział przełożonego",
    "DepartmentLabel": "Dział",
    "ShowCityFieldLabel": "Pokaż miasto",
    "ShowCountryFieldLabel": "Pokaż kraj",
    "ShowStructuredAddressFieldLabel": "Pokaż adres strukturalny",
    "ShowStreetAddressFieldLabel": "Pokaż ulicę",
    "ShowPostalCodeFieldLabel": "Pokaż kod pocztowy",
    "ShowStateFieldLabel": "Pokaż województwo/region",
    "ShowAddressMapFieldLabel": "Pokaż podgląd mapy adresu",
    "AzureMapsSubscriptionKeyFieldLabel": "Klucz subskrypcji Azure Maps",
    "ExternalMapProviderFieldLabel": "Zewnętrzny dostawca map (awaryjnie)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Miasto",
    "CountryFieldLabel": "Kraj",
    "CopyCityAriaLabel": "Kopiuj miasto",
    "CopyCountryAriaLabel": "Kopiuj kraj",
    "ShowPresenceFieldLabel": "Pokaż status obecności"
  }
});
