// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Ustawienia",
    ShowTitleFieldLabel: "Pokaż tytuł",
    TitleFieldLabel: "Tytuł",
    LoadingMessage: "Ładowanie sponsorów…",
    NoSponsorsTitle: "Brak sponsorów",
    NoSponsorsMessage: "Nie znaleziono sponsorów dla Twojego konta.",
    SponsorUnavailableTitle: "Sponsor niedostępny",
    SponsorUnavailableMessage:
      "Twój sponsor nie jest już dostępny. Skontaktuj się z odpowiedzialną osobą w projekcie, aby przypisano nowego sponsora do Twojego konta.",
    ErrorMessageTitle: "Wystąpił błąd",
    ErrorMessage: "Nie można załadować informacji o sponsorze. Spróbuj ponownie później.",
    EditModePlaceholder: "Informacje o sponsorze gościa — przełącz do trybu wyświetlania, aby zobaczyć sponsorów.",
    GuestOnlyPlaceholder: "Ten składnik Web Part jest widoczny tylko dla użytkowników-gości w trybie wyświetlania.",
    MockModeFieldLabel: "Zawsze pokazuj sponsorów demo (publiczny tryb demo)",
    MockModeFieldDescription: "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    MockModeFieldTooltip:
      "Po włączeniu tryb demonstracyjny pojawia się tylko na live stronie do celów testowania. Tryb edycji i podgląd pozostają bez zmian.",
    MockModePlaceholder:
      "Informacje o sponsorze gościa — aktywny tryb demonstracyjny. Przełącz do trybu wyświetlania, aby zobaczyć dane testowe.",
    MockSimulatedHintFieldLabel: "Symuluj powiadomienie gościa",
    MockSimulatedHintNoneOption: "Brak powiadomienia",
    MockSimulatedHintTeamsAccessPendingOption: "Microsoft Teams nie zostało jeszcze skonfigurowane",
    MockSimulatedHintVersionMismatchOption: "Dostępna aktualizacja",
    MockSimulatedHintSponsorUnavailableOption: "Sponsor niedostępny",
    MockSimulatedHintNoSponsorsOption: "Nie znaleziono sponsorów",
    MaxSponsorCountFieldLabel: "Widoczni sponsorzy",
    MaxSponsorCountFieldTooltip:
      "Ogranicza liczbę wyświetlanych kart sponsora. Tylko aktywni (dostępni) sponsorzy liczą się dla tego limitu. Jeśli przypisane konto sponsora nie jest więcej dostępne (wyłączone, usunięte lub jeszcze nie aprowizowane), następny sponsor w porządku priorytetów automatycznie postępuje naprzód, aby wypełnić puste miejsce. Gwarantuje to, że goście zawsze widzą skonfigurowaną liczbę dostępnych kontaktów.",
    PresenceAvailable: "Dostępny",
    PresenceAvailableIdle: "Dostępny, bezczynny",
    PresenceAway: "Nieobecny",
    PresenceBeRightBack: "Zaraz wróci",
    PresenceBusy: "Zajęty",
    PresenceBusyIdle: "Zajęty, bezczynny",
    PresenceDoNotDisturb: "Nie przeszkadzać",
    PresenceInAMeeting: "Na spotkaniu",
    PresenceInACall: "W trakcie rozmowy",
    PresencePresenting: "Prezentuje",
    PresenceFocusing: "W trybie skupienia",
    PresenceOutOfOffice: "Poza biurem",
    PresenceOutOfOfficeSuffix: ", poza biurem",
    PresenceOffline: "Offline",
    ContactDetailsAriaLabel: "Dane kontaktowe dla {0}",
    ContactActionsAriaLabel: "Akcje kontaktowe",
    CloseLabel: "Zamknij",
    ChatTitle: "Rozpocznij czat z {name}",
    EmailTitle: "Wyślij e-mail do {name}",
    CallTitle: "Rozpocznij rozmowę audio z {name}",
    ChatLabel: "Czat",
    EmailLabel: "E-mail",
    CallLabel: "Zadzwoń",
    ContactInfoSection: "Kontakt",
    EmailFieldLabel: "E-mail",
    WorkPhoneFieldLabel: "Telefon służbowy",
    MobileFieldLabel: "Telefon komórkowy",
    WorkLocationFieldLabel: "Lokalizacja miejsca pracy",
    AddressFieldLabel: "Adres",
    StreetAddressFieldLabel: "Ulica",
    PostalCodeFieldLabel: "Kod pocztowy",
    StateFieldLabel: "Województwo/region",
    OrganizationSection: "Organizacja",
    ReportsToSection: "Podlega",
    ManagerLabel: "Menedżer",
    CopiedFeedback: "Skopiowano!",
    CopyEmailAriaLabel: "Kopiuj adres e-mail",
    CopyWorkPhoneAriaLabel: "Kopiuj telefon służbowy",
    CopyMobileAriaLabel: "Kopiuj numer telefonu komórkowego",
    CopyLocationAriaLabel: "Kopiuj lokalizację miejsca pracy",
    CopyAddressAriaLabel: "Kopiuj adres",
    CopyStreetAddressAriaLabel: "Kopiuj ulicę",
    CopyPostalCodeAriaLabel: "Kopiuj kod pocztowy",
    CopyStateAriaLabel: "Kopiuj województwo/region",
    AddressMapSectionLabel: "Podgląd mapy",
    AddressMapLoadingLabel: "Ładowanie podglądu mapy...",
    OpenAddressInMapLabel: "Otwórz w mapie",
    TeamsAccessPendingTitle: "Microsoft Teams nie został jeszcze skonfigurowany",
    TeamsAccessPendingMessage:
      "Twój dostęp gościa do Microsoft Teams w tej organizacji nie został jeszcze skonfigurowany. Twoje własne konto Teams nie jest tym dotknięte. Poproś swojego sponsora o dodanie Cię do zespołu — po tym funkcje Teams, takie jak czat, połączenia i spotkania, będą dostępne tutaj.",
    TeamsNotReadyChatTooltip:
      "Czat niedostępny w tej organizacji — Twój dostęp gościa Teams nie został jeszcze skonfigurowany",
    TeamsNotReadyCallTooltip:
      "Połączenie niedostępne w tej organizacji — Twój dostęp gościa Teams nie został jeszcze skonfigurowany",
    VersionMismatchTitle: "Dostępna aktualizacja",
    VersionMismatchMessage:
      "Dostępna jest aktualizacja tego składnika Web Part. Propoś administratora, aby upewnił się, że składnik Web Part i Guest Sponsor API używają tej samej wersji.",
    InsufficientPermissionsTitle: "Brak uprawnień",
    InsufficientPermissionsMessage:
      "Nie można załadować informacji o sponsorze — wymagane uprawnienie usługi nie zostało przyznane. Skontaktuj się z administratorem IT.",
    GuestNotificationsGroupName: "Powiadomienia dla gości",
    GuestNotificationsGroupHint: "Kontroluj, które powiadomienia informacyjne są wyświetlane użytkownikiem-gościom.",
    ShowTeamsAccessPendingHintLabel: "Pokaż powiadomienie «Microsoft Teams nie zostało jeszcze skonfigurowane»",
    ShowVersionMismatchHintLabel: "Pokaż powiadomienie «Dostępna aktualizacja»",
    ShowSponsorUnavailableHintLabel: "Pokaż powiadomienie «Sponsor niedostępny»",
    ShowNoSponsorsHintLabel: "Pokaż powiadomienie «Nie znaleziono sponsorów»",
    DisplayGroupName: "Wyświetlanie",
    CardLayoutFieldLabel: "Układ karty",
    CardLayoutAutoOption: "Automatyczny",
    CardLayoutAutoThresholdFieldLabel: "Przełącz na układ kompaktowy od tej liczby sponsorów",
    CardLayoutFullOption: "Pełny",
    CardLayoutCompactOption: "Kompaktowy",
    ShowBusinessPhonesFieldLabel: "Pokaż telefon służbowy",
    ShowMobilePhoneFieldLabel: "Pokaż numer telefonu komórkowego",
    ShowWorkLocationFieldLabel: "Pokaż lokalizację miejsca pracy",
    ShowStreetAddressFieldLabel: "Pokaż ulicę",
    ShowPostalCodeFieldLabel: "Pokaż kod pocztowy",
    ShowStateFieldLabel: "Pokaż województwo/region",
    AzureMapsSubscriptionKeyFieldLabel: "Klucz subskrypcji Azure Maps",
    MapProviderModeAutoLabel: "Tryb automatyczny (zalecane)",
    MapProviderModeManualLabel: "Ręczny (taki sam dla wszystkich urządzeń)",
    MapProviderModeHint:
      "Wybierz dostawcę mapy dla każdego systemu operacyjnego, w tym dla iOS i Androida. Link otwiera się w przeglądarce lub w aplikacji dostawcy, jeśli jest zainstalowana.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Dostawca map",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Wyłączone (brak linku do mapy)",
    AddressMapProviderHint:
      "Włącz przynajmniej miasto i kraj — to wystarczy, aby dowolny dostawca map wyświetlił znaczącą lokalizację.",
    AzureMapsPreviewHint:
      "Dodaj klucz subskrypcji Azure Maps, aby wyświetlić mały podgląd mapy w sekcji kontaktu. Jeśli wdrożono interfejs API Guest Sponsor, dołączone zostało konto Azure Maps — skopiuj klucz z ustawień uwierzytelniania. Bez klucza wyświetlany jest tylko link do mapy powyżej.",
    ShowManagerFieldLabel: "Pokaż menedżera",
    UseInformalAddressFieldLabel: "Forma nieformalna (ty)",
    SponsorEligibilityGroupName: "Kwalifikowalność sponsora",
    SponsorEligibilityGroupHint:
      "Przypisania sponsorów w Microsoft Entra są zarządzane przez Twoją organizację i nie zawsze są dokładne. Te filtry poprawiają jakość sponsorów wyświetlanych gościom i zapobiegają niezamierzonemu ujawnieniu informacji spowodowanemu nieprawidłowymi przypisaniami.",
    SponsorFilterFieldLabel: "Sponsor musi mieć",
    SponsorFilterTeamsOption: "Licencję Teams (zalecane)",
    SponsorFilterExchangeOption: "Licencję Exchange Online",
    SponsorFilterAnyOption: "Licencję (dowolna aktywna licencja)",
    RequireUserMailboxFieldLabel: "Wymagaj typu skrzynki pocztowej użytkownika",
    LocationDisplayHintSeparateRows: "Włączone pola adresowe są łączone w jeden klikalny wiersz.",
    AdvancedDisplayGroupName: "Zaawansowane opcje wyświetlania",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "Podstawowy adres URL",
    WebPartClientIdFieldLabel: "Identyfikator aplikacji (klienta)",
    SessionCacheTtlMinutesFieldLabel: "Czas trwania pamięci podręcznej sesji (minuty)",
    PpClientIdHintLabel: "Gdzie znajd\u0119 identyfikator klienta?",
    PpClientIdHintBody:
      "Skopiuj identyfikator klienta (identyfikator aplikacji) z rejestracji aplikacji utworzonej podczas konfiguracji.",
    FunctionEntraLinkLabel: "Znajdź w Microsoft Entra →",
    ProxyStatusChecking: "Sprawdzanie połączenia…",
    ProxyStatusOk: "Połączenie udane",
    ProxyStatusError: "Połączenie nieudane",
    PpSetupIntro: "Wymagana konfiguracja:",
    PpSetupRerunHint:
      "Problem z połączeniem? Skrypty konfiguracji są idempotentne \u2014 ponowne uruchomienie z tymi samymi parametrami naprawia większość problemów.",
    CopyToClipboardLabel: "Kopiuj",
    CopiedToClipboardLabel: "Skopiowano!",
    AuthorSectionGroupName: "O aplikacji",
    AuthorSectionCreatedBy: "Stworzone i utrzymywane przez",
    AuthorSectionIntro: "Zarządzanie Microsoft 365, tożsamości i dostęp gości \u2014 nasza dziedzina.",
    AuthorSectionWebsiteLinkLabel: "Skontaktuj się",
    AuthorSectionConsultingText:
      "Stworzyliśmy ten składnik Web Part, bo właśnie tym zajmujemy się na co dzień. Od architektury po wdrożenie pomagamy organizacjom budować bezpieczne i skalowalne środowiska współpracy w usłudze Microsoft 365.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Wersja webpartu",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Kliknij przycisk, aby rozpocz\u0105\u0107 wdro\u017cenie:",
    AuthorSectionDeploymentGuideLabel: "Przewodnik wdrożeniowy",
    NewReleaseAvailableLabel: "Dost\u0119pna nowa wersja \u2014 otw\u00f3rz GitHub Releases",
    DiagnosticsGroupName: "Dost\u0119pno\u015b\u0107 dla go\u015bci",
    DiagnosticsGroupHint:
      "Sprawdza, czy pakiet JavaScript sk\u0142adnika Web Part i witryna strony docelowej s\u0105 dost\u0119pne dla u\u017cytkownik\u00f3w-go\u015bci B2B.",
    DiagnosticsChecking: "Sprawdzanie dost\u0119pno\u015bci dla go\u015bci\u2026",
    DiagnosticsRetryButtonLabel: "Uruchom sprawdzenia ponownie",
    DiagPublicCdnOk:
      "Pakiet dostarczany przez publiczn\u0105 sie\u0107 CDN Office 365 \u2014 anonimowe dostarczanie, brak specjalnych uprawnie\u0144 wymaganych dla go\u015bci.",
    DiagPrivateCdnInfo:
      "Pakiet dostarczany przez prywatn\u0105 sie\u0107 CDN Office 365 \u2014 go\u015bcie z dost\u0119pem do odczytu witryny mog\u0105 go za\u0142adowa\u0107. Upewnij si\u0119, \u017ce witryna strony docelowej jest dost\u0119pna dla go\u015bci.",
    DiagSiteColCatalogOk:
      "Pakiet dostarczany z katalogu aplikacji zbioru witryn \u2014 dost\u0119p go\u015bci wynika z uprawnie\u0144 samej witryny.",
    DiagTenantCatalogEveryoneOk:
      "Pakiet dostarczany z katalogu aplikacji dzier\u017cawcy. Grupa \u2018Wszyscy\u2019 ma dost\u0119p do odczytu katalogu \u2014 u\u017cytkownicy-go\u015bcie mog\u0105 za\u0142adowa\u0107 pakiet.",
    DiagTenantCatalogEveryoneDenied:
      "Pakiet dostarczany z katalogu aplikacji dzier\u017cawcy, ale \u2018Wszyscy\u2019 nie maj\u0105 dost\u0119pu do odczytu. U\u017cytkownicy-go\u015bcie nie mog\u0105 za\u0142adowa\u0107 sk\u0142adnika Web Part. Zalecenie: w\u0142\u0105cz publiczn\u0105 sie\u0107 CDN Office 365 lub przyznaj \u2018Wszyscy\u2019 dost\u0119p Odwiedzaj\u0105cego do witryny katalogu.",
    DiagTenantCatalogEveryoneUnknown:
      "Pakiet dostarczany z katalogu aplikacji dzier\u017cawcy. Nie mo\u017cna zweryfikowa\u0107, czy \u2018Wszyscy\u2019 maj\u0105 dost\u0119p do odczytu (niewystarczaj\u0105ce uprawnienia). Sprawd\u017a r\u0119cznie, czy go\u015bcie mog\u0105 dotrze\u0107 do katalogu, lub w\u0142\u0105cz publiczn\u0105 sie\u0107 CDN Office 365.",
    DiagAssetSourceUnknown:
      "Nie mo\u017cna okre\u015bli\u0107 \u017ar\u00f3d\u0142a pakietu. Sprawd\u017a r\u0119cznie, czy u\u017cytkownicy-go\u015bcie mog\u0105 uzyska\u0107 dost\u0119p do pakietu JavaScript sk\u0142adnika Web Part.",
    DiagSiteEveryoneOk:
      "\u2018Wszyscy\u2019 s\u0105 w grupie Odwiedzaj\u0105cych witryny \u2014 nowo zaakceptowani go\u015bcie uzyskuj\u0105 natychmiastowy dost\u0119p do odczytu strony docelowej.",
    DiagSiteEveryoneMissing:
      "\u2018Wszyscy\u2019 nie s\u0105 w grupie Odwiedzaj\u0105cych witryny. Dost\u0119p go\u015bci mo\u017ce zale\u017ce\u0107 od statycznej grupy zabezpiecze\u0144 Entra (akceptowalne) lub dynamicznej (op\u00f3\u017anienie do 24\u00a0godzin dla nowych go\u015bci). Je\u015bli nie skonfigurowano grupy obejmuj\u0105cej go\u015bci, zobaczy\u0105 oni stron\u0119 odmowy dost\u0119pu.",
    DiagSiteEveryoneUnknown:
      "Nie mo\u017cna zweryfikowa\u0107 uprawnie\u0144 Odwiedzaj\u0105cych witryny. Upewnij si\u0119, \u017ce u\u017cytkownicy-go\u015bcie maj\u0105 przynajmniej dost\u0119p do odczytu tej witryny.",
    ShowSponsorJobTitleFieldLabel: "Pokaż stanowisko sponsora",
    ShowManagerJobTitleFieldLabel: "Pokaż stanowisko przełożonego",
    ShowSponsorDepartmentFieldLabel: "Pokaż dział sponsora",
    ShowManagerDepartmentFieldLabel: "Pokaż dział przełożonego",
    DepartmentLabel: "Dział",
    ShowCityFieldLabel: "Pokaż miasto",
    ShowCountryFieldLabel: "Pokaż kraj",
    CityFieldLabel: "Miasto",
    CountryFieldLabel: "Kraj",
    CopyCityAriaLabel: "Kopiuj miasto",
    CopyCountryAriaLabel: "Kopiuj kraj",
    ShowPresenceFieldLabel: "Pokaż status obecności",
    ShowSponsorPhotoFieldLabel: "Pokaż zdjęcie sponsora",
    ShowManagerPhotoFieldLabel: "Pokaż zdjęcie przełożonego",
    TitlePlaceholder: "Moi sponsorzy",
    TitleSizeFieldLabel: "Rozmiar tytułu",
    TitleSizeH2Option: "Nagłówek 2",
    TitleSizeH3Option: "Nagłówek 3",
    TitleSizeH4Option: "Nagłówek 4",
    TitleSizeNormalOption: "Normalny",
    WelcomeDialogTitle: "Skonfiguruj Informacje o sponsorze gościa",
    WelcomeDialogBody:
      "Ten składnik Web Part wyświetla każdemu użytkownikowi-gościowi jego sponsorów Microsoft Entra na stronie docelowej SharePoint. Aby składnik był przydatny, przypisania sponsorów powinny być aktywnie zarządzane, a proces cyklu życia gości powinien być już wdrożony — sprawia, że odpowiedzialność staje się widoczna, ale nie zastępuje leżącego u jej podstaw ładu.",
    WelcomeDialogBroughtToYouBy:
      "Stworzone przez Workoho — specjalistów w zakresie ładu dostępu gości i zarządzania cyklem życia.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Zaczynajmy",
    WelcomeDialogNextButton: "Dalej",
    WelcomeDialogBackButton: "Wstecz",
    WelcomeDialogSkipButton: "Nie teraz",
    WelcomeDialogSaveButton: "Zapisz",
    WelcomeDialogSkipApiButton: "Pomiń",
    InvalidUrlFormat: "Wprowadź prawidłowy adres URL (np. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Wprowadź prawidłowy GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Wybierz metodę konfiguracji",
    WelcomeDialogSetupIntro:
      "Wybierz ścieżkę wdrożenia. Możesz przełączać się między obiema opcjami w dowolnym momencie za pomocą ustawień składnika Web Part.",
    WelcomeDialogOptionApiTitle: "Używaj Guest Sponsor API",
    WelcomeDialogOptionApiBody:
      "Pełne możliwości dzięki Azure Function. Wymaga jednorazowej konfiguracji Azure — zalecane do produkcji.",
    WelcomeDialogOptionApiDocsLabel: "Wyświetl przewodnik konfiguracji",
    WelcomeDialogSetupGuideNote:
      "Te kroki to skrót do szybkiej konfiguracji. Przed uruchomieniem skryptów przeczytaj przewodnik, aby zrozumieć, co robi każde polecenie.",
    WelcomeDialogDeployToAzureLabel: "Wdróż API na platformie Azure",
    WelcomeDialogDeployNote:
      "Ta opcja wymaga wdrożenia Guest Sponsor API w subskrypcji Azure. Możesz to zrobić tutaj \u2014 zajmuje to tylko kilka minut.",
    WelcomeDialogSetupStepsOrderHint: "Wykonaj te kroki po kolei:",
    WelcomeDialogSetupStep1Label: "Utwórz rejestrację aplikacji",
    WelcomeDialogSetupStep2Hint: "Używa rejestracji aplikacji utworzonej w kroku 1",
    WelcomeDialogSetupStep3Label: "Przyznaj uprawnienia Graph",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupStep3Hint: "Używa rejestracji aplikacji (krok 1) i adresu URL Function App (krok 2)",
    ViewScriptSourceLabel: "Zbadaj skrypt",
    WelcomeDialogConnectApiTitle: "Wprowadź dane połączenia z API",
    WelcomeDialogConnectApiIntro:
      "Wprowadź dane połączenia dla swojego Guest Sponsor API. Możesz pominąć ten krok na razie i dodać je później w ustawieniach składnika Web Part.",
    WelcomeDialogUrlHintLabel: "Gdzie znaleźć adres URL?",
    WelcomeDialogUrlHintBody:
      "Skopiuj adres URL aplikacji funkcji z portalu Azure po wdrożeniu. Przejdź do aplikacji funkcji → Przegląd → Domena domyślna.",
    WelcomeDialogOptionDemoTitle: "Odkryj w trybie demonstracyjnym",
    WelcomeDialogOptionDemoBody:
      "Wypróbuj składnik z symulowanymi danymi sponsorów — bez konfiguracji Azure. W dowolnym momencie przełącz się na prawdziwe API w ustawieniach.",
    WelcomeDialogFunctionUrlRequired: "Podaj podstawowy adres URL Guest Sponsor API.",
    WelcomeDialogDoneApiTitle: "API skonfigurowane!",
    WelcomeDialogDoneApiBody:
      "Połączenie z Guest Sponsor API zostało zapisane. Pamiętaj, aby zapisać stronę, aby ustawienia zostały zastosowane dla wszystkich.",
    WelcomeDialogDoneApiSkippedTitle: "Prawie gotowe!",
    WelcomeDialogDoneApiSkippedBody:
      "Nie wprowadzono żadnych poświadczeń. Aby zakończyć konfigurację: otwórz ustawienia składnika Web Part, wprowadź podstawowy adres URL i identyfikator klienta w sekcji Guest Sponsor API, a następnie zapisz stronę.",
    WelcomeDialogDoneDemoTitle: "Tryb demonstracyjny aktywowany!",
    WelcomeDialogDoneDemoBody:
      "Przełącz się w tryb widoku, aby zobaczyć składnik z symulowanymi kartami sponsorów. Połącz Guest Sponsor API z ustawień, gdy będziesz gotowy.",
    PpSectionLivePage: "▶ Strona na żywo",
    PpSectionDemoMode: "🧪 Tryb demonstracyjny",
    PpSectionCardLayout: "🗂️ Układ karty",
    PpSectionProfileFields: "👤 Pola profilu",
    PpSectionPhone: "📞 Numery telefonów",
    PpSectionWorkLocation: "📍 Miejsce pracy",
    PpSectionAddress: "🏠 Adres pocztowy",
    PpSectionMapLink: "🧭 Link do mapy",
    PpSectionMapPreview: "🗺️ Wbudowany podgląd mapy"
  };
});
