define([], function() {
  return {
    "PropertyPaneDescription": "Configure o web part de Informações do Patrocinador Convidado.",
    "BasicGroupName": "Configurações",
    "TitleFieldLabel": "Título",
    "LoadingMessage": "Carregando seus patrocinadores…",
    "NoSponsorsTitle": "Nenhum patrocinador encontrado",
    "NoSponsorsMessage": "Nenhum patrocinador encontrado para sua conta.",
    "SponsorUnavailableTitle": "Patrocinador indisponível",
    "SponsorUnavailableMessage": "Seu patrocinador/responsável não está mais disponível. Entre em contato com o responsável pelo projeto para que um novo patrocinador/responsável seja atribuído à sua conta.",
    "ErrorMessageTitle": "Ocorreu um erro",
    "ErrorMessage": "Não foi possível carregar as informações do patrocinador. Tente novamente mais tarde.",
    "EditModePlaceholder": "Informações do Patrocinador Convidado — alterne para o modo de exibição para ver os patrocinadores.",
    "GuestOnlyPlaceholder": "Este web part é visível apenas para usuários convidados no modo de exibição.",
    "MockModeFieldLabel": "Sempre exibir patrocinadores demo (modo demo público)",
    "MockModePlaceholder": "Informações do Patrocinador Convidado — Modo de demonstração ativo. Alterne para o modo de exibição para ver os dados fictícios.",
    "MockSimulatedHintFieldLabel": "Simular notificação de convidado",
    "MockSimulatedHintNoneOption": "Nenhuma notificação",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams ainda não configurado",
    "MockSimulatedHintVersionMismatchOption": "Atualização disponível",
    "MockSimulatedHintSponsorUnavailableOption": "Patrocinador não disponível",
    "MockSimulatedHintNoSponsorsOption": "Nenhum patrocinador encontrado",
    "MaxSponsorCountFieldLabel": "Patrocinadores visíveis (página ao vivo)",
    "MockSponsorCountFieldLabel": "Número de patrocinadores de demonstração",

    "PresenceAvailable": "Disponível",
    "PresenceAvailableIdle": "Disponível, inativo",
    "PresenceAway": "Ausente",
    "PresenceBeRightBack": "Volto já",
    "PresenceBusy": "Ocupado",
    "PresenceBusyIdle": "Ocupado, inativo",
    "PresenceDoNotDisturb": "Não perturbe",
    "PresenceInAMeeting": "Em uma reunião",
    "PresenceInACall": "Em uma chamada",
    "PresencePresenting": "Apresentando",
    "PresenceFocusing": "Em foco",
    "PresenceOutOfOffice": "Fora do escritório",
    "PresenceOutOfOfficeSuffix": ", fora do escritório",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Detalhes de contato para {0}",
    "ContactActionsAriaLabel": "Ações de contato",
    "ChatTitle": "Iniciar um chat com {name}",
    "EmailTitle": "Enviar e-mail para {name}",
    "CallTitle": "Iniciar uma chamada de áudio com {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Ligar",

    "ContactInfoSection": "Contato",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Telefone comercial",
    "MobileFieldLabel": "Celular",
    "WorkLocationFieldLabel": "Local de trabalho",
    "AddressFieldLabel": "Endereço",
    "StreetAddressFieldLabel": "Rua",
    "PostalCodeFieldLabel": "CEP",
    "StateFieldLabel": "Estado/região",

    "OrganizationSection": "Organização",
    "ReportsToSection": "Reporta-se a",
    "ManagerLabel": "Gerente",

    "CopiedFeedback": "Copiado!",
    "CopyEmailAriaLabel": "Copiar endereço de e-mail",
    "CopyWorkPhoneAriaLabel": "Copiar telefone comercial",
    "CopyMobileAriaLabel": "Copiar número de celular",
    "CopyLocationAriaLabel": "Copiar local de trabalho",
    "CopyAddressAriaLabel": "Copiar endereço",
    "CopyStreetAddressAriaLabel": "Copiar rua",
    "CopyPostalCodeAriaLabel": "Copiar CEP",
    "CopyStateAriaLabel": "Copiar estado/região",
    "AddressMapSectionLabel": "Pré-visualização do mapa",
    "AddressMapLoadingLabel": "Carregando pré-visualização do mapa...",
    "OpenAddressInMapLabel": "Abrir no mapa",

    "TeamsAccessPendingTitle": "Microsoft Teams ainda não configurado",
    "TeamsAccessPendingMessage": "Seu acesso de convidado ao Microsoft Teams nesta organização ainda não foi configurado. Sua própria conta do Teams não é afetada. Peça ao seu patrocinador para adicionar você a uma equipe — depois disso, recursos do Teams como chat, chamadas e reuniões ficarão disponíveis aqui.",
    "TeamsNotReadyChatTooltip": "Chat indisponível aqui — seu acesso de convidado do Teams ainda não foi configurado",
    "TeamsNotReadyCallTooltip": "Chamada indisponível aqui — seu acesso de convidado do Teams ainda não foi configurado",

    "VersionMismatchTitle": "Atualização disponível",
    "VersionMismatchMessage": "Há uma atualização disponível para esta web part. Peça ao seu administrador para garantir que a web part e a Guest Sponsor API estejam executando a mesma versão.",
    "InsufficientPermissionsTitle": "Permissão insuficiente",
    "InsufficientPermissionsMessage": "Não foi possível carregar as informações do patrocinador — uma permissão de serviço necessária não foi concedida. Entre em contato com seu administrador de TI.",

    "GuestNotificationsGroupName": "Notificações para convidados",
    "GuestNotificationsGroupHint": "Controle quais notificações informativas são exibidas para usuários convidados.",
    "ShowTeamsAccessPendingHintLabel": "Exibir aviso «Microsoft Teams ainda não configurado»",
    "ShowVersionMismatchHintLabel": "Exibir aviso «Atualização disponível»",
    "ShowSponsorUnavailableHintLabel": "Exibir aviso «Patrocinador não disponível»",
    "ShowNoSponsorsHintLabel": "Exibir aviso «Nenhum patrocinador encontrado»",
    "DisplayGroupName": "Exibição",
    "CardLayoutFieldLabel": "Layout do cartão",
    "CardLayoutAutoOption": "Automático",
    "CardLayoutAutoThresholdFieldLabel": "Mudar para layout compacto a partir deste número de patrocinadores",
    "CardLayoutFullOption": "Completo",
    "CardLayoutCompactOption": "Compacto",
    "ShowBusinessPhonesFieldLabel": "Mostrar telefone comercial",
    "ShowMobilePhoneFieldLabel": "Mostrar número de celular",
    "ShowWorkLocationFieldLabel": "Mostrar local de trabalho",
    "ShowManagerFieldLabel": "Mostrar gerente",
    "UseInformalAddressFieldLabel": "Tratamento informal",

    "ShowWorkLocationFallbackFieldLabel": "Mostrar local de trabalho como fallback",
    "LocationDisplayHintGeoWithFallback": "Cidade e país são combinados em uma única linha geográfica. O local de trabalho só é exibido se não houver dados de cidade/país.",
    "LocationDisplayHintGeoOnly": "Cidade e país são combinados em uma única linha geográfica. O local de trabalho fica oculto.",
    "LocationDisplayHintOfficeOnly": "Apenas o local de trabalho é exibido. Ative cidade e/ou país para mostrar uma linha geográfica.",
    "LocationDisplayHintHidden": "Todos os campos de localização e endereço estão ocultos.",
    "LocationDisplayHintSeparateRows": "Os campos de endereço ativados são combinados em uma única linha clicável.",
    "AdvancedDisplayGroupName": "Opções avançadas de exibição",
    "ManagerOptionsDisabledHint": "Ative a exibição do gerente para configurar campos específicos do gerente.",
    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "URL base da Guest Sponsor API",
    "FunctionClientIdFieldLabel": "ID de cliente da Guest Sponsor API (Registro de aplicativo)",
    "ProxyStatusChecking": "Verificando Guest Sponsor API…",
    "ProxyStatusOk": "Guest Sponsor API acessível",
    "ProxyStatusError": "Guest Sponsor API inacessível",
    "AuthorSectionGroupName": "Sobre a Workoho",
    "AuthorSectionIntro": "Governança do Microsoft 365, identidades e acesso de convidados \u2014 nossa área.",
    "AuthorSectionWebsiteLinkLabel": "Fale conosco",
    "AuthorSectionConsultingText": "Desenvolvemos este Web Part porque é exatamente com isso que trabalhamos todos os dias. Da arquitetura ao rollout, ajudamos organizações a construir uma colaboração segura e escalável no Microsoft 365.",
    "AuthorSectionPartnerPrefix": "A Workoho é",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "parceira Platinum de vendas e implementação.",
    "AuthorSectionPartnerTagline": "O EasyLife 365 automatiza o gerenciamento do ciclo de vida no Teams, sites SharePoint, Viva Engage e outros espaços do Microsoft 365 — incluindo integração de convidados e gerenciamento de patrocinadores.",
    "AuthorSectionSourceCodeLabel": "Código-fonte no GitHub",
    "AuthorSectionVersionLabel": "Versão do web part",
    "NewReleaseAvailableLabel": "Nova versão disponível — abrir no GitHub Releases",
    "ShowSponsorJobTitleFieldLabel": "Mostrar cargo do patrocinador",
    "ShowManagerJobTitleFieldLabel": "Mostrar cargo do responsável",
    "ShowSponsorDepartmentFieldLabel": "Mostrar departamento do patrocinador",
    "ShowManagerDepartmentFieldLabel": "Mostrar departamento do responsável",
    "DepartmentLabel": "Departamento",
    "ShowCityFieldLabel": "Exibir cidade",
    "ShowCountryFieldLabel": "Exibir país",
    "ShowStreetAddressFieldLabel": "Mostrar rua",
    "ShowPostalCodeFieldLabel": "Mostrar CEP",
    "ShowStateFieldLabel": "Mostrar estado/região",
    "AzureMapsSubscriptionKeyFieldLabel": "Chave de assinatura do Azure Maps",
    "ExternalMapProviderFieldLabel": "Provedor de mapas",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "MapProviderNoneOption": "Desativado (sem link de mapa)",
    "AddressMapProviderHint": "Ative pelo menos a cidade e o país — isso é suficiente para qualquer provedor de mapas exibir uma localização relevante.",
    "CityFieldLabel": "Cidade",
    "CountryFieldLabel": "País",
    "CopyCityAriaLabel": "Copiar cidade",
    "CopyCountryAriaLabel": "Copiar país",
    "ShowPresenceFieldLabel": "Exibir status de presença",
    "ShowSponsorPhotoFieldLabel": "Exibir foto do patrocinador",
    "ShowManagerPhotoFieldLabel": "Exibir foto do responsável",
  }
});
