// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function() {
  return {
    "BasicGroupName": "Configurações",
    "ShowTitleFieldLabel": "Mostrar título",
    "TitleFieldLabel": "Título",
    "LoadingMessage": "Carregando seus patrocinadores…",
    "NoSponsorsTitle": "Nenhum patrocinador encontrado",
    "NoSponsorsMessage": "Nenhum patrocinador encontrado para sua conta.",
    "SponsorUnavailableTitle": "Patrocinador indisponível",
    "SponsorUnavailableMessage": "Seu patrocinador/responsável não está mais disponível. Entre em contato com o responsável pelo projeto para que um novo patrocinador/responsável seja atribuído à sua conta.",
    "ErrorMessageTitle": "Ocorreu um erro",
    "ErrorMessage": "Não foi possível carregar as informações do patrocinador. Tente novamente mais tarde.",
    "EditModePlaceholder": "Informações do Patrocinador Convidado — alterne para o modo de exibição para ver os patrocinadores.",
    "GuestOnlyPlaceholder": "Este web part é visível apenas para usuários convidados no modo de exibição.",
    "MockModeFieldLabel": "Sempre exibir patrocinadores demo (modo demo público)",
    "MockModeFieldDescription": "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    "MockModeFieldTooltip": "Quando habilitado, o modo de demonstração aparece apenas na página ao vivo para fins de teste. O modo de edição e visualização não mudam.",
    "MockModePlaceholder": "Informações do Patrocinador Convidado — Modo de demonstração ativo. Alterne para o modo de exibição para ver os dados fictícios.",
    "MockSimulatedHintFieldLabel": "Simular notificação de convidado",
    "MockSimulatedHintNoneOption": "Nenhuma notificação",
    "MockSimulatedHintTeamsAccessPendingOption": "Microsoft Teams ainda não configurado",
    "MockSimulatedHintVersionMismatchOption": "Atualização disponível",
    "MockSimulatedHintSponsorUnavailableOption": "Patrocinador não disponível",
    "MockSimulatedHintNoSponsorsOption": "Nenhum patrocinador encontrado",
    "MaxSponsorCountFieldLabel": "Patrocinadores visíveis",
    "MaxSponsorCountFieldTooltip": "Limita o número de cartões de patrocinador exibidos. Apenas patrocinadores ativos (disponíveis) contam para este limite. Se a conta de um patrocinador atribuído não estiver mais disponível (desabilitada, excluída ou ainda não provisionada), o próximo patrocinador na ordem de prioridade avança automaticamente para preencher o espaço vazio. Isso garante que os convidados sempre vejam o número configurado de contatos disponíveis.",

    "PresenceAvailable": "Disponível",
    "PresenceAvailableIdle": "Disponível, inativo",
    "PresenceAway": "Ausente",
    "PresenceBeRightBack": "Volto já",
    "PresenceBusy": "Ocupado",
    "PresenceBusyIdle": "Ocupado, inativo",
    "PresenceDoNotDisturb": "Não perturbe",
    "PresenceInAMeeting": "Em uma reunião",
    "PresenceInACall": "Em uma chamada",
    "PresencePresenting": "Apresentando",
    "PresenceFocusing": "Em foco",
    "PresenceOutOfOffice": "Fora do escritório",
    "PresenceOutOfOfficeSuffix": ", fora do escritório",
    "PresenceOffline": "Offline",

    "CloseLabel": "Fechar",
    "ContactDetailsAriaLabel": "Detalhes de contato para {0}",
    "ContactActionsAriaLabel": "Ações de contato",
    "ChatTitle": "Iniciar um chat com {name}",
    "EmailTitle": "Enviar e-mail para {name}",
    "CallTitle": "Iniciar uma chamada de áudio com {name}",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Ligar",

    "ContactInfoSection": "Contato",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Telefone comercial",
    "MobileFieldLabel": "Celular",
    "WorkLocationFieldLabel": "Local de trabalho",
    "AddressFieldLabel": "Endereço",
    "StreetAddressFieldLabel": "Rua",
    "PostalCodeFieldLabel": "CEP",
    "StateFieldLabel": "Estado/região",

    "OrganizationSection": "Organização",
    "ReportsToSection": "Reporta-se a",
    "ManagerLabel": "Gerente",

    "CopiedFeedback": "Copiado!",
    "CopyEmailAriaLabel": "Copiar endereço de e-mail",
    "CopyWorkPhoneAriaLabel": "Copiar telefone comercial",
    "CopyMobileAriaLabel": "Copiar número de celular",
    "CopyLocationAriaLabel": "Copiar local de trabalho",
    "CopyAddressAriaLabel": "Copiar endereço",
    "CopyStreetAddressAriaLabel": "Copiar rua",
    "CopyPostalCodeAriaLabel": "Copiar CEP",
    "CopyStateAriaLabel": "Copiar estado/região",
    "AddressMapSectionLabel": "Pré-visualização do mapa",
    "AddressMapLoadingLabel": "Carregando pré-visualização do mapa...",
    "OpenAddressInMapLabel": "Abrir no mapa",

    "TeamsAccessPendingTitle": "Microsoft Teams ainda não configurado",
    "TeamsAccessPendingMessage": "Seu acesso de convidado ao Microsoft Teams nesta organização ainda não foi configurado. Sua própria conta do Teams não é afetada. Peça ao seu patrocinador para adicionar você a uma equipe — depois disso, recursos do Teams como chat, chamadas e reuniões ficarão disponíveis aqui.",
    "TeamsNotReadyChatTooltip": "Chat indisponível aqui — seu acesso de convidado do Teams ainda não foi configurado",
    "TeamsNotReadyCallTooltip": "Chamada indisponível aqui — seu acesso de convidado do Teams ainda não foi configurado",

    "VersionMismatchTitle": "Atualização disponível",
    "VersionMismatchMessage": "Há uma atualização disponível para esta web part. Peça ao seu administrador para garantir que a web part e a Guest Sponsor API estejam executando a mesma versão.",
    "InsufficientPermissionsTitle": "Permissão insuficiente",
    "InsufficientPermissionsMessage": "Não foi possível carregar as informações do patrocinador — uma permissão de serviço necessária não foi concedida. Entre em contato com seu administrador de TI.",

    "GuestNotificationsGroupName": "Notificações para convidados",
    "GuestNotificationsGroupHint": "Controle quais notificações informativas são exibidas para usuários convidados.",
    "ShowTeamsAccessPendingHintLabel": "Exibir aviso «Microsoft Teams ainda não configurado»",
    "ShowVersionMismatchHintLabel": "Exibir aviso «Atualização disponível»",
    "ShowSponsorUnavailableHintLabel": "Exibir aviso «Patrocinador não disponível»",
    "ShowNoSponsorsHintLabel": "Exibir aviso «Nenhum patrocinador encontrado»",
    "DisplayGroupName": "Exibição",
    "CardLayoutFieldLabel": "Layout do cartão",
    "CardLayoutAutoOption": "Automático",
    "CardLayoutAutoThresholdFieldLabel": "Mudar para layout compacto a partir deste número de patrocinadores",
    "CardLayoutFullOption": "Completo",
    "CardLayoutCompactOption": "Compacto",
    "ShowBusinessPhonesFieldLabel": "Mostrar telefone comercial",
    "ShowMobilePhoneFieldLabel": "Mostrar número de celular",
    "ShowWorkLocationFieldLabel": "Mostrar local de trabalho",
    "ShowManagerFieldLabel": "Mostrar gerente",
    "SponsorEligibilityGroupName": "Elegibilidade do patrocinador",
    "SponsorEligibilityGroupHint": "As atribuições de patrocinador no Microsoft Entra são gerenciadas pela sua organização e podem não ser sempre precisas. Esses filtros melhoram a qualidade dos patrocinadores exibidos aos convidados e evitam a divulgação não intencional de informações causada por atribuições incorretas.",
    "SponsorFilterFieldLabel": "O patrocinador deve ser",
    "SponsorFilterTeamsOption": "Licenciado pelo Teams (recomendado)",
    "SponsorFilterExchangeOption": "Licenciado pelo Exchange Online",
    "SponsorFilterAnyOption": "Licenciado (qualquer licença ativa)",
    "RequireUserMailboxFieldLabel": "Exigir tipo de caixa de correio do usuário",
    "UseInformalAddressFieldLabel": "Tratamento informal",

    "LocationDisplayHintSeparateRows": "Os campos de endereço ativados são combinados em uma única linha clicável.",
    "AdvancedDisplayGroupName": "Opções avançadas de exibição",
    "FunctionGroupName": "Guest Sponsor API",
    "FunctionUrlFieldLabel": "URL base",
    "FunctionClientIdFieldLabel": "ID do aplicativo (cliente)",
    "PpClientIdHintLabel": "Onde encontro o ID de cliente?",
    "PpClientIdHintBody": "Copie o ID de cliente (ID do aplicativo) do registro de aplicativo criado durante a configura\u00e7\u00e3o.",
    "FunctionEntraLinkLabel": "Encontrar no Microsoft Entra →",
    "ProxyStatusChecking": "Verificando conexão…",
    "ProxyStatusOk": "Conexão bem-sucedida",
    "ProxyStatusError": "Conexão falhou",
    "PpSetupIntro": "Configuração necessária:",
    "PpSetupRerunHint": "Problema de conexão? Os scripts de configuração são idempotentes \u2014 executá-los novamente com os mesmos parâmetros corrige a maioria dos problemas.",
    "CopyToClipboardLabel": "Copiar",
    "CopiedToClipboardLabel": "Copiado!",
    "AuthorSectionGroupName": "Sobre a Workoho",
    "AuthorSectionIntro": "Governança do Microsoft 365, identidades e acesso de convidados \u2014 nossa área.",
    "AuthorSectionWebsiteLinkLabel": "Fale conosco",
    "AuthorSectionConsultingText": "Desenvolvemos este Web Part porque é exatamente com isso que trabalhamos todos os dias. Da arquitetura ao rollout, ajudamos organizações a construir uma colaboração segura e escalável no Microsoft 365.",
    "AuthorSectionPartnerPrefix": "A Workoho é",
    "AuthorSectionPartnerLinkLabel": "EasyLife 365",
    "AuthorSectionPartnerSuffix": "Parceira Platinum.",
    "AuthorSectionPartnerTagline": "O EasyLife 365 automatiza o gerenciamento do ciclo de vida no Teams, sites SharePoint, Viva Engage e outros espaços do Microsoft 365 — incluindo integração de convidados e gerenciamento de patrocinadores.",
    "AuthorSectionSourceCodeLabel": "Código-fonte",
    "AuthorSectionVersionLabel": "Versão do web part",
    "AuthorSectionDeployToAzureLabel": "Deploy to Azure",
    "DeployToAzureClickHint": "Clique no bot\u00e3o para iniciar a implanta\u00e7\u00e3o:",
    "AuthorSectionDeploymentGuideLabel": "Guia de implantação",
    "NewReleaseAvailableLabel": "Nova versão disponível — abrir no GitHub Releases",
    "ShowSponsorJobTitleFieldLabel": "Mostrar cargo do patrocinador",
    "ShowManagerJobTitleFieldLabel": "Mostrar cargo do responsável",
    "ShowSponsorDepartmentFieldLabel": "Mostrar departamento do patrocinador",
    "ShowManagerDepartmentFieldLabel": "Mostrar departamento do responsável",
    "DepartmentLabel": "Departamento",
    "ShowCityFieldLabel": "Exibir cidade",
    "ShowCountryFieldLabel": "Exibir país",
    "ShowStreetAddressFieldLabel": "Mostrar rua",
    "ShowPostalCodeFieldLabel": "Mostrar CEP",
    "ShowStateFieldLabel": "Mostrar estado/região",
    "AzureMapsSubscriptionKeyFieldLabel": "Chave de assinatura do Azure Maps",    "MapProviderModeAutoLabel": "Modo automático (recomendado)",
    "MapProviderModeManualLabel": "Manual (igual para todos os dispositivos)",
    "MapProviderModeHint": "Escolha um provedor de mapa para cada sistema operacional, incluindo iOS e Android. O link abre no navegador ou no aplicativo do provedor, se instalado.",
    "MapProviderIosLabel": "iOS:",
    "MapProviderAndroidLabel": "Android:",
    "MapProviderWindowsLabel": "Windows:",
    "MapProviderMacOSLabel": "macOS:",
    "MapProviderLinuxLabel": "Linux:",    "ExternalMapProviderFieldLabel": "Provedor de mapas",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderNoneOption": "Desativado (sem link de mapa)",
    "AddressMapProviderHint": "Ative pelo menos a cidade e o país — isso é suficiente para qualquer provedor de mapas exibir uma localização relevante.",
    "AzureMapsPreviewHint": "Adicione a chave de assinatura do Azure Maps para mostrar uma pequena pré-visualização de mapa na seção de contato. Se você implantou a API Guest Sponsor, uma conta do Azure Maps foi incluída — copie a chave das configurações de autenticação. Sem a chave, apenas o link de mapa acima será exibido.",
    "CityFieldLabel": "Cidade",
    "CountryFieldLabel": "País",
    "CopyCityAriaLabel": "Copiar cidade",
    "CopyCountryAriaLabel": "Copiar país",
    "ShowPresenceFieldLabel": "Exibir status de presença",
    "ShowSponsorPhotoFieldLabel": "Exibir foto do patrocinador",
    "ShowManagerPhotoFieldLabel": "Exibir foto do responsável",
    "TitlePlaceholder": "Meus patrocinadores",
    "TitleSizeFieldLabel": "Tamanho do título",
    "TitleSizeH2Option": "Título 2",
    "TitleSizeH3Option": "Título 3",
    "TitleSizeH4Option": "Título 4",
    "TitleSizeNormalOption": "Normal",

    "WelcomeDialogTitle": "Configurar Informações do Patrocinador Convidado",
    "WelcomeDialogBody": "Esta Web Part exibe a cada usuário convidado seus sponsors do Microsoft Entra na página de entrada do SharePoint. Para que a Web Part seja útil, as atribuições de sponsors devem ser gerenciadas ativamente e um processo de ciclo de vida para convidados já deve estar em vigor — ela torna essa responsabilidade visível, mas não substitui a governança subjacente.",
    "WelcomeDialogBroughtToYouBy": "Desenvolvido pela Workoho — especialistas em governança de convidados e gerenciamento de ciclo de vida.",
    "WelcomeDialogWorkohoLinkLabel": "workoho.com",
    "WelcomeDialogNextButton": "Próximo",
    "WelcomeDialogBackButton": "Voltar",
    "WelcomeDialogSkipButton": "Agora não",
    "WelcomeDialogSaveButton": "Salvar",
    "WelcomeDialogSkipApiButton": "Ignorar",
    "InvalidUrlFormat": "Por favor, insira uma URL válida (ex.: my-app.azurewebsites.net)",
    "InvalidGuidFormat": "Por favor, insira um GUID válido (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    "WelcomeDialogSetupTitle": "Pronto em minutos",
    "WelcomeDialogSetupIntro": "Escolha o caminho de implantação. Você pode alternar entre as duas opções a qualquer momento pelas configurações da Web Part.",
    "WelcomeDialogOptionApiTitle": "Usar a API Guest Sponsor",
    "WelcomeDialogOptionApiBody": "Experiência completa com uma Azure Function. Requer configuração única no Azure — recomendado para produção.",
    "WelcomeDialogOptionApiDocsLabel": "Ver guia de configuração",
    "WelcomeDialogDeployToAzureLabel": "Implantar a API no Azure",
    "WelcomeDialogDeployNote": "Esta opção requer que a API Guest Sponsor seja implantada em sua assinatura do Azure. Você pode fazer isso aqui mesmo \u2014 leva apenas alguns minutos.",
    "WelcomeDialogSetupStep1Label": "Criar registro do aplicativo",
    "WelcomeDialogSetupStep3Label": "Conceder permissões do Graph",
    "WelcomeDialogSetupPwshHint": "PowerShell 7+:",
    "WelcomeDialogSetupStep3Hint": "Usa valores das etapas 1 e 2",
    "WelcomeDialogConnectApiTitle": "Conectar a API Guest Sponsor",
    "WelcomeDialogConnectApiIntro": "Opcionalmente, insira os detalhes de conexão da sua API Guest Sponsor. Você pode adicioná-los mais tarde nas configurações da Web Part.",
    "WelcomeDialogOptionDemoTitle": "Explorar no modo de demonstração",
    "WelcomeDialogOptionDemoBody": "Experimente o Web Part com dados de sponsors simulados — sem configuração do Azure. Alterne para a API real nas configurações a qualquer momento.",
    "WelcomeDialogFunctionUrlRequired": "Informe a URL base da API Guest Sponsor.",
    "WelcomeDialogDoneApiTitle": "API configurada!",
    "WelcomeDialogDoneApiSkippedTitle": "Quase lá!",
    "WelcomeDialogDoneApiSkippedBody": "Nenhuma credencial foi inserida. Abra as configurações da web part para conectar a API do Patrocinador Convidado quando estiver pronto.",
    "WelcomeDialogDoneApiBody": "A conexão com a API Guest Sponsor foi salva. Lembre-se de salvar a página para que suas configurações sejam aplicadas para todos.",
    "WelcomeDialogDoneDemoTitle": "Modo de demonstração ativado!",
    "WelcomeDialogDoneDemoBody": "Alterne para o modo de exibição para ver o Web Part com cartões de sponsors simulados. Conecte a API Guest Sponsor nas configurações quando estiver pronto.",
    "WelcomeDialogDismissButton": "Vamos lá",
    "PpSectionLivePage": "▶ Página ao vivo",
    "PpSectionDemoMode": "🧪 Modo demonstração",
    "PpSectionCardLayout": "🗂️ Layout do cartão",
    "PpSectionProfileFields": "👤 Campos de perfil",
    "PpSectionPhone": "📞 Números de telefone",
    "PpSectionWorkLocation": "📍 Localização do trabalho",
    "PpSectionAddress": "🏠 Endereço postal",
    "PpSectionMapLink": "🧭 Link do mapa",
    "PpSectionMapPreview": "🗺️ Pré-visualização de mapa em linha"
  }
});
