define([], function() {
  return {
    "PropertyPaneDescription": "Configure o web part de Informa\u00e7\u00f5es do Patrocinador Convidado.",
    "BasicGroupName": "Configura\u00e7\u00f5es",
    "TitleFieldLabel": "T\u00edtulo",
    "LoadingMessage": "Carregando seus patrocinadores\u2026",
    "NoSponsorsMessage": "Nenhum patrocinador encontrado para sua conta.",
    "SponsorUnavailableMessage": "Seu patrocinador/respons\u00e1vel n\u00e3o est\u00e1 mais dispon\u00edvel. Entre em contato com o respons\u00e1vel pelo projeto para que um novo patrocinador/respons\u00e1vel seja atribu\u00eddo \u00e0 sua conta.",
    "ErrorMessage": "N\u00e3o foi poss\u00edvel carregar as informa\u00e7\u00f5es do patrocinador. Tente novamente mais tarde.",
    "EditModePlaceholder": "Informa\u00e7\u00f5es do Patrocinador Convidado \u2014 alterne para o modo de exibi\u00e7\u00e3o para ver os patrocinadores.",
    "GuestOnlyPlaceholder": "Este web part \u00e9 vis\u00edvel apenas para usu\u00e1rios convidados no modo de exibi\u00e7\u00e3o.",
    "MockModeFieldLabel": "Modo de demonstra\u00e7\u00e3o (dados fict\u00edcios)",
    "MockModePlaceholder": "Informa\u00e7\u00f5es do Patrocinador Convidado \u2014 Modo de demonstra\u00e7\u00e3o ativo. Alterne para o modo de exibi\u00e7\u00e3o para ver os dados fict\u00edcios.",

    "PresenceAvailable": "Dispon\u00edvel",
    "PresenceAvailableIdle": "Dispon\u00edvel, inativo",
    "PresenceAway": "Ausente",
    "PresenceBeRightBack": "Volto j\u00e1",
    "PresenceBusy": "Ocupado",
    "PresenceBusyIdle": "Ocupado, inativo",
    "PresenceDoNotDisturb": "N\u00e3o perturbe",
    "PresenceInAMeeting": "Em uma reuni\u00e3o",
    "PresenceInACall": "Em uma chamada",
    "PresencePresenting": "Apresentando",
    "PresenceFocusing": "Em foco",
    "PresenceOutOfOffice": "Fora do escrit\u00f3rio",
    "PresenceOutOfOfficeSuffix": ", fora do escrit\u00f3rio",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Detalhes de contato para {0}",
    "ContactActionsAriaLabel": "A\u00e7\u00f5es de contato",
    "ChatTitle": "Conversar no Microsoft Teams",
    "EmailTitle": "Enviar e-mail",
    "CallTitle": "Chamada de \u00e1udio no Microsoft Teams",
    "ChatLabel": "Chat",
    "EmailLabel": "E-mail",
    "CallLabel": "Ligar",

    "ContactInfoSection": "Informa\u00e7\u00f5es de contato",
    "EmailFieldLabel": "E-mail",
    "WorkPhoneFieldLabel": "Telefone comercial",
    "MobileFieldLabel": "Celular",
    "WorkLocationFieldLabel": "Local de trabalho",
    "StreetAddressFieldLabel": "Rua",
    "PostalCodeFieldLabel": "CEP",
    "StateFieldLabel": "Estado/região",

    "OrganizationSection": "Organiza\u00e7\u00e3o",
    "ManagerLabel": "Gerente",

    "CopiedFeedback": "Copiado!",
    "CopyEmailAriaLabel": "Copiar endere\u00e7o de e-mail",
    "CopyWorkPhoneAriaLabel": "Copiar telefone comercial",
    "CopyMobileAriaLabel": "Copiar n\u00famero de celular",
    "CopyLocationAriaLabel": "Copiar local de trabalho",
    "CopyStreetAddressAriaLabel": "Copiar rua",
    "CopyPostalCodeAriaLabel": "Copiar CEP",
    "CopyStateAriaLabel": "Copiar estado/região",
    "AddressMapSectionLabel": "Pre-visualizacao do mapa",
    "AddressMapLoadingLabel": "Carregando pre-visualizacao do mapa...",
    "OpenAddressInMapLabel": "Abrir no mapa",

    "TeamsAccessPendingTitle": "Microsoft Teams ainda n\u00e3o configurado",
    "TeamsAccessPendingMessage": "Seu acesso de convidado ao Microsoft Teams nesta organiza\u00e7\u00e3o ainda n\u00e3o foi configurado. Sua pr\u00f3pria conta do Teams n\u00e3o \u00e9 afetada. Pe\u00e7a ao seu patrocinador para adicion\u00e1-lo a uma equipe \u2014 depois disso, recursos do Teams como chat, chamadas e reuni\u00f5es ficar\u00e3o dispon\u00edveis aqui.",
    "TeamsNotReadyChatTooltip": "Chat indispon\u00edvel aqui \u2014 seu acesso de convidado do Teams ainda n\u00e3o foi configurado",
    "TeamsNotReadyCallTooltip": "Chamada indispon\u00edvel aqui \u2014 seu acesso de convidado do Teams ainda n\u00e3o foi configurado",

    "DisplayGroupName": "Exibi\u00e7\u00e3o",
    "ShowBusinessPhonesFieldLabel": "Mostrar telefone comercial",
    "ShowMobilePhoneFieldLabel": "Mostrar n\u00famero de celular",
    "ShowWorkLocationFieldLabel": "Mostrar local de trabalho",
    "ShowManagerFieldLabel": "Mostrar gerente",
    "UseInformalAddressFieldLabel": "Tratamento informal",

    "ShowWorkLocationFallbackFieldLabel": "Mostrar local de trabalho como fallback",
    "LocationDisplayHintGeoWithFallback": "Cidade e país são combinados em uma única linha geográfica. O local de trabalho só é exibido se não houver dados de cidade/país.",
    "LocationDisplayHintGeoOnly": "Cidade e país são combinados em uma única linha geográfica. O local de trabalho fica oculto.",
    "LocationDisplayHintOfficeOnly": "Apenas o local de trabalho é exibido. Ative cidade e/ou país para mostrar uma linha geográfica.",
    "LocationDisplayHintHidden": "Todas as informações de localização estão ocultas.",
    "AddressMapFallbackHint": "Se nenhuma chave do Azure Maps estiver configurada ou a busca falhar, um link externo de mapa sera exibido.",
    "LocationDisplayHintAddressEnabled": "Os campos de endereco estruturado estao habilitados e podem ser exibidos em linhas adicionais.",
    "LocationDisplayHintSeparateRows": "Cidade/pais e local de trabalho sao exibidos em linhas separadas quando habilitados.",
    "AdvancedDisplayGroupName": "Opções avançadas de exibição",
    "ManagerOptionsDisabledHint": "Ative a exibição do gerente para configurar campos específicos do gerente.",
    "FunctionGroupName": "Azure Function",
    "FunctionUrlFieldLabel": "URL da API de patrocinadores (Azure Function)",
    "FunctionClientIdFieldLabel": "ID do cliente da API de patrocinadores (Registro de aplicativo Azure Function)",
    "ProxyStatusChecking": "Verificando Azure Function\u2026",
    "ProxyStatusOk": "Azure Function acess\u00edvel",
    "ProxyStatusError": "Azure Function inacess\u00edvel",
    "ShowSponsorJobTitleFieldLabel": "Mostrar cargo do patrocinador",
    "ShowManagerJobTitleFieldLabel": "Mostrar cargo do respons\u00e1vel",
    "ShowSponsorDepartmentFieldLabel": "Mostrar departamento do patrocinador",
    "ShowManagerDepartmentFieldLabel": "Mostrar departamento do respons\u00e1vel",
    "DepartmentLabel": "Departamento",
    "ShowCityFieldLabel": "Exibir cidade",
    "ShowCountryFieldLabel": "Exibir pa\u00eds",
    "ShowStructuredAddressFieldLabel": "Mostrar endereco estruturado",
    "ShowStreetAddressFieldLabel": "Mostrar rua",
    "ShowPostalCodeFieldLabel": "Mostrar CEP",
    "ShowStateFieldLabel": "Mostrar estado/regiao",
    "ShowAddressMapFieldLabel": "Mostrar pre-visualizacao do mapa de endereco",
    "AzureMapsSubscriptionKeyFieldLabel": "Chave de assinatura do Azure Maps",
    "ExternalMapProviderFieldLabel": "Provedor de mapa externo (fallback)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Cidade",
    "CountryFieldLabel": "Pa\u00eds",
    "CopyCityAriaLabel": "Copiar cidade",
    "CopyCountryAriaLabel": "Copiar pa\u00eds",
    "ShowPresenceFieldLabel": "Exibir status de presen\u00e7a"
  }
});
