// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Definições",
    ShowTitleFieldLabel: "Mostrar título",
    TitleFieldLabel: "Título",
    LoadingMessage: "A carregar os seus patrocinadores…",
    NoSponsorsTitle: "Nenhum patrocinador encontrado",
    NoSponsorsMessage: "Nenhum patrocinador encontrado para a sua conta.",
    SponsorUnavailableTitle: "Patrocinador indisponível",
    SponsorUnavailableMessage:
      "O seu patrocinador/responsável já não está disponível. Contacte o responsável pelo projeto para que seja atribuído um novo patrocinador/responsável à sua conta.",
    ErrorMessageTitle: "Ocorreu um erro",
    ErrorMessage: "Não foi possível carregar as informações do patrocinador. Tente novamente mais tarde.",
    EditModePlaceholder:
      "Informações do Patrocinador Convidado — mude para o modo de vista para ver os patrocinadores.",
    GuestOnlyPlaceholder: "Esta web part é visível apenas para utilizadores convidados no modo de vista.",
    MockModeFieldLabel: "Mostrar sempre patrocinadores de demonstração (modo de demonstração público)",
    MockModeFieldDescription: "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    MockModeFieldTooltip:
      "Quando ativado, o modo de demonstração aparece apenas na página ao vivo para fins de teste. O modo de edição e visualização não mudam.",
    MockModePlaceholder:
      "Informações do Patrocinador Convidado — Modo de demonstração ativo. Mude para o modo de vista para ver os dados fictícios.",
    MockSimulatedHintFieldLabel: "Simular notificação de convidado",
    MockSimulatedHintNoneOption: "Nenhuma notificação",
    MockSimulatedHintTeamsAccessPendingOption: "Microsoft Teams ainda não configurado",
    MockSimulatedHintVersionMismatchOption: "Atualização disponível",
    MockSimulatedHintSponsorUnavailableOption: "Patrocinador não disponível",
    MockSimulatedHintNoSponsorsOption: "Nenhum patrocinador encontrado",
    MaxSponsorCountFieldLabel: "Patrocinadores visíveis",
    MaxSponsorCountFieldTooltip:
      "Limita o número de cartões de patrocinador apresentados. Apenas patrocinadores ativos (disponíveis) contam para este limite. Se a conta de um patrocinador atribuído deixar de estar disponível (desativada, eliminada ou ainda não aprovisionada), o patrocinador seguinte por ordem de prioridade avança automaticamente para preencher o lugar. Isto garante que os convidados veem sempre o número configurado de contactos disponíveis.",
    PresenceAvailable: "Disponível",
    PresenceAvailableIdle: "Disponível, inativo",
    PresenceAway: "Ausente",
    PresenceBeRightBack: "Volto já",
    PresenceBusy: "Ocupado",
    PresenceBusyIdle: "Ocupado, inativo",
    PresenceDoNotDisturb: "Não perturbe",
    PresenceInAMeeting: "Numa reunião",
    PresenceInACall: "Numa chamada",
    PresencePresenting: "A apresentar",
    PresenceFocusing: "Em foco",
    PresenceOutOfOffice: "Fora do escritório",
    PresenceOutOfOfficeSuffix: ", fora do escritório",
    PresenceOffline: "Offline",
    ContactDetailsAriaLabel: "Detalhes de contacto de {0}",
    ContactActionsAriaLabel: "Ações de contacto",
    CloseLabel: "Fechar",
    ChatTitle: "Iniciar um chat com {name}",
    EmailTitle: "Enviar e-mail para {name}",
    CallTitle: "Iniciar uma chamada de áudio com {name}",
    ChatLabel: "Chat",
    EmailLabel: "E-mail",
    CallLabel: "Ligar",
    ContactInfoSection: "Contacto",
    EmailFieldLabel: "E-mail",
    WorkPhoneFieldLabel: "Telefone comercial",
    MobileFieldLabel: "Telemóvel",
    WorkLocationFieldLabel: "Local de trabalho",
    AddressFieldLabel: "Endereço",
    StreetAddressFieldLabel: "Rua",
    PostalCodeFieldLabel: "Código postal",
    StateFieldLabel: "Distrito/Região",
    OrganizationSection: "Organização",
    ReportsToSection: "Reporta a",
    ManagerLabel: "Gestor",
    CopiedFeedback: "Copiado!",
    CopyEmailAriaLabel: "Copiar endereço de e-mail",
    CopyWorkPhoneAriaLabel: "Copiar telefone comercial",
    CopyMobileAriaLabel: "Copiar número de telemóvel",
    CopyLocationAriaLabel: "Copiar local de trabalho",
    CopyAddressAriaLabel: "Copiar endereço",
    CopyStreetAddressAriaLabel: "Copiar rua",
    CopyPostalCodeAriaLabel: "Copiar código postal",
    CopyStateAriaLabel: "Copiar distrito/região",
    AddressMapSectionLabel: "Pré-visualização do mapa",
    AddressMapLoadingLabel: "A carregar pré-visualização do mapa...",
    OpenAddressInMapLabel: "Abrir no mapa",
    TeamsAccessPendingTitle: "Microsoft Teams ainda não configurado",
    TeamsAccessPendingMessage:
      "O seu acesso de convidado ao Microsoft Teams nesta organização ainda não foi configurado. A sua própria conta do Teams não é afetada. Peça ao seu patrocinador para o adicionar a uma equipa — depois disso, funcionalidades do Teams como chat, chamadas e reuniões ficarão disponíveis aqui.",
    TeamsNotReadyChatTooltip: "Chat indisponível aqui — o seu acesso de convidado do Teams ainda não foi configurado",
    TeamsNotReadyCallTooltip:
      "Chamada indisponível aqui — o seu acesso de convidado do Teams ainda não foi configurado",
    VersionMismatchTitle: "Atualização disponível",
    VersionMismatchMessage:
      "Há uma atualização disponível para esta web part. Peça ao seu administrador para garantir que a web part e a Guest Sponsor API estão a executar a mesma versão.",
    InsufficientPermissionsTitle: "Permissão insuficiente",
    InsufficientPermissionsMessage:
      "Não foi possível carregar as informações do patrocinador — uma permissão de serviço necessária não foi concedida. Contacte o seu administrador de TI.",
    ServiceAuthorizationIssueTitle: "Problema temporário do serviço",
    ServiceAuthorizationIssueMessage:
      "Não foi possível carregar as informações do patrocinador porque o serviço de patrocinadores não conseguiu concluir uma etapa de autorização interna. Tente novamente dentro de instantes. Se o problema persistir, contacte o seu administrador de TI.",
    GuestNotificationsGroupName: "Notificações para convidados",
    GuestNotificationsGroupHint: "Controle quais notificações informativas são apresentadas a utilizadores convidados.",
    ShowTeamsAccessPendingHintLabel: "Mostrar aviso «Microsoft Teams ainda não configurado»",
    ShowVersionMismatchHintLabel: "Mostrar aviso «Atualização disponível»",
    ShowSponsorUnavailableHintLabel: "Mostrar aviso «Patrocinador não disponível»",
    ShowNoSponsorsHintLabel: "Mostrar aviso «Nenhum patrocinador encontrado»",
    DisplayGroupName: "Vista",
    CardLayoutFieldLabel: "Layout do cartão",
    CardLayoutAutoOption: "Automático",
    CardLayoutAutoThresholdFieldLabel: "Mudar para layout compacto a partir deste número de patrocinadores",
    CardLayoutFullOption: "Completo",
    CardLayoutCompactOption: "Compacto",
    ShowBusinessPhonesFieldLabel: "Mostrar telefone comercial",
    ShowMobilePhoneFieldLabel: "Mostrar número de telemóvel",
    ShowWorkLocationFieldLabel: "Mostrar local de trabalho",
    ShowStreetAddressFieldLabel: "Mostrar rua",
    ShowPostalCodeFieldLabel: "Mostrar código postal",
    ShowStateFieldLabel: "Mostrar distrito/região",
    AzureMapsSubscriptionKeyFieldLabel: "Chave de subscrição do Azure Maps",
    MapProviderModeAutoLabel: "Modo automático (recomendado)",
    MapProviderModeManualLabel: "Manual (igual para todos os dispositivos)",
    MapProviderModeHint:
      "Escolha um fornecedor de mapa para cada sistema operativo, incluindo iOS e Android. O link abre no browser ou na aplicação do fornecedor, se instalada.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Fornecedor de mapas",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Desativado (sem link de mapa)",
    AddressMapProviderHint:
      "Ative pelo menos a cidade e o país — isso é suficiente para qualquer fornecedor de mapas apresentar uma localização relevante.",
    AzureMapsPreviewHint:
      "Adicione a chave de subscrição do Azure Maps para mostrar uma pequena pré-visualização de mapa na secção de contacto. Se implementou a API Guest Sponsor, uma conta do Azure Maps foi incluída — copie a chave das definições de autenticação. Sem a chave, apenas o link de mapa acima será apresentado.",
    ShowManagerFieldLabel: "Mostrar gestor",
    UseInformalAddressFieldLabel: "Tratamento informal",
    SponsorEligibilityGroupName: "Elegibilidade do patrocinador",
    SponsorEligibilityGroupHint:
      "As atribuições de patrocinador no Microsoft Entra são geridas pela sua organização e podem não ser sempre precisas. Estes filtros melhoram a qualidade dos patrocinadores apresentados aos convidados e evitam a divulgação não intencional de informações causada por atribuições incorretas.",
    SponsorFilterFieldLabel: "O patrocinador deve ser",
    SponsorFilterTeamsOption: "Licenciado pelo Teams (recomendado)",
    SponsorFilterExchangeOption: "Licenciado pelo Exchange Online",
    SponsorFilterAnyOption: "Licenciado (qualquer licença ativa)",
    RequireUserMailboxFieldLabel: "Exigir tipo de caixa de correio do utilizador",
    LocationDisplayHintSeparateRows: "Os campos de endereço ativados são combinados numa única linha clicável.",
    AdvancedDisplayGroupName: "Opções avançadas de visualização",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "URL base",
    WebPartClientIdFieldLabel: "ID da aplicação (cliente)",
    SessionCacheTtlMinutesFieldLabel: "Duração da cache de sessão (minutos)",
    PpClientIdHintLabel: "Onde encontro o ID de cliente?",
    PpClientIdHintBody:
      "Copie o ID de cliente (ID da aplicação) do registo da aplicação criado durante a configuração.",
    FunctionEntraLinkLabel: "Encontrar no Microsoft Entra →",
    ProxyStatusChecking: "A verificar ligação…",
    ProxyStatusOk: "Ligação bem-sucedida",
    ProxyStatusError: "Falha na ligação",
    PpSetupIntro: "Configuração necessária:",
    PpSetupRerunHint:
      "Problema de ligação? O script de configuração é idempotente — executá-lo novamente com os mesmos parâmetros corrige a maioria dos problemas.",
    CopyToClipboardLabel: "Copiar",
    CopiedToClipboardLabel: "Copiado!",
    AuthorSectionGroupName: "Sobre",
    AuthorSectionCreatedBy: "Criado e mantido por",
    AuthorSectionIntro: "Governança do Microsoft 365, identidades e acesso de convidados — a nossa área.",
    AuthorSectionWebsiteLinkLabel: "Fale connosco",
    AuthorSectionConsultingText:
      "Desenvolvemos esta Web Part porque é exatamente com isso que trabalhamos todos os dias. Da arquitetura à implementação, ajudamos organizações a construir uma colaboração segura e escalável no Microsoft 365.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Versão da web part",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Clique no botão para iniciar a implementação:",
    AuthorSectionDeploymentGuideLabel: "Guia de implementação",
    NewReleaseAvailableLabel: "Nova versão disponível — abrir no GitHub Releases",
    DiagnosticsGroupName: "Acessibilidade para convidados",
    DiagnosticsGroupHint:
      "Verifica se o pacote JavaScript da web part e o site de página de destino estão acessíveis para utilizadores convidados B2B.",
    DiagnosticsChecking: "A verificar acessibilidade para convidados…",
    DiagnosticsRetryButtonLabel: "Executar verificações novamente",
    DiagPublicCdnOk:
      "Pacote distribuído via CDN pública do Office 365 — entrega anónima, nenhuma permissão especial necessária para convidados.",
    DiagPrivateCdnInfo:
      "Pacote distribuído via CDN privada do Office 365 — convidados com acesso de leitura ao site podem carregá-lo. Certifique-se de que o site de página de destino está acessível para convidados.",
    DiagSiteColCatalogOk:
      "Pacote distribuído a partir do catálogo de aplicações do conjunto de sites — o acesso de convidados segue as permissões próprias do site.",
    DiagTenantCatalogEveryoneOk:
      "Pacote distribuído a partir do catálogo de aplicações do inquilino. O grupo 'Todos' tem acesso de leitura ao catálogo — utilizadores convidados podem carregar o pacote.",
    DiagTenantCatalogEveryoneDenied:
      "Pacote distribuído a partir do catálogo de aplicações do inquilino, mas 'Todos' não tem acesso de leitura. Utilizadores convidados não conseguem carregar a web part. Recomendação: ative a CDN pública do Office 365 ou conceda acesso de Visitante a 'Todos' no site do catálogo.",
    DiagTenantCatalogEveryoneUnknown:
      "Pacote distribuído a partir do catálogo de aplicações do inquilino. Não foi possível verificar se 'Todos' tem acesso de leitura (permissões insuficientes). Verifique manualmente se os convidados conseguem aceder ao catálogo ou ative a CDN pública do Office 365.",
    DiagAssetSourceUnknown:
      "Não foi possível determinar a origem do pacote. Verifique manualmente se os utilizadores convidados conseguem aceder ao pacote JavaScript da web part.",
    DiagSiteEveryoneOk:
      "'Todos' está no grupo de Visitantes do site — convidados recém-aceites obtêm acesso de leitura imediato à página de destino.",
    DiagSiteEveryoneMissing:
      "'Todos' não está no grupo de Visitantes do site. O acesso de convidados pode depender de um grupo de segurança Entra estático (aceitável) ou dinâmico (até 24 horas de atraso para novos convidados). Se nenhum grupo inclusivo de convidados estiver configurado, os convidados verão uma página de acesso negado.",
    DiagSiteEveryoneUnknown:
      "Não foi possível verificar as permissões de visitante do site. Certifique-se de que os utilizadores convidados têm pelo menos acesso de leitura a este site.",
    ShowSponsorJobTitleFieldLabel: "Mostrar cargo do patrocinador",
    ShowManagerJobTitleFieldLabel: "Mostrar cargo do responsável",
    ShowSponsorDepartmentFieldLabel: "Mostrar departamento do patrocinador",
    ShowManagerDepartmentFieldLabel: "Mostrar departamento do responsável",
    DepartmentLabel: "Departamento",
    ShowCityFieldLabel: "Mostrar cidade",
    ShowCountryFieldLabel: "Mostrar país",
    CityFieldLabel: "Cidade",
    CountryFieldLabel: "País",
    CopyCityAriaLabel: "Copiar cidade",
    CopyCountryAriaLabel: "Copiar país",
    ShowPresenceFieldLabel: "Mostrar estado de presença",
    ShowSponsorPhotoFieldLabel: "Mostrar foto do patrocinador",
    ShowManagerPhotoFieldLabel: "Mostrar foto do responsável",
    TitlePlaceholder: "Os meus patrocinadores",
    TitleSizeFieldLabel: "Tamanho do título",
    TitleSizeH2Option: "Título 2",
    TitleSizeH3Option: "Título 3",
    TitleSizeH4Option: "Título 4",
    TitleSizeNormalOption: "Normal",
    WelcomeDialogTitle: "Configurar Informações do Patrocinador Convidado",
    WelcomeDialogBody:
      "Esta Web Part apresenta a cada utilizador convidado os seus sponsors do Microsoft Entra na página de entrada do SharePoint. Para que a Web Part seja útil, as atribuições de sponsors devem ser geridas ativamente e um processo de ciclo de vida para convidados já deve estar em vigor — ela torna essa responsabilidade visível, mas não substitui a governança subjacente.",
    WelcomeDialogBroughtToYouBy:
      "Desenvolvido pela Workoho — especialistas em governança de convidados e gestão do ciclo de vida.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Vamos lá",
    WelcomeDialogNextButton: "Seguinte",
    WelcomeDialogBackButton: "Anterior",
    WelcomeDialogSkipButton: "Agora não",
    WelcomeDialogSaveButton: "Guardar",
    WelcomeDialogSkipApiButton: "Ignorar",
    InvalidUrlFormat: "Por favor, introduza um URL válido (ex.: my-app.azurewebsites.net)",
    InvalidGuidFormat: "Por favor, introduza um GUID válido (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Escolha o seu caminho de configuração",
    WelcomeDialogSetupIntro:
      "Escolha o caminho de implementação. Pode alternar entre as duas opções a qualquer momento pelas definições da Web Part.",
    WelcomeDialogOptionApiTitle: "Usar a API Guest Sponsor",
    WelcomeDialogOptionApiBody:
      "Experiência completa com uma Azure Function. Requer configuração única no Azure — recomendado para produção.",
    WelcomeDialogOptionApiDocsLabel: "Ver guia de configuração",
    WelcomeDialogSetupGuideNote:
      "Este comando é um atalho. Antes de o executar, leia o guia de configuração para perceber o que faz.",
    WelcomeDialogDeployToAzureLabel: "Implementar a API no Azure",
    WelcomeDialogDeployNote:
      "Esta opção requer que a API Guest Sponsor seja implementada na sua subscrição do Azure. Pode fazê-lo aqui mesmo — demora apenas alguns minutos.",
    WelcomeDialogPreflightTitle: "Before deployment, the installer checks:",
    WelcomeDialogPreflightTools: "PowerShell, Azure CLI, Azure Developer CLI, and Bicep support.",
    WelcomeDialogPreflightSignIn: "Azure sign-in and the target subscription.",
    WelcomeDialogPreflightRoles: "Azure RBAC and Entra roles, with a copy/paste request if anything is missing.",
    WelcomeDialogSetupStepsOrderHint: "Conclua estes passos por ordem:",
    WelcomeDialogSetupStep1Label: "Criar registo da aplicação",
    WelcomeDialogSetupStep2Hint: "Usa o Registo de Aplicação criado no passo 1",
    WelcomeDialogSetupStep3Label: "Conceder permissões do Graph",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupShellHint: "macOS/Linux shell:",
    WelcomeDialogUseShellCommandLabel: "macOS/Linux without PowerShell?",
    WelcomeDialogUsePowerShellCommandLabel: "Use PowerShell command",
    WelcomeDialogSetupStep3Hint: "Usa o Registo de Aplicação (passo 1) e o URL da Function App (passo 2)",
    ViewScriptSourceLabel: "Inspecionar script",
    WelcomeDialogConnectApiTitle: "Introduza os detalhes de ligação à API",
    WelcomeDialogConnectApiIntro:
      "Introduza os detalhes de ligação da sua API Guest Sponsor. Pode ignorar este passo por agora e adicioná-los mais tarde nas definições da Web Part.",
    WelcomeDialogUrlHintLabel: "Onde encontrar o URL?",
    WelcomeDialogUrlHintBody:
      "Copie o URL da Function App no portal do Azure após a implementação. Aceda à sua Function App → Descrição Geral → Domínio predefinido.",
    WelcomeDialogOptionDemoTitle: "Explorar no modo de demonstração",
    WelcomeDialogOptionDemoBody:
      "Experimente a Web Part com dados de sponsors simulados — sem configuração do Azure. Alterne para a API real nas definições a qualquer momento.",
    WelcomeDialogFunctionUrlRequired: "Indique o URL base da API Guest Sponsor.",
    WelcomeDialogDoneApiTitle: "API configurada!",
    WelcomeDialogDoneApiBody:
      "A ligação com a API Guest Sponsor foi guardada. Lembre-se de guardar a página para que as suas definições sejam aplicadas para todos.",
    WelcomeDialogDoneApiSkippedTitle: "Quase lá!",
    WelcomeDialogDoneApiSkippedBody:
      "Nenhuma credencial foi introduzida. Para concluir a configuração: abra as definições da web part, introduza o URL de base e o ID de cliente em Guest Sponsor API e guarde a página.",
    WelcomeDialogDoneDemoTitle: "Modo de demonstração ativado!",
    WelcomeDialogDoneDemoBody:
      "Mude para o modo de vista para ver a Web Part com cartões de sponsors simulados. Ligue a API Guest Sponsor nas definições quando estiver pronto.",
    PpSectionLivePage: "▶ Página ao vivo",
    PpSectionDemoMode: "🧪 Modo demonstração",
    PpSectionCardLayout: "🗂️ Layout do cartão",
    PpSectionProfileFields: "👤 Campos de perfil",
    PpSectionPhone: "📞 Números de telefone",
    PpSectionWorkLocation: "📍 Localização do trabalho",
    PpSectionAddress: "🏠 Endereço postal",
    PpSectionMapLink: "🧭 Link do mapa",
    PpSectionMapPreview: "🗺️ Pré-visualização de mapa em linha"
  };
});
