// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Setări",
    ShowTitleFieldLabel: "Afișați titlul",
    TitleFieldLabel: "Titlu",
    LoadingMessage: "Se încarcă sponsorii…",
    NoSponsorsTitle: "Nu s-au găsit sponsori",
    NoSponsorsMessage: "Nu s-au găsit sponsori pentru contul dumneavoastră.",
    SponsorUnavailableTitle: "Sponsorul nu este disponibil",
    SponsorUnavailableMessage:
      "Sponsorul dumneavoastră nu mai este disponibil. Vă rugăm să contactați persoana responsabilă din proiect pentru a vă fi atribuit un nou sponsor.",
    ErrorMessageTitle: "A apărut o eroare",
    ErrorMessage: "Nu s-au putut încărca informațiile despre sponsor. Vă rugăm să încercați din nou mai târziu.",
    EditModePlaceholder:
      "Informații despre sponsorul invitat — comutați în modul de vizualizare pentru a vedea sponsorii.",
    GuestOnlyPlaceholder:
      "Această componentă web este vizibilă numai pentru utilizatorii invitați în modul de vizualizare.",
    MockModeFieldLabel: "Activați modul demo public pentru utilizatorii interni",
    MockModeFieldDescription:
      "Se aplică numai paginii live pentru vizitatori. În modul de editare, previzualizarea nu se modifică. Activați această opțiune pentru a testa componenta web cu sponsori simulați pentru utilizatorii interni din organizația dvs.; când este dezactivată, numai utilizatorii invitați văd conținutul sponsorilor.",
    MockModeFieldTooltip:
      "Când este activat, modul demo apare pe pagina live doar pentru testare. Modul de editare și previzualizarea rămân nemodificate.",
    MockModePlaceholder:
      "Informații despre sponsorul invitat — Modul demo este activ. Comutați în modul de vizualizare pentru a vedea sponsorii simulați.",
    MockSimulatedHintFieldLabel: "Simulați o notificare pentru invitat",
    MockSimulatedHintNoneOption: "Niciuna (fără notificare)",
    MockSimulatedHintTeamsAccessPendingOption: "Teams nu a fost configurat încă",
    MockSimulatedHintVersionMismatchOption: "Actualizare disponibilă",
    MockSimulatedHintSponsorUnavailableOption: "Sponsorul nu este disponibil",
    MockSimulatedHintNoSponsorsOption: "Nu s-au găsit sponsori",
    MaxSponsorCountFieldLabel: "Sponsori vizibili",
    MaxSponsorCountFieldTooltip:
      "Limitează numărul de carduri de sponsor active afișate. Numai sponsorii activi (disponibili) sunt luați în calcul pentru această limită. Dacă contul unui sponsor atribuit devine indisponibil (dezactivat, șters sau neaprovizionat), următorul sponsor din ordinea de prioritate avansează automat pentru a ocupa locul liber. Astfel, invitații văd întotdeauna numărul configurat de contacte disponibile.",
    PresenceAvailable: "Disponibil",
    PresenceAvailableIdle: "Disponibil, inactiv",
    PresenceAway: "Absent",
    PresenceBeRightBack: "Revin imediat",
    PresenceBusy: "Ocupat",
    PresenceBusyIdle: "Ocupat, inactiv",
    PresenceDoNotDisturb: "Nu deranjați",
    PresenceInAMeeting: "În ședință",
    PresenceInACall: "În apel",
    PresencePresenting: "Prezintă",
    PresenceFocusing: "Concentrat",
    PresenceOutOfOffice: "În afara biroului",
    PresenceOutOfOfficeSuffix: ", în afara biroului",
    PresenceOffline: "Offline",
    ContactDetailsAriaLabel: "Detalii de contact pentru {0}",
    ContactActionsAriaLabel: "Acțiuni de contact",
    CloseLabel: "Închidere",
    ChatTitle: "Porniți un chat cu {name}",
    EmailTitle: "Trimiteți un e-mail la {name}",
    CallTitle: "Porniți un apel audio cu {name}",
    ChatLabel: "Chat",
    EmailLabel: "E-mail",
    CallLabel: "Apel",
    ContactInfoSection: "Contact",
    EmailFieldLabel: "E-mail",
    WorkPhoneFieldLabel: "Telefon de serviciu",
    MobileFieldLabel: "Mobil",
    WorkLocationFieldLabel: "Locație de muncă",
    AddressFieldLabel: "Adresă",
    StreetAddressFieldLabel: "Stradă",
    PostalCodeFieldLabel: "Cod poștal",
    StateFieldLabel: "Județ/Regiune",
    OrganizationSection: "Organizație",
    ReportsToSection: "Subordonat față de",
    ManagerLabel: "Manager",
    CopiedFeedback: "Copiat!",
    CopyEmailAriaLabel: "Copiați adresa de e-mail",
    CopyWorkPhoneAriaLabel: "Copiați telefonul de serviciu",
    CopyMobileAriaLabel: "Copiați numărul de mobil",
    CopyLocationAriaLabel: "Copiați locația de muncă",
    CopyAddressAriaLabel: "Copiați adresa",
    CopyStreetAddressAriaLabel: "Copiați strada",
    CopyPostalCodeAriaLabel: "Copiați codul poștal",
    CopyStateAriaLabel: "Copiați județul/regiunea",
    AddressMapSectionLabel: "Previzualizare hartă",
    AddressMapLoadingLabel: "Se încarcă previzualizarea hărții…",
    OpenAddressInMapLabel: "Deschidere în hartă",
    TeamsAccessPendingTitle: "Microsoft Teams nu a fost configurat încă",
    TeamsAccessPendingMessage:
      "Accesul dumneavoastră de invitat la Microsoft Teams în această organizație nu a fost configurat încă. Aceasta nu afectează propriul cont Teams. Rugați-vă sponsorul să vă adauge într-o echipă — după aceea, funcțiile Teams, cum ar fi chat-ul, apelurile și ședințele, vor deveni disponibile aici.",
    TeamsNotReadyChatTooltip:
      "Chat-ul nu este disponibil în această organizație — accesul dumneavoastră de invitat la Teams nu a fost configurat încă",
    TeamsNotReadyCallTooltip:
      "Apelul nu este disponibil în această organizație — accesul dumneavoastră de invitat la Teams nu a fost configurat încă",
    VersionMismatchTitle: "Actualizare disponibilă",
    VersionMismatchMessage:
      "Este disponibilă o actualizare a componentei web. Rugați administratorul să se asigure că componenta web și API-ul Guest Sponsor rulează aceeași versiune.",
    InsufficientPermissionsTitle: "Permisiune necesară",
    InsufficientPermissionsMessage:
      "Nu s-au putut încărca informațiile despre sponsor — o permisiune de serviciu necesară nu a fost acordată. Vă rugăm să contactați administratorul IT.",
    GuestNotificationsGroupName: "Notificări pentru invitați",
    GuestNotificationsGroupHint: "Controlați ce notificări informative sunt afișate utilizatorilor invitați.",
    ShowTeamsAccessPendingHintLabel: 'Afișați notificarea "Teams nu a fost configurat încă"',
    ShowVersionMismatchHintLabel: 'Afișați notificarea "Actualizare disponibilă"',
    ShowSponsorUnavailableHintLabel: 'Afișați notificarea "Sponsorul nu este disponibil"',
    ShowNoSponsorsHintLabel: 'Afișați notificarea "Nu s-au găsit sponsori"',
    DisplayGroupName: "Afișaj",
    CardLayoutFieldLabel: "Aspect card",
    CardLayoutAutoOption: "Automat",
    CardLayoutAutoThresholdFieldLabel: "Comutare la compact la cel puțin atâția sponsori",
    CardLayoutFullOption: "Complet",
    CardLayoutCompactOption: "Compact",
    ShowBusinessPhonesFieldLabel: "Afișați numerele de telefon de serviciu",
    ShowMobilePhoneFieldLabel: "Afișați numărul de mobil",
    ShowWorkLocationFieldLabel: "Afișați locația de muncă",
    ShowStreetAddressFieldLabel: "Afișați strada",
    ShowPostalCodeFieldLabel: "Afișați codul poștal",
    ShowStateFieldLabel: "Afișați județul/regiunea",
    AzureMapsSubscriptionKeyFieldLabel: "Cheie de abonament Azure Maps",
    MapProviderModeAutoLabel: "Mod automat (recomandat)",
    MapProviderModeManualLabel: "Manual (același pentru toate dispozitivele)",
    MapProviderModeHint:
      "Alegeți un furnizor de hărți pentru fiecare sistem de operare, inclusiv iOS și Android. Linkurile se deschid în browser sau în aplicația furnizorului, dacă este instalată.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Furnizor de hărți",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Dezactivat (fără link la hartă)",
    AddressMapProviderHint:
      "Activați cel puțin orașul și țara — aceasta este suficientă pentru orice furnizor de hărți pentru a afișa o locație semnificativă.",
    AzureMapsPreviewHint:
      "Adăugați cheia de abonament Azure Maps pentru a afișa o previzualizare mică a hărții în secțiunea de contact. Dacă ați implementat API-ul Guest Sponsor, un cont Azure Maps a fost inclus — copiați cheia din setările sale de autentificare. Fără o cheie, se afișează numai linkul la hartă de mai sus.",
    ShowManagerFieldLabel: "Afișați managerul",
    UseInformalAddressFieldLabel: "Utilizați adresarea informală (tu)",
    SponsorEligibilityGroupName: "Eligibilitatea sponsorului",
    SponsorEligibilityGroupHint:
      "Atribuirile de sponsori în Microsoft Entra sunt gestionate de organizația dvs. și pot să nu fie întotdeauna corecte. Aceste filtre ajută la îmbunătățirea calității sponsorilor afișați invitaților și previn divulgarea neintențională de informații cauzată de atribuiri incorecte.",
    SponsorFilterFieldLabel: "Sponsorul trebuie să fie",
    SponsorFilterTeamsOption: "Licențiat pentru Teams (recomandat)",
    SponsorFilterExchangeOption: "Licențiat pentru Exchange Online",
    SponsorFilterAnyOption: "Licențiat (orice licență activă)",
    RequireUserMailboxFieldLabel: "Solicitați tipul de cutie poștală al utilizatorului",
    LocationDisplayHintSeparateRows: "Câmpurile de adresă activate sunt combinate într-un singur rând clicabil.",
    AdvancedDisplayGroupName: "Opțiuni avansate de afișare",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "URL de bază",
    WebPartClientIdFieldLabel: "ID aplicație (client)",
    SessionCacheTtlMinutesFieldLabel: "Durata cache-ului de sesiune (minute)",
    PpClientIdHintLabel: "Unde găsesc ID-ul clientului?",
    PpClientIdHintBody:
      "Copiați ID-ul clientului (ID-ul aplicației) din înregistrarea aplicației creată în timpul configurării.",
    FunctionEntraLinkLabel: "Găsiți în Microsoft Entra →",
    ProxyStatusChecking: "Se verifică conexiunea la Guest Sponsor API…",
    ProxyStatusOk: "Conexiune reușită",
    ProxyStatusError: "Conexiune eșuată",
    PpSetupIntro: "Configurare necesară:",
    PpSetupRerunHint:
      "Problemă de conexiune? Scriptul de configurare este idempotent — rularea lui din nou cu aceiași parametri rezolvă cele mai multe probleme.",
    CopyToClipboardLabel: "Copiere",
    CopiedToClipboardLabel: "Copiat!",
    AuthorSectionGroupName: "Despre",
    AuthorSectionCreatedBy: "Creat și întreținut de",
    AuthorSectionIntro: "Guvernanță Microsoft 365, identitate și acces pentru invitați — domeniul nostru.",
    AuthorSectionWebsiteLinkLabel: "Lucrați cu noi",
    AuthorSectionConsultingText:
      "Am creat această componentă web deoarece lucrăm cu exact aceste provocări în fiecare zi. De la arhitectură la implementare, ajutăm organizațiile să proiecteze colaborare sigură și scalabilă pe Microsoft 365.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Versiunea componentei web",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Faceți clic pe buton pentru a porni implementarea:",
    AuthorSectionDeploymentGuideLabel: "Ghid de implementare",
    NewReleaseAvailableLabel: "Versiune nouă disponibilă — faceți clic pentru a deschide GitHub Releases",
    DiagnosticsGroupName: "Accesibilitate pentru invitați",
    DiagnosticsGroupHint:
      "Verifică dacă pachetul JavaScript al componentei web și site-ul paginii de destinație sunt accesibile pentru utilizatorii invitați B2B.",
    DiagnosticsChecking: "Se execută verificările de accesibilitate pentru invitați…",
    DiagnosticsRetryButtonLabel: "Rulează din nou verificările",
    DiagPublicCdnOk:
      "Pachetul este livrat prin intermediul CDN-ului public Office 365 — livrare anonimă, nu sunt necesare permisiuni speciale pentru utilizatorii invitați.",
    DiagPrivateCdnInfo:
      "Pachetul este livrat prin intermediul CDN-ului privat Office 365 — invitații cu acces de citire la site îl pot încărca. Asigurați-vă că site-ul paginii de destinație este accesibil pentru invitați.",
    DiagSiteColCatalogOk:
      "Pachetul este livrat din catalogul de aplicații al colecției de site-uri — accesul invitaților respectă permisiunile proprii ale site-ului.",
    DiagTenantCatalogEveryoneOk:
      "Pachetul este livrat din catalogul de aplicații al entității găzduite. Cerința 'Toți' are acces de citire la catalog — utilizatorii invitați pot încărca pachetul.",
    DiagTenantCatalogEveryoneDenied:
      "Pachetul este livrat din catalogul de aplicații al entității găzduite, dar 'Toți' nu au acces de citire. Utilizatorii invitați nu pot încărca componenta web. Recomandare: activați CDN-ul public Office 365 sau acordați 'Toților' acces de vizitator la site-ul catalogului de aplicații.",
    DiagTenantCatalogEveryoneUnknown:
      "Pachetul este livrat din catalogul de aplicații al entității găzduite. Nu s-a putut verifica dacă 'Toți' au acces de citire (permisiuni insuficiente). Verificați manual dacă invitații pot accesa catalogul de aplicații sau activați CDN-ul public Office 365.",
    DiagAssetSourceUnknown:
      "Sursa pachetului nu a putut fi determinată. Verificați manual dacă utilizatorii invitați pot accesa pachetul JavaScript al componentei web.",
    DiagSiteEveryoneOk:
      "'Toți' se află în grupul Vizitatori al site-ului — invitații nou acceptați primesc imediat acces de citire la pagina de destinație.",
    DiagSiteEveryoneMissing:
      "'Toți' nu se află în grupul Vizitatori al site-ului. Accesul invitaților poate depinde de un grup de securitate Entra static (acceptabil) sau dinamic (până la 24 h întârziere pentru invitați noi). Dacă nu este configurat niciun grup care să includă invitații, aceștia vor vedea o pagină de acces refuzat.",
    DiagSiteEveryoneUnknown:
      "Nu s-au putut verifica permisiunile vizitatorilor site-ului. Vă rugăm să verificați că utilizatorii invitați au cel puțin acces de citire la acest site.",
    ShowSponsorJobTitleFieldLabel: "Afișați funcția sponsorului",
    ShowManagerJobTitleFieldLabel: "Afișați funcția managerului",
    ShowSponsorDepartmentFieldLabel: "Afișați departamentul sponsorului",
    ShowManagerDepartmentFieldLabel: "Afișați departamentul managerului",
    DepartmentLabel: "Departament",
    ShowCityFieldLabel: "Afișați orașul",
    ShowCountryFieldLabel: "Afișați țara",
    CityFieldLabel: "Oraș",
    CountryFieldLabel: "Țară",
    CopyCityAriaLabel: "Copiați orașul",
    CopyCountryAriaLabel: "Copiați țara",
    ShowPresenceFieldLabel: "Afișați starea de prezență",
    ShowSponsorPhotoFieldLabel: "Afișați fotografia sponsorului",
    ShowManagerPhotoFieldLabel: "Afișați fotografia managerului",
    TitlePlaceholder: "Sponsorii mei",
    TitleSizeFieldLabel: "Dimensiunea titlului",
    TitleSizeH2Option: "Titlu 2",
    TitleSizeH3Option: "Titlu 3",
    TitleSizeH4Option: "Titlu 4",
    TitleSizeNormalOption: "Normal",
    WelcomeDialogTitle: "Configurați Informații despre sponsorul invitat",
    WelcomeDialogBody:
      "Această componentă web afișează fiecărui utilizator invitat sponsorii săi din Microsoft Entra pe pagina de destinație SharePoint. Pentru ca aceasta să fie utilă, atribuirile de sponsori ar trebui să fie gestionate activ și ar trebui să existe deja un proces de gestionare a ciclului de viață al invitaților — componenta face vizibilă această responsabilitate, dar nu înlocuiește guvernanța de bază.",
    WelcomeDialogBroughtToYouBy:
      "Construit de Workoho — specialiști în guvernanța accesului invitaților și gestionarea ciclului de viață.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Să mergem",
    WelcomeDialogNextButton: "Înainte",
    WelcomeDialogBackButton: "Înapoi",
    WelcomeDialogSkipButton: "Nu acum",
    WelcomeDialogSaveButton: "Salvare",
    WelcomeDialogSkipApiButton: "Omitere",
    InvalidUrlFormat: "Introduceți un URL valid (de ex. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Introduceți un GUID valid (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Alegeți calea de configurare",
    WelcomeDialogSetupIntro:
      "Alegeți calea de implementare. Puteți comuta oricând între ambele opțiuni din setările componentei web.",
    WelcomeDialogOptionApiTitle: "Utilizați Guest Sponsor API",
    WelcomeDialogOptionApiBody:
      "Experiență completă bazată pe Azure Function. Necesită o configurare unică Azure — recomandat pentru producție.",
    WelcomeDialogOptionApiDocsLabel: "Vizualizați ghidul de configurare",
    WelcomeDialogSetupGuideNote:
      "Această comandă reprezintă o scurtătură. Înainte de a o rula, citiți ghidul de configurare pentru a înțelege ce face.",
    WelcomeDialogDeployToAzureLabel: "Implementați API-ul în Azure",
    WelcomeDialogDeployNote:
      "Această opțiune necesită implementarea Guest Sponsor API în abonamentul Azure. Puteți face acest lucru chiar de aici — durează doar câteva minute.",
    WelcomeDialogPreflightTitle: "Before deployment, the installer checks:",
    WelcomeDialogPreflightTools: "PowerShell, Azure CLI, Azure Developer CLI, and Bicep support.",
    WelcomeDialogPreflightSignIn: "Azure sign-in and the target subscription.",
    WelcomeDialogPreflightRoles: "Azure RBAC and Entra roles, with a copy/paste request if anything is missing.",
    WelcomeDialogSetupStepsOrderHint: "Parcurgeți acești pași în ordine:",
    WelcomeDialogSetupStep1Label: "Creați înregistrarea aplicației",
    WelcomeDialogSetupStep2Hint: "Utilizează înregistrarea aplicației creată la pasul 1",
    WelcomeDialogSetupStep3Label: "Acordați permisiuni Graph",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupShellHint: "macOS/Linux shell:",
    WelcomeDialogUseShellCommandLabel: "macOS/Linux without PowerShell?",
    WelcomeDialogUsePowerShellCommandLabel: "Use PowerShell command",
    WelcomeDialogSetupStep3Hint: "Utilizează înregistrarea aplicației (pasul 1) și URL-ul Function App (pasul 2)",
    ViewScriptSourceLabel: "Inspectați scriptul",
    WelcomeDialogConnectApiTitle: "Introduceți detaliile de conexiune API",
    WelcomeDialogConnectApiIntro:
      "Introduceți detaliile de conexiune pentru Guest Sponsor API. Puteți sări peste acest pas acum şi să le adăugați mai târziu în setările componentei web.",
    WelcomeDialogUrlHintLabel: "Unde găsesc URL-ul?",
    WelcomeDialogUrlHintBody:
      "Copiați URL-ul Function App din portalul Azure după implementare. Navigați la Function App → Prezentare generală → Domeniu implicit.",
    WelcomeDialogOptionDemoTitle: "Explorați în modul Demo",
    WelcomeDialogOptionDemoBody:
      "Activați modul demo pentru a afișa sponsori simulați pe pagina live, inclusiv pentru utilizatorii interni din organizație. Utilizați-l pentru testare fără configurarea Azure și comutați oricând la API-ul real.",
    WelcomeDialogFunctionUrlRequired: "Introduceți URL-ul de bază al Guest Sponsor API.",
    WelcomeDialogDoneApiTitle: "API configurat!",
    WelcomeDialogDoneApiBody:
      "Conexiunea la Guest Sponsor API a fost salvată. Nu uitați să salvați pagina pentru ca setările să fie aplicate pentru toți.",
    WelcomeDialogDoneApiSkippedTitle: "Aproape gata!",
    WelcomeDialogDoneApiSkippedBody:
      "Nu au fost introduse acreditări. Pentru a finaliza configurarea: deschideți setările componentei web, introduceți URL-ul de bază și ID-ul de client în Guest Sponsor API, apoi salvați pagina.",
    WelcomeDialogDoneDemoTitle: "Modul Demo activat!",
    WelcomeDialogDoneDemoBody:
      "Modul demo este acum activ pentru pagina live. Salvați pagina pentru a-l aplica vizitatorilor, apoi comutați în modul de vizualizare pentru a verifica cardurile de sponsor simulate.",
    PpSectionLivePage: "▶ Pagina live",
    PpSectionDemoMode: "🧪 Mod demo public",
    PpSectionCardLayout: "🗂️ Aspect card",
    PpSectionProfileFields: "👤 Câmpuri profil",
    PpSectionPhone: "📞 Numere de telefon",
    PpSectionWorkLocation: "📍 Locație de muncă",
    PpSectionAddress: "🏠 Adresă poștală",
    PpSectionMapLink: "🧭 Link hartă",
    PpSectionMapPreview: "🗺️ Previzualizare hartă integrată"
  };
});
