define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurera webbdelen G\u00e4stsponsorsinfo.",
    "BasicGroupName": "Inst\u00e4llningar",
    "TitleFieldLabel": "Titel",
    "LoadingMessage": "L\u00e4ser in dina sponsorer\u2026",
    "NoSponsorsMessage": "Inga sponsorer hittades f\u00f6r ditt konto.",
    "SponsorUnavailableMessage": "Din sponsor/\u00e4gare \u00e4r inte l\u00e4ngre tillg\u00e4nglig. Kontakta din projektansvarige f\u00f6r att f\u00e5 en ny sponsor/\u00e4gare tilldelad till ditt konto.",
    "ErrorMessage": "Det gick inte att l\u00e4sa in sponsorinformation. F\u00f6rs\u00f6k igen senare.",
    "EditModePlaceholder": "G\u00e4stsponsorsinfo \u2014 v\u00e4xla till visningsl\u00e4ge f\u00f6r att se sponsorer.",
    "GuestOnlyPlaceholder": "Den h\u00e4r webbdelen visas bara f\u00f6r g\u00e4stanv\u00e4ndare i visningsl\u00e4ge.",
    "MockModeFieldLabel": "Demol\u00e4ge (testdata)",
    "MockModePlaceholder": "G\u00e4stsponsorsinfo \u2014 Demol\u00e4ge aktivt. V\u00e4xla till visningsl\u00e4ge f\u00f6r att se testdata.",

    "PresenceAvailable": "Tillg\u00e4nglig",
    "PresenceAvailableIdle": "Tillg\u00e4nglig, inaktiv",
    "PresenceAway": "Borta",
    "PresenceBeRightBack": "Strax tillbaka",
    "PresenceBusy": "Upptagen",
    "PresenceBusyIdle": "Upptagen, inaktiv",
    "PresenceDoNotDisturb": "St\u00f6r ej",
    "PresenceInAMeeting": "I ett m\u00f6te",
    "PresenceInACall": "I ett samtal",
    "PresencePresenting": "Presenterar",
    "PresenceFocusing": "Fokuserar",
    "PresenceOutOfOffice": "Fr\u00e5nvarande fr\u00e5n kontoret",
    "PresenceOutOfOfficeSuffix": ", fr\u00e5nvarande fr\u00e5n kontoret",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Kontaktuppgifter f\u00f6r {0}",
    "ContactActionsAriaLabel": "Kontakt\u00e5tg\u00e4rder",
    "ChatTitle": "Chatta i Microsoft Teams",
    "EmailTitle": "Skicka e-post",
    "CallTitle": "Ljudsamtal i Microsoft Teams",
    "ChatLabel": "Chatt",
    "EmailLabel": "E-post",
    "CallLabel": "Ring",

    "ContactInfoSection": "Kontaktinformation",
    "EmailFieldLabel": "E-post",
    "WorkPhoneFieldLabel": "Arbetstelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbetsplats",
    "StreetAddressFieldLabel": "Gata",
    "PostalCodeFieldLabel": "Postnummer",
    "StateFieldLabel": "Delstat/region",

    "OrganizationSection": "Organisation",
    "ManagerLabel": "Chef",

    "CopiedFeedback": "Kopierat!",
    "CopyEmailAriaLabel": "Kopiera e-postadress",
    "CopyWorkPhoneAriaLabel": "Kopiera arbetstelefon",
    "CopyMobileAriaLabel": "Kopiera mobilnummer",
    "CopyLocationAriaLabel": "Kopiera arbetsplats",
    "CopyStreetAddressAriaLabel": "Kopiera gata",
    "CopyPostalCodeAriaLabel": "Kopiera postnummer",
    "CopyStateAriaLabel": "Kopiera delstat/region",
    "AddressMapSectionLabel": "Kartforhandsvisning",
    "AddressMapLoadingLabel": "Laddar kartforhandsvisning...",
    "OpenAddressInMapLabel": "Oppna i karta",

    "TeamsAccessPendingTitle": "Microsoft Teams \u00e4r \u00e4nnu inte konfigurerat",
    "TeamsAccessPendingMessage": "Din g\u00e4st\u00e5tkomst till Microsoft Teams i den h\u00e4r organisationen har \u00e4nnu inte konfigurerats. Ditt eget Teams-konto p\u00e5verkas inte. Be din sponsor att l\u00e4gga till dig i ett team \u2014 d\u00e4refter kan du anv\u00e4nda Teams-funktioner som chatt, samtal och m\u00f6ten h\u00e4r.",
    "TeamsNotReadyChatTooltip": "Chatt inte tillg\u00e4nglig h\u00e4r \u2014 din Teams-g\u00e4st\u00e5tkomst har \u00e4nnu inte konfigurerats",
    "TeamsNotReadyCallTooltip": "Samtal inte tillg\u00e4ngligt h\u00e4r \u2014 din Teams-g\u00e4st\u00e5tkomst har \u00e4nnu inte konfigurerats",

    "DisplayGroupName": "Visning",
    "ShowBusinessPhonesFieldLabel": "Visa arbetstelefonnummer",
    "ShowMobilePhoneFieldLabel": "Visa mobilnummer",
    "ShowWorkLocationFieldLabel": "Visa arbetsplats",
    "ShowManagerFieldLabel": "Visa chef",
    "UseInformalAddressFieldLabel": "Informellt tilltal",

    "ShowWorkLocationFallbackFieldLabel": "Visa arbetsplats som reserv",
    "LocationDisplayHintGeoWithFallback": "Stad och land kombineras till en gemensam geografisk rad. Arbetsplatsen visas bara om inga uppgifter om stad/land finns.",
    "LocationDisplayHintGeoOnly": "Stad och land kombineras till en gemensam geografisk rad. Arbetsplatsen är dold.",
    "LocationDisplayHintOfficeOnly": "Endast arbetsplatsen visas. Aktivera stad och/eller land för att visa en geografisk rad i stället.",
    "LocationDisplayHintHidden": "All platsinformation är dold.",
    "AddressMapFallbackHint": "Om ingen Azure Maps-nyckel ar konfigurerad eller om uppslagningen misslyckas visas en extern kartlank.",
    "LocationDisplayHintAddressEnabled": "Strukturerade adressfalt ar aktiverade och kan visas i ytterligare rader.",
    "LocationDisplayHintSeparateRows": "Stad/land och arbetsplats visas som separata rader nar de ar aktiverade.",
    "AdvancedDisplayGroupName": "Avancerade visningsalternativ",
    "ManagerOptionsDisabledHint": "Aktivera visning av chef för att konfigurera chefspecifika fält.",
    "FunctionGroupName": "Azure-funktion",
    "FunctionUrlFieldLabel": "Sponsor-API-URL (Azure-funktion)",
    "FunctionClientIdFieldLabel": "Sponsor-API-klient-ID (Azure Function-appregistrering)",
    "ProxyStatusChecking": "Kontrollerar Azure Function\u2026",
    "ProxyStatusOk": "Azure Function n\u00e5bar",
    "ProxyStatusError": "Azure Function inte n\u00e5bar",
    "ShowSponsorJobTitleFieldLabel": "Visa sponsorns jobbtitel",
    "ShowManagerJobTitleFieldLabel": "Visa chefens jobbtitel",
    "ShowSponsorDepartmentFieldLabel": "Visa sponsorns avdelning",
    "ShowManagerDepartmentFieldLabel": "Visa chefens avdelning",
    "DepartmentLabel": "Avdelning",
    "ShowCityFieldLabel": "Visa stad",
    "ShowCountryFieldLabel": "Visa land",
    "ShowStructuredAddressFieldLabel": "Visa strukturerad adress",
    "ShowStreetAddressFieldLabel": "Visa gata",
    "ShowPostalCodeFieldLabel": "Visa postnummer",
    "ShowStateFieldLabel": "Visa delstat/region",
    "ShowAddressMapFieldLabel": "Visa adresskartans forhandsvisning",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-prenumerationsnyckel",
    "ExternalMapProviderFieldLabel": "Extern kartleverantor (reserv)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Stad",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopiera stad",
    "CopyCountryAriaLabel": "Kopiera land",
    "ShowPresenceFieldLabel": "Visa n\u00e4rvaro\u00f6status"
  }
});
