// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "Inställningar",
    ShowTitleFieldLabel: "Visa titel",
    TitleFieldLabel: "Titel",
    LoadingMessage: "Läser in dina sponsorer…",
    NoSponsorsTitle: "Inga sponsorer hittades",
    NoSponsorsMessage: "Inga sponsorer hittades för ditt konto.",
    SponsorUnavailableTitle: "Sponsor ej tillgänglig",
    SponsorUnavailableMessage:
      "Din sponsor är inte längre tillgänglig. Kontakta din projektansvarige för att få en ny sponsor tilldelad till ditt konto.",
    ErrorMessageTitle: "Något gick fel",
    ErrorMessage: "Det gick inte att läsa in sponsorinformation. Försök igen senare.",
    EditModePlaceholder: "Gästsponsorsinfo — växla till visningsläge för att se sponsorer.",
    GuestOnlyPlaceholder: "Den här webbdelen visas bara för gästanvändare i visningsläge.",
    MockModeFieldLabel: "Visa alltid demosponsorer (offentligt demoläge)",
    MockModeFieldDescription: "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    MockModeFieldTooltip:
      "Vid aktivering visas demoläge endast på live-sidan för testningsändamål. Redigeringsläge och förhandsvisning förblir oförändrat.",
    MockModePlaceholder: "Gästsponsorsinfo — Demoläge aktivt. Växla till visningsläge för att se testdata.",
    MockSimulatedHintFieldLabel: "Simulera gästavisering",
    MockSimulatedHintNoneOption: "Ingen avisering",
    MockSimulatedHintTeamsAccessPendingOption: "Microsoft Teams inte konfigurerat ännu",
    MockSimulatedHintVersionMismatchOption: "Uppdatering tillgänglig",
    MockSimulatedHintSponsorUnavailableOption: "Sponsorn är inte tillgänglig",
    MockSimulatedHintNoSponsorsOption: "Inga sponsorer hittades",
    MaxSponsorCountFieldLabel: "Synliga sponsorer",
    MaxSponsorCountFieldTooltip:
      "Begränsar antalet visade sponsorkort. Bara aktiva (tillgängliga) sponsorer räknas mot denna gräns. Om en tilldelad sponsors konto inte längre är tillgängligt (inaktiverat, raderat eller ännu inte etablerat), rykker näste sponsor i prioritetsordningen automatiskt fram för att fylla det tomma utrymmet. Detta garanterar att gäster alltid ser det konfigurerade antalet tillgängliga kontakter.",
    PresenceAvailable: "Tillgänglig",
    PresenceAvailableIdle: "Tillgänglig, inaktiv",
    PresenceAway: "Borta",
    PresenceBeRightBack: "Strax tillbaka",
    PresenceBusy: "Upptagen",
    PresenceBusyIdle: "Upptagen, inaktiv",
    PresenceDoNotDisturb: "Stör ej",
    PresenceInAMeeting: "I ett möte",
    PresenceInACall: "I ett samtal",
    PresencePresenting: "Presenterar",
    PresenceFocusing: "Fokuserar",
    PresenceOutOfOffice: "Frånvarande från kontoret",
    PresenceOutOfOfficeSuffix: ", frånvarande från kontoret",
    PresenceOffline: "Offline",
    ContactDetailsAriaLabel: "Kontaktuppgifter för {0}",
    ContactActionsAriaLabel: "Kontaktåtgärder",
    CloseLabel: "Stäng",
    ChatTitle: "Starta en chatt med {name}",
    EmailTitle: "Skicka e-post till {name}",
    CallTitle: "Starta ett röstsamtal med {name}",
    ChatLabel: "Chatt",
    EmailLabel: "E-post",
    CallLabel: "Ring",
    ContactInfoSection: "Kontakt",
    EmailFieldLabel: "E-post",
    WorkPhoneFieldLabel: "Arbetstelefon",
    MobileFieldLabel: "Mobil",
    WorkLocationFieldLabel: "Arbetsplats",
    AddressFieldLabel: "Adress",
    StreetAddressFieldLabel: "Gata",
    PostalCodeFieldLabel: "Postnummer",
    StateFieldLabel: "Delstat/region",
    OrganizationSection: "Organisation",
    ReportsToSection: "Rapporterar till",
    ManagerLabel: "Chef",
    CopiedFeedback: "Kopierat!",
    CopyEmailAriaLabel: "Kopiera e-postadress",
    CopyWorkPhoneAriaLabel: "Kopiera arbetstelefon",
    CopyMobileAriaLabel: "Kopiera mobilnummer",
    CopyLocationAriaLabel: "Kopiera arbetsplats",
    CopyAddressAriaLabel: "Kopiera adress",
    CopyStreetAddressAriaLabel: "Kopiera gata",
    CopyPostalCodeAriaLabel: "Kopiera postnummer",
    CopyStateAriaLabel: "Kopiera delstat/region",
    AddressMapSectionLabel: "Kartförhandsvisning",
    AddressMapLoadingLabel: "Laddar kartförhandsvisning...",
    OpenAddressInMapLabel: "Öppna i karta",
    TeamsAccessPendingTitle: "Microsoft Teams är ännu inte konfigurerat",
    TeamsAccessPendingMessage:
      "Din gäståtkomst till Microsoft Teams i den här organisationen har ännu inte konfigurerats. Ditt eget Teams-konto påverkas inte. Be din sponsor att lägga till dig i ett team — därefter kan du använda Teams-funktioner som chatt, samtal och möten här.",
    TeamsNotReadyChatTooltip: "Chatt inte tillgänglig här — din Teams-gäståtkomst har ännu inte konfigurerats",
    TeamsNotReadyCallTooltip: "Samtal inte tillgängligt här — din Teams-gäståtkomst har ännu inte konfigurerats",
    VersionMismatchTitle: "Uppdatering tillgänglig",
    VersionMismatchMessage:
      "Det finns en uppdatering tillgänglig för den här webbdelen. Be din administratör att se till att webbdelen och Guest Sponsor API körs med samma version.",
    InsufficientPermissionsTitle: "Behörighet saknas",
    InsufficientPermissionsMessage:
      "Det gick inte att läsa in sponsorinformation — en nödvändig tjänstbehörighet har inte beviljats. Kontakta din IT-administratör.",
    GuestNotificationsGroupName: "Aviseringar för gäster",
    GuestNotificationsGroupHint: "Styr vilka informationsaviseringar som visas för gästanvändare.",
    ShowTeamsAccessPendingHintLabel: "Visa aviseringen «Microsoft Teams inte konfigurerat ännu»",
    ShowVersionMismatchHintLabel: "Visa aviseringen «Uppdatering tillgänglig»",
    ShowSponsorUnavailableHintLabel: "Visa aviseringen «Sponsor inte tillgänglig»",
    ShowNoSponsorsHintLabel: "Visa aviseringen «Inga sponsorer hittades»",
    DisplayGroupName: "Visning",
    CardLayoutFieldLabel: "Kortlayout",
    CardLayoutAutoOption: "Automatisk",
    CardLayoutAutoThresholdFieldLabel: "Byt till kompakt layout från detta antal sponsorer",
    CardLayoutFullOption: "Full",
    CardLayoutCompactOption: "Kompakt",
    ShowBusinessPhonesFieldLabel: "Visa arbetstelefonnummer",
    ShowMobilePhoneFieldLabel: "Visa mobilnummer",
    ShowWorkLocationFieldLabel: "Visa arbetsplats",
    ShowStreetAddressFieldLabel: "Visa gata",
    ShowPostalCodeFieldLabel: "Visa postnummer",
    ShowStateFieldLabel: "Visa delstat/region",
    AzureMapsSubscriptionKeyFieldLabel: "Azure Maps-prenumerationsnyckel",
    MapProviderModeAutoLabel: "Automatiskt läge (rekommenderas)",
    MapProviderModeManualLabel: "Manuellt (samma för alla enheter)",
    MapProviderModeHint:
      "Välj en kartleverantör per operativsystem, inklusive iOS och Android. Länken öppnas i webbläsaren eller i leverantörens app om den är installerad.",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "Kartleverantör",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "Inaktiverad (ingen kartlänk)",
    AddressMapProviderHint:
      "Aktivera minst stad och land — det räcker för valfri kartleverantör att visa en meningsfull plats.",
    AzureMapsPreviewHint:
      "Lägg till din Azure Maps-prenumerationsnyckel för att visa en liten kartförhandsvisning i kontaktsektionen. Om du har distribuerat Guest Sponsor API inkluderades ett Azure Maps-konto — kopiera nyckeln från autentiseringsinställningarna. Utan nyckel visas bara kartlänken ovan.",
    ShowManagerFieldLabel: "Visa chef",
    UseInformalAddressFieldLabel: "Informellt tilltal",
    SponsorEligibilityGroupName: "Sponsorbehörighet",
    SponsorEligibilityGroupHint:
      "Sponsortilldelningar i Microsoft Entra hanteras av din organisation och är inte alltid korrekta. Dessa filter förbättrar kvaliteten på de sponsorer som visas för gäster och förhindrar oavsiktlig informationsspridning orsakad av felaktiga tilldelningar.",
    SponsorFilterFieldLabel: "Sponsor måste vara",
    SponsorFilterTeamsOption: "Teams-licensierad (rekommenderas)",
    SponsorFilterExchangeOption: "Exchange Online-licensierad",
    SponsorFilterAnyOption: "Licensierad (valfri aktiv licens)",
    RequireUserMailboxFieldLabel: "Kräv användarpostlådetyp",
    LocationDisplayHintSeparateRows: "Aktiverade adressfält kombineras till en enda klickbar rad.",
    AdvancedDisplayGroupName: "Avancerade visningsalternativ",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "Bas-URL",
    WebPartClientIdFieldLabel: "Program-ID (klient)",
    PpClientIdHintLabel: "Var hittar jag klient-ID?",
    PpClientIdHintBody: "Kopiera klient-ID (program-ID) fr\u00e5n appregistreringen som skapades vid installationen.",
    FunctionEntraLinkLabel: "Hitta i Microsoft Entra →",
    ProxyStatusChecking: "Kontrollerar anslutning…",
    ProxyStatusOk: "Anslutning lyckades",
    ProxyStatusError: "Anslutning misslyckades",
    PpSetupIntro: "Nödvändig konfiguration:",
    PpSetupRerunHint:
      "Anslutningsproblem? Installationsskripten är idempotenta \u2014 att köra dem igen med samma parametrar löser de flesta problem.",
    CopyToClipboardLabel: "Kopiera",
    CopiedToClipboardLabel: "Kopierat!",
    AuthorSectionGroupName: "Om",
    AuthorSectionCreatedBy: "Skapad och underhållen av",
    AuthorSectionIntro: "Microsoft 365-styrning, identiteter och gäståtkomst \u2014 vårt område.",
    AuthorSectionWebsiteLinkLabel: "Kontakta oss",
    AuthorSectionConsultingText:
      "Vi byggde den här webbdelen för att det är precis vad vi arbetar med varje dag. Från arkitektur till driftsättning hjälper vi organisationer att bygga säkra och skalbara samarbetsmiljöer på Microsoft 365.",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Webbdelens version",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "Klicka p\u00e5 knappen f\u00f6r att starta distributionen:",
    AuthorSectionDeploymentGuideLabel: "Driftsättningsguide",
    NewReleaseAvailableLabel: "Ny version tillg\u00e4nglig \u2014 \u00f6ppna GitHub Releases",
    DiagnosticsGroupName: "G\u00e4st\u00e5tkomst",
    DiagnosticsGroupHint:
      "Kontrollerar om web-partets JavaScript-paket och landningssidan \u00e4r tillg\u00e4ngliga f\u00f6r B2B-g\u00e4stanv\u00e4ndare.",
    DiagnosticsChecking: "Kontrollerar g\u00e4st\u00e5tkomst\u2026",
    DiagnosticsRetryButtonLabel: "Kör kontrollerna igen",
    DiagPublicCdnOk:
      "Paketet levereras via det offentliga Office 365 CDN \u2014 anonym leverans, inga s\u00e4rskilda beh\u00f6righeter kr\u00e4vs f\u00f6r g\u00e4ster.",
    DiagPrivateCdnInfo:
      "Paketet levereras via det privata Office 365 CDN \u2014 g\u00e4ster med l\u00e4sbeh\u00f6righet p\u00e5 webbplatsen kan ladda det. Kontrollera att landningssidan \u00e4r tillg\u00e4nglig f\u00f6r g\u00e4ster.",
    DiagSiteColCatalogOk:
      "Paketet levereras fr\u00e5n webbplatssamlingens appkatalog \u2014 g\u00e4st\u00e5tkomst f\u00f6ljer platsens egna beh\u00f6righeter.",
    DiagTenantCatalogEveryoneOk:
      "Paketet levereras fr\u00e5n klientens appkatalog. Gruppen \u2018Alla\u2019 har l\u00e4sbeh\u00f6righet till katalogen \u2014 g\u00e4stanv\u00e4ndare kan ladda paketet.",
    DiagTenantCatalogEveryoneDenied:
      "Paketet levereras fr\u00e5n klientens appkatalog men \u2018Alla\u2019 saknar l\u00e4sbeh\u00f6righet. G\u00e4stanv\u00e4ndare kan inte ladda web-parten. Rekommendation: aktivera det offentliga Office 365 CDN eller ge \u2018Alla\u2019 bes\u00f6karbeh\u00f6righet p\u00e5 appkatalogens webbplats.",
    DiagTenantCatalogEveryoneUnknown:
      "Paketet levereras fr\u00e5n klientens appkatalog. Det gick inte att verifiera om \u2018Alla\u2019 har l\u00e4sbeh\u00f6righet (otillr\u00e4ckliga beh\u00f6righeter). Kontrollera manuellt att g\u00e4ster n\u00e5r katalogen eller aktivera det offentliga Office 365 CDN.",
    DiagAssetSourceUnknown:
      "Paketets k\u00e4lla kunde inte fastst\u00e4llas. Kontrollera manuellt att g\u00e4stanv\u00e4ndare n\u00e5r web-partets JavaScript-paket.",
    DiagSiteEveryoneOk:
      "\u2018Alla\u2019 ing\u00e5r i webbplatsens bes\u00f6kargrupp \u2014 nyligen accepterade g\u00e4ster f\u00e5r omedelbar l\u00e4sbeh\u00f6righet till landningssidan.",
    DiagSiteEveryoneMissing:
      "\u2018Alla\u2019 ing\u00e5r inte i webbplatsens bes\u00f6kargrupp. G\u00e4st\u00e5tkomst kanske beror p\u00e5 en statisk Entra-s\u00e4kerhetsgrupp (acceptabelt) eller dynamisk grupp (upp till 24\u00a0timmars f\u00f6rdr\u00f6jning f\u00f6r nya g\u00e4ster). Om ingen g\u00e4stvl\u00e4nlig grupp \u00e4r konfigurerad ser g\u00e4ster en sida om nekad \u00e5tkomst.",
    DiagSiteEveryoneUnknown:
      "Webbplatsens bes\u00f6karbeh\u00f6righeter kunde inte verifieras. Kontrollera att g\u00e4stanv\u00e4ndare har minst l\u00e4sbeh\u00f6righet p\u00e5 den h\u00e4r webbplatsen.",
    ShowSponsorJobTitleFieldLabel: "Visa sponsorns jobbtitel",
    ShowManagerJobTitleFieldLabel: "Visa chefens jobbtitel",
    ShowSponsorDepartmentFieldLabel: "Visa sponsorns avdelning",
    ShowManagerDepartmentFieldLabel: "Visa chefens avdelning",
    DepartmentLabel: "Avdelning",
    ShowCityFieldLabel: "Visa stad",
    ShowCountryFieldLabel: "Visa land",
    CityFieldLabel: "Stad",
    CountryFieldLabel: "Land",
    CopyCityAriaLabel: "Kopiera stad",
    CopyCountryAriaLabel: "Kopiera land",
    ShowPresenceFieldLabel: "Visa närvarostatus",
    ShowSponsorPhotoFieldLabel: "Visa sponsorns foto",
    ShowManagerPhotoFieldLabel: "Visa chefens foto",
    TitlePlaceholder: "Mina sponsorer",
    TitleSizeFieldLabel: "Titelstorlek",
    TitleSizeH2Option: "Rubrik 2",
    TitleSizeH3Option: "Rubrik 3",
    TitleSizeH4Option: "Rubrik 4",
    TitleSizeNormalOption: "Normal",
    WelcomeDialogTitle: "Konfigurera Gästsponsorsinfo",
    WelcomeDialogBody:
      "Den här webbdelen visar varje gästanvändare deras Microsoft Entra-sponsorer på din SharePoint-startsida. För att webbdelen ska vara meningsfull bör sponsortilldelningar aktivt förvaltas och en livscykelprocess för gäster redan finnas på plats — den synliggör det ansvaret, men ersätter inte den underliggande styrningen.",
    WelcomeDialogBroughtToYouBy: "Utvecklat av Workoho — specialister på gäststyrning och livscykelhantering.",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "Kör igång",
    WelcomeDialogNextButton: "Nästa",
    WelcomeDialogBackButton: "Tillbaka",
    WelcomeDialogSkipButton: "Inte nu",
    WelcomeDialogSaveButton: "Spara",
    WelcomeDialogSkipApiButton: "Hoppa över",
    InvalidUrlFormat: "Ange en giltig URL (t.ex. my-app.azurewebsites.net)",
    InvalidGuidFormat: "Ange ett giltigt GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)",
    WelcomeDialogSetupTitle: "Välj din konfigurationsväg",
    WelcomeDialogSetupIntro:
      "Välj din driftsättningsväg. Du kan växla mellan båda alternativen när som helst via webbdelens inställningar.",
    WelcomeDialogOptionApiTitle: "Använd Guest Sponsor API",
    WelcomeDialogOptionApiBody:
      "Fullständig upplevelse via en Azure Function. Kräver engångskonfiguration i Azure — rekommenderas för produktion.",
    WelcomeDialogOptionApiDocsLabel: "Visa installationsguide",
    WelcomeDialogSetupGuideNote:
      "Dessa steg är en genväg. Läs installationsguiden innan du kör skript — så att du förstår vad varje kommando gör.",
    WelcomeDialogDeployToAzureLabel: "Distribuera API:et till Azure",
    WelcomeDialogDeployNote:
      "Det här alternativet kräver att Guest Sponsor API distribueras till din Azure-prenumeration. Du kan göra det här \u2014 det tar bara några minuter.",
    WelcomeDialogSetupStepsOrderHint: "Slutför dessa steg i ordning:",
    WelcomeDialogSetupStep1Label: "Skapa appregistrering",
    WelcomeDialogSetupStep2Hint: "Använder appregistreringen som skapades i steg 1",
    WelcomeDialogSetupStep3Label: "Bevilja Graph-behörigheter",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupStep3Hint: "Använder appregistreringen (steg 1) och Function App-URL:en (steg 2)",
    ViewScriptSourceLabel: "Granska skript",
    WelcomeDialogConnectApiTitle: "Ange API-anslutningsinformation",
    WelcomeDialogConnectApiIntro:
      "Ange anslutningsinformation för ditt Guest Sponsor API. Du kan hoppa över det här steget nu och lägga till det senare i webbdelens inställningar.",
    WelcomeDialogUrlHintLabel: "Var hittar jag URL:en?",
    WelcomeDialogUrlHintBody:
      "Kopiera Function App-URL:en från Azure-portalen efter distributionen. Gå till din Function App → Översikt → Standarddomän.",
    WelcomeDialogOptionDemoTitle: "Utforska i deoläge",
    WelcomeDialogOptionDemoBody:
      "Prova webbdelen med simulerade sponsordata — ingen Azure-konfiguration krävs. Byt till det verkliga API:et från inställningarna när som helst.",
    WelcomeDialogFunctionUrlRequired: "Ange bas-URL:en för Guest Sponsor API.",
    WelcomeDialogDoneApiTitle: "API konfigurerat!",
    WelcomeDialogDoneApiBody:
      "Anslutningen till Guest Sponsor API har sparats. Kom ihåg att spara sidan så att dina inställningar tillämpas för alla.",
    WelcomeDialogDoneApiSkippedTitle: "Nästan klart!",
    WelcomeDialogDoneApiSkippedBody:
      "Inga inloggningsuppgifter angavs. Slutför konfigurationen: öppna webbdelens inställningar, ange bas-URL och klient-ID under Guest Sponsor API och spara sidan.",
    WelcomeDialogDoneDemoTitle: "Deoläge aktiverat!",
    WelcomeDialogDoneDemoBody:
      "Byt till visningsläge för att se webbdelen med simulerade sponsorkort. Anslut Guest Sponsor API från inställningarna när du är redo.",
    PpSectionLivePage: "▶ Live-sida",
    PpSectionDemoMode: "🧪 Demoläge",
    PpSectionCardLayout: "🗂️ Kortlayout",
    PpSectionProfileFields: "👤 Profilfält",
    PpSectionPhone: "📞 Telefonnummer",
    PpSectionWorkLocation: "📍 Arbetsort",
    PpSectionAddress: "🏠 Postadress",
    PpSectionMapLink: "🧭 Kartlänk",
    PpSectionMapPreview: "🗺️ Infogad kartförhandsvisning"
  };
});
