define([], function() {
  return {
    "PropertyPaneDescription": "Konfigurera webbdelen Gästsponsorsinfo.",
    "BasicGroupName": "Inställningar",
    "TitleFieldLabel": "Titel",
    "LoadingMessage": "Läser in dina sponsorer…",
    "NoSponsorsMessage": "Inga sponsorer hittades för ditt konto.",
    "SponsorUnavailableMessage": "Din sponsor/ägare är inte längre tillgänglig. Kontakta din projektansvarige för att få en ny sponsor/ägare tilldelad till ditt konto.",
    "ErrorMessage": "Det gick inte att läsa in sponsorinformation. Försök igen senare.",
    "EditModePlaceholder": "Gästsponsorsinfo — växla till visningsläge för att se sponsorer.",
    "GuestOnlyPlaceholder": "Den här webbdelen visas bara för gästanvändare i visningsläge.",
    "MockModeFieldLabel": "Demoläge (testdata)",
    "MockModePlaceholder": "Gästsponsorsinfo — Demoläge aktivt. Växla till visningsläge för att se testdata.",

    "PresenceAvailable": "Tillgänglig",
    "PresenceAvailableIdle": "Tillgänglig, inaktiv",
    "PresenceAway": "Borta",
    "PresenceBeRightBack": "Strax tillbaka",
    "PresenceBusy": "Upptagen",
    "PresenceBusyIdle": "Upptagen, inaktiv",
    "PresenceDoNotDisturb": "Stör ej",
    "PresenceInAMeeting": "I ett möte",
    "PresenceInACall": "I ett samtal",
    "PresencePresenting": "Presenterar",
    "PresenceFocusing": "Fokuserar",
    "PresenceOutOfOffice": "Frånvarande från kontoret",
    "PresenceOutOfOfficeSuffix": ", frånvarande från kontoret",
    "PresenceOffline": "Offline",

    "ContactDetailsAriaLabel": "Kontaktuppgifter för {0}",
    "ContactActionsAriaLabel": "Kontaktåtgärder",
    "ChatTitle": "Chatta i Microsoft Teams",
    "EmailTitle": "Skicka e-post",
    "CallTitle": "Ljudsamtal i Microsoft Teams",
    "ChatLabel": "Chatt",
    "EmailLabel": "E-post",
    "CallLabel": "Ring",

    "ContactInfoSection": "Kontaktinformation",
    "EmailFieldLabel": "E-post",
    "WorkPhoneFieldLabel": "Arbetstelefon",
    "MobileFieldLabel": "Mobil",
    "WorkLocationFieldLabel": "Arbetsplats",
    "StreetAddressFieldLabel": "Gata",
    "PostalCodeFieldLabel": "Postnummer",
    "StateFieldLabel": "Delstat/region",

    "OrganizationSection": "Organisation",
    "ManagerLabel": "Chef",

    "CopiedFeedback": "Kopierat!",
    "CopyEmailAriaLabel": "Kopiera e-postadress",
    "CopyWorkPhoneAriaLabel": "Kopiera arbetstelefon",
    "CopyMobileAriaLabel": "Kopiera mobilnummer",
    "CopyLocationAriaLabel": "Kopiera arbetsplats",
    "CopyStreetAddressAriaLabel": "Kopiera gata",
    "CopyPostalCodeAriaLabel": "Kopiera postnummer",
    "CopyStateAriaLabel": "Kopiera delstat/region",
    "AddressMapSectionLabel": "Kartförhandsvisning",
    "AddressMapLoadingLabel": "Laddar kartförhandsvisning...",
    "OpenAddressInMapLabel": "Öppna i karta",

    "TeamsAccessPendingTitle": "Microsoft Teams är ännu inte konfigurerat",
    "TeamsAccessPendingMessage": "Din gäståtkomst till Microsoft Teams i den här organisationen har ännu inte konfigurerats. Ditt eget Teams-konto påverkas inte. Be din sponsor att lägga till dig i ett team — därefter kan du använda Teams-funktioner som chatt, samtal och möten här.",
    "TeamsNotReadyChatTooltip": "Chatt inte tillgänglig här — din Teams-gäståtkomst har ännu inte konfigurerats",
    "TeamsNotReadyCallTooltip": "Samtal inte tillgängligt här — din Teams-gäståtkomst har ännu inte konfigurerats",

    "VersionMismatchMessage": "Det finns en uppdatering tillgänglig för den här webbdelen. Be din administratör att se till att webbdelen och Azure Function körs med samma version.",
    "InsufficientPermissionsMessage": "Det gick inte att läsa in sponsorinformation — en nödvändig tjänstbehörighet har inte beviljats. Kontakta din IT-administratör.",

    "DisplayGroupName": "Visning",
    "ShowBusinessPhonesFieldLabel": "Visa arbetstelefonnummer",
    "ShowMobilePhoneFieldLabel": "Visa mobilnummer",
    "ShowWorkLocationFieldLabel": "Visa arbetsplats",
    "ShowManagerFieldLabel": "Visa chef",
    "UseInformalAddressFieldLabel": "Informellt tilltal",

    "ShowWorkLocationFallbackFieldLabel": "Visa arbetsplats som reserv",
    "LocationDisplayHintGeoWithFallback": "Stad och land kombineras till en gemensam geografisk rad. Arbetsplatsen visas bara om inga uppgifter om stad/land finns.",
    "LocationDisplayHintGeoOnly": "Stad och land kombineras till en gemensam geografisk rad. Arbetsplatsen är dold.",
    "LocationDisplayHintOfficeOnly": "Endast arbetsplatsen visas. Aktivera stad och/eller land för att visa en geografisk rad i stället.",
    "LocationDisplayHintHidden": "All platsinformation är dold.",
    "AddressMapFallbackHint": "Om ingen Azure Maps-nyckel är konfigurerad eller om uppslagningen misslyckas visas en extern kartlänk.",
    "LocationDisplayHintAddressEnabled": "Strukturerade adressfält är aktiverade och kan visas i ytterligare rader.",
    "LocationDisplayHintSeparateRows": "Stad/land och arbetsplats visas som separata rader när de är aktiverade.",
    "AdvancedDisplayGroupName": "Avancerade visningsalternativ",
    "ManagerOptionsDisabledHint": "Aktivera visning av chef för att konfigurera chefspecifika fält.",
    "FunctionGroupName": "Azure-funktion",
    "FunctionUrlFieldLabel": "Sponsor-API-URL (Azure-funktion)",
    "FunctionClientIdFieldLabel": "Sponsor-API-klient-ID (Azure Function-appregistrering)",
    "ProxyStatusChecking": "Kontrollerar Azure Function…",
    "ProxyStatusOk": "Azure Function nåbar",
    "ProxyStatusError": "Azure Function inte nåbar",
    "ShowSponsorJobTitleFieldLabel": "Visa sponsorns jobbtitel",
    "ShowManagerJobTitleFieldLabel": "Visa chefens jobbtitel",
    "ShowSponsorDepartmentFieldLabel": "Visa sponsorns avdelning",
    "ShowManagerDepartmentFieldLabel": "Visa chefens avdelning",
    "DepartmentLabel": "Avdelning",
    "ShowCityFieldLabel": "Visa stad",
    "ShowCountryFieldLabel": "Visa land",
    "ShowStructuredAddressFieldLabel": "Visa strukturerad adress",
    "ShowStreetAddressFieldLabel": "Visa gata",
    "ShowPostalCodeFieldLabel": "Visa postnummer",
    "ShowStateFieldLabel": "Visa delstat/region",
    "ShowAddressMapFieldLabel": "Visa adresskartans förhandsvisning",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps-prenumerationsnyckel",
    "ExternalMapProviderFieldLabel": "Extern kartleverantör (reserv)",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "Stad",
    "CountryFieldLabel": "Land",
    "CopyCityAriaLabel": "Kopiera stad",
    "CopyCountryAriaLabel": "Kopiera land",
    "ShowPresenceFieldLabel": "Visa närvarostatus"
  }
});
