define([], function() {
  return {
    "PropertyPaneDescription": "配置访客赞助商信息 Web 部件。",
    "BasicGroupName": "设置",
    "TitleFieldLabel": "标题",
    "LoadingMessage": "正在加载您的赞助商…",
    "NoSponsorsMessage": "未找到您帐户的赞助商。",
    "SponsorUnavailableMessage": "您的赞助商/所有者不再可用。请联系您的项目负责人，为您的帐户分配新的赞助商/所有者。",
    "ErrorMessage": "无法加载赞助商信息。请稍后重试。",
    "EditModePlaceholder": "访客赞助商信息 — 切换到查看模式以查看赞助商。",
    "GuestOnlyPlaceholder": "此 Web 部件在查看模式下仅对访客用户可见。",
    "MockModeFieldLabel": "演示模式（模拟数据）",
    "MockModePlaceholder": "访客赞助商信息 — 演示模式已激活。切换到查看模式以查看模拟数据。",

    "PresenceAvailable": "有空",
    "PresenceAvailableIdle": "有空（闲置）",
    "PresenceAway": "离开",
    "PresenceBeRightBack": "马上回来",
    "PresenceBusy": "忙碌",
    "PresenceBusyIdle": "忙碌（闲置）",
    "PresenceDoNotDisturb": "请勿打扰",
    "PresenceInAMeeting": "会议中",
    "PresenceInACall": "通话中",
    "PresencePresenting": "演示中",
    "PresenceFocusing": "专注中",
    "PresenceOutOfOffice": "不在办公室",
    "PresenceOutOfOfficeSuffix": "，不在办公室",
    "PresenceOffline": "脱机",

    "ContactDetailsAriaLabel": "{0} 的联系人详细信息",
    "ContactActionsAriaLabel": "联系人操作",
    "ChatTitle": "在 Microsoft Teams 中聊天",
    "EmailTitle": "发送电子邮件",
    "CallTitle": "在 Microsoft Teams 中进行音频通话",
    "ChatLabel": "聊天",
    "EmailLabel": "电子邮件",
    "CallLabel": "通话",

    "ContactInfoSection": "联系信息",
    "EmailFieldLabel": "电子邮件",
    "WorkPhoneFieldLabel": "工作电话",
    "MobileFieldLabel": "手机",
    "WorkLocationFieldLabel": "工作地点",
    "StreetAddressFieldLabel": "街道",
    "PostalCodeFieldLabel": "邮政编码",
    "StateFieldLabel": "省/州",

    "OrganizationSection": "组织",
    "ManagerLabel": "上级",

    "CopiedFeedback": "已复制!",
    "CopyEmailAriaLabel": "复制电子邮件地址",
    "CopyWorkPhoneAriaLabel": "复制工作电话",
    "CopyMobileAriaLabel": "复制手机号码",
    "CopyLocationAriaLabel": "复制工作地点",
    "CopyStreetAddressAriaLabel": "复制街道",
    "CopyPostalCodeAriaLabel": "复制邮政编码",
    "CopyStateAriaLabel": "复制省/州",
    "AddressMapSectionLabel": "地图预览",
    "AddressMapLoadingLabel": "正在加载地图预览...",
    "OpenAddressInMapLabel": "在地图中打开",

    "TeamsAccessPendingTitle": "Microsoft Teams 尚未设置",
    "TeamsAccessPendingMessage": "您在此组织中的来宾 Microsoft Teams 访问权限尚未设置。这不影响您自己的 Teams 账户。请联系您的赞助人将您添加到团队中 — 添加后，您即可在此使用聊天、通话和会议等 Teams 功能。",
    "TeamsNotReadyChatTooltip": "此组织中聊天不可用 — 您的 Teams 来宾访问权限尚未设置",
    "TeamsNotReadyCallTooltip": "此组织中通话不可用 — 您的 Teams 来宾访问权限尚未设置",

    "VersionMismatchMessage": "此 Web 部件有可用更新。请联系管理员确保 Web 部件和 Azure Function 运行相同版本。",
    "InsufficientPermissionsMessage": "无法加载赞助商信息 — 尚未授予所需的服务权限。请联系您的 IT 管理员。",

    "DisplayGroupName": "显示",
    "ShowBusinessPhonesFieldLabel": "显示工作电话",
    "ShowMobilePhoneFieldLabel": "显示手机号码",
    "ShowWorkLocationFieldLabel": "显示工作地点",
    "ShowManagerFieldLabel": "显示上级",
    "UseInformalAddressFieldLabel": "使用非正式称谓",

    "ShowWorkLocationFallbackFieldLabel": "将工作地点显示为后备信息",
    "LocationDisplayHintGeoWithFallback": "城市和国家/地区会合并为一行地理信息。仅当没有城市/国家/地区数据时才显示工作地点。",
    "LocationDisplayHintGeoOnly": "城市和国家/地区会合并为一行地理信息。工作地点已隐藏。",
    "LocationDisplayHintOfficeOnly": "仅显示工作地点。启用城市和/或国家/地区即可改为显示地理信息行。",
    "LocationDisplayHintHidden": "所有位置信息均已隐藏。",
    "AddressMapFallbackHint": "如果未配置 Azure Maps 密钥或查找失败，将显示外部地图链接。",
    "LocationDisplayHintAddressEnabled": "已启用结构化地址字段，可在附加行中显示。",
    "LocationDisplayHintSeparateRows": "启用后，城市/国家（地区）与工作地点将分行显示。",
    "AdvancedDisplayGroupName": "高级显示选项",
    "ManagerOptionsDisabledHint": "启用显示上级后，才能配置上级专用字段。",
    "FunctionGroupName": "Azure 函数",
    "FunctionUrlFieldLabel": "发起人 API URL（Azure 函数）",
    "FunctionClientIdFieldLabel": "发起人 API 客户端 ID（Azure 函数应用注册）",
    "ProxyStatusChecking": "正在检查 Azure Function…",
    "ProxyStatusOk": "Azure Function 可访问",
    "ProxyStatusError": "Azure Function 无法访问",
    "ShowSponsorJobTitleFieldLabel": "显示担保人的职位",
    "ShowManagerJobTitleFieldLabel": "显示经理的职位",
    "ShowSponsorDepartmentFieldLabel": "显示担保人的部门",
    "ShowManagerDepartmentFieldLabel": "显示经理的部门",
    "DepartmentLabel": "部门",
    "ShowCityFieldLabel": "显示城市",
    "ShowCountryFieldLabel": "显示国家/地区",
    "ShowStructuredAddressFieldLabel": "显示结构化地址",
    "ShowStreetAddressFieldLabel": "显示街道",
    "ShowPostalCodeFieldLabel": "显示邮政编码",
    "ShowStateFieldLabel": "显示省/州",
    "ShowAddressMapFieldLabel": "显示地址地图预览",
    "AzureMapsSubscriptionKeyFieldLabel": "Azure Maps 订阅密钥",
    "ExternalMapProviderFieldLabel": "外部地图提供商（回退）",
    "MapProviderBingOption": "Bing Maps",
    "MapProviderGoogleOption": "Google Maps",
    "MapProviderAppleOption": "Apple Maps",
    "MapProviderOpenStreetMapOption": "OpenStreetMap",
    "MapProviderHereOption": "HERE WeGo",
    "CityFieldLabel": "城市",
    "CountryFieldLabel": "国家/地区",
    "CopyCityAriaLabel": "复制城市",
    "CopyCountryAriaLabel": "复制国家/地区",
    "ShowPresenceFieldLabel": "显示在线状态"
  }
});
