// SPDX-FileCopyrightText: 2026 Workoho GmbH <https://workoho.com>
// SPDX-FileCopyrightText: 2026 Julian Pawlowski <https://github.com/jpawlowski>
// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0

define([], function () {
  return {
    BasicGroupName: "设置",
    ShowTitleFieldLabel: "显示标题",
    TitleFieldLabel: "标题",
    LoadingMessage: "正在加载您的赞助商…",
    NoSponsorsTitle: "未找到担保人",
    NoSponsorsMessage: "未找到您帐户的赞助商。",
    SponsorUnavailableTitle: "担保人不可用",
    SponsorUnavailableMessage: "您的赞助商不再可用。请联系您的项目负责人，为您的帐户分配新的赞助商。",
    ErrorMessageTitle: "出现了错误",
    ErrorMessage: "无法加载赞助商信息。请稍后重试。",
    EditModePlaceholder: "访客赞助商信息 — 切换到查看模式以查看赞助商。",
    GuestOnlyPlaceholder: "此 Web 部件在查看模式下仅对访客用户可见。",
    MockModeFieldLabel: "始终显示演示赞助商（公开演示模式）",
    MockModeFieldDescription: "Applies only to the live page for visitors. In edit mode, the preview does not change.",
    MockModeFieldTooltip: "启用后，演示模式仅在实时页面上显示以进行测试。编辑模式和预览保持不变。",
    MockModePlaceholder: "访客赞助商信息 — 演示模式已激活。切换到查看模式以查看模拟数据。",
    MockSimulatedHintFieldLabel: "模拟访客通知",
    MockSimulatedHintNoneOption: "无通知",
    MockSimulatedHintTeamsAccessPendingOption: "Microsoft Teams 尚未设置",
    MockSimulatedHintVersionMismatchOption: "有可用更新",
    MockSimulatedHintSponsorUnavailableOption: "赞助商不可用",
    MockSimulatedHintNoSponsorsOption: "未找到赞助商",
    MaxSponsorCountFieldLabel: "可见赞助人数",
    MaxSponsorCountFieldTooltip:
      "限制显示的赞助商卡片数量。只有活跃（可用）的赞助商才计入此限制。如果分配的赞助商账户不再可用（已禁用、删除或尚未预配），优先级顺序中的下一个赞助商会自动向前推进以填补空位。这确保了来宾始终能看到配置的数量的可用联系人。",
    PresenceAvailable: "有空",
    PresenceAvailableIdle: "有空（闲置）",
    PresenceAway: "离开",
    PresenceBeRightBack: "马上回来",
    PresenceBusy: "忙碌",
    PresenceBusyIdle: "忙碌（闲置）",
    PresenceDoNotDisturb: "请勿打扰",
    PresenceInAMeeting: "会议中",
    PresenceInACall: "通话中",
    PresencePresenting: "演示中",
    PresenceFocusing: "专注中",
    PresenceOutOfOffice: "不在办公室",
    PresenceOutOfOfficeSuffix: "，不在办公室",
    PresenceOffline: "脱机",
    ContactDetailsAriaLabel: "{0} 的联系人详细信息",
    ContactActionsAriaLabel: "联系人操作",
    CloseLabel: "关闭",
    ChatTitle: "与 {name} 开始聊天",
    EmailTitle: "向 {name} 发送电子邮件",
    CallTitle: "与 {name} 开始音频通话",
    ChatLabel: "聊天",
    EmailLabel: "电子邮件",
    CallLabel: "通话",
    ContactInfoSection: "联系方式",
    EmailFieldLabel: "电子邮件",
    WorkPhoneFieldLabel: "工作电话",
    MobileFieldLabel: "手机",
    WorkLocationFieldLabel: "工作地点",
    AddressFieldLabel: "地址",
    StreetAddressFieldLabel: "街道",
    PostalCodeFieldLabel: "邮政编码",
    StateFieldLabel: "省/州",
    OrganizationSection: "组织",
    ReportsToSection: "汇报给",
    ManagerLabel: "上级",
    CopiedFeedback: "已复制!",
    CopyEmailAriaLabel: "复制电子邮件地址",
    CopyWorkPhoneAriaLabel: "复制工作电话",
    CopyMobileAriaLabel: "复制手机号码",
    CopyLocationAriaLabel: "复制工作地点",
    CopyAddressAriaLabel: "复制地址",
    CopyStreetAddressAriaLabel: "复制街道",
    CopyPostalCodeAriaLabel: "复制邮政编码",
    CopyStateAriaLabel: "复制省/州",
    AddressMapSectionLabel: "地图预览",
    AddressMapLoadingLabel: "正在加载地图预览...",
    OpenAddressInMapLabel: "在地图中打开",
    TeamsAccessPendingTitle: "Microsoft Teams 尚未设置",
    TeamsAccessPendingMessage:
      "您在此组织中的来宾 Microsoft Teams 访问权限尚未设置。这不影响您自己的 Teams 账户。请联系您的赞助人将您添加到团队中 — 添加后，您即可在此使用聊天、通话和会议等 Teams 功能。",
    TeamsNotReadyChatTooltip: "此组织中聊天不可用 — 您的 Teams 来宾访问权限尚未设置",
    TeamsNotReadyCallTooltip: "此组织中通话不可用 — 您的 Teams 来宾访问权限尚未设置",
    VersionMismatchTitle: "有可用更新",
    VersionMismatchMessage: "此 Web 部件有可用更新。请联系管理员确保 Web 部件和 Guest Sponsor API 运行相同版本。",
    InsufficientPermissionsTitle: "权限不足",
    InsufficientPermissionsMessage: "无法加载赞助商信息 — 尚未授予所需的服务权限。请联系您的 IT 管理员。",
    ServiceAuthorizationIssueTitle: "服务暂时出现问题",
    ServiceAuthorizationIssueMessage:
      "无法加载赞助商信息，因为赞助商服务无法完成内部授权步骤。请稍后重试。如果问题持续存在，请联系您的 IT 管理员。",
    GuestNotificationsGroupName: "访客通知",
    GuestNotificationsGroupHint: "控制向访客用户显示哪些信息通知。",
    ShowTeamsAccessPendingHintLabel: "显示「Microsoft Teams 尚未设置」通知",
    ShowVersionMismatchHintLabel: "显示「有可用更新」通知",
    ShowSponsorUnavailableHintLabel: "显示「赞助商不可用」通知",
    ShowNoSponsorsHintLabel: "显示「未找到赞助商」通知",
    DisplayGroupName: "显示",
    CardLayoutFieldLabel: "卡片布局",
    CardLayoutAutoOption: "自动",
    CardLayoutAutoThresholdFieldLabel: "达到此数量的担保人时切换为紧凑布局",
    CardLayoutFullOption: "完整",
    CardLayoutCompactOption: "紧凑",
    ShowBusinessPhonesFieldLabel: "显示工作电话",
    ShowMobilePhoneFieldLabel: "显示手机号码",
    ShowWorkLocationFieldLabel: "显示工作地点",
    ShowStreetAddressFieldLabel: "显示街道",
    ShowPostalCodeFieldLabel: "显示邮政编码",
    ShowStateFieldLabel: "显示省/州",
    AzureMapsSubscriptionKeyFieldLabel: "Azure Maps 订阅密钥",
    MapProviderModeAutoLabel: "自动模式（推荐）",
    MapProviderModeManualLabel: "手动（所有设备相同）",
    MapProviderModeHint:
      "为每个操作系统选择一个地图提供商，包括 iOS 和 Android。链接将在浏览器中打开，如果安装了提供商的应用则在应用中打开。",
    MapProviderIosLabel: "iOS:",
    MapProviderAndroidLabel: "Android:",
    MapProviderWindowsLabel: "Windows:",
    MapProviderMacOSLabel: "macOS:",
    MapProviderLinuxLabel: "Linux:",
    ExternalMapProviderFieldLabel: "地图提供商",
    MapProviderBingOption: "Bing Maps",
    MapProviderGoogleOption: "Google Maps",
    MapProviderAppleOption: "Apple Maps",
    MapProviderOpenStreetMapOption: "OpenStreetMap",
    MapProviderNoneOption: "禁用（无地图链接）",
    AddressMapProviderHint: "至少启用城市和国家/地区 — 这足以让任何地图提供商显示有意义的位置。",
    AzureMapsPreviewHint:
      "添加 Azure Maps 订阅密钥后，可在联系信息区域显示一个小型地图预览。如果您已部署 Guest Sponsor API，其中已包含一个 Azure Maps 帐户 — 请从其身份验证设置中复制密钥。未配置密钥时，仅显示上方地图链接。",
    ShowManagerFieldLabel: "显示上级",
    UseInformalAddressFieldLabel: "使用非正式称谓",
    SponsorEligibilityGroupName: "保证人资格",
    SponsorEligibilityGroupHint:
      "Microsoft Entra 中的赞助商分配由您的组织自行维护，并非总是准确。这些筛选器可提高展示给来宾的赞助商质量，并防止因分配错误而导致的信息意外泄露。",
    SponsorFilterFieldLabel: "保证人必须已",
    SponsorFilterTeamsOption: "拥有 Teams 许可证（推荐）",
    SponsorFilterExchangeOption: "拥有 Exchange Online 许可证",
    SponsorFilterAnyOption: "拥有许可证（任何有效许可证）",
    RequireUserMailboxFieldLabel: "要求用户邮筱类型",
    LocationDisplayHintSeparateRows: "启用的地址字段将合并为一个可点击的行。",
    AdvancedDisplayGroupName: "高级显示选项",
    FunctionGroupName: "Guest Sponsor API",
    FunctionUrlFieldLabel: "基础 URL",
    WebPartClientIdFieldLabel: "应用程序（客户端）ID",
    SessionCacheTtlMinutesFieldLabel: "会话缓存持续时间（分钟）",
    PpClientIdHintLabel: "在哪里找到客户端 ID？",
    PpClientIdHintBody: "从设置时创建的应用注册中复制客户端 ID（应用程序 ID）。",
    FunctionEntraLinkLabel: "在 Microsoft Entra 中查找 →",
    ProxyStatusChecking: "正在检查连接…",
    ProxyStatusOk: "连接成功",
    ProxyStatusError: "连接失败",
    PpSetupIntro: "必需的设置：",
    PpSetupRerunHint: "连接问题？安装脚本是幂等的 \u2014 使用相同参数重新运行可修复大多数问题。",
    CopyToClipboardLabel: "复制",
    CopiedToClipboardLabel: "已复制！",
    AuthorSectionGroupName: "关于",
    AuthorSectionCreatedBy: "创建并维护者",
    AuthorSectionIntro: "Microsoft 365 治理、身份管理与来宾访问 \u2014 我们的专业领域。",
    AuthorSectionWebsiteLinkLabel: "联系我们",
    AuthorSectionConsultingText:
      "我们开发这个 Web 部件，正是因为这是我们每天打交道的课题。从架构设计到落地实施，我们帮助组织在 Microsoft 365 上构建安全、可扩展的协作环境。",
    AuthorSectionAppWebsiteLabel: "Website",
    AuthorSectionVersionLabel: "Web 部件版本",
    AuthorSectionDeployToAzureLabel: "Deploy to Azure",
    DeployToAzureClickHint: "\u70b9\u51fb\u6309\u94ae\u5f00\u59cb\u90e8\u7f72\uff1a",
    AuthorSectionDeploymentGuideLabel: "部署指南",
    NewReleaseAvailableLabel: "\u6709\u65b0\u7248\u672c\u53ef\u7528 \u2014 \u6253\u5f00 GitHub Releases",
    DiagnosticsGroupName: "\u5ba2\u6237\u53ef\u8bbf\u95ee\u6027",
    DiagnosticsGroupHint:
      "\u68c0\u67e5 Web \u90e8\u4ef6\u7684 JavaScript \u5305\u4e0e\u767b\u5f55\u9875\u7ad9\u70b9\u662f\u5426\u53ef\u4f9b B2B \u5ba2\u6237\u7528\u6237\u8bbf\u95ee\u3002",
    DiagnosticsChecking: "\u6b63\u5728\u68c0\u67e5\u5ba2\u6237\u53ef\u8bbf\u95ee\u6027\u2026",
    DiagnosticsRetryButtonLabel: "重新运行检查",
    DiagPublicCdnOk:
      "\u5305\u901a\u8fc7 Office 365 \u516c\u5171 CDN \u5206\u53d1\uff0c\u533f\u540d\u4f20\u8f93\uff0c\u5ba2\u6237\u65e0\u9700\u7279\u6b8a\u6743\u9650\u3002",
    DiagPrivateCdnInfo:
      "\u5305\u901a\u8fc7 Office 365 \u79c1\u6709 CDN \u5206\u53d1\uff0c\u5177\u6709\u7ad9\u70b9\u8bfb\u53d6\u6743\u9650\u7684\u5ba2\u6237\u53ef\u4ee5\u52a0\u8f7d\u3002\u8bf7\u786e\u4fdd\u767b\u5f55\u9875\u7ad9\u70b9\u5bf9\u5ba2\u6237\u53ef\u8bbf\u95ee\u3002",
    DiagSiteColCatalogOk:
      "\u5305\u4ece\u672c\u7ad9\u70b9\u96c6\u5e94\u7528\u76ee\u5f55\u5206\u53d1\uff0c\u5ba2\u6237\u8bbf\u95ee\u6743\u9650\u6309\u7ad9\u70b9\u81ea\u8eab\u8bbe\u7f6e\u6267\u884c\u3002",
    DiagTenantCatalogEveryoneOk:
      "\u5305\u4ece\u79df\u6237\u5e94\u7528\u76ee\u5f55\u5206\u53d1\u3002\u201c\u6240\u6709\u4eba\u201d\u7ec4\u5bf9\u76ee\u5f55\u5177\u6709\u8bfb\u53d6\u6743\u9650\uff0c\u5ba2\u6237\u7528\u6237\u53ef\u4ee5\u52a0\u8f7d\u5305\u3002",
    DiagTenantCatalogEveryoneDenied:
      "\u5305\u4ece\u79df\u6237\u5e94\u7528\u76ee\u5f55\u5206\u53d1\uff0c\u4f46\u201c\u6240\u6709\u4eba\u201d\u7ec4\u65e0\u8bfb\u53d6\u6743\u9650\u3002\u5ba2\u6237\u7528\u6237\u65e0\u6cd5\u52a0\u8f7d Web \u90e8\u4ef6\u3002\u5efa\u8bae\uff1a\u542f\u7528 Office 365 \u516c\u5171 CDN\uff0c\u6216\u5c06\u5e94\u7528\u76ee\u5f55\u7ad9\u70b9\u7684\u8bbf\u5ba2\u8005\u6743\u9650\u6388\u4e88\u201c\u6240\u6709\u4eba\u201d\u3002",
    DiagTenantCatalogEveryoneUnknown:
      "\u5305\u4ece\u79df\u6237\u5e94\u7528\u76ee\u5f55\u5206\u53d1\u3002\u65e0\u6cd5\u786e\u8ba4\u201c\u6240\u6709\u4eba\u201d\u662f\u5426\u5177\u6709\u8bfb\u53d6\u6743\u9650\uff08\u6743\u9650\u4e0d\u8db3\uff09\u3002\u8bf7\u624b\u52a8\u9a8c\u8bc1\u5ba2\u6237\u662f\u5426\u80fd\u8bbf\u95ee\u5e94\u7528\u76ee\u5f55\uff0c\u6216\u542f\u7528 Office 365 \u516c\u5171 CDN\u3002",
    DiagAssetSourceUnknown:
      "\u65e0\u6cd5\u786e\u5b9a\u5305\u7684\u6765\u6e90\u3002\u8bf7\u624b\u52a8\u9a8c\u8bc1\u5ba2\u6237\u7528\u6237\u662f\u5426\u80fd\u8bbf\u95ee Web \u90e8\u4ef6\u7684 JavaScript \u5305\u3002",
    DiagSiteEveryoneOk:
      "\u201c\u6240\u6709\u4eba\u201d\u5df2\u52a0\u5165\u7ad9\u70b9\u8bbf\u5ba2\u8005\u7ec4\uff0c\u65b0\u63a5\u5165\u7684\u5ba2\u6237\u53ef\u7acb\u5373\u83b7\u5f97\u767b\u5f55\u9875\u7684\u8bfb\u53d6\u6743\u9650\u3002",
    DiagSiteEveryoneMissing:
      "\u201c\u6240\u6709\u4eba\u201d\u672a\u52a0\u5165\u7ad9\u70b9\u8bbf\u5ba2\u8005\u7ec4\u3002\u5ba2\u6237\u8bbf\u95ee\u53ef\u80fd\u4f9d\u8d56\u4e8e\u9759\u6001 Entra \u5b89\u5168\u7ec4\uff08\u53ef\u63a5\u53d7\uff09\u6216\u52a8\u6001\u7ec4\uff08\u65b0\u5ba2\u6237\u53ef\u80fd\u5ef6\u8fdf\u6700\u957f 24\u00a0\u5c0f\u65f6\u624d\u80fd\u751f\u6548\uff09\u3002\u5982\u679c\u672a\u914d\u7f6e\u5305\u542b\u5ba2\u6237\u7684\u7ec4\uff0c\u5ba2\u6237\u5c06\u770b\u5230\u8bbf\u95ee\u62d2\u7edd\u9875\u9762\u3002",
    DiagSiteEveryoneUnknown:
      "\u65e0\u6cd5\u9a8c\u8bc1\u7ad9\u70b9\u8bbf\u5ba2\u8005\u6743\u9650\u3002\u8bf7\u786e\u4fdd\u5ba2\u6237\u7528\u6237\u81f3\u5c11\u5177\u6709\u8be5\u7ad9\u70b9\u7684\u8bfb\u53d6\u6743\u9650\u3002",
    ShowSponsorJobTitleFieldLabel: "显示担保人的职位",
    ShowManagerJobTitleFieldLabel: "显示经理的职位",
    ShowSponsorDepartmentFieldLabel: "显示担保人的部门",
    ShowManagerDepartmentFieldLabel: "显示经理的部门",
    DepartmentLabel: "部门",
    ShowCityFieldLabel: "显示城市",
    ShowCountryFieldLabel: "显示国家/地区",
    CityFieldLabel: "城市",
    CountryFieldLabel: "国家/地区",
    CopyCityAriaLabel: "复制城市",
    CopyCountryAriaLabel: "复制国家/地区",
    ShowPresenceFieldLabel: "显示在线状态",
    ShowSponsorPhotoFieldLabel: "显示担保人照片",
    ShowManagerPhotoFieldLabel: "显示上级照片",
    TitlePlaceholder: "我的赞助商",
    TitleSizeFieldLabel: "标题大小",
    TitleSizeH2Option: "标题 2",
    TitleSizeH3Option: "标题 3",
    TitleSizeH4Option: "标题 4",
    TitleSizeNormalOption: "正文",
    WelcomeDialogTitle: "设置访客赞助商信息",
    WelcomeDialogBody:
      "此 Web 部件在 SharePoint 登录页上向每位来宾用户显示其 Microsoft Entra 担保人。要使此 Web 部件有意义，担保人分配应得到主动管理，且来宾生命周期管理流程应已就位 — 它让责任可见，但不能替代背后的治理。",
    WelcomeDialogBroughtToYouBy: "由 Workoho 开发 — 专注于来宾治理和生命周期管理。",
    WelcomeDialogWorkohoLinkLabel: "workoho.com",
    WelcomeDialogDismissButton: "开始使用",
    WelcomeDialogNextButton: "下一步",
    WelcomeDialogBackButton: "返回",
    WelcomeDialogSkipButton: "暂不",
    WelcomeDialogSaveButton: "保存",
    WelcomeDialogSkipApiButton: "跳过",
    InvalidUrlFormat: "请输入有效的URL（例如：my-app.azurewebsites.net）",
    InvalidGuidFormat: "请输入有效的GUID（xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx）",
    WelcomeDialogSetupTitle: "选择设置路径",
    WelcomeDialogSetupIntro: "选择您的部署路径。您可以随时通过 Web 部件设置在两个选项之间切换。",
    WelcomeDialogOptionApiTitle: "使用 Guest Sponsor API",
    WelcomeDialogOptionApiBody: "由 Azure Function 提供支持的完整体验。需要一次性 Azure 设置 — 推荐用于生产环境。",
    WelcomeDialogOptionApiDocsLabel: "查看设置指南",
    WelcomeDialogSetupGuideNote: "此命令是快速入门捷径。运行前，请阅读设置指南，了解其作用。",
    WelcomeDialogDeployToAzureLabel: "将 API 部署到 Azure",
    WelcomeDialogDeployNote:
      "此选项需要将 Guest Sponsor API 部署到您的 Azure 订阅。您可以在此处完成 \u2014 只需几分钟。",
    WelcomeDialogPreflightTitle: "Before deployment, the installer checks:",
    WelcomeDialogPreflightTools: "PowerShell, Azure CLI, Azure Developer CLI, and Bicep support.",
    WelcomeDialogPreflightSignIn: "Azure sign-in and the target subscription.",
    WelcomeDialogPreflightRoles: "Azure RBAC and Entra roles, with a copy/paste request if anything is missing.",
    WelcomeDialogSetupStepsOrderHint: "请按顺序完成以下步骤：",
    WelcomeDialogSetupStep1Label: "创建应用注册",
    WelcomeDialogSetupStep2Hint: "使用步骤 1 中创建的应用注册",
    WelcomeDialogSetupStep3Label: "授予 Graph 权限",
    WelcomeDialogSetupPwshHint: "PowerShell 7+:",
    WelcomeDialogSetupShellHint: "macOS/Linux shell:",
    WelcomeDialogUseShellCommandLabel: "macOS/Linux without PowerShell?",
    WelcomeDialogUsePowerShellCommandLabel: "Use PowerShell command",
    WelcomeDialogSetupStep3Hint: "使用应用注册（步骤 1）和函数应用 URL（步骤 2）",
    ViewScriptSourceLabel: "检查脚本",
    WelcomeDialogConnectApiTitle: "输入 API 连接详细信息",
    WelcomeDialogConnectApiIntro:
      "输入 Guest Sponsor API 的连接详细信息。您可以暂时跳过此步骤，稍后在 Web 部件设置中添加。",
    WelcomeDialogUrlHintLabel: "在哪里找到 URL？",
    WelcomeDialogUrlHintBody: "部署后，从 Azure 门户复制 Function App URL。请转到您的 Function App → 概述 → 默认域。",
    WelcomeDialogOptionDemoTitle: "在演示模式下探索",
    WelcomeDialogOptionDemoBody: "使用模拟赞助商数据试用 Web 部件 — 无需 Azure 设置。随时可以从设置中切换到真实 API。",
    WelcomeDialogFunctionUrlRequired: "请输入 Guest Sponsor API 的基础 URL。",
    WelcomeDialogDoneApiTitle: "API 已配置！",
    WelcomeDialogDoneApiBody: "与 Guest Sponsor API 的连接已保存。请记得保存页面，以便将设置应用给所有人。",
    WelcomeDialogDoneApiSkippedTitle: "即将完成！",
    WelcomeDialogDoneApiSkippedBody:
      "尚未输入凭据。要完成配置：打开 Web 部件设置，在 Guest Sponsor API 下输入基本 URL 和客户端 ID，然后保存页面。",
    WelcomeDialogDoneDemoTitle: "演示模式已激活！",
    WelcomeDialogDoneDemoBody:
      "切换到查看模式，查看带有模拟赞助商卡片的 Web 部件。准备好后，可从 Web 部件设置中连接 Guest Sponsor API。",
    PpSectionLivePage: "▶ 实时页面",
    PpSectionDemoMode: "🧪 演示模式",
    PpSectionCardLayout: "🗂️ 卡片布局",
    PpSectionProfileFields: "👤 个人资料字段",
    PpSectionPhone: "📞 电话号码",
    PpSectionWorkLocation: "📍 工作地点",
    PpSectionAddress: "🏠 邮寄地址",
    PpSectionMapLink: "🧭 地图链接",
    PpSectionMapPreview: "🗺️ 内联地图预览"
  };
});
